Repository erda-project/erda, pull requests merged in 2021-03, with the labels that each got.

#23 feature: apistructs add pipeline storage config
  apistructs/pipeline_dto.go
  apistructs/pipeline_dto_test.go
  bundle/servicegroup.go
Labels: lgtm

#26 feat(Owners): update owners file
  OWNERS
Labels: approved

#27 remove(clientgo): remove client go redundant files
  pkg/clientgo/apps/v1/apps_client.go
  pkg/clientgo/config.go
  pkg/clientgo/core/v1/core_client.go
Labels: approved

#30 feature: add golangci-lint & github-action
  .github/workflows/golangci-lint.yml
  .golangci.yml
  apistructs/member.go
Labels: approved

#32 feat(template): update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, release-note, size/XS
