Repository erda-project/erda, pull requests merged in 2021-04, with the labels that each got.

#36 feature: provide metricq client
  .golangci.yml
  go.mod
  go.sum
  providers/metrics/query/error.go
  providers/metrics/query/examples/examples.yaml
  providers/metrics/query/examples/main.go
  providers/metrics/query/provider.go
  providers/metrics/query/query.go
  providers/metrics/query/query_requst.go
  providers/metrics/query/query_response.go
  providers/metrics/query/struct_output.go
Labels: enhancement

#145 Migrate apm related code
  .github/workflows/ci-it.yml
  .golangci.yml
  Makefile
  go.mod
  modules/monitor/apm/common/common.go
  modules/monitor/apm/report/provider.go
  modules/monitor/apm/report/report.go
  modules/monitor/apm/report/routes.go
  modules/monitor/apm/runtime/provider.go
  modules/monitor/apm/runtime/routes.go
  modules/monitor/apm/runtime/runtime.go
  modules/monitor/apm/topology/provider.go
  modules/monitor/apm/topology/routes.go
  modules/monitor/apm/topology/todo
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
  modules/monitor/apm/trace/provider.go
  modules/monitor/apm/trace/routes.go
  modules/monitor/apm/trace/todo
  modules/monitor/apm/trace/trace.go
Labels: enhancement

#161 How to build the Erda project.
  docs/guides/dev/How-to-build-erda-project.md
Labels: documentation

#163 DOCS: build a single module
  Makefile
  docs/guides/dev/How-to-build-erda-project.md
Labels: documentation

#169 docs: add show case gif in readme
  README.md
Labels: documentation

#172 docs: fix screenshot gif not run
  README.md
Labels: documentation

#159 Modify static files to the assets directory.
  README.md
  docs/assets/arch.png
  docs/assets/functional_architecture.jpg
  docs/assets/logo-small.jpg
  docs/assets/logo.jpg
  docs/assets/vision.png
  docs/assets/wechat-small.jpg
  docs/assets/wechat.jpg
Labels: documentation

#246 Support: add service instance state API
  conf/monitor/i18n/topology.yml
  modules/monitor/apm/topology/routes.go
  modules/monitor/apm/topology/topology.go
Labels: enhancement

#249 Fix: Request error rate calculation error
  conf/monitor/i18n/topology.yml
  modules/monitor/apm/topology/topology.go
Labels: bug

#271 Calculate disk io and network io
  Makefile
  build/scripts/base_image.sh
  build/scripts/docker_image.sh
  modules/monitor/apm/topology/routes.go
  modules/monitor/apm/topology/topology.go
Labels: enhancement

#274 Calculate the number of running instances
  modules/monitor/apm/topology/topology.go
Labels: enhancement

#275 Configure openapi interface
  modules/openapi/api/apis/monitor/monitor_apm_topology_process_diskio.go
  modules/openapi/api/apis/monitor/monitor_apm_topology_process_netio.go
  modules/openapi/api/apis/monitor/monitor_apm_topology_service_instances_list.go
Labels: enhancement
