Repository erda-project/erda, pull requests merged in 2021-11, with the labels that each got.

#2702 refactor: 💡 request nodes list asynchronized
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
  modules/cmp/metrics/metrics.go
Labels: cmp, refactor

#2701 fix: round value in scheduler log
  go.mod
  go.sum
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
  modules/scheduler/executor/plugins/k8s/check_quota.go
  modules/scheduler/executor/plugins/k8s/check_quota_test.go
Labels: bugfix, approved, scheduler

#2691 fix: add clusterName in update project quota audit
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/core-services/services/project/project.go
  pkg/resourcecalculator/calculator.go
Labels: bugfix, approved

#2719 fix: steve request poniter changed in goroutine
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadChart/render.go
  modules/cmp/component-protocol/cputil/util.go
  modules/cmp/steve_request.go
Labels: cmp, bugfix, approved

#2715 fix: 🐛 lb,platform label deduplicated
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/filter/filter.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render_test.go
Labels: cmp, bugfix, approved

#2721 fix: update the style to test dashboard
  modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_avg_cost_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/at_api_chart_group/at_api_rate_failed_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/at_plan_latest_waterfall_chart_group/chart/model.go
  modules/dop/component-protocol/components/test-dashboard/common/barchart.go
  modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_avg_cost_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_failed_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/scene_chart_group/scene_rate_passed_chart/render.go
Labels: dop, approved

#2706 fix: modify the audit message for org update
  apistructs/org.go
  modules/core-services/endpoints/organization.go
  modules/core-services/services/org/org.go
  modules/core-services/services/org/org_test.go
  modules/openapi/api/apis/dop/cmdb_orgs_update.go
  pkg/erda-configs/audit/template.json
Labels: approved

#2724 fix: update replicas to 1 for gittar
  erda.yml
Labels: approved

#2731 fix: test-dashboard polish each score before calc total score
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
Labels: dop, bugfix

#2733 elasticsearch common iterator
  modules/core/monitor/entity/persist/provider.go
  modules/core/monitor/log/storage/elasticsearch/iterator.go
  modules/core/monitor/metric/persist/provider.go
  modules/core/monitor/storekit/elasticsearch/iterator.go
Labels: msp, feature

#2460 feature: eventbox support custom notify channel
  apistructs/notify_channel.go
  apistructs/notify_channel_test.go
  bundle/notify_channel.go
  modules/eventbox/subscriber/group/group.go
  modules/eventbox/subscriber/sms/sms.go
  modules/pkg/etcdclient/etcdclient.go
  modules/pkg/etcdclient/etcdclient_test.go
Labels: msp, feature

#2427 feature: Notify channel
  .erda/migrations/core-services/20211014-01-erda_notify_channel.sql
  api/proto-go/all.go
  api/proto-go/core/services/notify/channel/client/client.go
  api/proto-go/core/services/notify/channel/client/provider.go
  api/proto-go/core/services/notify/channel/pb/channel.form.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.http.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.json.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.validator.pb.go
  api/proto-go/core/services/notify/channel/pb/channel_grpc.pb.go
  api/proto-go/core/services/notify/channel/pb/register.services.pb.go
  api/proto/core/services/notify/channel/channel.proto
  cmd/core-services/main.go
  conf/core-services/core-services.yaml
  conf/core-services/i18n/cs-i18n.yml
  go.mod
  go.sum
  modules/core-services/initialize.go
  modules/core-services/model/notify_channel.go
  modules/core-services/provider.go
  modules/core-services/services/notify/channel/db/notify_channel.go
  modules/core-services/services/notify/channel/kind/aliyun_sms.go
  modules/core-services/services/notify/channel/kind/aliyun_sms_test.go
  modules/core-services/services/notify/channel/kind/interface.go
  modules/core-services/services/notify/channel/notify.chanel.service.go
  modules/core-services/services/notify/channel/notify.chanel.service_test.go
  modules/core-services/services/notify/channel/provider.go
  pkg/common/errors/warn.go
  pkg/kms/kmstypes/api_const.go
Labels: msp, core feature, approved

#2740 fix bugs
  conf/cmp/i18n/component-protocol.yaml
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/batchOperationTipModal/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-pods/addPodFileEditor/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-pods/addPodFileEditor/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFileEditor/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFileEditor/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFileEditor/workload_template.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workload-detail.yml
  modules/cmp/metrics/metrics.go
  modules/cmp/steve_request.go
Labels: cmp, bugfix, approved

#2734 feat: 🎸 audit cmd with buffer
  modules/cmp/steve/middleware/audit.go
  modules/cmp/steve/middleware/dispatcher.go
  modules/cmp/steve/middleware/dispatcher_test.go
Labels: cmp, feature, approved

#2726 pagingRequest use pageNo unifiedly
  apistructs/cicd.go
  apistructs/cicd_test.go
  apistructs/pipeline.go
  modules/dop/endpoints/pipeline.go
  modules/pipeline/dbclient/op_pipeline.go
Labels: dop, feature, approved

#2736 fix: test-dashboard correct cacl logic of bug-reopen-score
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
Labels: dop, bugfix, approved

#2750 bugfix/fix: remove cache failed
  conf/cmp/i18n/component-protocol.yaml
  modules/cmp/component-protocol/components/cmp-dashboard-podDetail/operationButton/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-podDetail/operationButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/workloadTable/render.go
  modules/cmp/steve_request.go
Labels: cmp, bugfix, approved

#2752 bugfix: record latency when http response status is ok
  modules/msp/apm/checker/plugins/http/provider.go
Labels: msp, bugfix

#2757 fix: restart confirm window out of display range
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go
Labels: approved

#2714 feature: migrate the API GetProject from core-services to dop
  .erda/migrations/cmdb/20211101-update-project-quota.sql
  apistructs/project.go
  apistructs/project_quota.go
  apistructs/project_test.go
  apistructs/testplan_test.go
  bundle/quota.go
  cmd/core-services/main.go
  cmd/dop/main.go
  conf/core-services/core-services.yaml
  conf/core-services/i18n/i18n.yaml
  conf/dop/dop.yaml
  conf/dop/i18n/resource-trans.yaml
  modules/core-services/dao/project.go
  modules/core-services/dao/quota.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/endpoints/organization.go
  modules/core-services/endpoints/project.go
  modules/core-services/initialize.go
  modules/core-services/model/project.go
  modules/core-services/provider.go
  modules/core-services/services/apierrors/errors.go
  modules/core-services/services/org/org.go
  modules/core-services/services/org/org_test.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
  modules/dop/dao/resource.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/organization.go
  modules/dop/endpoints/project.go
  modules/dop/initialize.go
  modules/dop/provider.go
  modules/dop/services/apierrors/errors.go
  modules/dop/services/org/fetch_resource.go
  modules/dop/services/org/fetch_resource_test.go
  modules/dop/services/org/org.go
  modules/dop/services/project/get.go
  modules/dop/services/project/option.go
  modules/dop/services/project/project.go
  modules/dop/services/project/project_test.go
  modules/openapi/api/apis/dop/cmdb_org_resources.go
  modules/openapi/api/apis/dop/cmdb_projects_detail.go
Labels: refactor, approved

#2756 fix es matching error
  modules/core/monitor/metric/storage/elasticsearch/provider.go
  modules/core/monitor/metric/storage/elasticsearch/provider_test.go
Labels: approved

#2749 test-dashboard: add tip for quality radar
  conf/dop/i18n/component-protocol.yaml
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/tip.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/tip_test.go
Labels: dop, feature

#2753 fix: update org update audit
  apistructs/audits.go
  modules/core-services/services/org/org.go
  modules/core-services/services/org/org_test.go
  modules/openapi/api/apis/dop/cmdb_orgs_update.go
Labels: approved

#2742 send pop out pipeline id to etcd, and watch pop out in leader
  modules/pipeline/endpoints/pipeline.go
  modules/pipeline/pipengine/reconciler/before_listen.go
  modules/pipeline/pipengine/reconciler/queuemanage/manager/queue.go
  modules/pipeline/pipengine/reconciler/queuemanage/manager/queue_test.go
  modules/pipeline/pipengine/reconciler/queuemanage/types/manager.go
Labels: pipeline, bugfix, approved

#2751 bugfix: ignore internal topology node in msp
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
Labels: msp, bugfix, approved

#2767 polish: frontend note
  conf/core-services/i18n/cs-i18n.yml
  modules/core-services/services/notify/channel/notify.chanel.service.go
  pkg/common/apis/response.go
  pkg/common/errors/warn.go
Labels: core feature

#2772 feature: event query support tags filter
  api/proto-go/core/monitor/event/pb/event_query.pb.go
  api/proto-go/core/monitor/event/pb/event_query.validator.pb.go
  api/proto/core/monitor/event/event_query.proto
  modules/core/monitor/event/query/event.query.service.go
  modules/core/monitor/event/query/event.query.service_test.go
Labels: msp, feature

#2773 fix: restart daemonset failed
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go
Labels: approved

#2650 Fix/pipeline apitest cost time
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/meta.go
  modules/pipeline/pipengine/reconciler/reconcile.go
  modules/pipeline/pipengine/reconciler/taskrun/framework.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/wait_test.go
  modules/pipeline/pipengine/reconciler/taskrun/taskrun.go
Labels: pipeline, bug, approved

#2786 polish: rm the column width of call count
  conf/monitor/monitor/chartview/service/translation_analysis_database.json
Labels: msp, approved

#2777 fix: CoreToMillCore error; fix: cluster_config error; fix: rollback_config error
  modules/core-services/dao/project.go
  modules/core-services/model/project.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
  pkg/resourcecalculator/calculator.go
  pkg/resourcecalculator/calculator_test.go
Labels: bug, approved

#2793 fix: resource overview i18n error
  bundle/quota.go
  modules/cmp/resource/class.go
  modules/cmp/resource/report_table.go
  modules/cmp/resource/summary.go
  modules/cmp/tasks/collect_daily_quota.go
  modules/cmp/tasks/ticker.go
Labels: feature, bug, approved

#2794 feature: modify the error document
  conf/core-services/i18n/i18n.yaml
Labels: feature, approved

#2790 fix the display problem of the pipeline log of the mobile application initialization
  modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
  pkg/erda-configs/i18n/pipeline.json
Labels: approved

#2799 bugfix: trace depth
  modules/msp/apm/trace/trace.service.go
  modules/msp/apm/trace/trace.service_test.go
Labels: msp, bugfix

#2792 bugfix: bar -> line
  conf/monitor/monitor/chartview/trace/trace_count.json
Labels: monitor-stack, bugfix

#2804 bugfix: fix event index template
  conf/monitor/streaming/event_index_template.json
Labels: msp, bugfix, approved

#2808 change mobile template git push addr
  modules/core-services/services/application/appliation.go
Labels: dop, core feature, bug, approved

#2809 fix: 🐛 node filter translation
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render.go
Labels: cmp, bugfix, approved

#2797 fix: dop ci generate pipeline cms ns by workspace's main-branch
  modules/dop/services/pipeline/pipeline.go
  modules/dop/services/pipeline/pipeline_test.go
  modules/pipeline/providers/cms/app.go
  modules/pipeline/providers/cms/app_test.go
Labels: dop, bugfix

#2780 polish: pr template add kind refactor&bugfix, remove bug
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, polish

#2779 polish test dashboard chart
  modules/dop/component-protocol/components/test-dashboard/at_plan_latest_waterfall_chart_group/chart/model.go
  modules/dop/component-protocol/components/test-dashboard/mt_plan_chart_group/chart/render.go
Labels: dop, polish

#2814 remove mobile init key
  modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
Labels: approved

#2817 fix: ignore virtual node when calculate resource
  modules/cmp/cluster_resource.go
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/charts/render.go
Labels: approved

#2807 polish: duration unit for trace query
  modules/core/monitor/metric/query/metricq/metricq.go
  modules/core/monitor/metric/query/metricq/provider.go
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
Labels: msp

#2821 Feature/resource overview refact table
  apistructs/cmp_resource_overview.go
  apistructs/cmp_resource_overview_test.go
  http-client.env.json
  modules/cmp/endpoints/http-tests/resource-overview.http
  modules/cmp/endpoints/resource_overview.go
  modules/cmp/resource/report_table.go
Labels: feature, approved

#2825 fix: error message is not clear when permissin denied
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/batchOperationTipModal/render.go
  modules/cmp/steve/handler.go
  modules/cmp/steve/parse.go
  modules/cmp/steve/parse_test.go
  modules/cmp/steve_request.go
Labels: cmp, approved

#2768 disable mysql basic ha
  modules/orchestrator/services/addon/addon_deploy.go
  modules/orchestrator/services/addon/addon_deploy_test.go
Labels: orchestrator

#2832 Bugfix/bugs
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/statusBadge/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/table/table.go
  modules/cmp/component-protocol/scenarios/cmp-dashboard-nodedetail.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workload-detail.yml
Labels: cmp, bugfix, approved

#2824 fix the problem about scaling service failed when quota is not enough
  modules/scheduler/executor/plugins/k8s/check_quota.go
  modules/scheduler/executor/plugins/k8s/check_quota_test.go
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/deployment_test.go
  modules/scheduler/executor/plugins/k8s/runtime.go
  modules/scheduler/impl/servicegroup/create.go
Labels: bugfix, approved, scheduler

#2816 loop task not reset begintime
  modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/queue.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/queue_test.go
Labels: pipeline, bug, approved

#2621 Fix user info interceptor desensitized, remove duplicate query
  modules/core/openapi-ng/interceptors/user-info/user_info.go
  modules/core/openapi-ng/interceptors/user-info/user_info_test.go
  modules/openapi/api/apis/openapi/component_protocol/notspec_response.go
  modules/openapi/api/apis/openapi/component_protocol/render.go
  modules/openapi/proxy/http/http.go
  pkg/http/httputil/header.go
Labels: openapi, bugfix, approved

#2836 fix: missing cpuRequest and memRequest in shared resource data
  modules/cmp/resource/report_table.go
  modules/cmp/tasks/collect_daily_quota.go
Labels: feature, approved

#2819 Add multiple-column index on mbox to optimize the query when creating mbox
  .erda/migrations/cmdb/20211103-mbox-index.sql
Labels: dop, feature, approved

#2785 feature: schesuler workspace switch 1.3
  modules/cmp/impl/clusters/import_cluster.go
Labels: pipeline, orchestrator, cluster-manager, feature, approved

#2784 feature: import cluster with enabled workspace scheduler
  modules/cmp/impl/clusters/import_cluster.go
  modules/cmp/impl/clusters/import_cluster_test.go
Labels: pipeline, orchestrator, cluster-manager, feature, approved

#2830 feature: test-dashboard radar bug score only calc unclosed bugs
  apistructs/workbench.go
  conf/dop/i18n/component-protocol.yaml
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/tip.go
  modules/dop/dao/issue.go
Labels: dop, feature

#2843 optimize: do not check log.Labels
  modules/extensions/loghub/exporter/output.go
  modules/extensions/loghub/exporter/output_test.go
Labels: msp, approved

#2849 use json number to decode span
  modules/msp/apm/trace/storage/consumer.go
Labels: msp, approved

#2783 fix: tag/workspace scheduler switch
  .erda/migrations/cmdb/20211102-cluster-scheduler-cover-tag.py
Labels: pipeline, orchestrator, bugfix, approved

#2852 k8s dashboard support k8s version < 1.16
  go.mod
  go.sum
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
  modules/cmp/initialize.go
  modules/cmp/steve/config.go
  modules/cmp/steve/factory.go
  modules/cmp/steve/proxy/proxy_store.go
  modules/cmp/steve/schema.go
  modules/cmp/steve/server.go
Labels: cmp, approved

#2853 Fix user info retriever, update unit test
  modules/core/openapi-ng/interceptors/user-info/user_info.go
  modules/core/openapi-ng/interceptors/user-info/user_info_test.go
Labels: bugfix, approved

#2845 recover pipeline metrics as before
  cmd/pipeline/main.go
  conf/pipeline/pipeline.yaml
  modules/pipeline/conf/conf.go
  modules/pipeline/initialize.go
  modules/pipeline/metrics/init.go
  modules/pipeline/metrics/pipeline.go
  modules/pipeline/metrics/task.go
  modules/pipeline/pipengine/reconciler/task.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
  modules/pipeline/pipengine/reconciler/taskrun/update.go
  modules/pipeline/pipengine/reconciler/teardown.go
  modules/pipeline/provider.go
Labels: pipeline, bug, approved

#2868 Hotfix/pipeline metrics
  cmd/pipeline/main.go
  conf/pipeline/pipeline.yaml
  modules/pipeline/conf/conf.go
  modules/pipeline/initialize.go
  modules/pipeline/metrics/init.go
  modules/pipeline/metrics/pipeline.go
  modules/pipeline/metrics/task.go
  modules/pipeline/pipengine/reconciler/task.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
  modules/pipeline/pipengine/reconciler/taskrun/update.go
  modules/pipeline/pipengine/reconciler/teardown.go
  modules/pipeline/provider.go
Labels: approved

#2860 modify customize alert rule
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/msp/apm/alert/alert.service.go
Labels: msp, bugfix

#2851 modify get condition values method
  api/proto-go/cmp/alert/pb/cmp_alert.form.pb.go
  api/proto-go/cmp/alert/pb/cmp_alert.pb.go
  api/proto-go/cmp/alert/pb/cmp_alert.validator.pb.go
  api/proto-go/core/monitor/alert/pb/alert.form.pb.go
  api/proto-go/core/monitor/alert/pb/alert.json.pb.go
  api/proto-go/core/monitor/alert/pb/alert.pb.go
  api/proto-go/core/monitor/alert/pb/alert.validator.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.form.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.validator.pb.go
  api/proto/cmp/alert/cmp_alert.proto
  api/proto/core/monitor/alert/alert.proto
  api/proto/msp/apm/alert/apm_alert.proto
  modules/cmp/alert.go
  modules/cmp/alert_test.go
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/alert.service_test.go
  modules/openapi/api/apis/cmp/cmp_alert_conditions_value.go
Labels: msp, bugfix

#2869 fix: empty request body
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/steve/middleware/audit.go
Labels: cmp, bugfix, approved

#2867 count coverage by package path
  apistructs/code_coverage_exec_record.go
  apistructs/code_coverage_exec_record_test.go
  modules/dop/component-protocol/components/code-coverage/startButton/render.go
  modules/dop/component-protocol/components/code-coverage/treeMapChart/render.go
  modules/dop/services/code_coverage/analyze.go
Labels: dop, feature, approved

#2872 gittar add tree search depth config
  modules/gittar/api/repo.go
  modules/gittar/conf/conf.go
Labels: feature, approved, gittar

#2871 modify display_url
  modules/core/monitor/alert/alert-apis/adapt/alert_route.go
Labels: msp

#2875 fix: add borderTime to timePicker
  modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/model.go
  modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/render.go
  modules/dop/component-protocol/components/test-dashboard/scene_and_api_filter/model.go
  modules/dop/component-protocol/components/test-dashboard/scene_and_api_filter/render.go
Labels: dop, approved

#2878 bugfix: quick-start support *.erda.local visit from inside k8s cluster
  quick-start/docker-compose.yml
  quick-start/env
  quick-start/nginx.conf
  quick-start/quick-start.sh
Labels: install

#2884 enhancing the access log of hepa
  modules/hepa/common/log_helper.go
  modules/hepa/k8s/k8s_adapter.go
Labels: hepa, feature, approved

#2883 fix: 🐛 calc size of cache interface value
  modules/cmp/cache/cache.go
  modules/cmp/cache/cache_test.go
Labels: cmp, bugfix, approved

#2888 prohibit delete system workload
  conf/cmp/i18n/component-protocol.yaml
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render_test.go
Labels: cmp, approved

#2890 feature: trim charset except utf8,utf8mb4
  pkg/database/sqlparser/ddlreverser/reverser.go
  pkg/database/sqlparser/snapshot/snapshot.go
  pkg/database/sqlparser/snapshot/snapshot_test.go
Labels: feature, approved, install

#2897 modify label scope id to org name
  modules/pipeline/metrics/pipeline.go
  modules/pipeline/metrics/task.go
Labels: pipeline, bugfix, approved

#2901 fix: update api and scene count of test dash board
  apistructs/autotest_scene.go
  apistructs/autotest_scene_test.go
  modules/dop/component-protocol/components/test-dashboard/overview_group/blocks/at/at_num_api/render.go
  modules/dop/services/autotest_v2/scene.go
Labels: dop, approved

#2893 Check guest role of member info with empty resource value
  modules/core-services/services/security/process.go
Labels: dop, bugfix, approved

#2902 add orchestrator addr
  erda.yml
Labels: approved

#2887 bugfix: log index cache got overwritten when multi esurls exists in erda cluster
  modules/extensions/loghub/index/query/clients.go
  modules/extensions/loghub/index/query/index.go
Labels: msp, bugfix

#2889 fix addon mysql account some not work
  erda.yml
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/table/table.go
  modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
  modules/dop/component-protocol/components/addon-mysql-account/filter/render.go
  modules/dop/component-protocol/components/addon-mysql-account/viewPassword/render.go
  modules/dop/component-protocol/components/addon-mysql-account/viewPasswordModal/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/config/configCopyParams/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/config/configDrawer/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/config/configPanel/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/editFormModal/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/filter/render.go
  modules/orchestrator/components/addon/mysql/kms.wrapper.go
  modules/orchestrator/components/addon/mysql/kms.wrapper.impl.go
  modules/orchestrator/components/addon/mysql/mysql.service.go
  modules/orchestrator/components/addon/mysql/mysql.service_test.go
  modules/orchestrator/components/addon/mysql/provider.go
  modules/orchestrator/dbclient/addon_mysql_account.go
  modules/orchestrator/initialize.go
  modules/orchestrator/services/addon/addon.go
  modules/orchestrator/services/addon/addon_handler.go
  modules/orchestrator/services/addon/addon_mysql.go
  modules/orchestrator/services/addon/addon_mysql_test.go
Labels: orchestrator, bugfix, approved

#2891 feat: 🎸 support bash cmd line
  go.mod
  go.sum
  modules/cmp/steve/middleware/audit.go
  modules/cmp/steve/middleware/dispatcher.go
  modules/cmp/steve/middleware/dispatcher_test.go
  modules/cmp/steve/websocket/decode.go
  modules/cmp/steve/websocket/decode_test.go
Labels: cmp, feature, approved

#2882 issues import support estimate time
  apistructs/issue.go
  apistructs/issue_test.go
  modules/dop/services/issue/convert.go
  modules/dop/services/issue/convert_test.go
  modules/dop/services/issue/import.go
  pkg/erda-configs/i18n/issue.json
Labels: dop, bug

#2911 init toolTip,value,path if report is nil
  modules/dop/component-protocol/components/code-coverage/treeMapChart/render.go
Labels: approved

#2916 fix the i18n in apim chart
  modules/hepa/provider.go
Labels: hepa, bugfix, approved

#2912 Hide iteration bar chart when single iteration is selected
  modules/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/model.go
  modules/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/render.go
  modules/dop/component-protocol/scenarios/issue-stats.yml
Labels: dop, feature, approved

#2922 make snippet task can be disable
  modules/pipeline/services/pipelinesvc/create_task.go
Labels: pipeline, bug, approved

#2920 refactor: 💡 add test, remove redundant code
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/common/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/common/utils.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoMapTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/utils.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/cpuTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/memTable/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
  modules/cmp/metrics/metrics.go
  modules/cmp/resource/class.go
  modules/cmp/steve/middleware/dispatcher.go
  modules/cmp/steve/middleware/dispatcher_test.go
Labels: cmp, refactor, approved

#2926 modify code coverage chart tooltip
  apistructs/code_coverage_exec_record.go
Labels: dop, bug

#2934 add cluster application in 1.4
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/msp/apm/alert/alert.service.go
Labels: approved

#2923 fix: remove itrIDs filter to rate scene and api chart
  modules/dop/dao/autotest_exec_history.go
  modules/dop/services/autotest_v2/testplan_v2.go
  modules/dop/services/autotest_v2/testplan_v2_test.go
Labels: dop, approved

#2936 Feature/fix addon mysql account
  apistructs/audits.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
  modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
  modules/dop/component-protocol/components/addon-mysql-account/common/datainit.go
  modules/dop/component-protocol/components/addon-mysql-attachment/editFormModal/render.go
  modules/orchestrator/components/addon/mysql/mysql.service.go
  modules/orchestrator/components/addon/mysql/mysql.service_test.go
  modules/orchestrator/components/addon/mysql/permission.wrapper.go
  modules/orchestrator/components/addon/mysql/provider.go
  pkg/erda-configs/audit/template.json
  pkg/erda-configs/permission/backend/sys/org/project/project.yml
Labels: approved

#2941 fix wrong audit template & missing params
  modules/orchestrator/components/addon/mysql/mysql.service.go
  modules/orchestrator/components/addon/mysql/mysql.service_test.go
  modules/orchestrator/components/addon/mysql/permission.wrapper.go
Labels: orchestrator, bugfix, approved

#2937 feature: ALTER TABLE ROW_FORMAT=DYNAMIC ;
  .erda/migrations/pipeline/20211026-pipeline-cron-row-format.sql
Labels: feature, approved

#2915 tk instead of tenantgroup
  modules/core/monitor/alert/alert-apis/adapt/customize.go
Labels: msp, bugfix

#2924 bugfix: history checker
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/checker.v1.service_test.go
  modules/msp/apm/checker/plugins/http/provider.go
Labels: msp, bugfix

#2945 fix typo
  pkg/erda-configs/audit/template.json
Labels: approved

#2933 Mbox deduplicate id column does not exceed the index length limit
  .erda/migrations/cmdb/20211102-mbox-deduplicateid-length.sql
Labels: dop, bugfix, approved

#2950 fix regexp pattern to support multiple line
  apistructs/audits.go
Labels: approved

#2952 close span query from es
  conf/msp/msp.yaml
Labels: approved

#2943 fix: 🐛 audit bug
  go.mod
  go.sum
  modules/cmp/steve/middleware/audit.go
  modules/cmp/steve/middleware/dispatcher.go
  modules/cmp/steve/middleware/dispatcher_test.go
Labels: approved

#2954 fix: 🐛 audit bug
  go.mod
  go.sum
  modules/cmp/steve/middleware/audit.go
  modules/cmp/steve/middleware/dispatcher.go
  modules/cmp/steve/middleware/dispatcher_test.go
Labels: approved

#2959 feature: add tip to test dashboard
  conf/dop/dop.yaml
  conf/dop/i18n/component-protocol.yaml
  modules/dop/component-protocol/components/test-dashboard/scenario.go
  modules/dop/component-protocol/components/test-dashboard/tip/render.go
  modules/dop/component-protocol/scenarios/test-dashboard.yml
Labels: dop, approved

#2921 bugfix pipeline repeated execution
  modules/pipeline/pipengine/reconciler/define.go
  modules/pipeline/pipengine/reconciler/listen.go
  modules/pipeline/pipengine/reconciler/listen_test.go
Labels: approved

#2961 set span es storage-reader optional to false
  modules/msp/apm/trace/query/provider.go
Labels: approved

#2960 polish: checker
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/checker.v1.service_test.go
Labels: approved

#2957 fix permission check
  .erda/migrations/cmdb/20211109-fix-sys-role.sql
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
  modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
  modules/dop/component-protocol/components/addon-mysql-account/common/datainit.go
  modules/dop/component-protocol/components/addon-mysql-account/viewPassword/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
  modules/orchestrator/components/addon/mysql/mysql.service.go
  modules/orchestrator/components/addon/mysql/mysql.service_test.go
Labels: approved

#2758 Auto test space archive status feature, space list support sort, filter by name, status
  .erda/migrations/qa/20211029-auto-test-space-archive-status.sql
  apistructs/audits.go
  apistructs/autotest_space.go
  apistructs/autotest_space_test.go
  bundle/autotest_space.go
  modules/dop/dao/autotest_space.go
  modules/dop/endpoints/autotests_space.go
  modules/dop/endpoints/endpoints.go
  modules/dop/services/autotest_v2/space.go
  modules/dop/services/autotest_v2/space_test.go
  modules/openapi/component-protocol/component_spec/button/spec.go
  modules/openapi/component-protocol/component_spec/form_modal/spec.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testscene_run.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/formModal/render.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/common/condition.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/filter/render.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/moreButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceFormModal/render.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/operation.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceList/render.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/protocol.yml
  pkg/erda-configs/audit/template.json
  pkg/erda-configs/i18n/autotest.json
Labels: dop, feature, approved

#2968 Update quick start kratos image version tags
  quick-start/docker-compose.yml
  quick-start/env
  quick-start/kratos/kratos.yml
Labels: dop, feature

#2967 feature: do not lint quota is less than request when the quota is not…
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
Labels: feature, approved

#2971 fix unit test
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadInfo/render_test.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/workloadStatus/render_test.go
Labels: cmp, bugfix

#2972 fix: accuracy group by owner
  apistructs/cmp_resource_overview.go
  conf/cmp/i18n/component-protocol.yaml
  modules/cmp/resource/report_table.go
Labels: bugfix, approved

#2980 fix: modify deployment name find methods
  modules/scheduler/executor/plugins/edas/edas.go
Labels: approved

#2910 refactor: manual test case&plan-case-relations paging use sql join
  .erda/migrations/qa/20211109-manual-test-fix-slow-sql.sql
  apistructs/testplan.go
  go.mod
  go.sum
  modules/dop/dao/testcase.go
  modules/dop/dao/testcase_test.go
  modules/dop/dao/testplan_testcase_relation.go
  modules/dop/dao/testplan_testcase_relation_test.go
  modules/dop/dao/testset.go
  modules/dop/dao/testset_test.go
  modules/dop/endpoints/testplan.go
  modules/dop/services/testcase/paging.go
  modules/dop/services/testplan/testplan.go
  modules/dop/services/testplan/testplan_test.go
  modules/dop/services/testset/create.go
Labels: dop, refactor

#2986 Update quick start identity schema
  quick-start/kratos/identity.schema.json
Labels: feature, approved

#2992 feature: upgrade quick-start components to v1.3
  quick-start/docker-compose.yml
  quick-start/env
  quick-start/quick-start.sh
Labels: approved, install

#2975 patch: 20211031-mysql-account.sql
  .erda/migrations/.patches/patch-20211031-mysql-account.sql
  .erda/migrations/orchestrator/20211031-mysql-account.sql
Labels: bugfix

#2981 fix mysql addon page slow
  modules/dop/component-protocol/components/addon-mysql-account/common/datainit.go
  modules/dop/component-protocol/components/addon-mysql-account/common/datainit_test.go
Labels: approved

#2996 fix: add dice_autotest_plan migration
  .erda/migrations/qa/20211110-auto-test-plan-update-data.sql
Labels: dop, approved

#2978 fix: query s_pod_info condition
  bundle/project.go
  bundle/quota.go
  go.mod
  go.sum
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
  modules/cmp/endpoints/cloud_resource_gateway.go
  modules/cmp/impl/addons/config.go
  modules/cmp/impl/aliyun-resources/clusterinfo.go
  modules/cmp/resource/report_table.go
  modules/cmp/resource/summary.go
  modules/cmp/tasks/collect_daily_quota.go
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/permission.go
  modules/core-services/endpoints/project.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
  modules/dop/services/pipeline/pipeline_test.go
  modules/dop/services/project/get.go
  modules/msp/apm/exception/query/exception.service_test.go
  modules/orchestrator/components/addon/mysql/mysql.service_test.go
  modules/orchestrator/components/addon/mysql/permission.wrapper.go
  pkg/http/httpclient/request_setter.go
  pkg/http/httpclient/request_setter_test.go
  pkg/swagger/ddlconv/test1.yml
  pkg/xmind/examples/xmind/a.xmind
Labels: approved

#2998 Hotfix/1.4/query pod info
  bundle/project.go
  bundle/quota.go
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
  modules/cmp/endpoints/cloud_resource_gateway.go
  modules/cmp/impl/addons/config.go
  modules/cmp/impl/aliyun-resources/clusterinfo.go
  modules/cmp/resource/report_table.go
  modules/cmp/resource/summary.go
  modules/cmp/tasks/collect_daily_quota.go
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/permission.go
  modules/core-services/endpoints/project.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
  modules/dop/services/pipeline/pipeline_test.go
  modules/dop/services/project/get.go
  modules/orchestrator/components/addon/mysql/mysql.service_test.go
  modules/orchestrator/components/addon/mysql/permission.wrapper.go
  pkg/http/httpclient/request_setter.go
  pkg/http/httpclient/request_setter_test.go
  pkg/swagger/ddlconv/test1.yml
  pkg/xmind/examples/xmind/a.xmind
Labels: bugfix

#2982 fix: 🐛 audit log start with new line
  go.mod
  go.sum
  modules/cmp/steve/middleware/audit.go
  modules/cmp/steve/middleware/dispatcher.go
  modules/cmp/steve/middleware/dispatcher_test.go
Labels: cmp, bugfix, approved

#2991 autotest not set bootstrap token
  modules/pipeline/pipengine/reconciler/reconcile.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare_test.go
Labels: pipeline, bug, approved

#3002 Update erda.yml
  erda.yml
Labels: install

#3005 shared bundle in auth
  modules/openapi/auth/user.go
Labels: approved

#3007 shared bundle in auth
  modules/openapi/auth/user.go
Labels: approved

#2892 autotest step concurrency interface display
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go
Labels: dop, bug

#3008 Feature/cache namespace belongs to
  modules/core-services/services/project/cache.go
  modules/core-services/services/project/cache_test.go
  modules/core-services/services/project/project.go
Labels: feature, approved

#3011 feature: cache workspace quota
  modules/core-services/services/project/cache.go
  modules/core-services/services/project/project.go
Labels: bugfix, approved

#2993 feature: update quick-start env file
  quick-start/env
  quick-start/nginx.conf
  quick-start/quick-start.sh
Labels: approved, install

#3014 shared http transport
  modules/extensions/loghub/index/query/clients.go
  pkg/http/httpclient/client.go
  pkg/http/httpclient/request.go
  pkg/http/httpclient/trace.go
Labels: approved

#3018 can not found projectID by tenant
  modules/msp/instance/permission/permission.go
  modules/msp/instance/service_type.go
Labels: approved

#3019 fix: remove envs in cluster-agent
  build/scripts/cluster-agent/shell-setup.sh
Labels: approved

#3016 Hotfix/query quota by once
  apistructs/core_services_quota.go
  apistructs/core_services_quota_test.go
  modules/cmp/resource/report_table.go
  modules/core-services/dao/project.go
  modules/core-services/initialize.go
  modules/core-services/services/project/cache.go
  modules/core-services/services/project/cache_test.go
  modules/core-services/services/project/project.go
Labels: bugfix, approved

#2987 polish: notify channel interaction optimization
  api/proto-go/core/services/notify/channel/client/client.go
  api/proto-go/core/services/notify/channel/pb/channel.form.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.http.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.json.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.pb.go
  api/proto-go/core/services/notify/channel/pb/channel.validator.pb.go
  api/proto-go/core/services/notify/channel/pb/channel_grpc.pb.go
  api/proto/core/services/notify/channel/channel.proto
  modules/core-services/services/notify/channel/db/notify_channel.go
  modules/core-services/services/notify/channel/notify.chanel.service.go
  modules/core-services/services/notify/channel/notify.chanel.service_test.go
Labels: msp

#3028 fix: delete cache
  modules/core-services/dao/project.go
  modules/core-services/services/project/cache.go
  modules/core-services/services/project/project.go
Labels: bugfix, approved

#3013 admin identity bugfix
  modules/admin/manager/cluster.go
  modules/admin/manager/cluster_test.go
Labels: admin, approved

#3003 fix dop slow sql
  .erda/migrations/cmdb/20211110-fix-slow-audit-and-ticket.sql
  .erda/migrations/qa/20211110-auto-test-fix-slow-sql.sql
  modules/core-services/services/audit/audit.go
Labels: dop, approved, polish

#2988 fix: upgrade falut tolerance
  modules/cluster-agent/client/client.go
  modules/cluster-agent/client/credential.go
  modules/cluster-dialer/server/dialer_test.go
  modules/cluster-dialer/server/tunnel-server_test.go
  modules/cmp/impl/clusters/credential.go
  modules/cmp/impl/clusters/credential_test.go
  modules/cmp/impl/clusters/import_cluster.go
Labels: cmp, cluster-manager, bugfix, approved

#3020 autotest loop step show info
  apistructs/pipeline_task.go
  apistructs/pipeline_task_test.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper_test.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/stages/model.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/stages/stages.go
Labels: approved

#3032 Fix auto test plan table column width, add scroll
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
Labels: dop, bugfix, approved

#3035 Fix illegal time data in issue dashboard scatter plot
  modules/dop/component-protocol/components/issue-dashboard/scatterPlot/render.go
  modules/dop/component-protocol/components/issue-dashboard/scatterPlot/render_test.go
Labels: dop, bugfix, approved

#3037 add success message
  conf/cmp/i18n/component-protocol.yaml
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/operationButton/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/render_test.go
  modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render_test.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/restartButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/model.go
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/render.go
Labels: approved

#3026 refactor: cmp/dop i18n support one config file per scenario
  conf/cmp/cmp.yaml
  conf/cmp/i18n/cp/common.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-events-list.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodedetail.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-poddetail.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-pods.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-workload-detail.yaml
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-workloads-list.yaml
  conf/dop/dop.yaml
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/addon-mysql-account.yaml
  conf/dop/i18n/cp/scenarios/addon-mysql-attachment.yaml
  conf/dop/i18n/cp/scenarios/code-coverage.yaml
  conf/dop/i18n/cp/scenarios/issue-dashboard.yml
  conf/dop/i18n/cp/scenarios/issue-manage.yaml
  conf/dop/i18n/cp/scenarios/scenes-import-record.yaml
  conf/dop/i18n/cp/scenarios/test-dashboard.yaml
  conf/dop/i18n/cp/scenarios/test-report.yaml
  go.mod
  go.sum
  modules/cmp/provider.go
  modules/dop/provider.go
  modules/dop/provider_test.go
Labels: dop, cmp, refactor, approved

#3040 fix: Recovery pass rate and execution rate statistics of auto test scene
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeInfo/render.go
Labels: dop, approved

#3027 bugfix: fix some problems about checker of apm
  .erda/migrations/msp/20211111-01-sp_metric.sql
  api/proto-go/msp/apm/checker/pb/checker_v1.form.pb.go
  api/proto-go/msp/apm/checker/pb/checker_v1.pb.go
  api/proto/msp/apm/checker/checker_v1.proto
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/checker.v1.service_test.go
  modules/msp/apm/checker/storage/db/checker.go
  modules/msp/apm/checker/storage/db/tables.go
Labels: msp, bugfix

#3044 fix: ignore platform namespaces
  modules/core-services/endpoints/namespace.go
Labels: bugfix, approved

#3036 Auto test space update time whenever elements in the space change
  apistructs/autotest_space.go
  apistructs/autotest_space_test.go
  bundle/autotest_space.go
  modules/dop/dao/autotest_space.go
  modules/dop/endpoints/autotest_scene.go
  modules/dop/endpoints/autotest_scene_step.go
  modules/dop/endpoints/autotests_space.go
  modules/dop/endpoints/scenesets.go
  modules/dop/services/autotest_v2/space.go
  modules/dop/services/sceneset/sceneset.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceAddButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceFormModal/render.go
  pkg/erda-configs/audit/template.json
Labels: dop, feature

#3042 use job cluster as cluster name if not empty
  apistructs/cluster_info.go
  modules/dop/services/pipeline/pipeline.go
  modules/dop/services/pipeline/pipeline_test.go
Labels: dop, bugfix, approved
