Repository erda-project/erda, pull requests merged in 2021-05, with the labels that each got.

#308 Topology bug fix
  modules/monitor/apm/topology/topology.go
Labels: bug

#488 update(doc): update install document
  docs/guides/deploy/How-to-install-the-Erda.md
Labels: lgtm

#381 modify loop calculate interval to make interval is accurate
  pkg/loop/interval.go
  pkg/loop/interval_test.go
Labels: v1.1

#494 feature/qa autotest space export and import
  apistructs/autotest_space.go
  go.mod
  go.sum
  modules/qa/endpoints/autotests_space.go
  modules/qa/endpoints/endpoint.go
  modules/qa/services/apierrors/errors.go
  modules/qa/services/autotest_v2/export.go
  modules/qa/services/autotest_v2/import.go
  modules/qa/services/autotest_v2/space_data.go
  modules/qa/services/i18n/i18n.go
  pkg/erda-configs/i18n/qa.json
  pkg/excel/export_by_cell.go
Labels: lgtm
