Repository erda-project/erda, pull requests merged in 2021-06, with the labels that each got.

#505 Remove host in items with API files path
  modules/cmdb/endpoints/application.go
  modules/cmdb/endpoints/organization.go
  modules/cmdb/services/issue/convert.go
  modules/cmdb/services/project/project.go
  pkg/filehelper/path.go
  pkg/filehelper/path_test.go
Labels: lgtm

#485 fix: change map to sync map to avoid concurrent problem
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/endpoints/addon_test.go
  modules/orchestrator/services/addon/addon.go
  modules/orchestrator/services/addon/addon_test.go
  modules/orchestrator/services/addon/microservice.go
  modules/orchestrator/services/addon/middleware.go
  pkg/license/license_key.txt
  pkg/swagger/openapi/ddl/test1.yml
  pkg/xmind/examples/xmind/a.xmind
Labels: lgtm

#513 modify quick start
  quick-start/docker-compose.yml
  quick-start/env
Labels: lgtm

#434 autotest move scene check in same sceneSet not have same pre_id scene
  modules/qa/dao/autotest_scene.go
Labels: lgtm

#397 snippet detail return all action output
  apistructs/extention.go
  apistructs/pipeline_yml.go
  modules/pipeline/services/snippetsvc/action_output_handler.go
  modules/pipeline/services/snippetsvc/action_output_handler_test.go
  modules/pipeline/services/snippetsvc/snippet_output_query.go
  modules/pipeline/services/snippetsvc/snippet_output_query_test.go
  pkg/expression/expression_reconcile.go
Labels: lgtm, v1.1

#423 fix(pipeline): action if expression handle unexpected panic
  pkg/expression/expression_reconcile.go
  pkg/expression/expression_reconcile_test.go
Labels: lgtm

#509 test plan generate performance optimization
  modules/qa/services/testplan/report.go
Labels: lgtm

#499 fix: host-based job scheduling
  modules/scheduler/executor/plugins/k8s/nodelabel.go
  modules/scheduler/executor/plugins/k8sjob/job.go
  modules/scheduler/schedulepolicy/constraintbuilders/k8s/build.go
Labels: lgtm

#496 fix: update the link of dingding push
  modules/gittar/api/merge.go
Labels: lgtm

#516 issue statistics iterator search error
  apistructs/iteration.go
  modules/cmdb/endpoints/iteration.go
Labels: lgtm

#520 fix: cancel line character limit of commit's and compare's response
  modules/gittar/pkg/gitmodule/repo_diff.go
Labels: lgtm

#522 feat: first user become admin, only if kratos enabled
  modules/cmdb/services/member/member.go
Labels: lgtm

#519 customize alert rule filter the application_id
  conf/monitor/monitor.yaml
  modules/monitor/alert/alert-apis/adapt/adapt.go
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/provider.go
  modules/monitor/alert/storage/alert-record/consumer.go
  modules/monitor/notify/template/query/provider.go
Labels: lgtm

#506 ElasticSearch query engine support diff and diffps functions
  go.mod
  go.sum
  modules/monitor/core/metrics/metricq/es-tsql/functions.go
  modules/monitor/core/metrics/metricq/es-tsql/influxql/functions.go
  modules/monitor/core/metrics/metricq/es-tsql/influxql/query.go
  modules/monitor/core/metrics/metricq/es-tsql/tsql-test/main.go
Labels: lgtm, v1.1

#523 update image to dockerhub for quickstart
  quick-start/docker-compose.yml
  quick-start/env
Labels: lgtm

#532 Hide fields that should not be displayed
  conf/monitor/monitor/monitor.yaml
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/provider.go
Labels: lgtm

#528 Fix/workbench public org bug
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectContent/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectTitle/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgSwitch/render.go
  pkg/erda-configs/i18n/workbench.json
Labels: lgtm

#535 before run check add millisecond field
  apistructs/pipeline_queue.go
  modules/pipeline/aop/plugins/pipeline/plugins/precheck_before_pop/before_run_check.go
  modules/pipeline/aop/plugins/pipeline/plugins/precheck_before_pop/plugin.go
  modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go
Labels: lgtm

#531 Feature/autotest run detail render retrofit
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go
  modules/qa/services/autotest_v2/testplan_v2.go
Labels: lgtm

#541 fix monitor config
  cmd/monitor/collector/main.go
  cmd/monitor/monitor/main.go
  cmd/monitor/streaming/main.go
Labels: lgtm

#545 Adjust codecov project target from 15% to 10%
  codecov.yml
Labels: lgtm

#543 add erda.yml
  erda.yml
Labels: lgtm

#540 feature(pipeline): queue polish the logic to set needReRangePendingQueue flag
  modules/pipeline/pipengine/queue/priorityqueue/priority_queue.go
  modules/pipeline/pipengine/queue/priorityqueue/priority_queue_test.go
  modules/pipeline/pipengine/reconciler/queuemanage/queue/add_pipeline.go
  modules/pipeline/pipengine/reconciler/queuemanage/queue/define.go
  modules/pipeline/pipengine/reconciler/queuemanage/queue/range_pending_queue.go
Labels: lgtm

#553 Reconstruction anomaly analysis
  modules/monitor/apm/topology/topology.go
Labels: lgtm

#555 Feature/autotest return error and render
  modules/openapi/api/apis/openapi/component_protocol/render.go
  modules/openapi/component-protocol/protocol.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/tabExecuteButton/executeButton.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/tabExecuteButton/executeButton.go
Labels: lgtm

#549 Fix/workbench jumplink logolink
  modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/model.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTip/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgSwitch/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/projectTipWithoutOrg/render.go
Labels: lgtm

#558 fix: org create failure in local erda
  quick-start/docker-compose.yml
Labels: lgtm

#551 add dice.yml
  erda.yml
Labels: lgtm

#544 fix autotest space copy input scene id bug
  modules/qa/endpoints/autotests_space.go
  modules/qa/endpoints/endpoint.go
  modules/qa/services/autotest_v2/space.go
  modules/qa/services/autotest_v2/space_data.go
Labels: lgtm

#548 Polish PR template for erda-style
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm

#565 External topology node data
  modules/monitor/apm/topology/topology.go
Labels: lgtm

#567 Add exception analysis operations grouped according to error id
  modules/monitor/apm/topology/topology.go
Labels: lgtm

#533 Hide fields that should not be displayed merge to release
  conf/monitor/monitor.yaml
  modules/monitor/alert/alert-apis/adapt/adapt.go
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/provider.go
  modules/monitor/alert/storage/alert-record/consumer.go
Labels: lgtm

#575 fix golangci exclude
  .golangci.yml
Labels: lgtm

#446 bugfix/cluster status algo fix
  modules/monitor/dashboard/org-apis/service.go
  modules/monitor/dashboard/org-apis/service_test.go
Labels: lgtm

#574 add readme section of quickstart
  README.md
  docs/assets/quickstart_create_org.jpg
  docs/assets/quickstart_personal_dashboard.jpg
  docs/assets/quickstart_switch_to_signup.jpg
  docs/guides/quickstart/quickstart-full.md
Labels: lgtm

#580 polish manual testcase export
  apistructs/testcase.go
  apistructs/testplan.go
  modules/qa/dbclient/apitest.go
  modules/qa/services/testcase/apis.go
  modules/qa/services/testcase/apitest.go
  modules/qa/services/testcase/convert.go
  modules/qa/services/testcase/export.go
  modules/qa/services/testcase/export_excel.go
  modules/qa/services/testcase/paging.go
  modules/qa/services/testplan/export.go
  pkg/excel/export_by_cell.go
Labels: lgtm

#581 Add kratos config in gittar, openapi posthandler
  modules/gittar/conf/conf.go
  modules/gittar/uc/user_center.go
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go
  modules/openapi/hooks/posthandle/injectuserinfo.go
  modules/openapi/hooks/posthandle/injectuserinfo_test.go
  pkg/ucauth/kratos.go
  pkg/ucauth/user_admin.go
Labels: lgtm

#579 Feature/msp menu api
  cmd/msp/main.go
  conf/msp/msp.yaml
  conf/resources.go
  go.mod
  go.sum
  modules/msp/instance/db/instance.go
  modules/msp/instance/db/instance_tenant.go
  modules/msp/instance/db/tables.go
  modules/msp/menu/db/menu.go
  modules/msp/menu/db/tables.go
  modules/msp/menu/menu.service.go
  modules/msp/menu/menu.service_test.go
  modules/msp/menu/provider.go
  modules/msp/menu/test.http
  pkg/common/apis/response.go
Labels: lgtm

#576 update readme, capitalize word
  README.md
Labels: lgtm

#566 Feature/autotest add mock value tooltip
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/helper.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/inParamsForm/inParamsForm.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/inParamsForm/model.go
  pkg/erda-configs/i18n/autotest.json
  pkg/expression/expression_reconcile.go
Labels: lgtm

#550 Feature/cron metric issue
  apistructs/issue.go
  modules/cmdb/conf/conf.go
  modules/cmdb/dao/issue.go
  modules/cmdb/endpoints/endpoints.go
  modules/cmdb/initialize.go
  modules/cmdb/services/monitor/monitor.go
Labels: lgtm

#585 snippet query app yml error, end with /.dice/pipelines/xx.yml will not find branch
  modules/gittar-adaptor/endpoints/snippet.go
  modules/gittar-adaptor/endpoints/snippet_test.go
  pkg/pipeline_snippet_client/snippet_client.go
Labels: lgtm

#583 Add topology getDashboardId() method ut
  modules/monitor/apm/topology/topology_test.go
Labels: lgtm

#369 fix: remove the devops auth of edgeOps
  pkg/erda-configs/permission/front/org/org.yml
Labels: lgtm

#590 docs(install): add simplified chinese install doc
  README.md
  docs/guides/deploy/How-to-install-the-Erda-zh.md
  docs/guides/deploy/How-to-install-the-Erda.md
Labels: lgtm

#578 exclude file
  .golangci.yml
Labels: lgtm

#588 Fix issue custom stages created with null value
  modules/cmdb/services/issue/stage.go
Labels: lgtm

#592 add components for create org
  apistructs/component_protocol.go
  apistructs/org.go
  bundle/org.go
  erda.yml
  modules/cmdb/conf/conf.go
  modules/cmdb/endpoints/organization.go
  modules/cmdb/services/org/org.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyOrgContent/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createOrgBtn/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createOrgBtnWrapper/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTipWithoutOrg/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgTitle/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/protocol.yml
  modules/openapi/conf/conf.go
  pkg/erda-configs/i18n/workbench.json
Labels: lgtm

#595 update(docs): update install documents format
  docs/guides/deploy/How-to-install-the-Erda-zh.md
  docs/guides/deploy/How-to-install-the-Erda.md
Labels: lgtm

#597 update erda.yml
  erda.yml
Labels: lgtm

#596 update(doc): add Simplified Chinese install document
  README.md
  docs/guides/deploy/How-to-install-Erda-zh.md
  docs/guides/deploy/How-to-install-Erda.md
Labels: lgtm

#601 Modify link to public project menu in my projects page
  modules/openapi/component-protocol/scenarios/project-list-my/components/emptyText/model.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/emptyText/render.go
Labels: lgtm

#598 feature: add migration lint to github ci
  .github/workflows/ci-it.yml
  tools/cli/cmd/migration_lint.go
Labels: lgtm

#603 batch create pipeline lost storageConfig then pipeline run will lost nfs volume
  modules/pipeline/services/pipelinesvc/create.go
Labels: lgtm

#605 define common errors, config center apis
  cmd/msp/main.go
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/msp/configcenter/config.center.service.go
  modules/msp/configcenter/config.center.service_test.go
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/configcenter/provider.go
  modules/msp/configcenter/test.http
  modules/msp/instance/db/tables.go
  modules/msp/menu/menu.service.go
  pkg/common/apis/response.go
  pkg/common/errors/authorization.go
  pkg/common/errors/data.go
  pkg/common/errors/errors.go
  pkg/common/errors/parameter.go
  pkg/common/errors/server.go
  pkg/common/permission/permission.go
Labels: lgtm

#521 Feature/batch create labels and page labels
  apistructs/pipeline_label.go
  modules/pipeline/dbclient/op_pipeline_labels.go
  modules/pipeline/endpoints/endpoints.go
  modules/pipeline/endpoints/pipeline.http
  modules/pipeline/endpoints/pipeline_label.go
  modules/pipeline/services/apierrors/errors.go
  modules/pipeline/services/pipelinesvc/create_label.go
Labels: lgtm

#608 protobuf data validate, config center apis permission
  go.mod
  go.sum
  modules/msp/configcenter/config.center.service.go
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/configcenter/provider.go
  modules/msp/configcenter/test.http
  modules/msp/instance/permission/permission.go
  modules/msp/menu/test.http
  pkg/common/apis/response.go
  pkg/common/errors/parameter.go
Labels: lgtm

#562 subscribe issue
  .erda/migrations/cmdb/20210610-addIssueSubscriber.sql
  apistructs/issue.go
  modules/cmdb/dao/issue_subscriber.go
  modules/cmdb/endpoints/endpoints.go
  modules/cmdb/endpoints/issue.go
  modules/cmdb/services/apierrors/errors.go
  modules/cmdb/services/issue/convert.go
  modules/cmdb/services/issue/issue.go
  modules/openapi/api/apis/cmdb/cmdb_issue_subscribe.go
  modules/openapi/api/apis/cmdb/cmdb_issue_unsubscribe.go
  modules/openapi/api/apis/orchestrator/orchestrator_micro_service_projects.go
Labels: lgtm

#584 feature: add cluster-manager
  apistructs/cluster.go
  bundle/bundle.go
  bundle/cluster.go
  bundle/ecp.go
  bundle/events.go
  bundle/urls.go
  cmd/cluster-manager/main.go
  conf/cluster-manager/cluster-manager.yaml
  modules/cluster-manager/conf/conf.go
  modules/cluster-manager/dbclient/cluster.go
  modules/cluster-manager/dbclient/dbclient.go
  modules/cluster-manager/endpoints/cluster.go
  modules/cluster-manager/endpoints/endpoints.go
  modules/cluster-manager/endpoints/prehandle.go
  modules/cluster-manager/initialize.go
  modules/cluster-manager/model/model.go
  modules/cluster-manager/provider.go
  modules/cluster-manager/services/apierrors/errors.go
  modules/cluster-manager/services/cluster/cluster.go
  pkg/discover/address.go
  pkg/k8sclient/client.go
Labels: cluster-manager, feature

#609 fix: update the proxy host of testplatform
  modules/openapi/api/apis/dop/adaptor_cicd_config_namespaces.go
  modules/openapi/api/apis/dop/adaptor_cicd_config_workspaces.go
  modules/openapi/api/apis/testplatform/autotest/autotests_reportsets_list.go
  modules/openapi/api/apis/testplatform/autotest/autotests_scenes_cancel.go
  modules/openapi/api/apis/testplatform/autotest/autotests_scenes_execute.go
  modules/openapi/api/apis/testplatform/autotest/batch-query-pipeline-snippet-yml.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_copy.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_create.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_delete.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_find_ancestors.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_fuzzy_search.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_get.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_history_list.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_list.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_move.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_save_pipeline.go
  modules/openapi/api/apis/testplatform/autotest/filetree_node_update_basic_info.go
  modules/openapi/api/apis/testplatform/autotest/global_config_create.go
  modules/openapi/api/apis/testplatform/autotest/global_config_delete.go
  modules/openapi/api/apis/testplatform/autotest/global_config_list.go
  modules/openapi/api/apis/testplatform/autotest/global_config_update.go
  modules/openapi/api/apis/testplatform/autotest/query-pipeline-snippet-yml.go
  modules/openapi/api/apis/testplatform/testcase/batch_clean_from_recycle_bin.go
  modules/openapi/api/apis/testplatform/testcase/batch_copy.go
  modules/openapi/api/apis/testplatform/testcase/batch_update.go
  modules/openapi/api/apis/testplatform/testcase/create.go
  modules/openapi/api/apis/testplatform/testcase/export.go
  modules/openapi/api/apis/testplatform/testcase/get.go
  modules/openapi/api/apis/testplatform/testcase/import.go
  modules/openapi/api/apis/testplatform/testcase/paging.go
  modules/openapi/api/apis/testplatform/testcase/update.go
  modules/openapi/api/apis/testplatform/testplan/apitest_cancel.go
  modules/openapi/api/apis/testplatform/testplan/apitest_execute.go
  modules/openapi/api/apis/testplatform/testplan/autotests_testplan_execute.go
  modules/openapi/api/apis/testplatform/testplan/autotests_testplan_paging.go
  modules/openapi/api/apis/testplatform/testplan/create.go
  modules/openapi/api/apis/testplatform/testplan/delete.go
  modules/openapi/api/apis/testplatform/testplan/generate_report.go
  modules/openapi/api/apis/testplatform/testplan/get.go
  modules/openapi/api/apis/testplatform/testplan/list.go
  modules/openapi/api/apis/testplatform/testplan/list_testsets.go
  modules/openapi/api/apis/testplatform/testplan/rel/add_issue_relation.go
  modules/openapi/api/apis/testplatform/testplan/rel/batch_update.go
  modules/openapi/api/apis/testplatform/testplan/rel/create.go
  modules/openapi/api/apis/testplatform/testplan/rel/export.go
  modules/openapi/api/apis/testplatform/testplan/rel/get.go
  modules/openapi/api/apis/testplatform/testplan/rel/paging.go
  modules/openapi/api/apis/testplatform/testplan/rel/remove_issue_relation.go
  modules/openapi/api/apis/testplatform/testplan/update.go
  modules/openapi/api/apis/testplatform/testset/clean_from_recycle_bin.go
  modules/openapi/api/apis/testplatform/testset/copy.go
  modules/openapi/api/apis/testplatform/testset/create.go
  modules/openapi/api/apis/testplatform/testset/get.go
  modules/openapi/api/apis/testplatform/testset/list.go
  modules/openapi/api/apis/testplatform/testset/recover_from_recycle_bin.go
  modules/openapi/api/apis/testplatform/testset/recycle.go
  modules/openapi/api/apis/testplatform/testset/rename.go
Labels: approved

#610 bugfix(dop): issue retain creator&assignee&createdAt&manHour after type changing
  modules/cmdb/services/issue/issue.go
Labels: approved, bugfix, dop

#602 Optimize the rate limiter parameters
  modules/volume-provisioner/deploy/all-in-one.yaml
  modules/volume-provisioner/deploy/pvc.yaml
  modules/volume-provisioner/deploy/storageclass.yaml
  modules/volume-provisioner/initialize.go
  modules/volume-provisioner/provider.go
Labels: approved, refactor

#617 msp registercenter api
  cmd/msp/main.go
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/msp/configcenter/config.center.service.go
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/instance/connom.go
  modules/msp/instance/db/instance.go
  modules/msp/instance/db/instance_tenant.go
  modules/msp/instance/db/tables.go
  modules/msp/registercenter/nacos/adapter.go
  modules/msp/registercenter/nacos/service_search_result.go
  modules/msp/registercenter/provider.go
  modules/msp/registercenter/register.center.service.go
  modules/msp/registercenter/register.center.service.host.go
  modules/msp/registercenter/register.center.service.host.runtime.go
  modules/msp/registercenter/register.center.service.monitor.go
  modules/msp/registercenter/register.center.service.route.go
  modules/msp/registercenter/zkproxy/adapter.go
  pkg/common/errors/parameter_test.go
  pkg/database/gormutil/gorm.go
  pkg/http/httputil/url.go
  pkg/http/httputil/url_test.go
Labels: approved

#614 add free org
  apistructs/org.go
  modules/cmdb/endpoints/organization.go
  modules/cmdb/model/organization.go
  modules/cmdb/services/org/org.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
Labels: approved, core feature, feature

#616 feature(dicehub): extension spec parse supportedVersions field from `supportedErdaVersions` tag
  apistructs/extention.go
Labels: approved, dop

#624 Hide and reorder disabled Issue state button in issue table
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go
Labels: approved

#626 list runtime doesn't return all runtimes
  apistructs/runtime_dto.go
  modules/orchestrator/services/runtime/runtime.go
Labels: approved, bugfix, dop

#599 render return error then continue render info and show error info
  modules/openapi/api/apis/openapi/component_protocol/render.go
  modules/openapi/component-protocol/scenario_render.go
Labels: bugfix, openapi

#627 feature: add cluster-manager && cluster-dialer
  erda.yml
  modules/cluster-manager/conf/conf.go
  modules/ecp/conf/conf.go
Labels: cluster-manager

#623 feat: update wechat QRcode
  docs/assets/wechat-small.jpg
  docs/assets/wechat.jpg
Labels: approved, documentation

#635 pipeline run user use nick info not user name
  apistructs/pipeline_dto.go
Labels: approved

#615 request config query simple pipeline base detail
  apistructs/cicd.go
  apistructs/pipeline.go
  bundle/pipeline.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/pipeline.go
  modules/openapi/api/apis/dop/adaptor_cicd_pipeline-detail.go
  modules/pipeline/endpoints/pipeline.go
  modules/pipeline/services/pipelinesvc/convert.go
  modules/pipeline/services/pipelinesvc/convert_test.go
  modules/pipeline/services/pipelinesvc/detail.go
  modules/pipeline/services/pipelinesvc/detail_test.go
Labels: feature

#628 feature: cluster-dialer support register
  go.mod
  go.sum
  modules/cluster-dialer/server/tunnel-server.go
Labels: approved, feature

#634 fix(service): on project namespace create service error
  apistructs/service.go
  modules/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  modules/scheduler/executor/plugins/k8s/addon/interface.go
  modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
  modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
  modules/scheduler/executor/plugins/k8s/daemonset.go
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/plugins/k8s/k8s_stateful.go
  modules/scheduler/executor/plugins/k8s/k8sservice/service.go
  modules/scheduler/executor/plugins/k8s/runtime.go
  modules/scheduler/executor/plugins/k8s/service.go
Labels: bugfix

#643 Public org list link update, remove org creation button
  modules/openapi/component-protocol/scenarios/org-list-all/components/createButton/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/protocol.yml
Labels: approved

#646 Public org list link and button update (#643)
  modules/openapi/component-protocol/scenarios/org-list-all/components/createButton/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/protocol.yml
Labels: approved

#647 Hotfix/workbench org create
  apistructs/component_protocol.go
  apistructs/org.go
  bundle/org.go
  modules/cmdb/conf/conf.go
  modules/cmdb/endpoints/organization.go
  modules/cmdb/services/org/org.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyOrgContent/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createOrgBtn/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createOrgBtnWrapper/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTipWithoutOrg/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgTitle/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/protocol.yml
  modules/openapi/conf/conf.go
  pkg/erda-configs/i18n/workbench.json
Labels: approved

#650 Feature/gereng org
  apistructs/org.go
  modules/cmdb/endpoints/organization.go
  modules/cmdb/model/organization.go
  modules/cmdb/services/org/org.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
Labels: approved

#651 [cherry-pick] fix(service): on project namespace create service error
  apistructs/service.go
  modules/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  modules/scheduler/executor/plugins/k8s/addon/interface.go
  modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
  modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
  modules/scheduler/executor/plugins/k8s/daemonset.go
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/plugins/k8s/k8s_stateful.go
  modules/scheduler/executor/plugins/k8s/k8sservice/service.go
  modules/scheduler/executor/plugins/k8s/runtime.go
  modules/scheduler/executor/plugins/k8s/service.go
Labels: auto-cherry-pick

#644 update runtime's scale
  apistructs/service.go
  bundle/servicegroup.go
  modules/orchestrator/dbclient/runtime_test.go
  modules/orchestrator/endpoints/server_handler.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/services/runtime/runtime_test.go
Labels: approved, dop, feature

#542 Asynchronous import/export of test cases, add file records table
  apistructs/file_records.go
  apistructs/testcase.go
  modules/dop/conf/conf.go
  modules/dop/dao/file_records.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/file_records.go
  modules/dop/endpoints/testcase.go
  modules/dop/initialize.go
  modules/dop/services/apierrors/errors.go
  modules/dop/services/testcase/export.go
  modules/dop/services/testcase/file_records.go
  modules/dop/services/testcase/import.go
  modules/openapi/api/apis/dop/qa_records_get.go
  modules/openapi/api/apis/dop/qa_records_list.go
  pkg/excel/export_by_cell.go
  pkg/http/httpclient/request.go
  pkg/xmind/xml.go
Labels: dop, feature

#661 fix: order by mr list by id desc
  modules/gittar/api/merge.go
  modules/gittar/models/merge_request.go
Labels: approved, dop, feature

#656 if autotest scene not have step, execute test plan include this scene will return error（not find snippet config）
  modules/dop/services/autotest_v2/scene.go
Labels: approved, bugfix, dop

#658 autotest cookie keep, sometimes create pipeline report too faster, one second create two cookie report, when get cookie by create time desc will get old cookie
  modules/pipeline/dbclient/op_pipeline_report.go
Labels: approved, bugfix, pipeline

#629 Fix custom issue panel query, issue button operation key update
  apistructs/issue.go
  modules/dop/dao/issue.go
  modules/dop/services/issuepanel/issue_panel.go
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueTable/render.go
Labels: approved, bugfix, dop

#664 feat(resource): update request resource with ratio directly
  .github/workflows/ci-it.yml
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/impl/servicegroup/scale.go
Labels: approved

#670 use sync to strategy compensate cron job, and add cron interval conf
  modules/pipeline/conf/conf.go
  modules/pipeline/services/pipelinesvc/cron_compensate.go
  modules/pipeline/services/pipelinesvc/cron_compensate_test.go
Labels: approved

#673 fix: recover cmdb health check for integrate
  modules/cmdb/endpoints/endpoints.go
  modules/cmdb/endpoints/health.go
  modules/cmdb/endpoints/info.go
Labels: approved

#679 optimize runtime api recycle
  modules/hepa/gateway/service/gateway_api_service.go
  modules/hepa/gateway/service/gateway_runtime_service_service.go
  modules/hepa/gateway/service/interface.go
  modules/hepa/repository/service/gateway_api_service.go
  modules/hepa/repository/service/interface.go
Labels: approved, hepa

#678 fix: move task-error api spec to core-services
  modules/openapi/api/apis/core_services/cmdb_error_log_create.go
  modules/openapi/api/apis/core_services/cmdb_errorbox_list.go
Labels: approved, bugfix

#672 fix: solve the problem of org list query failure caused by refactor
  bundle/org.go
  modules/dop/endpoints/organization.go
Labels: approved

#677 fix: add needApproval field of pipeline list response
  apistructs/pipeline_dto.go
  modules/pipeline/services/pipelinesvc/detail.go
Labels: approved, pipeline, refactor

#681 feature: update front permission
  pkg/erda-configs/permission/front/org/org.yml
Labels: approved

#675 Compensation strategy and timed task creation conflict resolution, compensation strategy asynchronously sets the number of concurrent
  modules/gittar/pkg/gc/gc.go
  modules/pipeline/conf/conf.go
  modules/pipeline/services/pipelinesvc/cron_compensate.go
  pkg/limit_sync_group/group.go
  pkg/limit_sync_group/group_test.go
Labels: approved

#680 migrate sql&registry ops logic from soldier to pkg
  modules/cluster-dialer/server/dialer_test.go
  modules/cluster-dialer/server/tunnel-server_test.go
  pkg/clusterdialer/dialer.go
  pkg/discover/address.go
  pkg/http/httpclient/client.go
  pkg/mysqlhelper/mysql.go
  pkg/registryhelper/manifests.go
Labels: refactor

#686 fix: cmdb can't get cluster
  bundle/org.go
  modules/cmdb/initialize.go
  modules/cmdb/services/cluster/cluster.go
Labels: admin, bugfix

#685 Feature/pkg secret algorithm
  pkg/secret/hmac/hmac.go
  pkg/secret/hmac/hmac_test.go
  pkg/secret/hmac/option.go
  pkg/secret/secret.go
  pkg/secret/validator/validator.go
  pkg/secret/validator/validator_test.go
Labels: approved, feature

#667 Feature/gittar repo optimize
  modules/core-services/endpoints/application.go
  modules/gittar/auth/auth.go
  modules/gittar/initialize.go
Labels: dop, feature

#687 fix: fix the bug caused by refactor
  modules/cmdb/initialize.go
  modules/core-services/conf/conf.go
  modules/core-services/endpoints/license.go
  modules/dop/conf/conf.go
  modules/openapi/api/apis/orchestrator/orchestrator_micro_service_projects.go
Labels: approved, bugfix, dop

#692 fix: update conf of core-services
  modules/core-services/conf/conf.go
Labels: approved

#701 add guest permissions for dashboard and ticket
  pkg/erda-configs/permission/front/org/project/project.yml
Labels: approved

#696 pipeline detail code optimization
  modules/pipeline/services/pipelinesvc/detail.go
Labels: approved

#688 use pkg/registryhelper instead of remote soldier access
  modules/dicehub/initialize.go
  modules/dicehub/recycle/cron.go
  modules/dicehub/registry/manifests.go
  modules/dicehub/service/release/release.go
Labels: approved, refactor

#706 fix: update bundle.WithCMDB() to bundle.WithCoreServices
  bundle/notice.go
  bundle/org.go
  modules/action-runner-scheduler/initialize.go
  modules/cmp/initialize.go
  modules/dicehub/initialize.go
  modules/dop/initialize.go
  modules/ecp/initialize.go
  modules/eventbox/dispatcher/dispatcher.go
  modules/eventbox/webhook/http.go
  modules/extensions/cloud/aliyun/metrics/cloudcat/api/limiter.go
  modules/extensions/loghub/index/query/provider.go
  modules/extensions/loghub/metrics/rules/provider.go
  modules/extensions/loghub/sls-import/provider.go
  modules/gittar/initialize.go
  modules/hepa/bundle/dice_bundle.go
  modules/monitor/alert/alert-apis/provider.go
  modules/monitor/apm/report/provider.go
  modules/monitor/common/permission/permission.go
  modules/monitor/core/logs/schema/manager.go
  modules/monitor/dashboard/org-apis/provider.go
  modules/monitor/dashboard/report/apis/provider.go
  modules/monitor/notify/template/query/provider.go
  modules/monitor/settings/provider.go
  modules/openapi/api/apis/uc/uc_pwd_security_config_get.go
  modules/openapi/api/apis/uc/uc_user_update_userinfo.go
  modules/openapi/auth/user.go
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueGantt/render_test.go
  modules/openapi/loginserver.go
  modules/orchestrator/initialize.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/impl/terminal/terminal.go
  modules/uc-adaptor/initialize.go
  pkg/common/permission/provider.go
Labels: approved

#708 feature: update UI permission key
  pkg/erda-configs/permission/front/org/org.yml
Labels: approved

#589 process instance info(show ip)
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
Labels: approved

#693 put the loop strategy in the framework.go, the task during the loop no longer has a end state at the databases, and it is directly updated to the analyzed state after the loop sleep
  modules/pipeline/pipengine/reconciler/task.go
  modules/pipeline/pipengine/reconciler/taskrun/framework.go
  modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
Labels: approved

#690 feature: add new baseline
  .erda/migrations/monitor/20210531-01-monitor-base.sql
  .erda/migrations/monitor/20210602-01-monitor-base.sql
  .erda/migrations/monitor/20210602-02-monitor-base.sql
  .erda/migrations/monitor/20210607-01-monitor-base.sql
  .erda/migrations/monitor/20210607-02-monitor-base.sql
  .erda/migrations/monitor/20210610-01-monitor-base.sql
  .erda/migrations/orchestrator/20210604-orchestrator-base.sql
  .erda/migrations/qa/20210608-qa-base.sql
Labels: approved, feature

#684 Feature/log download naming
  modules/monitor/core/logs/query/query.go
  modules/monitor/core/logs/query/routes.go
Labels: approved, feature

#682 Test case file records table migration
  .erda/migrations/qa/20210625-test-file-records.sql
Labels: approved, dop, feature

#691 fix(scheduler): optimize scheduler try delete ds or deploy
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: approved

#714 feat: update config page target key
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/components/appSiteBreadcrumb/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/appSiteManage/render.go
  modules/openapi/component-protocol/scenarios/edge-application/components/applicationList/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet/components/configSetList/render.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteList/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go
  modules/openapi/component-protocol/scenarios/org-list-my/components/list/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/browsePublicProjects/render.go
  pkg/erda-configs/permission/front/org/org.yml
Labels: approved

#713 bugfix: task loop reset flags for wait step timeout
  modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
Labels: approved

#712 bugfix autotest scenario outputs, can not showing the children output
  modules/dop/services/autotest_v2/scene_step.go
Labels: approved

#715 bugfix(pipeline): task loop reset flags for wait step timeout
  modules/pipeline/pipengine/reconciler/task_loop.go
Labels: approved

#711 fix(soldier): the error file path for edas
  build/dockerfiles/Dockerfile
  build/dockerfiles/soldier/Dockerfile
  modules/soldier/autoop/cron.go
Labels: approved

#718 fix(edas): scale will restart pod
  modules/scheduler/executor/plugins/edas/edas.go
Labels: approved

#721 Revert "feat: increase guest permissions for dashboard and ticket (#7…
  pkg/erda-configs/permission/front/org/project/project.yml
Labels: approved

#695 fix(scheduler): optimize scheduler try delete ds or deploy
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: approved

#723 remove tar.gz from dockerfile
  build/dockerfiles/Dockerfile
Labels: approved

#727 fix kong addr acquire logic & add UT
  modules/hepa/repository/service/gateway_kong_info_service.go
  modules/hepa/repository/service/gateway_kong_info_service_test.go
Labels: approved

#638 permission code refactor, app scopeType permission extension project-app permission
  apistructs/application.go
  modules/core-services/endpoints/permission.go
  modules/core-services/services/permission/permission.go
  modules/core-services/services/security/adaptor.go
  modules/core-services/services/security/handler.go
  modules/core-services/services/security/process.go
  modules/core-services/utils/appmode.go
  modules/core-services/utils/appmode_test.go
  modules/dop/endpoints/pipeline.go
  modules/dop/endpoints/pipeline_test.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  pkg/http/httputil/header.go
Labels: approved, core feature

#726 feature: issueKanban support loadMore event
  apistructs/component_protocol.go
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/issue_kanban.go
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/render.go
Labels: approved

#719 [cherry-pick] fix(soldier): the error file path for edas
  build/dockerfiles/Dockerfile
  build/dockerfiles/soldier/Dockerfile
  modules/soldier/autoop/cron.go
Labels: approved

#728 fix: remove the case that dop call dop
  bundle/filetree.go
  modules/dop/endpoints/application.go
  modules/dop/endpoints/configmanage.go
  modules/dop/endpoints/issue.go
  modules/dop/endpoints/pipeline.go
  modules/dop/endpoints/release.go
  modules/dop/initialize.go
  modules/dop/services/apidocsvc/api_docs.go
  modules/dop/services/apidocsvc/svc.go
  modules/dop/services/autotest_v2/export.go
  modules/dop/services/autotest_v2/scene.go
  modules/dop/services/autotest_v2/service.go
  modules/dop/services/filesvc/delete.go
  modules/dop/services/filesvc/download.go
  modules/dop/services/filesvc/upload.go
  modules/dop/services/permission/permission.go
  modules/dop/services/projectpipelinefiletree/filetree.go
  modules/dop/services/testcase/export.go
  modules/dop/services/testcase/file_records.go
  modules/dop/services/testcase/import.go
  modules/dop/services/testcase/service.go
Labels: approved

#730 remove 'if exists' in alter table specs
  pkg/database/sqlparser/ddlreverser/reverser.go
Labels: approved, bugfix

#732 appModeCheck move to apistructs package
  apistructs/application.go
  apistructs/application_test.go
  modules/core-services/endpoints/application.go
  modules/core-services/services/application/appliation.go
  modules/core-services/utils/appmode.go
  modules/dop/endpoints/application.go
  modules/dop/utils/appmode.go
  modules/dop/utils/protocol.go
  modules/dop/utils/protocol_test.go
Labels: approved

#734 change soldier dockerfile copy addr
  build/dockerfiles/soldier/Dockerfile
Labels: approved

#735 permission use db not use bdl
  modules/core-services/services/security/process.go
Labels: approved

#729 set some caches client info just when pipeline start
  modules/pipeline/initialize.go
  pkg/pipeline_network_hook_client/client_register.go
Labels: approved
