Repository erda-project/erda, pull requests merged in 2021-08, with the labels that each got.

#1245 revert tmc migration sql change
  .erda/migrations/msp/20200528-tmc-base.sql
Labels: approved, bugfix, msp

#1247 fix: add the validations for git commit struct
  modules/gittar/api/repo.go
  modules/gittar/pkg/gitmodule/repo_edit.go
Labels: approved, feature, gittar

#1249 fix monitor settings save
  modules/core/monitor/settings/settings.service.go
Labels: approved

#1252 update(scheduler): reduce the cluster info sync time
  modules/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
Labels: approved

#1253 fix query metric for multi org
  go.mod
  modules/monitor/dashboard/org-apis/permission.go
  modules/monitor/dashboard/org-apis/provider.go
  modules/monitor/dashboard/project-apis/provider.go
  modules/monitor/dashboard/runtime-apis/provider.go
Labels: approved

#1255 feature: fix menu by tenant permission
  apistructs/addon.go
  apistructs/msp.go
  bundle/msp.go
  go.mod
  go.sum
  modules/core-services/dao/project.go
  modules/hepa/gateway/service/gateway_global_service.go
  modules/monitor/apm/topology/routes.go
  modules/msp/menu/menu.service.go
  modules/msp/tenant/db/project.go
  modules/msp/tenant/db/tenant.go
  modules/msp/tenant/project/project.service.go
  modules/msp/tenant/provider.go
  modules/msp/tenant/tenant.service.go
  modules/openapi/api/apis/msp/tenant/project/delete_msp_project.go
  modules/orchestrator/services/addon/addon_handler.go
  modules/orchestrator/services/addon/microservice.go
Labels: approved

#1246 fix that the personal message mailbox cannot access the project link
  pkg/erda-configs/i18n/notify_item.yml
Labels: approved, bugfix, dop

#1248 change the username of issue stream to nickname
  modules/dop/endpoints/issue_stream.go
Labels: approved, bugfix, dop

#1254 Fixed the issue when two different applications with the same branch at the same time
  modules/orchestrator/services/runtime/runtime.go
Labels: approved, bugfix, dop

#1157 add flink status judge, change flink pull policy
  modules/pipeline/conf/conf.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/util.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
Labels: approved, bugfix, pipeline

#1266 fix: update api spec's host to avoid 502
  modules/openapi/api/apis/dop/adaptor_cicd_config_namespaces.go
  modules/openapi/api/apis/dop/adaptor_cicd_config_workspaces.go
Labels: approved

#1197 add provider named extension in dicehub
  cmd/dicehub/main.go
  conf/dicehub/dicehub.yaml
  modules/dicehub/extension/db/extension.go
  modules/dicehub/extension/db/table.go
  modules/dicehub/extension/extention.service.go
  modules/dicehub/extension/extention.service_test.go
  modules/dicehub/extension/menu.go
  modules/dicehub/extension/provider.go
  pkg/common/apis/header.go
Labels: dop, refactor

#1267 Convert the loop field to an integer
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
Labels: approved, bug, openapi

#1260 bugfix: Fix msp project permission
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/instance/permission/permission.go
  modules/msp/menu/menu.service.go
Labels: approved, bugfix, msp

#1219 record job inspect in task result and reveal events
  apistructs/k8s.go
  apistructs/pipeline_task.go
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
  modules/pipeline/pipengine/actionexecutor/plugins/demo/demo.go
  modules/pipeline/pipengine/actionexecutor/plugins/memory/memory.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
  modules/pipeline/pipengine/actionexecutor/types/define.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/queue.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/wait.go
  modules/pipeline/pipengine/reconciler/taskrun/update.go
  modules/pipeline/services/pipelinesvc/detail.go
Labels: feature, pipeline

#1272 bugfix: fix msp project list i18n.
  modules/openapi/api/apis/msp/tenant/project/get_msp_projects.go
Labels: approved, bugfix, msp

#1275 update(Version): update version tag
  VERSION
Labels: approved, feature

#1279 fix: fix the bug for kanban of filter by time
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueKanban/issue_kanban.go
Labels: approved, bugfix, openapi

#1283 set header user id
  bundle/autotest_space.go
Labels: approved, bugfix, openapi

#1284 delete dicehub yml extension_menu
  conf/dicehub/dicehub.yaml
Labels: approved

#1258 feature: add patches migrations
  .erda/migrations/_patches_/patch-20210528-pipeline-base.sql
  .erda/migrations/_patches_/patch-20210528-qa-base.sql
Labels: approved, feature, install

#1286 Revert "feature: add patches migrations"
  .erda/migrations/_patches_/patch-20210528-pipeline-base.sql
  .erda/migrations/_patches_/patch-20210528-qa-base.sql
Labels: approved

#1271 optimize: update quick-start script and doc
  docs/assets/quickstart_create_org.png
  docs/guides/quickstart/quickstart-full.md
  quick-start/docker-compose.yml
  quick-start/quick-start.sh
Labels: approved, documentation, install

#1290 fixed quick-start.sh
  quick-start/quick-start.sh
Labels: approved, install

#1296 optimize: update quick-start.sh
  quick-start/quick-start.sh
Labels: approved, install

#1297 log-store bootstrap bugfix
  modules/core/monitor/log/schema/manager.go
  modules/core/monitor/log/storage/provider.go
Labels: approved

#1299 Update quickstart-full.md
  docs/guides/quickstart/quickstart-full.md
Labels: approved

#1294 put the pipelineID into the request body when the action cancel pipeline
  modules/dop/endpoints/pipeline.go
Labels: approved, dop, feature

#1143 move update pipeline status from reconcile to listen
  apistructs/pipeline_status.go
  modules/pipeline/events/manager.go
  modules/pipeline/pipengine/reconciler/listen.go
  modules/pipeline/pipengine/reconciler/reconcile.go
  modules/pipeline/pipengine/reconciler/teardown.go
  modules/pipeline/pipengine/reconciler/teardown_test.go
Labels: approved, bugfix, pipeline

#1292 support migration patches to resolve errors causing by baseline changes
  pkg/database/sqlparser/migrator/db.go
  pkg/database/sqlparser/migrator/equal.go
  pkg/database/sqlparser/migrator/equal_test.go
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/parameters.go
  pkg/database/sqlparser/migrator/schema.go
  pkg/database/sqlparser/migrator/scripts.go
  pkg/database/sqlparser/migrator/service.go
  pkg/database/sqlparser/migrator/tabledef.go
  pkg/database/sqlparser/snapshot/snapshot.go
Labels: approved, install

#1301 bugfix:Fix project overview charts display error
  .erda/migrations/monitor/20210804-dashboard.sql
Labels: approved, bugfix, msp

#1303 order by dataview list
  modules/core/monitor/dataview/db/db.go
Labels: approved

#1306 bugfix: Fix db migration
  .erda/migrations/monitor/20210804-1930-dashboard.sql
  .erda/migrations/monitor/20210804-dashboard.sql
Labels: approved, bugfix, msp

#1307 get tk by msp_tenant and compatible old version
  modules/monitor/common/db/instance_tenant.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/provider.go
  modules/msp/tenant/db/db.go
  modules/msp/tenant/db/tenant.go
Labels: bugfix, msp

#1309 fix: edas executor connect kubernetes error
  modules/scheduler/executor/plugins/edas/edas.go
Labels: approved, bugfix, orchestrator

#1313 feature: update erda-migration image and envs in quick-start
  quick-start/docker-compose.yml
Labels: approved, feature, install

#1256 add service group log when they're created or deleted
  modules/scheduler/executor/plugins/edas/edas.go
  modules/scheduler/executor/plugins/k8s/daemonset.go
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/plugins/k8s/runtime.go
  modules/scheduler/executor/plugins/k8s/service.go
  modules/scheduler/impl/servicegroup/delete.go
Labels: approved, orchestrator

#1317 update(cmp): remove auto scanner code
  modules/cmp/autoscanner/autoScanner.go
  modules/cmp/initialize.go
Labels: approved, cmp

#1311 bugfix: gateway chart
  .erda/migrations/monitor/20210804-2123-dashboard.sql
  go.mod
  go.sum
  modules/msp/tenant/db/tenant.go
  modules/msp/tenant/project/project.service.go
  modules/openapi/api/apis/msp/tenant/project/get_msp_metric_project_overview.go
Labels: bugfix, msp

#1319 bugfix: fix checker no item when add a new
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/permission.go
  modules/msp/apm/checker/apis/provider.go
  modules/msp/apm/checker/storage/db/checker.go
  modules/msp/resource/deploy/handlers/monitor/monitor.go
  modules/msp/tenant/project/project.service.go
Labels: bugfix, msp

#1323 doc: add v1.1.1 changeLog
  CHANGELOG/CHANGELOG-1.x.md
Labels: documentation

#1329 feature: add default sort
  modules/msp/tenant/project/project.service.go
Labels: approved, feature, msp

#1328 fix testscene-run action component protocol
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
Labels: bug, openapi

#1327 fix: trim space of the field in createCommit validate
  modules/gittar/pkg/gitmodule/repo_edit.go
Labels: bugfix, gittar

#1312 Remove deprecated org prefix in org dto domain
  modules/core-services/endpoints/organization.go
Labels: dop, feature

#1318 modify k8s executor jobname when remove
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
Labels: approved, bugfix, pipeline

#1325 fix Log display
  modules/dop/services/cdp/cdp.go
Labels: dop, bug

#1337 if end status don`t calculate status
  modules/pipeline/pipengine/reconciler/listen.go
Labels: pipeline, bugfix, approved

#1338 doc: fix the version link anchor
  CHANGELOG/CHANGELOG-1.x.md
Labels: documentation, approved

#1341 fix: list cluster bundle with orgID and clusterType
  bundle/cluster.go
Labels: approved

#1344 feature: add .patches module as default
  pkg/database/sqlparser/migrator/scripts.go
Labels: feature, approved, install

#1346 bugfix pipeline send running events lost info
  modules/pipeline/pipengine/reconciler/listen.go
Labels: dop, pipeline, bug, approved

#1339 modify workbench copywriting
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectContent/render.go
  pkg/erda-configs/i18n/workbench.json
Labels: openapi, bugfix

#1331 feature: modify project overview dashboard
  .erda/migrations/monitor/20210805-2109-dashboard.sql
  modules/openapi/api/apis/msp/tenant/project/get_msp_metric_project_overview.go
Labels: msp, feature

#1355 get detail value from getLabel func
  modules/pipeline/services/pipelinesvc/convert.go
Labels: approved

#1358 App pipeline inodes use URLEncoding instead of StdEncoding
  modules/dop/services/filetree/filetree.go
  modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
Labels: approved

#1360 feature: support new baseline files
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/schema.go
  pkg/database/sqlparser/migrator/scripts.go
  pkg/database/sqlparser/migrator/service.go
  pkg/database/sqlparser/migrator/tabledef.go
Labels: feature, approved, install

#1361 fix replica in erda.yml
  erda.yml
Labels: bug, approved, install

#1364 set DeleteNs true to delete cms
  modules/dop/services/autotest/global_config.go
Labels: dop, bugfix, approved

#1367 bugfix: Fix msp checkers
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/permission.go
Labels: msp, bugfix, approved

#1369 tag rename
  modules/monitor/dashboard/report/engine/resource.go
Labels: msp, bugfix, approved

#1371 fix: scheduler maybe register empty address to eventbox
  modules/eventbox/webhook/builtin.go
  modules/scheduler/server/server.go
Labels: approved

#1375 bugfix: compatible with history projects
  bundle/msp.go
  modules/hepa/gateway/service/gateway_global_service.go
  modules/msp/tenant/provider.go
  modules/msp/tenant/tenant.service.go
  modules/orchestrator/services/addon/addon_handler.go
Labels: msp, bugfix, approved

#1300 Support to get Action from git, in order to debug Action quickly
  modules/dicehub/service/extension/extension.go
  modules/dicehub/service/extension/git.go
Labels: dop, feature, approved

#1377 fix patch error
  pkg/database/sqlparser/migrator/migrator.go
Labels: bugfix, approved, install

#1379 modify nexus timeout
  pkg/nexus/nexus.go
Labels: dop, bugfix, approved

#1381 Supplement erda uninstall documentation
  docs/guides/deploy/How-to-install-Erda-zh.md
  docs/guides/deploy/How-to-install-Erda.md
Labels: documentation, approved

#1389 Release/1.0 Supplement erda uninstall documentation
  docs/guides/deploy/How-to-install-Erda-zh.md
  docs/guides/deploy/How-to-install-Erda.md
Labels: documentation, approved

#1382 Optimize application list endpoint and user workbench render
  modules/core-services/endpoints/application.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/content/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectTip/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectTitle/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/protocol.yml
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/joinedBrief/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myApplication/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myApplicationList/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectList/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectTitle/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/protocol.yml
Labels: dop, bugfix, approved

#1397 autotest scene check same name
  modules/dop/dao/autotest_scene.go
  modules/dop/services/autotest_v2/scene.go
Labels: dop, bug, approved

#1400 feature: add charset to dsn
  pkg/database/sqlparser/migrator/parameters.go
  pkg/database/sqlparser/pygrator/settings.go
Labels: feature, approved, install

#1401 update vision.png
  docs/assets/vision.png
Labels: documentation, approved

#1405 Master: Adjust the content of the uninstall erda document
  docs/guides/deploy/How-to-install-Erda-zh.md
  docs/guides/deploy/How-to-install-Erda.md
Labels: documentation, approved

#1386 Pipeline task event display optimization
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
  modules/pipeline/services/pipelinesvc/detail.go
  modules/pipeline/services/pipelinesvc/detail_test.go
Labels: pipeline, bugfix

#1394 fix testscene-run action scene name to display abnormally
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testscene_run.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testscene_run_test.go
Labels: pipeline, openapi, bugfix

#1388 feature: support show agent registered and remove extra field
  modules/cmp/i18n/i18n.go
  modules/cmp/impl/clusters/clusterinfo.go
Labels: cmp, feature, approved

#1411 add Asynchronous ability for testplan-run action
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run_test.go
Labels: pipeline, feature, openapi, approved

#1393 fix: manage config is nil in edas executor
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/util/util.go
  modules/scheduler/executor/util/util_test.go
Labels: approved

#1416 change the ready status of the kubernetes component instance is abnormal recover is true
  .erda/migrations/monitor/20210812-monitor-rules-recover.sql
Labels: msp, bugfix

#1409 add filters when customize rule update
  modules/core/monitor/alert/alert-apis/alert.service.go
Labels: msp, bugfix

#1422 when creating a pipeline to cache action information, add a lock to read the map
  modules/pipeline/services/pipelinesvc/passedDataWhenCreate.go
Labels: dop, pipeline, bug

#1426 dbmigration delete affairs
  .erda/migrations/monitor/20210812-monitor-rules-recover.sql
Labels: msp, bugfix, approved

#1430 Modified the problem that the pipeline cannot be triggered when on merge
  modules/dop/endpoints/pipeline.go
Labels: dop, bug, approved, gittar

#1436 project dashboard add bug_en and working_en statistics，because title cannot il8n
  .erda/migrations/monitor/20210813-monitor-project-dashboard.sql
Labels: approved

#1347 cmp cache
  go.mod
  go.sum
  modules/cmp/cache/README.md
  modules/cmp/cache/cache.go
  modules/cmp/cache/cache_test.go
Labels: cmp, feature, approved

#1356 update(edas): return error when application list is zero
  modules/openapi/api/generate/generate_doc.go
  modules/scheduler/executor/plugins/edas/edas.go
Labels: orchestrator, bugfix, approved

#1432 update(scheduler): change delete option from Foreground to BackGround
  modules/scheduler/executor/plugins/edas/edas.go
  modules/scheduler/executor/plugins/k8s/k8sapi/types.go
Labels: orchestrator, bugfix, approved

#1444 sync migrator from branch master
  pkg/database/sqlparser/ddlreverser/reverser_test.go
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/parameters.go
  pkg/database/sqlparser/migrator/schema.go
  pkg/database/sqlparser/migrator/scripts.go
  pkg/database/sqlparser/migrator/service.go
  pkg/database/sqlparser/migrator/tabledef.go
  pkg/database/sqlparser/pygrator/settings.go
Labels: feature, approved, install

#1446 update(edas): return error when application list is zero
  modules/scheduler/executor/plugins/edas/edas.go
Labels: approved

#1447 add v1.2.0 changelog
  CHANGELOG/CHANGELOG-1.x.md
Labels: documentation, approved

#1378 concurrent query issue for workbench endpoint optimization
  apistructs/issue.go
  apistructs/workbench.go
  modules/dop/dao/issue.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/workbench.go
  modules/dop/initialize.go
  modules/dop/services/issue/issue.go
  modules/dop/services/workbench/workbench.go
  modules/dop/services/workbench/workbench_test.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
Labels: dop, refactor, bugfix, approved

#1451 Fix/openapi components i18n
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/org-list-all/components/list/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/components/page/render.go
  modules/openapi/component-protocol/scenarios/org-list-all/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/project-list-all/components/list/list.go
  modules/openapi/component-protocol/scenarios/project-list-all/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/browsePublicProjects/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/emptyText/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/i18n/i18n.go
  pkg/erda-configs/i18n/org_list_all.json
  pkg/erda-configs/i18n/project_list_all.json
  pkg/erda-configs/i18n/project_list_my.json
  pkg/erda-configs/i18n/workbench.json
Labels: openapi, bugfix, approved

#1448 quick test、build cache
  .github/workflows/ci-it.yml
  .github/workflows/code-check.yml
  .github/workflows/license.yml
  Makefile
  build/scripts/test_in_container.sh
  go.mod
  pkg/semver/semver.go
  tools/gotools/go-copyright/main.go
  tools/gotools/go-imports-order/main.go
  tools/gotools/go-test-sum/cover/profile.go
  tools/gotools/go-test-sum/main.go
  tools/upload-cli/main.go
Labels: approved

#1425 modify cluster_name and application_id in expression filters
  modules/core/monitor/alert/alert-apis/adapt/alert_convert.go
  modules/core/monitor/alert/alert-apis/adapt/alert_convert_test.go
  modules/core/monitor/alert/alert-apis/adapt/expression.go
Labels: msp, bugfix, approved

#1458 feature: add i18n for addon
  modules/orchestrator/initialize.go
  pkg/erda-configs/i18n/orchestrator.json
Labels: orchestrator, feature, approved

#1462 optimize: not retry on post request to hepa
  bundle/msp.go
  modules/msp/resource/deploy/handlers/handler.go
  modules/msp/resource/deploy/handlers/handler_test.go
Labels: msp, bugfix, approved

#1449 Support pushing Extension from external repository，push extension no longer requires admin account
  Makefile
  build/dockerfiles/Dockerfile
  build/scripts/dicehub/extension-push.sh
  build/scripts/docker_image.sh
  modules/dicehub/extension/action.go
  modules/dicehub/extension/action_test.go
  modules/dicehub/extension/db/extension.go
  modules/dicehub/extension/extention.service.go
  modules/dicehub/extension/provider.go
Labels: dop, feature, approved

#1463 bugfix: change log-analytics created index prefix
  modules/msp/resource/deploy/handlers/loganalytics/loganalytics.go
Labels: msp, bugfix, approved

#1461 chngc set cluster_name in filter rule but invalidate
  modules/monitor/alert/alert-apis/adapt/alert_convert.go
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/org-custom-apis.go
Labels: msp, bugfix

#1452 feature: set env nexus_username and nexus_password not require
  modules/dop/conf/conf.go
Labels: dop, feature, approved

#1471 feature: not to do "not null lint" on alter table stmt
  pkg/database/sqllint/linters/not_null_linter.go
  pkg/database/sqllint/linters/not_null_linter_test.go
Labels: feature, approved

#1468 BUG fix: build image will false,if MODULE_PATH is not "dicehub"
  build/dockerfiles/Dockerfile
  build/scripts/dicehub/extension-push.sh
Labels: dop, bugfix, approved

#1434 pipeline filetree add il8n format
  modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/fileTree/render.go
  modules/openapi/component-protocol/scenarios/app-pipeline-tree/components/nodeFormModal/render.go
  pkg/erda-configs/i18n/pipeline.json
Labels: dop, bugfix, approved

#1473 patch 2 migrations files
  .erda/migrations/.patches/patch-20210721-fixAuditHistory.sql
  .erda/migrations/.patches/patch-20210729-scheduler-index-update.sql
  .erda/migrations/cmdb/20210721-fixAuditHistory.sql
Labels: approved, install

#1476 feature: patch 2 migrations files
  .erda/migrations/.patches/patch-20210721-fixAuditHistory.sql
  .erda/migrations/.patches/patch-20210729-scheduler-index-update.sql
  .erda/migrations/cmdb/20210721-fixAuditHistory.sql
Labels: approved, install

#1477 update cmp deploy cpu and memory
  erda.yml
Labels: approved

#1474 fix: do not exec empty patch file
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/script.go
  pkg/database/sqlparser/migrator/script_test.go
Labels: approved, install

#1480 create alert rule is failed
  modules/core/monitor/alert/alert-apis/adapt/alert_convert.go
Labels: msp, bugfix

#1478 release/1.2 support push extension no need Admin account
  Makefile
  build/dockerfiles/Dockerfile
  build/scripts/dicehub/extension-push.sh
  build/scripts/docker_image.sh
  modules/dicehub/dbclient/extention.go
  modules/dicehub/endpoints/endpoints.go
  modules/dicehub/initialize.go
  modules/dicehub/service/extension/action.go
  modules/dicehub/service/extension/extension.action_test.go
Labels: dop, feature, approved

#1482 create alert rule but message is assert culster_name or application_i…
  modules/monitor/alert/alert-apis/adapt/alert_convert.go
Labels: msp, bugfix

#1450 bugfix: fix response body format
  modules/msp/apm/trace/db/trace_request_history.go
  modules/msp/apm/trace/trace.service.go
  modules/msp/apm/trace/trace.service_test.go
Labels: msp, bugfix, approved

#1484 bugfix: fix bug of loghub
  cmd/monitor/extensions/loghub/main.go
  conf/monitor/extensions/loghub/output/elasticsearch-rollover.yaml
  modules/extensions/loghub/exporter/output.go
  modules/extensions/loghub/exporter/output/elasticsearch-proxy/proxy.go
  modules/extensions/loghub/loghub.go
Labels: msp, bugfix

#1485 fix(scheduler): sync instance info memory leak
  modules/scheduler/executor/plugins/k8s/instanceinfosync/gc.go
  modules/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: orchestrator, bugfix, approved

#1469 Put selected users at the top of issue filter list
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/state_conditions.go
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/state_conditions_test.go
Labels: dop, feature

#1494 when "make build-push-all" ,add extension file in image
  Makefile
  build/dockerfiles/Dockerfile
Labels: dop, feature, approved

#1489 fix : create extension false when init provider
  build/dockerfiles/Dockerfile
  modules/dicehub/initialize.go
Labels: dop, bugfix, approved

#1431 fix(service): list specify pod for status
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/plugins/k8s/pod/pod.go
  modules/scheduler/executor/plugins/k8s/pod/pod_test.go
Labels: orchestrator, bugfix, approved

#1498 Fix project list components pagination
  modules/openapi/component-protocol/scenarios/project-list-all/components/list/list.go
  modules/openapi/component-protocol/scenarios/project-list-all/components/list/model.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/list/model.go
Labels: approved

#1501 update quick-start image to v1.2
  quick-start/docker-compose.yml
  quick-start/quick-start.sh
Labels: install

#1500 compare schema only on first time udpating
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/migrator_test.go
Labels: feature, approved, install

#1502 bugfix: change the quick-start used code version
  quick-start/docker-compose.yml
  quick-start/quick-start.sh
Labels: install

#1488 fix : create extension failed when init provider
  build/dockerfiles/Dockerfile
  modules/dicehub/extension/provider.go
  modules/dicehub/extension/provider_test.go
Labels: dop, bugfix, approved

#1479 updates to v1.2.0 changelog
  CHANGELOG/CHANGELOG-1.x.md
Labels: approved

#1508 Fix work bench application list and empty content
  modules/core-services/services/project/project.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyProjectIssue/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/protocol.yml
Labels: approved

#1504 optimize: update quick-start code commit version
  quick-start/quick-start.sh
Labels: install

#1510 when creating a pipeline to cache action information, add a lock to read the map
  modules/pipeline/services/pipelinesvc/passedDataWhenCreate.go
  modules/pipeline/services/pipelinesvc/passedDataWhenCreate_test.go
Labels: pipeline, bug, approved

#1483 retry reconcile task until no platform errors
  apistructs/pipeline_task.go
  apistructs/pipeline_task_test.go
  modules/pipeline/pipengine/reconciler/task.go
  modules/pipeline/pipengine/reconciler/task_test.go
  modules/pipeline/pipengine/reconciler/taskrun/framework.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/pipengine/reconciler/taskrun/update.go
  modules/pipeline/pkg/errorsx/errors.go
  modules/pipeline/pkg/errorsx/errors_test.go
  modules/pipeline/services/pipelinesvc/callback.go
  modules/pipeline/services/pipelinesvc/callback_test.go
  modules/pipeline/spec/pipeline_task.go
Labels: pipeline, bugfix, approved

#1505 Update cache
  apistructs/steve.go
  modules/cmp/cache/cache.go
  modules/cmp/cache/cache_test.go
  modules/cmp/conf/conf.go
  modules/cmp/steve/formatter/node.go
  modules/cmp/steve/formatter/node_test.go
  modules/cmp/steve/proxy/cache_store.go
  modules/cmp/steve/proxy/cache_store_test.go
  modules/cmp/steve/proxy/proxy_store.go
  modules/cmp/steve/schema.go
  modules/cmp/steve/server.go
Labels: approved

#1516 feature: cmp import cluster use single chart
  build/dockerfiles/Dockerfile-cluster-ops
  cmd/cluster-ops/main.go
  conf/cluster-init/cluster-init.yaml
  conf/cluster-ops/cluster-ops.yaml
  modules/cluster-init/config/config.go
  modules/cluster-ops/client/client.go
  modules/cluster-ops/config/config.go
  modules/cluster-ops/provider.go
  modules/cmp/conf/conf.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/endpoints/endpoints.go
  modules/cmp/impl/clusters/cluster_hook.go
  modules/cmp/impl/clusters/clusterinfo.go
  modules/cmp/impl/clusters/import_cluster.go
  modules/cmp/impl/clusters/proxy-deploy.go
  modules/cmp/impl/clusters/update_cluster.go
  modules/cmp/impl/clusters/upgrade_edge_cluster.go
  modules/cmp/initialize.go
  modules/cmp/services/kubernetes/kubernetes.go
Labels: approved

#1511 add ecp i18 entry
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/components/appSiteBreadcrumb/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/components/siteIpList/operation.go
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/components/siteIpList/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/components/statusViewGroup/operation.go
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/components/statusViewGroup/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site-ip/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/appSiteBreadcrumb/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/appSiteManage/operation.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/appSiteManage/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/siteNameFilter/opertaion.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/siteNameFilter/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/statusViewGroup/operation.go
  modules/openapi/component-protocol/scenarios/edge-app-site/components/statusViewGroup/render.go
  modules/openapi/component-protocol/scenarios/edge-app-site/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/edge-application/components/addAppButton/operation.go
  modules/openapi/component-protocol/scenarios/edge-application/components/addAppButton/render.go
  modules/openapi/component-protocol/scenarios/edge-application/components/addAppDrawer/operation.go
  modules/openapi/component-protocol/scenarios/edge-application/components/addAppDrawer/render.go
  modules/openapi/component-protocol/scenarios/edge-application/components/appConfigForm/operation.go
  modules/openapi/component-protocol/scenarios/edge-application/components/appConfigForm/render.go
  modules/openapi/component-protocol/scenarios/edge-application/components/applicationList/operation.go
  modules/openapi/component-protocol/scenarios/edge-application/components/applicationList/render.go
  modules/openapi/component-protocol/scenarios/edge-application/components/keyValueList/operation.go
  modules/openapi/component-protocol/scenarios/edge-application/components/keyValueList/render.go
  modules/openapi/component-protocol/scenarios/edge-application/components/keyValueListTitle/operation.go
  modules/openapi/component-protocol/scenarios/edge-application/components/keyValueListTitle/render.go
  modules/openapi/component-protocol/scenarios/edge-application/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/clusterAddButton/operation.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/clusterAddButton/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/configItemFormModal/operation.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/configItemFormModal/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/configItemList/operation.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/configItemList/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/configItemListFilter/operation.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/components/configItemListFilter/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet-item/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/edge-configSet/components/clusterAddButton/operation.go
  modules/openapi/component-protocol/scenarios/edge-configSet/components/clusterAddButton/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet/components/configSetFormModal/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet/components/configSetList/operation.go
  modules/openapi/component-protocol/scenarios/edge-configSet/components/configSetList/render.go
  modules/openapi/component-protocol/scenarios/edge-configSet/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteAddButton/operation.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteAddButton/render.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteAddDrawer/operation.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteAddDrawer/render.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteFormModal/operation.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteFormModal/render.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteList/operation.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteList/render.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteNameFilter/opertaion.go
  modules/openapi/component-protocol/scenarios/edge-site/components/siteNameFilter/render.go
  modules/openapi/component-protocol/scenarios/edge-site/components/sitePreview/operation.go
  modules/openapi/component-protocol/scenarios/edge-site/components/sitePreview/render.go
  modules/openapi/component-protocol/scenarios/edge-site/i18n/i18n.go
  pkg/erda-configs/i18n/ecp.json
Labels: approved

#1517 ops support permission bugfix
  modules/cmp/endpoints/addons.go
  modules/cmp/endpoints/cloud_resource.go
  modules/cmp/endpoints/cloud_resource_account.go
  modules/cmp/endpoints/cloud_resource_ecs.go
  modules/cmp/endpoints/cloud_resource_vpc.go
  modules/cmp/endpoints/cloud_resource_vsw.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/endpoints/labels.go
  pkg/erda-configs/permission/backend/sys/org/org.yml
Labels: auto-cherry-pick, cmp, bug, approved

#1521 feature: cmp import cluster use single chart
  build/dockerfiles/Dockerfile-cluster-ops
  cmd/cluster-ops/main.go
  conf/cluster-init/cluster-init.yaml
  conf/cluster-ops/cluster-ops.yaml
  modules/cluster-init/config/config.go
  modules/cluster-ops/client/client.go
  modules/cluster-ops/config/config.go
  modules/cluster-ops/provider.go
  modules/cmp/conf/conf.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/endpoints/endpoints.go
  modules/cmp/impl/clusters/cluster_hook.go
  modules/cmp/impl/clusters/clusterinfo.go
  modules/cmp/impl/clusters/import_cluster.go
  modules/cmp/impl/clusters/proxy-deploy.go
  modules/cmp/impl/clusters/update_cluster.go
  modules/cmp/impl/clusters/upgrade_edge_cluster.go
  modules/cmp/initialize.go
  modules/cmp/services/kubernetes/kubernetes.go
Labels: approved

#1506 feature: add parentPath for git commit response
  modules/gittar/pkg/gitmodule/commit.go
  modules/gittar/pkg/gitmodule/repo_edit.go
  modules/gittar/pkg/gitmodule/repo_edit_test.go
Labels: feature, approved, gittar

#1518 support patch container snippet through erda.yml
  apistructs/service.go
  modules/scheduler/executor/plugins/k8s/addon/interface.go
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/deployment/deployment.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/impl/servicegroup/servicegroup.go
  pkg/parser/diceyml/define.go
  pkg/parser/diceyml/diceyml.go
  pkg/parser/diceyml/diceyml_test.go
  pkg/parser/diceyml/fieldname_validate_visitor.go
  pkg/parser/diceyml/utils.go
Labels: approved

#1507 fix: change the error prompt from Chinese to English for addon delete
  modules/orchestrator/services/addon/addon.go
  modules/orchestrator/services/addon/addon_test.go
Labels: orchestrator, feature, approved

#1435 fix: enciphered data will Replaced by '******' when log output
  cmd/actionagent/main.go
  modules/actionagent/define.go
  modules/actionagent/file_watch.go
  modules/actionagent/file_watch_test.go
  modules/actionagent/pull_bootstrap_info.go
  modules/actionagent/step_logic.go
  modules/pipeline/endpoints/pipeline_task.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/services/pipelinesvc/precheck.go
  modules/pipeline/services/pipelinesvc/run.go
  modules/pipeline/services/pipelinesvc/secret.go
  modules/pipeline/spec/pipeline_extra.go
  modules/pipeline/spec/pipeline_task.go
Labels: pipeline, feature, approved

#1522 Fix/pipeline events errors optimization
  apistructs/pipeline_task.go
  modules/pipeline/pipengine/reconciler/taskrun/framework.go
  modules/pipeline/services/pipelinesvc/detail.go
  modules/pipeline/services/pipelinesvc/detail_test.go
Labels: pipeline, bug

#1526 fix patch snippet issue
  modules/scheduler/executor/plugins/k8s/deployment/deployment.go
  pkg/parser/diceyml/define.go
Labels: bugfix, approved, deploy

#1528 Modify README.md file to update license statement
  README.md
Labels: approved

#1420 fix typo existant->existent
  pkg/encoding/jsonpath/jsonpath_test.go
Labels: approved, typo

#1531 Support pushing extensions according to the git directory of repo/addons
  modules/dicehub/extension/action.go
Labels: dop, feature, approved

#1532 release/1.2 Support pushing extensions according to the git directory of repo/addons
  modules/dicehub/service/extension/action.go
Labels: dop, feature, approved

#1529 restore task uuid after cancel
  apistructs/pipeline_task.go
  apistructs/pipeline_task_test.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
Labels: pipeline, bugfix, approved

#1503 support for orchestrator running with multi instances
  Makefile
  cmd/orchestrator/main.go
  conf/orchestrator/orchestrator.yaml
  go.mod
  go.sum
  modules/core/monitor/log/storage/provider_test.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/initialize.go
  modules/orchestrator/provider.go
  pkg/loop/loop.go
  pkg/loop/loop_test.go
Labels: orchestrator, feature, approved

#1537 restore task uuid after cancel
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
Labels: pipeline, bugfix, approved

#1535 add more log about removing ingress
  modules/hepa/gateway/service/gateway_openapi_consumer_service.go
  modules/hepa/gateway/service/gateway_zone_service.go
  modules/hepa/k8s/k8s_adapter.go
  modules/hepa/k8s/k8s_adapter_test.go
Labels: approved

#1540 bugfix: use nc command to check if netcat installed
  quick-start/quick-start.sh
Labels: bugfix, install

#1542 feat: add event list scenario
  apistructs/component_protocol.go
  apistructs/steve.go
  bundle/steve.go
  bundle/steve_node.go
  modules/cmp/steve/aggregator.go
  modules/openapi/api/apis/cmp/cmp_k8s_create.go
  modules/openapi/api/apis/cmp/cmp_k8s_get.go
  modules/openapi/api/apis/cmp/cmp_k8s_list.go
  modules/openapi/api/apis/cmp/cmp_k8s_update.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/model.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/render.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/eventTable/render_test.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/filter/model.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/filter/render.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/components/filter/render_test.go
  modules/openapi/component-protocol/scenarios/cmp-dashboard-events/protocol.yml
Labels: approved

#1544 feat: update doc url in home page
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTip/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTipWithoutOrg/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/projectTipWithoutOrg/render.go
Labels: approved

#1523 add v1.2.1 changelog
  CHANGELOG/CHANGELOG-1.x.md
Labels: documentation, approved
