Repository erda-project/erda, pull requests merged in 2021-07, with the labels that each got.

#741 feature: update erda-migration image in quick-start
  quick-start/docker-compose.yml
Labels: approved, feature

#748 fix(scheduler): do not create any service when port count equal 0
  modules/scheduler/executor/plugins/edas/edas.go
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: approved

#745 fix: remove the case that dop call dop
  modules/dop/initialize.go
  modules/dop/services/filetree/filetree.go
Labels: approved, bugfix, dop

#738 Implement Excption API
  cmd/msp/main.go
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/msp/apm/exception/exception.service.go
  modules/msp/apm/exception/exception.service_test.go
  modules/msp/apm/exception/provider.go
Labels: msp, refactor

#753 should not make new parameter clusterDialAddr in if logic
  pkg/clusterdialer/dialer.go
Labels: approved

#752 add new pipeline input length too short
  modules/openapi/component-protocol/scenarios/app-pipeline-tree/protocol.yml
Labels: approved, feature, pipeline

#746 Feature/dop ticket bugfix
  modules/dop/endpoints/ticket.go
  modules/dop/model/ticket.go
  modules/dop/services/ticket/ticket.go
Labels: approved, bugfix, dop

#754 refctor service-ip api
  go.mod
  go.sum
  modules/dop/endpoints/snippet_test.go
  modules/msp/registercenter/provider.go
  modules/msp/registercenter/register.center.service.go
  modules/orchestrator/endpoints/addon_test.go
  modules/orchestrator/services/addon/addon_test.go
Labels: approved, msp, refactor

#756 msp metric api
  cmd/msp/main.go
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/core/monitor/metric/query/convert.go
  modules/core/monitor/metric/query/metric.service.go
  modules/core/monitor/metric/query/provider.go
  modules/core/monitor/metric/query/test.http
  modules/msp/apm/metric/compatible.go
  modules/msp/apm/metric/provider.go
  modules/msp/apm/metric/proxy.go
  modules/msp/apm/metric/routes.go
  modules/msp/apm/metric/routes_test.go
  modules/msp/apm/metric/test.http
  modules/msp/instance/db/monitor/monitor.go
  modules/msp/instance/permission/permission.go
Labels: approved

#759 Update erda.yml
  erda.yml
Labels: approved

#751 Add test api file size, stage value not null
  modules/dop/services/issue/stage.go
  modules/dop/services/testcase/export.go
  modules/dop/services/testcase/import.go
  modules/dop/services/ticket/ticket.go
Labels: approved, dop, feature

#757 Update erda cli upload oss bucket
  build/scripts/upload_cli/main.go
Labels: approved

#742 change query snippet detail api, use handler snippetConfig, some config not have batch-query-snippet-yml api
  modules/pipeline/endpoints/endpoints.go
  modules/pipeline/endpoints/snippet.go
  modules/pipeline/initialize.go
  modules/pipeline/services/pipelinesvc/action_output_handler.go
  modules/pipeline/services/pipelinesvc/action_output_handler_test.go
  modules/pipeline/services/pipelinesvc/create.go
  modules/pipeline/services/pipelinesvc/snippet.go
  modules/pipeline/services/pipelinesvc/snippet_test.go
  modules/pipeline/services/snippetsvc/define.go
  modules/pipeline/services/snippetsvc/snippet_output_query.go
  modules/pipeline/services/snippetsvc/snippet_output_query_test.go
Labels: approved, pipeline

#739 Readme modifications
  README.md
Labels: approved

#761 export and import autotest space sync
  apistructs/autotest_space.go
  apistructs/file_records.go
  modules/dop/dao/file_records.go
  modules/dop/endpoints/autotests_space.go
  modules/dop/endpoints/endpoints.go
  modules/dop/initialize.go
  modules/dop/services/autotest_v2/export.go
  modules/dop/services/autotest_v2/import.go
  modules/dop/services/autotest_v2/service.go
  modules/dop/services/autotest_v2/space_data.go
  modules/dop/services/testcase/file_records.go
Labels: approved, dop, feature

#630 Enable docker build cache for go build [buildkit should be enabled]
  Makefile
  build/dockerfiles/Dockerfile
  build/scripts/base_image.sh
  build/scripts/docker_image.sh
Labels: approved

#762 fix(scheduler): depend on inject error server name
  modules/scheduler/executor/plugins/k8s/deployment.go
Labels: approved, bugfix

#758 personal message for issue
  .erda/migrations/cmdb/20210702-updateMbox.sql
  apistructs/event.go
  apistructs/event_test.go
  apistructs/issue.go
  apistructs/issue_stream_locale.go
  apistructs/mbox.go
  bundle/events.go
  modules/core-services/dao/mbox.go
  modules/core-services/model/mbox.go
  modules/core-services/services/mbox/mbox.go
  modules/core-services/services/mbox/mbox_test.go
  modules/dop/conf/conf.go
  modules/dop/dao/issue.go
  modules/dop/dao/issue_subscriber.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/issue.go
  modules/dop/endpoints/issue_callback.go
  modules/dop/endpoints/issue_stream.go
  modules/dop/services/issue/issue.go
  modules/dop/services/issuestream/issue_stream.go
  modules/eventbox/subscriber/email/email.go
  modules/eventbox/subscriber/mbox/mbox.go
  modules/openapi/api/apis/dop/cmdb_issue_subscribe.go
  modules/openapi/api/apis/dop/cmdb_issue_subscribe_batchupdate.go
  modules/openapi/api/apis/dop/cmdb_issue_unsubscribe.go
  pkg/erda-configs/i18n/notify_item.yml
Labels: approved, dop, feature

#760 msp checker bug
  conf/msp/msp.yaml
  modules/msp/apm/checker/task/fetcher/scheduled/dispatcher.go
  providers/metrics/report/collector.go
  providers/metrics/report/collector_test.go
  providers/metrics/report/disruptor_test.go
  providers/metrics/report/provider.go
Labels: approved

#763 streaming bootstrap fix
  cmd/monitor/streaming/main.go
  conf/monitor/streaming/streaming.yaml
  modules/core/monitor/metric/storage/provider.go
Labels: approved

#767 remove publisher id in listOrg
  modules/dop/endpoints/organization.go
Labels: approved

#768 task prepare use k8sjob executor create volume
  erda.yml
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
Labels: approved

#771 downgrade log level for `become-admin` function
  modules/core-services/services/member/member.go
Labels: dop, refactor

#613 Implement getTrace,getSpans through protobuf
  cmd/msp/main.go
  conf/msp/msp.yaml
  modules/monitor/trace/query/interfaces.go
  modules/msp/apm/trace/provider.go
  modules/msp/apm/trace/trace.service.go
  modules/msp/apm/trace/trace.service_test.go
Labels: msp

#733 feat(admin): add approve and notice init
  apistructs/approve.go
  bundle/approve.go
  bundle/audit.go
  bundle/notice.go
  cmd/admin/main.go
  conf/admin/admin.yaml
  erda.yml
  modules/admin/apierrors/errors.go
  modules/admin/config/config.go
  modules/admin/dao/dbclient.go
  modules/admin/dao/host.go
  modules/admin/manager/approve.go
  modules/admin/manager/audit.go
  modules/admin/manager/cluster.go
  modules/admin/manager/host.go
  modules/admin/manager/id.go
  modules/admin/manager/manager.go
  modules/admin/manager/notice.go
  modules/admin/provider.go
  modules/cmp/autoscanner/autoScanner.go
  modules/openapi/api/apis/admin/admin_approve_get.go
  modules/openapi/api/apis/admin/admin_approve_list.go
  modules/openapi/api/apis/admin/admin_approve_update.go
  modules/openapi/api/apis/admin/admin_audits_export.go
  modules/openapi/api/apis/admin/admin_audits_list.go
  modules/openapi/api/apis/admin/admin_cluster_list.go
  modules/openapi/api/apis/admin/admin_notice_create.go
  modules/openapi/api/apis/admin/admin_notice_delete.go
  modules/openapi/api/apis/admin/admin_notice_list.go
  modules/openapi/api/apis/admin/admin_notice_publish.go
  modules/openapi/api/apis/admin/admin_notice_unpublish.go
  modules/openapi/api/apis/admin/admin_notice_update.go
  modules/openapi/api/apis/cmp/cmp_running_tasks_list.go
Labels: admin, approved, refactor

#775 k8sjob query status use jobName
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
Labels: approved

#772 Fix test cases xmind import issue
  modules/dop/initialize.go
  modules/dop/services/autotest_v2/export.go
  modules/dop/services/autotest_v2/service.go
  modules/dop/services/testcase/export.go
  pkg/excel/export_by_cell.go
Labels: approved

#774 Increase dop resources due to module migration.
  erda.yml
Labels: approved

#778 if roles empty rolesProcess should return false access
  modules/core-services/services/security/process.go
Labels: approved

#779 hepa support cluster dialer
  conf/hepa/hepa.yaml
  modules/hepa/config/config.go
  modules/hepa/endpoint/factories/edas.go
  modules/hepa/endpoint/factories/k8s.go
  modules/hepa/gateway/service/gateway_api_policy_service.go
  modules/hepa/gateway/service/gateway_domain_service.go
  modules/hepa/gateway/service/gateway_global_service.go
  modules/hepa/gateway/service/gateway_runtime_service_service.go
  modules/hepa/gateway/service/gateway_zone_service.go
  modules/hepa/k8s/k8s_adapter.go
  modules/hepa/provider.go
  modules/hepa/server/router.go
  pkg/http/customhttp/request.go
Labels: approved

#744 Defined exception openapi.
  modules/openapi/api/apis/msp/apm/exception/exception_event.go
  modules/openapi/api/apis/msp/apm/exception/exception_event_id_list.go
  modules/openapi/api/apis/msp/apm/exception/exception_list.go
Labels: approved, msp, refactor

#773 Defined trace openapi.
  modules/openapi/api/apis/msp/apm/trace/get_spans.go
  modules/openapi/api/apis/msp/apm/trace/get_trace_list.go
Labels: approved, msp, refactor

#777 feature: move org resource interface from cmdb to cmp
  modules/cmp/autoscanner/autoScanner.go
  modules/cmp/conf/conf.go
  modules/cmp/dbclient/models.go
  modules/cmp/dbclient/org_resource_deployment.go
  modules/cmp/dbclient/org_resource_job.go
  modules/cmp/endpoints/endpoints.go
  modules/cmp/endpoints/org_resource.go
  modules/cmp/impl/addons/config.go
  modules/cmp/impl/clusters/upgrade_edge_cluster.go
  modules/cmp/impl/org-resource/org_resource.go
  modules/cmp/initialize.go
  modules/cmp/services/apierrors/errors.go
  pkg/k8sclient/scheme/register.go
Labels: approved, cmp

#781 monitor alert to proto
  cmd/monitor/monitor/main.go
  conf/monitor/monitor/monitor.yaml
  modules/monitor/alert/alert-apis/adapt/adapt.go
  modules/monitor/alert/alert-apis/adapt/alert.go
  modules/monitor/alert/alert-apis/adapt/alert_convert.go
  modules/monitor/alert/alert-apis/adapt/alert_test.go
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/adapt/customize_convert.go
  modules/monitor/alert/alert-apis/adapt/dashboard.go
  modules/monitor/alert/alert-apis/adapt/expression.go
  modules/monitor/alert/alert-apis/adapt/record.go
  modules/monitor/alert/alert-apis/adapt/record_convert.go
  modules/monitor/alert/alert-apis/alert-apis.go
  modules/monitor/alert/alert-apis/alert-record-apis.go
  modules/monitor/alert/alert-apis/alert.service.go
  modules/monitor/alert/alert-apis/custom-apis.go
  modules/monitor/alert/alert-apis/interfaces.go
  modules/monitor/alert/alert-apis/org-alert-apis.go
  modules/monitor/alert/alert-apis/org-alert-record-apis.go
  modules/monitor/alert/alert-apis/org-custom-apis.go
  modules/monitor/alert/alert-apis/provider.go
  modules/monitor/alert/alert-apis/routes.go
  modules/monitor/apm/alert/alert.go
  modules/monitor/apm/alert/permission.go
  modules/monitor/apm/alert/provider.go
  modules/monitor/apm/alert/routes.go
  pkg/common/permission/permission.go
Labels: approved, msp, refactor

#788 update proto go
  go.mod
  go.sum
Labels: approved, msp, refactor

#789 bugfix: fix configcenter,api-gateway,monitor deploy bug
  bundle/scheduler.go
  modules/msp/instance/db/monitor/tables.go
  modules/msp/resource/deploy/handlers/apigateway/apigateway.go
  modules/msp/resource/deploy/handlers/configcenter/configcenter.go
  modules/msp/resource/deploy/handlers/handler.go
  modules/msp/resource/deploy/handlers/monitor/monitor.go
  modules/msp/resource/deploy/handlers/mysql/mysql.go
  modules/msp/resource/deploy/handlers/nacos/nacos.go
  modules/msp/resource/resource.service.go
  modules/msp/resource/utils/nacos_client.go
  modules/orchestrator/services/addon/addon_deploy.go
Labels: approved

#785 fix: mv api from cmdb to core-services
  apistructs/org.go
  bundle/org.go
  modules/cmdb/endpoints/cluster.go
  modules/cmdb/endpoints/endpoints.go
  modules/cmdb/services/cluster/cluster.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/endpoints/organization.go
  modules/core-services/initialize.go
  modules/core-services/services/org/org.go
  modules/openapi/api/apis/core_services/cmdb_cluster_dereference.go
Labels: approved

#787 fix msp block、fix register center
  modules/msp/apm/metric/routes.go
  modules/msp/instance/db/tables.go
  modules/msp/registercenter/nacos/adapter.go
  modules/msp/registercenter/nacos/service_search_result.go
  modules/msp/registercenter/provider.go
Labels: approved, msp, refactor

#786 feature: scheduler k8s executor support new manage type
  bundle/cluster.go
  modules/cluster-manager/services/cluster/cluster.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/impl/cluster/cluster.go
  modules/scheduler/impl/cluster/hook.go
  modules/scheduler/initialize.go
  pkg/apitestsv2/netportal_test.go
  pkg/http/httpclient/client.go
Labels: approved, orchestrator

#791 fix register center bug
  modules/msp/apm/checker/apis/test.http
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/registercenter/nacos/adapter.go
  modules/msp/registercenter/nacos/service_search_result.go
  modules/msp/registercenter/provider.go
  modules/msp/registercenter/test.http
Labels: approved, msp

#793 fix: slove the problem of projects' sort and add the cache of project's stats
  apistructs/application.go
  apistructs/member.go
  bundle/app.go
  bundle/member.go
  bundle/project.go
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/endpoints/member.go
  modules/core-services/endpoints/project.go
  modules/core-services/services/apierrors/errors.go
  modules/core-services/services/project/project.go
  modules/dop/conf/conf.go
  modules/dop/endpoints/project.go
  modules/dop/initialize.go
Labels: approved

#795 bugfix: fix protobuf unknown field
  go.mod
  go.sum
Labels: approved

#792 move all issue notify to issue stream
  apistructs/issue_stream.go
  apistructs/issue_stream_test.go
  modules/dop/endpoints/issue_callback.go
  modules/dop/services/issue/issue.go
  modules/dop/services/issuestream/issue_stream.go
Labels: approved, bugfix, dop

#796 fix: mv user's api from cmdb to core-services
  bundle/user.go
  modules/cmdb/endpoints/endpoints.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/endpoints/manual_review.go
  modules/core-services/endpoints/user.go
  modules/openapi/api/apis/core_services/cmdb_user_list.go
  modules/openapi/api/apis/core_services/cmdb_user_search.go
Labels: approved

#794 get header value from context
  pkg/common/apis/header.go
Labels: approved

#790 update(admin): forward api to backend and add user api
  bundle/approve.go
  bundle/audit.go
  bundle/notice.go
  modules/admin/manager/approve.go
  modules/admin/manager/audit.go
  modules/admin/manager/cluster.go
  modules/admin/manager/id.go
  modules/admin/manager/manager.go
  modules/admin/manager/notice.go
  modules/admin/manager/user.go
  modules/cmp/autoscanner/autoScanner.go
Labels: admin, approved, bugfix, refactor

#801 feature: generate oas3 document of all services when make prepare
  go.mod
  go.sum
  modules/openapi/api/generate/generate_doc.go
Labels: approved, feature, openapi

#804 document: add CHANGELOG
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-template.md
  CHANGELOG/README.md
  README.md
Labels: approved, documentation

#803 fix config center bug
  go.mod
  go.sum
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/registercenter/nacos/adapter.go
  modules/msp/registercenter/nacos/service_search_result.go
Labels: approved

#808 pipeline loop task generate params add current task status, because loop is before update current task db storage status
  modules/pipeline/pexpr/pexpr_params/task_params.go
  modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
Labels: approved

#812 document: polish changelog template and 1.0.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-template.md
Labels: approved, documentation

#800 update install doc: helm get package version from Erda VERSION
  docs/guides/deploy/How-to-install-Erda-zh.md
  docs/guides/deploy/How-to-install-Erda.md
Labels: approved, documentation, install

#805 fix(admin): from json body to raw body when forward to backend
  bundle/approve.go
  bundle/notice.go
  modules/admin/manager/notice.go
  modules/cmp/autoscanner/autoScanner.go
Labels: admin, approved, bugfix

#810 update exception openapi
  modules/openapi/api/apis/msp/apm/exception/exception_event.go
  modules/openapi/api/apis/msp/apm/exception/exception_event_id_list.go
Labels: approved, msp, refactor

#807 feature: migrate /api/monitor/instances/{tk} api
  go.mod
  go.sum
  modules/msp/resource/deploy/handlers/monitorcollector/monitor_collector.go
  modules/msp/resource/provider.go
  modules/msp/resource/resource.service.go
  modules/openapi/api/apis/tmc/tmc_monitor_instance.go
Labels: approved, msp, refactor

#821 update erda.yml for eventbox and orchestrator
  erda.yml
Labels: approved, dop, orchestrator

#820 fix trace query bug
  modules/msp/apm/metric/routes.go
Labels: approved, bugfix, msp, refactor

#822 feature: Implement Trace debug
  conf/msp/i18n/msp-i18n.yaml
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/msp/apm/trace/db/tables.go
  modules/msp/apm/trace/db/trace_request_history.go
  modules/msp/apm/trace/provider.go
  modules/msp/apm/trace/trace.service.go
  modules/msp/apm/trace/trace.service_test.go
  modules/openapi/api/apis/msp/apm/trace/get_trace_debug_history.go
  modules/openapi/api/apis/msp/apm/trace/get_trace_debug_history_status.go
  modules/openapi/api/apis/msp/apm/trace/list_trace_debug_histories.go
  modules/openapi/api/apis/msp/apm/trace/post_trace_debug_history.go
  modules/openapi/api/apis/msp/apm/trace/put_trace_debug_history_stop.go
Labels: approved, msp, refactor

#814 fix: remove the case of call themself with dop and core-services
  modules/core-services/endpoints/user.go
  modules/dop/endpoints/issue.go
  modules/dop/endpoints/sonar.go
  modules/dop/initialize.go
  modules/dop/services/issue/issue.go
  modules/dop/services/pipeline/pipeline.go
  modules/dop/services/testplan/testlan_case_rel.go
  modules/dop/services/testplan/testplan.go
Labels: approved

#819 feat(admin): adapt to the methods of user model include search and list
  .gitignore
  apistructs/user.go
  bundle/user.go
  modules/admin/manager/user.go
  modules/openapi/api/apis/admin/admin_user_list.go
  modules/openapi/api/apis/admin/admin_user_search.go
Labels: admin, approved, feature, refactor

#825 Add project member query pagesize
  modules/openapi/component-protocol/scenarios/issue-manage/components/issueFilter/props.go
Labels: approved

#811 replace step value should use stepIDAssociationMap instead of sceneID…
  modules/dop/services/autotest_v2/space_data.go
Labels: approved

#798 modify workbench create org rule and some jump link
  modules/core-services/endpoints/organization.go
  modules/core-services/utils/regexp.go
  modules/core-services/utils/regexp_test.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/emptyOrgContent/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTip/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/createProjectTipWithoutOrg/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/emptyOrgText/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/projectTipWithoutOrg/render.go
Labels: approved, dop, refactor

#806 feature: cmp support new import method
  .erda/migrations/cluster-manager/20210708-add-manageconfig.sql
  .erda/migrations/cmp/20210528-cmp-base.sql
  apistructs/cluster.go
  apistructs/cmp.go
  apistructs/cmp_cloud_resource.go
  apistructs/erda_operator.go
  apistructs/org.go
  bundle/cluster.go
  bundle/org.go
  cmd/cluster-init/main.go
  conf/cluster-init/cluster-init.yaml
  erda.yml
  go.mod
  go.sum
  modules/admin/manager/cluster.go
  modules/cluster-init/client/client.go
  modules/cluster-init/config/config.go
  modules/cluster-init/provider.go
  modules/cluster-manager/services/apierrors/errors.go
  modules/cluster-manager/services/cluster/cluster.go
  modules/cmp/conf/conf.go
  modules/cmp/dbclient/models.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/endpoints/common.go
  modules/cmp/endpoints/endpoints.go
  modules/cmp/endpoints/records.go
  modules/cmp/i18n/i18n.go
  modules/cmp/impl/clusters/cluster_hook.go
  modules/cmp/impl/clusters/clusterinfo.go
  modules/cmp/impl/clusters/import_cluster.go
  modules/cmp/impl/clusters/offline_edge_cluster.go
  modules/cmp/impl/clusters/proxy-deploy.go
  modules/cmp/impl/clusters/update_cluster.go
  modules/cmp/impl/clusters/upgrade_edge_cluster.go
  modules/cmp/initialize.go
  modules/cmp/services/kubernetes/kubernetes.go
  modules/openapi/api/apis/cmdb/cmdb_cluster_create.go
  modules/openapi/api/apis/cmp/cmp_cluster_import.go
  modules/openapi/api/apis/cmp/cmp_cluster_init_command.go
  pkg/helm/getter.go
  pkg/helm/helm.go
  pkg/helm/manager.go
  pkg/k8sclient/client.go
  pkg/k8sclient/config/config.go
  pkg/k8sclient/scheme/register.go
Labels: approved, cmp, feature

#827 bugfix: metric query bug
  modules/msp/apm/metric/routes.go
Labels: approved, bugfix, msp, refactor

#826 feature: Automatically inject i18n for trace debug
  modules/msp/apm/trace/provider.go
  modules/msp/apm/trace/trace.service.go
Labels: approved, msp, refactor

#818 bugfix: db model default value config not sync with database
  modules/msp/instance/db/tables.go
  modules/msp/instance/db/tmc_ini.go
  modules/msp/instance/db/tmc_request_relation.go
  modules/msp/instance/db/tmc_version.go
  modules/msp/resource/deploy/handlers/loganalytics/loganalytics.go
  modules/msp/resource/utils/es_client.go
Labels: approved, bugfix, msp

#829 change edge site offline api to ecp
  modules/ecp/services/kubernetes/uniteddeployment.go
  modules/openapi/api/apis/cmp/cmp_edge_host_offline.go
Labels: approved

#813 feature: support migration in python
  .github/workflows/ci-it.yml
  pkg/database/sqlparser/ddlreverser/reverser.go
  pkg/database/sqlparser/ddlreverser/reverser_test.go
  pkg/database/sqlparser/migrator/db.go
  pkg/database/sqlparser/migrator/equal_test.go
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/model.go
  pkg/database/sqlparser/migrator/parameters.go
  pkg/database/sqlparser/migrator/script.go
  pkg/database/sqlparser/migrator/scripts.go
  pkg/database/sqlparser/migrator/scripts_test.go
  pkg/database/sqlparser/migrator/service.go
  pkg/database/sqlparser/pygrator/entrypoint.go
  pkg/database/sqlparser/pygrator/entrypoint_test.go
  pkg/database/sqlparser/pygrator/model.go
  pkg/database/sqlparser/pygrator/model_test.go
  pkg/database/sqlparser/pygrator/package.go
  pkg/database/sqlparser/pygrator/package_test.go
  pkg/database/sqlparser/pygrator/requirements.go
  pkg/database/sqlparser/pygrator/script.go
  pkg/database/sqlparser/pygrator/script_test.go
  pkg/database/sqlparser/pygrator/settings.go
  pkg/database/sqlparser/pygrator/settings_test.go
  pkg/database/sqlparser/snapshot/snapshot.go
  pkg/database/sqlparser/table/table_test.go
  pkg/strutil/namestyle.go
  pkg/strutil/namestyle_test.go
  tools/cli/cmd/migrate.go
  tools/cli/cmd/migrate_lint.go
  tools/cli/cmd/migrate_mkpy.go
  tools/cli/cmd/migrate_record.go
  tools/cli/command/root_cmd.go
Labels: approved, feature

#797 Asynchronous copy manual test testset, change actions not blocking channel
  apistructs/file_records.go
  apistructs/testset.go
  modules/dop/conf/conf.go
  modules/dop/endpoints/autotests_space.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/testcase.go
  modules/dop/endpoints/testset.go
  modules/dop/initialize.go
  modules/dop/services/testcase/export.go
  modules/dop/services/testcase/file_records.go
  modules/dop/services/testcase/import.go
  modules/dop/services/testset/copy.go
Labels: approved, dop, feature

#832 fix cluster migration error
  .erda/migrations/cmdb/20210708-add-manageconfig.sql
  .erda/migrations/ops/20210528-ops-base.sql
Labels: approved

#815 fix multi metric bug
  modules/msp/apm/metric/routes.go
  modules/msp/apm/metric/routes_test.go
Labels: approved, bugfix, msp, refactor

#834 Set auto test wait time api positive
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/waitEditor/render.go
Labels: approved

#836 bugfix: servicemesh deploy terminus_key read error
  modules/msp/instance/db/instance_tenant.go
  modules/msp/resource/deploy/handlers/servicemesh/servicemesh.go
Labels: approved

#833 add collector addr env
  erda.yml
Labels: approved

#816 fix config center bug
  go.mod
  go.sum
  modules/msp/configcenter/config.center.service.go
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/configcenter/provider.go
  modules/msp/configcenter/test.http
Labels: approved

#839 Fix the problem that dialer does not transparently transmit backend response headers
  modules/cluster-dialer/server/tunnel-server.go
  modules/msp/resource/utils/es_client.go
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: approved

#824 Feature/reportengine fix
  build/dockerfiles/reportengine/Dockerfile
  cmd/monitor/extensions/cloud-import/main.go
  cmd/monitor/extensions/loghub/main.go
  cmd/monitor/extensions/reportengine/main.go
  cmd/monitor/monitor/main.go
  conf/monitor/extensions/cloud-import.yaml
  conf/monitor/extensions/loghub/log-exporter.deployment.yml
  conf/monitor/extensions/loghub/log-metrics.deployment.yml
  conf/monitor/extensions/loghub/log-metrics.yml
  conf/monitor/extensions/loghub/output/elasticsearch-rollover.yml
  conf/monitor/extensions/loghub/output/elasticsearch.index.rollover.json
  conf/monitor/extensions/loghub/output/elasticsearch.index.template.json
  conf/monitor/extensions/loghub/output/elasticsearch.yml
  conf/monitor/extensions/loghub/output/stdout.yml
  conf/monitor/extensions/loghub/output/udp.yml
  conf/monitor/extensions/report-engine.yaml
  conf/resources.go
  modules/cmdb/services/apierrors/errors.go
  modules/core-services/endpoints/access_key.go
  modules/core-services/services/apierrors/errors.go
  modules/monitor/dashboard/report/apis/provider.go
  modules/monitor/dashboard/report/apis/report-task-apis.go
  modules/monitor/dashboard/report/apis/report-task-apis_test.go
  modules/monitor/dashboard/report/engine/provider.go
Labels: approved

#841 feature: fix pip install command
  pkg/database/sqlparser/pygrator/package.go
Labels: approved, feature

#840 update cluster dialer connect
  modules/extensions/loghub/index/query/clients.go
  modules/msp/configcenter/nacos/adapter.go
  modules/msp/registercenter/nacos/adapter.go
  modules/msp/registercenter/test.http
  modules/msp/registercenter/zkproxy/adapter.go
  modules/msp/resource/utils/es_client.go
  pkg/http/httpclient/client.go
Labels: approved

#835 bugfix:fix createTime updateTime is ""
  modules/msp/apm/trace/trace.service.go
  modules/openapi/api/apis/msp/apm/trace/get_trace_debug_history_status.go
  modules/openapi/api/apis/msp/apm/trace/post_trace_debug_history.go
  modules/openapi/api/apis/msp/apm/trace/put_trace_debug_history_stop.go
Labels: approved, bugfix, msp, refactor

#843 fix(admin): inject error port when start admin
  erda.yml
  modules/admin/config/config.go
  modules/admin/provider.go
Labels: approved

#844 feature: remove duplicates
  pkg/database/sqlparser/migrator/migrator.go
Labels: approved, feature

#842 modify create org regex, add default if not planFinishedAt
  modules/core-services/endpoints/organization.go
  modules/core-services/utils/regexp.go
  modules/core-services/utils/regexp_test.go
  modules/dop/endpoints/organization.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/tableGroup/render.go
  modules/openapi/component-protocol/scenarios/home-page-content/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
  pkg/erda-configs/i18n/workbench.json
Labels: approved, bugfix, dop

#848 bugfix:remove gocql query policy
  modules/msp/apm/exception/exception.service.go
Labels: approved, bugfix, msp, refactor

#850 fix: fix the bug of execute manaual test api
  modules/dop/endpoints/attempt.go
  modules/dop/endpoints/endpoints.go
Labels: approved

#851 bugfix: Fix trace gocql policy
  modules/msp/apm/trace/trace.service.go
Labels: approved, bugfix, msp, refactor

#852 update erda-infra version
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/msp/apm/checker/storage/sync-cache/provider.go
Labels: approved

#856 fix the crate strategy save value is nil
  modules/monitor/alert/alert-apis/adapt/alert_convert.go
Labels: bugfix, msp

#845 fix: terminal && import cluster
  erda.yml
  modules/cluster-dialer/server/tunnel-server.go
  modules/cluster-manager/model/model.go
  modules/cluster-manager/services/cluster/cluster.go
  modules/cmp/impl/clusters/import_cluster.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/plugins/k8s/terminal.go
Labels: approved

#830 feature: support tip prxoy cluster status by init command
  modules/cmp/endpoints/cluster.go
  modules/cmp/impl/clusters/import_cluster.go
  modules/cmp/impl/clusters/proxy-deploy.go
Labels: approved

#859 bug fix and modify backendPath
  modules/monitor/alert/alert-apis/alert.service.go
  modules/monitor/alert/storage/alert-record/consumer.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/permission.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_create.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_delete.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_record.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_attrs.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_histories.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_issue_create.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_issue_update.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_records.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_switch.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_update.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alerts.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alerts_rules.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_create.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_dash_preview.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_delete.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_metrics.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_notify_target.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_switch.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alert_update.go
  modules/openapi/api/apis/tmc/tmc_micro_service_customize_alerts.go
Labels: bugfix, msp

#864 fix: fix the bug of execute manaual test api
  modules/dop/endpoints/attempt.go
  modules/dop/endpoints/endpoints.go
Labels: approved

#863 get new proto-go
  go.mod
  go.sum
Labels: bugfix, msp

#862 fix: cluster init retry
  modules/cmp/impl/clusters/import_cluster.go
  modules/openapi/api/apis/cmp/cmp_cluster_init_retry.go
Labels: approved

#849 fix hepa issue
  modules/hepa/gateway/service/gateway_zone_service.go
Labels: approved

#868 modify created_time is now
  modules/monitor/alert/storage/alert-record/consumer.go
  modules/openapi/api/apis/tmc/tmc_micro_service_alert_record_attrs.go
Labels: approved

#872 bugfix: Fix trace bug(openapi)
  go.sum
  modules/msp/apm/trace/db/trace_request_history.go
  modules/openapi/api/apis/msp/apm/trace/get_trace_debug_history.go
Labels: approved, bugfix, msp, refactor

#874 Update proto go
  go.mod
  go.sum
Labels: approved, msp, refactor

#876 bugfix: Fix create trace debug
  modules/msp/apm/trace/trace.service.go
Labels: approved, bugfix, msp, refactor

#877 remove some environment from erda yaml
  erda.yml
Labels: approved

#878 fix: scheduler cpu subscribe radio patch error
  modules/scheduler/impl/cluster/hook.go
Labels: approved, bugfix, orchestrator

#881 Fix the potential problem of deleting the api but not deleting the ingress when the apiserver is unreachable
  modules/hepa/cmd/hepa/main.go
  modules/hepa/gateway/service/gateway_openapi_service.go
  modules/hepa/k8s/k8s_adapter.go
Labels: approved, bugfix, hepa

#889 bugfix:Fix instances status bug
  modules/monitor/apm/topology/topology.go
Labels: approved, bugfix, msp, refactor

#887 fix update time and delete userIDs
  go.mod
  go.sum
  modules/monitor/alert/alert-apis/alert.service.go
  modules/monitor/alert/storage/alert-record/consumer.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/provider.go
Labels: bugfix, msp

#895 optimize: add debug log
  modules/msp/resource/deploy/coordinator/provider.go
  modules/msp/resource/deploy/handlers/apigateway/provider.go
  modules/msp/resource/deploy/handlers/configcenter/provider.go
  modules/msp/resource/deploy/handlers/etcd/provider.go
  modules/msp/resource/deploy/handlers/generalability/provider.go
  modules/msp/resource/deploy/handlers/handler.go
  modules/msp/resource/deploy/handlers/jvmprofiler/provider.go
  modules/msp/resource/deploy/handlers/loganalytics/provider.go
  modules/msp/resource/deploy/handlers/loges/provider.go
  modules/msp/resource/deploy/handlers/logexporter/provider.go
  modules/msp/resource/deploy/handlers/monitor/provider.go
  modules/msp/resource/deploy/handlers/monitorcollector/provider.go
  modules/msp/resource/deploy/handlers/monitorkafka/provider.go
  modules/msp/resource/deploy/handlers/monitorzk/provider.go
  modules/msp/resource/deploy/handlers/mysql/provider.go
  modules/msp/resource/deploy/handlers/nacos/provider.go
  modules/msp/resource/deploy/handlers/postgresql/provider.go
  modules/msp/resource/deploy/handlers/registercenter/provider.go
  modules/msp/resource/deploy/handlers/servicemesh/provider.go
  modules/msp/resource/deploy/handlers/zkproxy/provider.go
  modules/msp/resource/deploy/handlers/zookeeper/provider.go
Labels: approved

#898 Fix checker terminus-request-sampled header
  modules/msp/apm/checker/plugins/http/trace.go
Labels: approved, bugfix, msp

#899 bugfix: nacos sql duplicate key error
  conf/msp/init_sqls/tmc/nacos.sql
  modules/msp/resource/deploy/handlers/mysql/mysql.go
Labels: approved

#892 fix: dialer register delay
  modules/cluster-dialer/server/tunnel-server.go
  modules/cmp/impl/clusters/update_cluster.go
Labels: approved, bugfix, cmp

#904 modify erda.yml create_org_enable env
  erda.yml
Labels: approved

#907 bugfix: api-gateway config error
  modules/msp/resource/deploy/handlers/apigateway/apigateway.go
Labels: approved

#802 upgrade client-go to 0.21.2
  go.mod
  go.sum
  modules/cmp/endpoints/kubernetes/configmap.go
  modules/cmp/endpoints/kubernetes/daemonset.go
  modules/cmp/endpoints/kubernetes/endpoints.go
  modules/cmp/endpoints/kubernetes/namespace.go
  modules/cmp/endpoints/kubernetes/node.go
  modules/cmp/endpoints/kubernetes/pod.go
  modules/cmp/endpoints/kubernetes/secret.go
  modules/cmp/endpoints/kubernetes/service.go
  modules/cmp/endpoints/kubernetes/statefulset.go
  modules/cmp/initialize.go
  pkg/clientgo/kubernetes/clientset.go
Labels: approved, feature, refactor

#896 fix(admin): list cluster without org when the user is the administrator
  modules/admin/manager/cluster.go
Labels: approved

#870 autotest change tooltip displayed text
  pkg/erda-configs/i18n/autotest.json
Labels: approved, dop, feature

#900 fix(edas): cancel func will not be used when it is nil
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: approved

#913 optimize msp code
  modules/monitor/utils/header.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/permission.go
  modules/msp/apm/checker/plugins/http/provider.go
  pkg/common/permission/permission.go
Labels: approved

#905 feature: add mkpypkg to debug erda pygrator
  tools/cli/cmd/migrate_mkpypkg.go
  tools/cli/cmd/migrate_record.go
  tools/cli/command/root_cmd.go
Labels: approved, feature

#908 Adjust the functional architecture diagram and documents
  README.md
  docs/assets/functional_architecture.jpg
Labels: approved, documentation

#894 fix personal message's bug
  apistructs/issue.go
  modules/dop/endpoints/issue_callback.go
  pkg/erda-configs/i18n/notify_item.yml
Labels: approved, bugfix, dop

#873 autotest scene pre parallel steps output shouldn't show between parallel steps
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/apiEditor/render.go
Labels: approved, bugfix, dop

#915 Test file records response i18n
  apistructs/file_records.go
  modules/dop/endpoints/file_records.go
  modules/dop/services/i18n/i18n.go
  modules/dop/services/testcase/file_records.go
  pkg/erda-configs/i18n/qa.json
Labels: approved

#921 bugfix: fix no tracing
  modules/msp/apm/trace/trace.service.go
Labels: approved, bugfix, msp, refactor

#927 bugfix: geteway TOP3 domain from req_host
  .erda/migrations/monitor/20210713-01-monitor-base.sql
Labels: approved, bugfix, msp

#903 fix ingress issues
  modules/hepa/k8s/k8s_adapter.go
Labels: approved, bugfix, hepa

#934 fix the bug of get alert rules error is ParseInt error
  go.mod
  go.sum
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/alert.service.go
  modules/msp/apm/alert/alert.service.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_create.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_delete.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_record.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_record_attrs.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_record_histories.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_record_issue_create.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_record_issue_update.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_records.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_update.go
  modules/openapi/api/apis/msp/apm/alert/apm_alerts.go
  modules/openapi/api/apis/msp/apm/alert/apm_alerts_rules.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_create.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_dash_preview.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_delete.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_metrics.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_notify_target.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_update.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alerts.go
Labels: bugfix, msp

#939 bugfix: fix addon deploy callback struct json serialization error
  modules/msp/resource/deploy/handlers/handler.go
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/services/addon/addon_deploy.go
  modules/orchestrator/services/addon/addon_handler.go
  pkg/mysqlhelper/mysql_test.go
Labels: bugfix, msp

#944 Cherry-pick: fix addon deploy callback struct json serialization error
  modules/msp/resource/deploy/handlers/handler.go
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/services/addon/addon_deploy.go
  modules/orchestrator/services/addon/addon_handler.go
  pkg/mysqlhelper/mysql_test.go
Labels: approved, auto-cherry-pick

#942 cherry pick Feature/add debug logs
  go.mod
  go.sum
  pkg/clusterdialer/dialer.go
  pkg/mysqlhelper/mysql.go
Labels: approved, auto-cherry-pick

#937 fix: update k8sHost to short domain
  modules/openapi/server.go
  modules/pkg/innerdomain/innerdomain.go
Labels: approved, bugfix, openapi

#935 Xlsx package upgrade to v3.2.4
  go.mod
  go.sum
Labels: approved, dop, refactor

#923 modify orgFormModal org name regexp
  modules/openapi/component-protocol/scenarios/home-page-sidebar/components/orgFormModal/render.go
Labels: approved, bugfix, dop

#926 feature(pipeline): gc(db&resource) config support setup from env
  modules/pipeline/conf/conf.go
  modules/pipeline/spec/pipeline.go
Labels: approved, feature, pipeline

#956 bugfix: optimize on deploy continuous processing when interrupted
  modules/msp/resource/deploy/handlers/handler.go
  modules/msp/resource/utils/nacos_client.go
Labels: approved

#960 Xlsx package upgrade to v3.2.4 (#935)
  go.mod
  go.sum
Labels: approved

#930 fix mobile users affecting user ratio data
  modules/dicehub/service/publish_item/item_statistics.go
Labels: approved, bugfix, dop

#963 merge the master code to release/1.1
  go.mod
  go.sum
  modules/monitor/alert/alert-apis/adapt/customize.go
  modules/monitor/alert/alert-apis/alert.service.go
  modules/monitor/alert/storage/alert-record/consumer.go
  modules/monitor/utils/httpRequest.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/permission.go
  modules/msp/apm/alert/provider.go
  modules/msp/apm/checker/plugins/http/provider.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_create.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_delete.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_record.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_record_attrs.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_record_histories.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_record_issue_create.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_record_issue_update.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_records.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alert_update.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alerts.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_alerts_rules.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_create.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_dash_preview.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_delete.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_metrics.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_notify_target.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alert_update.go
  modules/openapi/api/apis/msp/apm/alert/tmc_micro_service_customize_alerts.go
Labels: approved

#965 bugfix: fix generate schema example error
  bundle/gen_example.go
  bundle/gen_example_test.go
Labels: approved, bugfix

#979 feature: update span proto
  go.mod
  go.sum
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/permission.go
  modules/msp/apm/trace/db/trace_request_history.go
  modules/msp/apm/trace/trace.service.go
  modules/msp/configcenter/config.center.service.go
  modules/msp/instance/permission/permission.go
  modules/msp/menu/menu.service.go
  modules/msp/registercenter/register.center.service.go
  modules/msp/registercenter/register.center.service.host.go
  modules/msp/registercenter/register.center.service.host.runtime.go
  modules/msp/registercenter/register.center.service.route.go
  pkg/common/errors/server.go
Labels: approved, msp, refactor

#976 fix(admin): list cluster info with correctly cluster struct
  modules/admin/manager/cluster.go
  modules/openapi/api/apis/admin/admin_cluster_get.go
Labels: admin, approved, bugfix

#977 fix(admin): export excel without orgID when the user is administrator
  bundle/audit.go
  modules/admin/manager/audit.go
Labels: admin, approved, bugfix

#980 fix: add api specs of orchestrator
  modules/openapi/api/apis/orchestrator/orchestrator_cluster_instances_usage.go
  modules/openapi/api/apis/orchestrator/orchestrator_instances_usage.go
Labels: approved, bugfix, dop

#974 autotest execute table auto with
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/executeTaskTable/render.go
Labels: approved

#981 update(scheduler): adapt soldier to get cluster info via cluster manager
  modules/scheduler/impl/terminal/terminal.go
Labels: approved

#969 action spec adds the execution selector field, and the pipeline selects the executor according to the field
  apistructs/extention.go
  modules/pipeline/services/pipelinesvc/create_task.go
  modules/pipeline/services/pipelinesvc/create_task_test.go
Labels: approved

#910 collect metrics bdl use new httpclient
  bundle/collector.go
Labels: approved

#975 change autotest refresh key
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-scenes/components/refreshButton/render.go
Labels: approved

#985 bugfix: order by startTime desc
  modules/msp/apm/trace/trace.service.go
Labels: approved, bugfix, msp, refactor

#988 bugfx: fix parse time zone bug
  modules/msp/apm/trace/db/trace_request_history.go
  modules/msp/apm/trace/trace.service.go
Labels: approved, bugfix, msp, refactor

#992 cherrypick: fix conflict 998fa88a195f518942643b2082a2ff001d45a628
  go.mod
  go.sum
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/permission.go
  modules/msp/apm/trace/db/trace_request_history.go
  modules/msp/apm/trace/trace.service.go
  modules/msp/configcenter/config.center.service.go
  modules/msp/instance/permission/permission.go
  modules/msp/menu/menu.service.go
  modules/msp/registercenter/register.center.service.go
  modules/msp/registercenter/register.center.service.host.go
  modules/msp/registercenter/register.center.service.host.runtime.go
  modules/msp/registercenter/register.center.service.route.go
  pkg/common/errors/server.go
Labels: approved

#970 Fix/pipeline report loop task
  .erda/migrations/pipeline/20210714-update-report-meta-type.sql
  .github/workflows/ci-it.yml
  apistructs/pipeline_report.go
  modules/pipeline/pipengine/reconciler/taskrun/task_loop.go
Labels: approved
