Repository erda-project/erda, pull requests merged in 2022-12, with the labels that each got.

#5623 fix: flink-operator compatibility in k8s 1.24 version
  go.mod
  go.sum
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
  pkg/k8sclient/scheme/register.go
Labels: bugfix, approved

#5622 feat(cp): define openapi cp api throuth protobuf to use protobuf's over_permission
  api/proto/core/openapi/component-protocol/cp.proto
  api/proto/openapiv1/openapi/component/protocol/openapi_component_protocol.proto
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  internal/core/openapi/legacy/component-protocol/provider/cp.service.go
  internal/core/openapi/legacy/component-protocol/provider/provider.go
  internal/core/openapi/legacy/component-protocol/proxy/notspec_error.go
  internal/core/openapi/legacy/component-protocol/proxy/notspec_response.go
  internal/core/openapi/legacy/component-protocol/proxy/render.go
Labels: feature

#5612 fix: erda cli push and pull project
  tools/cli/cmd/push.go
  tools/cli/command/erda.go
  tools/cli/common/application.go
  tools/cli/common/issue.go
  tools/cli/common/mr.go
  tools/cli/common/project.go
  tools/cli/common/record.go
  tools/cli/common/repo.go
Labels: bugfix, approved

#5624 fix: fix render over_permission
  api/proto/common/openapi.proto
  api/proto/core/monitor/dataview/dataview.proto
  api/proto/core/openapi/component-protocol/cp.proto
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  internal/core/openapi/openapi-ng/auth/auth.go
  internal/core/openapi/openapi-ng/auth/over_permission/match/registry.go
  internal/core/openapi/openapi-ng/auth/over_permission/match/request_body_value.go
  internal/core/openapi/openapi-ng/auth/over_permission/match/request_body_value_test.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_id/check.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_id/provider.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_name/check.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_name/check_test.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_name/provider.go
Labels: bugfix, approved

#5626 fix: sort the cookie reports in order to make sure the latest cookie will be used
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie_test.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
Labels: bugfix, approved

#5627 fix: fix cloud manage pod detail chart, round_float change to max
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
Labels: bugfix

#5630 fix(erda-server): clusters sensitive information leakage
  internal/apps/admin/manager/cluster.go
  internal/apps/admin/manager/cluster_test.go
  internal/apps/admin/manager/id.go
Labels: admin, bugfix

#5629 fix: some security breach
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  internal/core/openapi/openapi-ng/interceptors/response/response.go
Labels: bugfix, approved

#5631 fix: rename name tag to container_id
  cmd/monitor/collector/bootstrap-agent.yaml
  erda.yml
Labels: bugfix, approved

#5633 fix: extend the length limit of the field `includes` `excludes`
  .erda/migrations/cmdb/20221213-code-coverage-include-exclude.sql
Labels: bugfix, approved

#5636 fix: list clusters nil ptr and missing org param
  internal/apps/admin/manager/cluster.go
Labels: bugfix

#5635 fix: fix over_permission not work
  internal/core/openapi/openapi-ng/auth/over_permission/match/common.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_id/check.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_name/check.go
  internal/core/openapi/openapi-ng/auth/over_permission/org_name/check_test.go
Labels: bugfix

#5638 fix: leaderwork failed to init assign map due to context cancel
  internal/tools/pipeline/providers/dispatcher/consistent.go
  internal/tools/pipeline/providers/leaderworker/leader_listen_worker_task.go
Labels: bugfix, approved

#5637 fix: temporary remove get cluster permission check
  internal/apps/admin/manager/cluster.go
  internal/apps/admin/manager/cluster_service_test.go
  internal/apps/admin/manager/cluster_test.go
Labels: bugfix

#5639 fix(pipeline): leader pipeline too many network connections due to query is edge cluster
  internal/tools/pipeline/providers/edgepipeline_register/interface.go
  internal/tools/pipeline/providers/edgepipeline_register/interface_test.go
Labels: pipeline, bugfix, approved

#5641 fix: cluster access key render auth fail
  internal/apps/cmp/endpoints/cluster_credential.go
  internal/apps/cmp/endpoints/common.go
  internal/apps/cmp/endpoints/commone_test.go
  internal/apps/cmp/i18n/i18n.go
Labels: bugfix

#5634 feat: trace query not equal condition
  api/proto/msp/apm/trace/trace.proto
  internal/apps/msp/apm/trace/query/commom/custom/trace_inparams.go
  internal/apps/msp/apm/trace/query/components/trace-query/table/provider.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
  internal/apps/msp/apm/trace/query/source/elasticsearch_source.go
  internal/apps/msp/apm/trace/query/source/elasticsearch_source_test.go
Labels: feature

#5642 feat: log-service use suitable regexp handler by pattern
  cmd/monitor/log-service/bootstrap.yaml
  cmd/monitor/log-service/main.go
  erda.yml
  internal/apps/msp/apm/log-service/analysis/consumer.go
  internal/apps/msp/apm/log-service/analysis/processors/processors.go
  internal/apps/msp/apm/log-service/analysis/processors/regex/regex.go
  internal/apps/msp/apm/log-service/analysis/processors/regex/regex_test.go
  internal/apps/msp/apm/log-service/analysis/provider.go
  internal/apps/msp/apm/log-service/analysis/self_metrics.go
Labels: feature, approved

#5643 fix: remove redundant migration dependency package
  .erda/migrations/cmdb/requirements.txt
Labels: bugfix

#5648 fix: fix transaction http error chart no data
  internal/apps/msp/apm/service/components/transaction-http-error/metric_table/provider.go
Labels: bugfix, approved

#5646 fix: many addon alert
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/notify_template.yaml
Labels: approved

#5650 fix: fix cloud dashboard no data
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5652 fix: metric inf panic
  internal/tools/monitor/core/metric/query/es-tsql/operator.go
  pkg/math/math.go
  pkg/math/math_test.go
Labels: bugfix

#5653 fix: metric use es meta panic
  internal/tools/monitor/core/metric/query/metricmeta/manager.go
  internal/tools/monitor/core/metric/query/metricmeta/manager_test.go
Labels: bugfix

#5651 fix: publish-items weak permission check
  internal/apps/dop/providers/publishitem/publish.item.service.go
Labels: bugfix, approved
