Repository erda-project/erda, pull requests merged in 2022-02, with the labels that each got.

#3957 fix: i18n of issue states
  apistructs/issue_state.go
  modules/dop/endpoints/project.go
  modules/dop/services/issuestate/issuestate.go
  modules/dop/services/issuestate/issuestate_test.go
  modules/dop/services/issuestate/state-en_US.json
  modules/dop/services/issuestate/state-zh_CN.json
Labels: dop, bugfix

#3992 feat: Project list item default logo, hierarchy change
  modules/dop/component-protocol/components/project-list-all/components/list/provider.go
  modules/dop/component-protocol/scenarios/project-list-all.yml
Labels: feature

#3997 feat: remove apm metrics compatible
  modules/core/monitor/metric/storage/elasticsearch/provider.go
Labels: feature, approved

#3996 refactor(cp-cluster): change memory to mem in chart
  conf/cmp/i18n/cp/scenarios/cmp-cluster-list.yaml
  modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
  modules/cmp/component-protocol/components/cmp-cluster-list/list/render_test.go
Labels: refactor, approved

#3971 fix: scheduler executor create at runtime
  modules/scheduler/executor/executor.go
  modules/scheduler/impl/cluster/clusterutil/clusterutil.go
Labels: bugfix

#4001 feat: Align definition and source proto definitions with code specifications
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto/core/pipeline/definition/definition.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  go.mod
  go.sum
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/providers/definition/db/define.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: dop, pipeline, feature, approved

#3999 fix: issue import export asynchronous（reopen）
  apistructs/file_records.go
  apistructs/issue.go
  modules/dop/conf/conf.go
  modules/dop/endpoints/issue.go
  modules/dop/initialize.go
  modules/dop/services/issue/export.go
  modules/dop/services/issue/import.go
  modules/dop/services/issue/issue.go
  modules/dop/services/testcase/file_records.go
Labels: dop, bugfix, approved

#4003 fix: console button
  modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml
Labels: bugfix, approved

#4004 fix: console button
  modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml
Labels: bugfix, approved

#4005 feat: aggregate release by default
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
Labels: feature, approved

#3998 fix: delete cluster bugfix
  bundle/core_services.go
  bundle/orchestrator.go
  modules/cmp/impl/clusters/offline_edge_cluster.go
  modules/cmp/impl/clusters/offline_test.go
  modules/core-services/dao/project.go
  modules/core-services/endpoints/project.go
  modules/core-services/services/apierrors/errors.go
  modules/core-services/services/project/project.go
  modules/orchestrator/dbclient/addon_instance_routing.go
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/endpoints/runtime.go
  modules/orchestrator/services/runtime/runtime.go
Labels: bugfix

#3774 refactor: pipeline eci refactor
  apistructs/job.go
  apistructs/pipeline_container_instance.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/logic/job.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/pkg/container_provider/container_instance_provider.go
  modules/pipeline/pkg/container_provider/container_provider_test.go
  modules/pipeline/services/pipelinesvc/create_task.go
  modules/pipeline/services/pipelinesvc/create_v2.go
  modules/pipeline/services/pipelinesvc/run.go
  modules/pipeline/spec/pipeline_extra.go
  modules/pipeline/spec/pipeline_task.go
Labels: pipeline, feature, refactor, approved

#4009 feat: Standard filter in issue manage
  conf/dop/i18n/cp/common.yaml
  modules/dop/component-protocol/components/app-list-all/filter/render.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/in_params.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/init_filter.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/model.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/model_test.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/props.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/provider.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/render.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/render_test.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/state.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/state_conditions.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/state_conditions_test.go
  modules/dop/component-protocol/scenarios/issue-manage.yml
  providers/component-protocol/issueFilter/conditions.go
  providers/component-protocol/issueFilter/filterset.go
  providers/component-protocol/issueFilter/gshelper/helper.go
  providers/component-protocol/issueFilter/provider.go
Labels: feature, approved

#4015 fix(dop): Optimize project list statistics
  modules/core-services/services/project/project.go
  modules/dop/endpoints/project.go
  modules/dop/initialize.go
Labels: dop, bugfix, approved

#4014 fix: k8s spark flink affinity
  go.mod
  go.sum
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/util.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
  pkg/schedule/schedulepolicy/labelconfig/labelconfig.go
  pkg/schedule/schedulepolicy/labelpipeline/identity.go
  pkg/schedule/schedulepolicy/policy.go
Labels: bugfix, approved

#4002 fix: Modification of branch calculation method
  modules/dop/services/filetree/filetree.go
  modules/dop/services/filetree/filetree_test.go
Labels: dop, bug, approved

#3969 feat: monitor diagnotor
  api/proto-go/all.go
  api/proto-go/core/monitor/diagnotor/client/client.go
  api/proto-go/core/monitor/diagnotor/client/provider.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor.form.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor.http.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor.json.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor.validator.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_agent.form.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_agent.http.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_agent.json.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_agent.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_agent.validator.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_agent_grpc.pb.go
  api/proto-go/core/monitor/diagnotor/pb/diagnotor_grpc.pb.go
  api/proto-go/core/monitor/diagnotor/pb/register.services.pb.go
  api/proto-go/msp/apm/diagnotor/client/client.go
  api/proto-go/msp/apm/diagnotor/client/provider.go
  api/proto-go/msp/apm/diagnotor/pb/apm_diagnotor.form.pb.go
  api/proto-go/msp/apm/diagnotor/pb/apm_diagnotor.http.pb.go
  api/proto-go/msp/apm/diagnotor/pb/apm_diagnotor.json.pb.go
  api/proto-go/msp/apm/diagnotor/pb/apm_diagnotor.pb.go
  api/proto-go/msp/apm/diagnotor/pb/apm_diagnotor.validator.pb.go
  api/proto-go/msp/apm/diagnotor/pb/apm_diagnotor_grpc.pb.go
  api/proto-go/msp/apm/diagnotor/pb/register.services.pb.go
  api/proto/core/monitor/diagnotor/diagnotor.proto
  api/proto/core/monitor/diagnotor/diagnotor_agent.proto
  api/proto/msp/apm/diagnotor/apm_diagnotor.proto
  cmd/monitor/diagnotor-agent/main.go
  cmd/monitor/monitor/main.go
  cmd/msp/main.go
  conf/monitor/diagnotor-agent/diagnotor-agent.yaml
  conf/monitor/monitor/monitor.yaml
  conf/msp/msp.yaml
  conf/resources.go
  go.mod
  go.sum
  modules/core/monitor/diagnotor/agent/bootstrap/bootstrap.go
  modules/core/monitor/diagnotor/agent/container-runtime/runtime.go
  modules/core/monitor/diagnotor/agent/diagnotor.agent.service.go
  modules/core/monitor/diagnotor/agent/process.go
  modules/core/monitor/diagnotor/agent/provider.go
  modules/core/monitor/diagnotor/controller/diagnotor.service.go
  modules/core/monitor/diagnotor/controller/provider.go
  modules/core/monitor/diagnotor/controller/schedule.go
  modules/core/monitor/diagnotor/controller/test.http
  modules/core/services/filenamager/file.manager.service.go
  modules/core/services/filenamager/file.manager.service_test.go
  modules/core/services/filenamager/test.http
  modules/msp/apm/diagnotor/common.go
  modules/msp/apm/diagnotor/diagnotor.service.go
  modules/msp/apm/diagnotor/provider.go
  modules/msp/apm/diagnotor/test.http
  pipeline.yml
  pkg/common/apis/response.go
  pkg/common/errors/grpc.go
  pkg/common/errors/grpc_test.go
  pkg/common/errors/warn.go
Labels: msp, feature

#4013 fix: sort project list
  modules/core-services/endpoints/project.go
Labels: core feature, bugfix

#4018 fix: comp not found
  go.mod
  go.sum
  modules/cmp/component-protocol/scenarios/cmp-dashboard-poddetail.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workload-detail.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml
Labels: bugfix, approved

#4019 fix: hide aggregate button
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
Labels: bugfix

#4020 fix: (cherry-pick to release/1.6-alpha.2) hide aggregate button (#4019)
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
Labels: bugfix

#4022 refactor(cp-deploy): change style
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: refactor

#4023 fix: Fix issueFilter default states, return all components
  modules/dop/component-protocol/scenarios/code-coverage.yml
  modules/dop/component-protocol/scenarios/test-report.yml
  providers/component-protocol/issueFilter/filterset.go
  providers/component-protocol/issueFilter/provider.go
Labels: bugfix, approved

#4021 feat: monitor diagnotor agent auto exit
  conf/monitor/diagnotor-agent/diagnotor-agent.yaml
  modules/core/monitor/diagnotor/agent/bootstrap/bootstrap.go
  modules/core/monitor/diagnotor/agent/process.go
  modules/core/monitor/diagnotor/agent/provider.go
  modules/core/monitor/diagnotor/controller/diagnotor.service.go
  modules/core/monitor/diagnotor/controller/schedule.go
  modules/openapi/api/apis/monitor/monitor_filemanager_upload.go
Labels: feature

#4024 fix(dop): Solve the problem of broken link caused by adding scenes
  go.mod
  go.sum
  modules/dop/component-protocol/scenarios/auto-test-scenes.yml
  modules/dop/services/autotest_v2/scene.go
Labels: dop, bugfix, approved

#4026 fix: use `where` delete pipeline reports
  modules/pipeline/dbclient/op_pipeline_report.go
Labels: bugfix, approved

#4025 feat: dereference env
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/deployment_test.go
  pkg/parser/diceyml/diceyml.go
  pkg/strutil/interpolate.go
  pkg/strutil/interpolate_test.go
Labels: feature, scheduler

#3766 feat: basic addon surpport stop/start
  apistructs/addon.go
  apistructs/runtime_dto.go
  bundle/orchestrator.go
  modules/orchestrator/dbclient/addon_instance_routing.go
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/services/addon/addon.go
  modules/orchestrator/services/addon/addon_deploy.go
  modules/orchestrator/services/addon/addon_test.go
  modules/orchestrator/services/apierrors/errors.go
  modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
  modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
Labels: approved

#4027 refactor(cp-project): change status
  modules/dop/component-protocol/components/project-runtime/list/list.go
  modules/dop/component-protocol/components/project-runtime/list/list_test.go
Labels: refactor

#4038 fix: set option: `returnAllComponents` true value
  modules/dop/component-protocol/scenarios/scenes-import-record.yml
Labels: bugfix, approved

#3478 feat: support Alicloud ECI and CSI
  apistructs/addon.go
  apistructs/cluster_info.go
  apistructs/runtime_dto.go
  bundle/orchestrator.go
  erda.yml
  modules/msp/resource/deploy/handlers/apigateway/apigateway.go
  modules/msp/resource/deploy/handlers/etcd/etcd.go
  modules/msp/resource/deploy/handlers/handler.go
  modules/msp/resource/deploy/handlers/loges/logeshandler.go
  modules/msp/resource/deploy/handlers/logexporter/logexporter.go
  modules/msp/resource/deploy/handlers/monitorcollector/monitor_collector.go
  modules/msp/resource/deploy/handlers/monitorkafka/monitor_kafka.go
  modules/msp/resource/deploy/handlers/monitorzk/monitor_zk.go
  modules/msp/resource/deploy/handlers/mysql/mysql.go
  modules/msp/resource/deploy/handlers/nacos/nacos.go
  modules/msp/resource/deploy/handlers/postgresql/postgresql.go
  modules/msp/resource/deploy/handlers/zkproxy/zkproxy.go
  modules/msp/resource/deploy/handlers/zookeeper/zookeeper.go
  modules/msp/resource/utils/common.go
  modules/orchestrator/services/addon/addon_deploy.go
  modules/orchestrator/services/addon/addon_sourcecov.go
  modules/orchestrator/services/addon/addon_status.go
  modules/orchestrator/services/addon/addon_test.go
  modules/orchestrator/services/deployment/deployment.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/utils/deployment_utils.go
  modules/scheduler/endpoints/endpoints.go
  modules/scheduler/executor/plugins/k8s/addon/daemonset/daemonset.go
  modules/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  modules/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  modules/scheduler/executor/plugins/k8s/addon/process.go
  modules/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
  modules/scheduler/executor/plugins/k8s/addon/redis/redis.go
  modules/scheduler/executor/plugins/k8s/addon/sourcecov/sourcecov.go
  modules/scheduler/executor/plugins/k8s/addon/utils.go
  modules/scheduler/executor/plugins/k8s/daemonset.go
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/deployment_test.go
  modules/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
  modules/scheduler/executor/plugins/k8s/k8s.go
  modules/scheduler/executor/plugins/k8s/k8s_event.go
  modules/scheduler/executor/plugins/k8s/persistentvolumeclaim/persistentvolumeclaim.go
  modules/scheduler/executor/plugins/k8s/statefulset.go
  modules/scheduler/executor/plugins/k8s/storageclass/storageclass.go
  modules/scheduler/impl/servicegroup/servicegroup.go
  modules/scheduler/task/task.go
  pkg/parser/diceyml/basic_validate_visitor.go
  pkg/parser/diceyml/define.go
Labels: feature

#4034 feat: group application release list for project release
  .erda/migrations/dicehub/20220211-release-list-group.py
  apistructs/release.go
  apistructs/release_test.go
  modules/dicehub/endpoints/release.go
  modules/dicehub/endpoints/release_test.go
  modules/dicehub/endpoints/release_test_data.zip
  modules/dicehub/service/release/release.go
  modules/dicehub/service/release/release_test.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_render.go
Labels: feature, approved

#4016 feat: add precheck for cluster offline
  apistructs/cmp.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/impl/clusters/add_edge_cluster.go
  modules/cmp/impl/clusters/offline_edge_cluster.go
  modules/cmp/impl/clusters/offline_test.go
Labels: feature, approved

#4046 feat: ignore org_id deleted_at sql check befor 20220209
  .erda/migrations/config.yml
Labels: msp, feature, approved

#4049 feat: ignore org_id deleted_at sql check befor 20220215
  .erda/migrations/config.yml
Labels: feature, approved

#4037 feat(orchestrator): the addon can also be deleted when the cluster is not exists
  bundle/cluster.go
  modules/orchestrator/services/addon/addon.go
Labels: orchestrator, feature, approved

#4047 fix: print error rather than return if unmarshal release list failed
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4053 fix(dop): remove the same name check of test plan updating
  modules/dop/services/autotest_v2/testplan_v2.go
Labels: dop, bugfix, approved

#4048 fix(cp-project): show kvinfo without service
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4058 fix: update infra
  go.mod
  go.sum
Labels: bugfix

#4042 feat: Automated testing, the request is proxied to the edge cluster regardless of whether it is an internal address or not
  pkg/apitestsv2/apitest_test.go
  pkg/apitestsv2/netportal.go
  pkg/apitestsv2/netportal_test.go
Labels: feature, approved

#4050 fix: kms describe api invoke wrong method
  modules/core-services/services/filesvc/svc.go
  modules/kms/endpoints/endpoints.go
  modules/kms/endpoints/kms.go
  pkg/kms/kms_test.go
Labels: bugfix, approved

#4051 feat: Standard filter in issue gantt
  modules/dop/component-protocol/components/issue-gantt/filter/model.go
  modules/dop/component-protocol/components/issue-gantt/filter/provider.go
  modules/dop/component-protocol/components/issue-gantt/filter/render.go
  modules/dop/component-protocol/components/issue-gantt/gantt/render.go
  modules/dop/component-protocol/scenarios/issue-gantt.yml
  providers/component-protocol/issueFilter/provider.go
Labels: feature, approved

#4017 feat: deployment order support batches
  .erda/migrations/orchestrator/20220211-deployment-order-batches.sql
  apistructs/deployment_order.go
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/initialize.go
  modules/orchestrator/queue/pusher_queue.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/deployment_order/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_cron.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/services/deployment_order/deployment_order_get_test.go
  modules/orchestrator/services/deployment_order/deployment_order_list.go
  modules/orchestrator/services/deployment_order/deployment_order_list_test.go
  modules/orchestrator/services/deployment_order/deployment_order_render.go
  modules/orchestrator/utils/deployment_utils.go
  modules/orchestrator/utils/parse.go
  modules/orchestrator/utils/parse_test.go
Labels: orchestrator, feature

#4054 fix: pipeline notify content
  modules/dop/services/cdp/cdp.go
  pkg/erda-configs/i18n/notify_item.yml
Labels: bugfix

#4036 feat: add root domin env to runtime
  modules/scheduler/executor/plugins/k8s/deployment.go
  modules/scheduler/executor/plugins/k8s/deployment_test.go
  modules/scheduler/executor/plugins/k8s/k8s.go
Labels: feature, approved

#4061 feat: support deployment order batches cherry pick
  .erda/migrations/config.yml
  .erda/migrations/orchestrator/20220211-deployment-order-batches.sql
  apistructs/deployment_order.go
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/initialize.go
  modules/orchestrator/queue/pusher_queue.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/deployment_order/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_cron.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/services/deployment_order/deployment_order_get_test.go
  modules/orchestrator/services/deployment_order/deployment_order_list.go
  modules/orchestrator/services/deployment_order/deployment_order_list_test.go
  modules/orchestrator/services/deployment_order/deployment_order_render.go
  modules/orchestrator/utils/deployment_utils.go
  modules/orchestrator/utils/parse.go
  modules/orchestrator/utils/parse_test.go
Labels: feature

#4062 fix(cp-project): sync render list with filter param
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4063 fix: modify bar and status add scope condition
  .erda/migrations/msp/20220216-menu.sql
  cmd/core-services/main.go
  cmd/messenger/main.go
  conf/core-services/core-services.yaml
  conf/messenger/messenger.yaml
  conf/msp/msp.yaml
  conf/resources.go
  erda.yml
  modules/messenger/notify/db/notify_history.go
  modules/msp/apm/alert/components/msp-alert-overview/alert-notify-charts/groupby-type-count/provider.go
Labels: bugfix, approved

#4065 fix: add AlarmHistory in msp menu
  .erda/migrations/msp/20220216-menu.sql
Labels: bugfix, approved

#4071 fix: modify eventbox.yaml
  conf/eventbox/eventbox.yaml
Labels: bugfix, approved

#4070 fix: release group can not be empty
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4072 fix: fix compatibility for old service volumes
  modules/scheduler/impl/servicegroup/servicegroup.go
Labels: bugfix

#4073 feat: Add the scheme to the header when the automation test agent requests
  pkg/apitestsv2/netportal.go
  pkg/http/httpclientutil/urlwrap.go
Labels: feature, approved

#4077 fix: fix compatible for old volume
  modules/orchestrator/services/deployment/deployment_context.go
Labels: bugfix

#4052 fix: fix application_*_service metric expression
  .erda/migrations/monitor/20220215-01-sp_metric_expression.sql
  conf/monitor/monitor/analyzer/metrics/apm/application_cache_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_db_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_http_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_mq_service.json
Labels: monitor-stack, bugfix

#4078 fix(cp-project): show filter state
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
Labels: bugfix

#4081 feat: alert event list & detail
  api/proto-go/core/monitor/alert/client/client.go
  api/proto-go/core/monitor/alert/pb/alert.form.pb.go
  api/proto-go/core/monitor/alert/pb/alert.http.pb.go
  api/proto-go/core/monitor/alert/pb/alert.json.pb.go
  api/proto-go/core/monitor/alert/pb/alert.pb.go
  api/proto-go/core/monitor/alert/pb/alert.validator.pb.go
  api/proto-go/core/monitor/alert/pb/alert_grpc.pb.go
  api/proto/core/monitor/alert/alert.proto
  conf/msp/i18n/cp/msp-alert-event-detail.yaml
  conf/msp/i18n/msp-i18n.yaml
  conf/openapi/openapi.yaml
  modules/cmp/alert_monitor_test.go
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/core/monitor/alert/alert-apis/db/alert_event.go
  modules/core/monitor/alert/alert-apis/db/alert_event_suppress.go
  modules/core/monitor/alert/alert-apis/db/db.go
  modules/core/monitor/alert/alert-apis/db/tables.go
  modules/core/monitor/alert/alert-apis/provider.go
  modules/core/monitor/alert/storage/alert-event/consumer.go
  modules/core/monitor/metric/query-example/provider.go
  modules/msp/apm/alert/alert_monitor_test.go
  modules/msp/apm/alert/components/common/constants.go
  modules/msp/apm/alert/components/msp-alert-event-detail/common/constants.go
  modules/msp/apm/alert/components/msp-alert-event-detail/common/inparams.go
  modules/msp/apm/alert/components/msp-alert-event-detail/common/model.go
  modules/msp/apm/alert/components/msp-alert-event-detail/common/utils.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/command.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/model.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-status-info/model.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-status-info/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/monitor-data-chart/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/more-operations/command.go
  modules/msp/apm/alert/components/msp-alert-event-detail/more-operations/model.go
  modules/msp/apm/alert/components/msp-alert-event-detail/more-operations/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/pause-form-modal/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/scenario.go
  modules/msp/apm/alert/components/msp-alert-event-list/common/constants.go
  modules/msp/apm/alert/components/msp-alert-event-list/common/inparams.go
  modules/msp/apm/alert/components/msp-alert-event-list/common/models.go
  modules/msp/apm/alert/components/msp-alert-event-list/common/utils.go
  modules/msp/apm/alert/components/msp-alert-event-list/configurableFilter/provider.go
  modules/msp/apm/alert/components/msp-alert-event-list/scenario.go
  modules/msp/apm/alert/components/msp-alert-event-list/searchFilter/provider.go
  modules/msp/apm/alert/components/msp-alert-event-list/table/provider.go
  modules/msp/apm/alert/components/provider.go
  modules/msp/apm/alert/components/scenarios/msp-alert-event-detail.yml
  modules/msp/apm/alert/components/scenarios/msp-alert-event-list.yml
Labels: msp

#4045 fix: fix msp project permissions
  modules/msp/apm/checker/apis/permission.go
  modules/msp/apm/checker/apis/permission_test.go
  modules/msp/apm/checker/apis/provider.go
Labels: msp, bugfix

#4084 fix(pipeline): add index to table pipeline_tasks
  .erda/migrations/pipeline/20220217-pipeline-task-add-index.sql
Labels: pipeline, bugfix, approved

#4086 fix: fix i18n
  conf/msp/i18n/cp/msp-alert-event-detail.yaml
Labels: msp, bugfix, approved

#4088 fix: db migration
  .erda/migrations/msp/20220217-alert_event_suppress.sql
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/msp/apm/alert/components/msp-alert-event-list/common/constants.go
Labels: msp, bugfix, approved

#4089 feat: download log API throttling
  conf/monitor/monitor/monitor.yaml
  modules/core/monitor/log/query/log.query.service.go
  modules/core/monitor/log/query/provider.go
  modules/core/monitor/storekit/elasticsearch/iterator.go
  modules/core/monitor/storekit/ratelimit.go
  modules/core/monitor/storekit/ratelimit_test.go
Labels: feature

#4090 fix: Get notifiy details in msp module
  modules/messenger/notify/db/alert_notify_index.go
  modules/messenger/notify/db/notify_history.go
  modules/messenger/notify/notify.service.go
  modules/msp/apm/alert/components/common/constants.go
  modules/msp/apm/alert/components/msp-notify-detail/common/utils.go
  modules/msp/apm/alert/components/msp-notify-detail/eventStatusInfo/model.go
  modules/msp/apm/alert/components/msp-notify-detail/eventStatusInfo/provider.go
  modules/msp/apm/alert/components/msp-notify-list/table/provider.go
  modules/msp/apm/alert/components/provider.go
Labels: bugfix, approved

#4091 fix: update file type config error
  modules/dop/services/environment/env_config.go
Labels: bugfix, approved

#4035 fix: check user is-existed when add member
  .erda/migrations/cmdb/20220214-delete-empty-userid-member.sql
  pkg/ucauth/user_admin.go
Labels: bugfix

#4087 fix(cp-deploy): change serverData icon from string to struct
  go.mod
  go.sum
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix, approved

#4093 fix: update infra
  go.mod
  go.sum
Labels: bugfix, approved

#4095 feat: endpoint support platform placeholder
  modules/hepa/services/runtime_service/impl/impl.go
  modules/hepa/services/runtime_service/impl/impl_test.go
  pkg/parser/diceyml/basic_validate_visitor.go
  pkg/parser/diceyml/basic_validate_visitor_test.go
Labels: hepa, orchestrator, feature

#4092 fix: Modify the x-axis in the notification type chart
  api/proto-go/core/messenger/notify/client/client.go
  api/proto-go/core/messenger/notify/pb/notify.form.pb.go
  api/proto-go/core/messenger/notify/pb/notify.json.pb.go
  api/proto-go/core/messenger/notify/pb/notify.pb.go
  api/proto-go/core/messenger/notify/pb/notify.validator.pb.go
  api/proto-go/core/messenger/notify/pb/notify_grpc.pb.go
  api/proto/core/messenger/notify/notify.proto
  conf/msp/i18n/msp-i18n.yaml
  modules/messenger/notify/db/notify_history.go
  modules/messenger/notify/notify.service.go
  modules/msp/apm/alert/components/msp-alert-overview/alert-notify-charts/groupby-type-count/provider.go
  modules/msp/apm/alert/components/msp-alert-overview/common/util.go
Labels: bugfix, approved

#4082 feat: App list item show open merge requests count
  apistructs/gittar.go
  bundle/gittar.go
  conf/dop/i18n/cp/scenarios/app-list-all.yaml
  modules/admin/services/workbench/app.go
  modules/dop/component-protocol/components/app-list-all/list/app.go
  modules/dop/component-protocol/components/app-list-all/list/provider.go
  modules/gittar/api/merge.go
  modules/gittar/initialize.go
  modules/gittar/models/merge_request.go
Labels: feature, approved

#4096 fix: Issue gantt filter condition key update, issue stage stream skip invalid type
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/render.go
  modules/dop/component-protocol/components/issue-gantt/filter/model.go
  modules/dop/component-protocol/components/issue-gantt/filter/provider.go
  modules/dop/services/issue/issue.go
Labels: bugfix, approved

#4094 feat: Add batch create comment issue stream api
  api/proto-go/all.go
  api/proto-go/dop/issue/client/client.go
  api/proto-go/dop/issue/client/provider.go
  api/proto-go/dop/issue/pb/register.services.pb.go
  api/proto-go/dop/issue/pb/stream.form.pb.go
  api/proto-go/dop/issue/pb/stream.http.pb.go
  api/proto-go/dop/issue/pb/stream.json.pb.go
  api/proto-go/dop/issue/pb/stream.pb.go
  api/proto-go/dop/issue/pb/stream.validator.pb.go
  api/proto-go/dop/issue/pb/stream_grpc.pb.go
  api/proto/dop/issue/stream.proto
  cmd/dop/main.go
  conf/dop/dop.yaml
  modules/dop/dao/issue_app_relation.go
  modules/dop/dao/issue_stream.go
  modules/dop/providers/issue/stream/provider.go
  modules/dop/providers/issue/stream/service.go
Labels: feature, approved

#4100 fix: modify record url
  modules/core/monitor/alert/alert-apis/adapt/alert.go
  modules/core/monitor/alert/alert-apis/adapt/alert_route.go
  modules/msp/apm/alert/alert.go
Labels: bugfix, approved

#4102 fix(dop,pipeline): Solve the problem of index hit failure caused by forced indexing
  modules/pipeline/dbclient/op_pipeline.go
Labels: dop, pipeline, bugfix, approved

#4104 fix: check user is-existed in member service
  modules/core-services/services/member/member.go
  modules/core-services/services/member/member_test.go
  pkg/ucauth/user_admin.go
Labels: bugfix

#4103 feat: Stop judging destructive statements
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/scripts.go
  pkg/database/sqlparser/migrator/tabledef.go
Labels: feature, approved, install

#4105 fix: Automated test execution access to net portal network proxy
  apistructs/cluster_info.go
  apistructs/pipeline.go
  modules/dop/services/autotest_v2/scene.go
  modules/pipeline/conf/conf.go
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/main.go
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/netportal.go
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/netportal_test.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  pkg/apitestsv2/options.go
  pkg/http/customhttp/request.go
Labels: dop, bugfix, approved

#4108 fix: Fix issue gantt return full data
  modules/dop/component-protocol/components/issue-gantt/gantt/render.go
Labels: bugfix, approved

#4113 feat: deployment order support show batch status
  apistructs/deployment_order.go
  conf/orchestrator/orchestrator.yaml
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/endpoints/deployment_order.go
  modules/orchestrator/initialize.go
  modules/orchestrator/provider.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_cron.go
  modules/orchestrator/services/deployment_order/deployment_order_cron_test.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/services/deployment_order/deployment_order_get_test.go
  modules/orchestrator/services/deployment_order/deployment_order_render.go
  modules/orchestrator/services/runtime/runtime.go
Labels: feature

#4110 fix: Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd
  modules/pipeline/pipengine/reconciler/cron_strategy_compensator.go
Labels: bugfix, approved

#4116 feat(core-services): core-services add log for kms
  modules/core-services/services/filesvc/svc.go
Labels: feature, approved

#4109 fix: Add member project owner error i18n, fix duplicate i18n key
  conf/core-services/i18n/i18n.yaml
  conf/dop/i18n/cp/scenarios/auto-test-scenes.yaml
  modules/core-services/initialize.go
  modules/core-services/services/member/member.go
  modules/dop/component-protocol/scenarios/auto-test-scenes.yml
  pkg/erda-configs/i18n/cmdb.json
  pkg/erda-configs/i18n/orchestrator.json
Labels: bugfix, approved

#4118 fix(deploy): fix i18n param
  conf/scheduler/i18n/log-trans.yaml
Labels: bugfix, deploy

#4120 ci: switch mysql to rds
  erda.yml
  pipeline.yml
Labels: approved

#4085 fix: pipeline creates k8s executors concurrently when initializing
  modules/pipeline/conf/conf.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
Labels: bugfix, approved

#4080 feat: kms support rsa 4096 3072 2048
  pkg/kms/kmscrypto/define.go
  pkg/kms/kmscrypto/rsa_2048_4096.go
  pkg/kms/kmscrypto/util.go
  pkg/kms/kmstypes/api_key.go
  pkg/kms/kmstypes/key.go
  pkg/kms/plugins/dicekms/kms.go
  pkg/kms/stores/etcd/store.go
Labels: feature, approved

#4121 feat: Auto test plan list uses standard filter
  conf/dop/i18n/cp/scenarios/auto-test-plan-list.yaml
  conf/openapi/openapi.yaml
  modules/dop/component-protocol/components/all.go
  modules/dop/component-protocol/components/auto-test-plan-list/common/helper.go
  modules/dop/component-protocol/components/auto-test-plan-list/components/addButton/render.go
  modules/dop/component-protocol/components/auto-test-plan-list/components/filter/provider.go
  modules/dop/component-protocol/components/auto-test-plan-list/components/formModal/render.go
  modules/dop/component-protocol/components/auto-test-plan-list/components/table/render.go
  modules/dop/component-protocol/components/auto-test-plan-list/components/table/render_test.go
  modules/dop/component-protocol/components/auto-test-plan-list/i18n/i18n.go
  modules/dop/component-protocol/components/auto-test-plan-list/scenario.go
  modules/dop/component-protocol/scenarios/auto-test-plan-list.yml
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
Labels: feature, approved

#4106 feat: alert strategy return alert rules count
  api/proto-go/core/monitor/alert/pb/alert.form.pb.go
  api/proto-go/core/monitor/alert/pb/alert.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.form.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.pb.go
  api/proto/core/monitor/alert/alert.proto
  api/proto/msp/apm/alert/apm_alert.proto
  modules/core/monitor/alert/alert-apis/adapt/alert.go
  modules/core/monitor/alert/alert-apis/db/alert_expression.go
Labels: msp, feature, approved

#4075 refactor(dop): remove core-services dependency on gittar
  apistructs/gittar.go
  bundle/app.go
  bundle/gittar.go
  modules/core-services/services/application/appliation.go
  modules/dop/endpoints/application.go
  modules/dop/endpoints/endpoints.go
  modules/dop/provider.go
  modules/dop/services/apierrors/errors.go
  modules/dop/services/project/project_template.go
  modules/gittar/models/repo.go
  modules/openapi/api/apis/dop/cmdb_applications_update.go
  pkg/gittarutil/repo.go
  pkg/strutil/interpolate_test.go
Labels: dop, refactor, approved

#4124 feat(gittar): add error output log to git cmd
  modules/gittar/helper/git_cmd.go
Labels: feature, approved, gittar

#4107 feat: alert config add filter name
  api/proto-go/core/monitor/alert/pb/alert.form.pb.go
  api/proto-go/core/monitor/alert/pb/alert.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.form.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.pb.go
  api/proto-go/msp/apm/notifygroup/pb/notifygroup.form.pb.go
  api/proto-go/msp/apm/notifygroup/pb/notifygroup.pb.go
  api/proto/core/monitor/alert/alert.proto
  api/proto/msp/apm/alert/apm_alert.proto
  api/proto/msp/apm/notifygroup/notifygroup.proto
  apistructs/notify_group.go
  bundle/notify_group.go
  modules/core-services/dao/notify_group.go
  modules/core-services/endpoints/notify_group.go
  modules/core/monitor/alert/alert-apis/adapt/alert.go
  modules/core/monitor/alert/alert-apis/adapt/customize.go
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/core/monitor/alert/alert-apis/db/alert.go
  modules/core/monitor/alert/alert-apis/db/customize_alert.go
  modules/core/monitor/alert/alert-apis/interfaces.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/notifygroup/notifygroup.service.go
Labels: msp, feature, approved

#4130 fix: rename metadata.proto to md.proto to resolve conflict
  Makefile
  api/proto-go/common/pb/md.form.pb.go
  api/proto-go/common/pb/md.http.pb.go
  api/proto-go/common/pb/md.json.pb.go
  api/proto-go/common/pb/md.pb.go
  api/proto-go/common/pb/md.validator.pb.go
  api/proto-go/core/monitor/log/query/client/client.custom.go
  api/proto-go/core/pipeline/base/pb/base.pb.go
  api/proto-go/core/pipeline/cluster/pb/cluster.pb.go
  api/proto/common/md.proto
  api/proto/core/pipeline/base/base.proto
  api/proto/core/pipeline/cluster/cluster.proto
Labels: bugfix

#4128 feat: cors in rate-limiting
  modules/hepa/apipolicy/policies/server-guard/dto.go
  modules/hepa/apipolicy/policies/server-guard/dto_test.go
  modules/hepa/apipolicy/policies/server-guard/policy.go
  pkg/strutil/interpolate.go
Labels: feature, approved

#4131 feat: cors in rate-limiting
  modules/hepa/apipolicy/policies/server-guard/dto.go
  modules/hepa/apipolicy/policies/server-guard/dto_test.go
  modules/hepa/apipolicy/policies/server-guard/policy.go
Labels: feature, approved

#4134 ci: custom migration username
  pipeline.yml
Labels: approved

#4137 feat: sls-log-to-metric
  cmd/monitor/extensions/slb-metric/main.go
  conf/monitor/extensions/slb-metric/slb-metric.yaml
  modules/extensions/loghub/sls-log-to-metric/consumer.go
  modules/extensions/loghub/sls-log-to-metric/consumer_manager.go
  modules/extensions/loghub/sls-log-to-metric/provider.go
Labels: feature, approved

#4136 fix: add dicehub port env in erda.yml
  erda.yml
Labels: bugfix

#4123 fix(pipeline): disable eci for pipelines containing custom tasks
  apistructs/pipeline_container_instance.go
  modules/pipeline/pkg/container_provider/container_instance_provider.go
  modules/pipeline/pkg/container_provider/container_provider_test.go
  modules/pipeline/services/pipelinesvc/create_v2.go
Labels: pipeline, bugfix, approved

#4142 feat(cp-project): add filter init param
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
  modules/dop/component-protocol/components/project-runtime/cleanData/render.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: feature

#4144 feat(cp-project): add filter init param
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
  modules/dop/component-protocol/components/project-runtime/cleanData/render.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: feature

#4145 fix: use old release dice if conflict when upload
  modules/dicehub/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4126 fix: exclude suppressed alert events when query
  modules/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/command.go
  modules/msp/apm/alert/components/msp-alert-event-list/table/provider.go
  modules/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-level-count/provider.go
  modules/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-type-count/provider.go
  modules/msp/apm/alert/components/msp-alert-overview/composite-header/cards/statistics.go
Labels: msp, bugfix

#3922 feat: migrate log-rules api to msp module
  api/proto-go/core/monitor/metric/client/client.go
  api/proto-go/core/monitor/metric/pb/meta.form.pb.go
  api/proto-go/core/monitor/metric/pb/meta.http.pb.go
  api/proto-go/core/monitor/metric/pb/meta.json.pb.go
  api/proto-go/core/monitor/metric/pb/meta.pb.go
  api/proto-go/core/monitor/metric/pb/meta.validator.pb.go
  api/proto-go/core/monitor/metric/pb/meta_grpc.pb.go
  api/proto/core/monitor/metric/meta.proto
  cmd/monitor/extensions/cloud-import/main.go
  cmd/monitor/extensions/loghub/main.go
  cmd/monitor/log-service/main.go
  cmd/monitor/monitor/main.go
  cmd/msp/main.go
  conf/monitor/monitor/monitor.yaml
  conf/msp/msp.yaml
  modules/core/monitor/metric/query/metric.meta.service.go
  modules/msp/apm/log-service/analysis/collector_writer.go
  modules/msp/apm/log-service/analysis/consumer.go
  modules/msp/apm/log-service/analysis/processors.go
  modules/msp/apm/log-service/analysis/processors/convert/convert.go
  modules/msp/apm/log-service/analysis/processors/processors.go
  modules/msp/apm/log-service/analysis/processors/processors_test.go
  modules/msp/apm/log-service/analysis/processors/regex/regex.go
  modules/msp/apm/log-service/analysis/processors/regex/regex_test.go
  modules/msp/apm/log-service/analysis/provider.go
  modules/msp/apm/log-service/rules/cloud_metrics.go
  modules/msp/apm/log-service/rules/cloud_metrics_test.go
  modules/msp/apm/log-service/rules/db/db.go
  modules/msp/apm/log-service/rules/db/log_metric_config.go
  modules/msp/apm/log-service/rules/log_metric_config.go
  modules/msp/apm/log-service/rules/model.go
  modules/msp/apm/log-service/rules/provider.go
  modules/msp/apm/log-service/rules/routes.go
  modules/msp/apm/log-service/rules/template.go
  modules/msp/apm/log-service/rules/test.http
  modules/openapi/api/apis/monitor/msp_addon_logs_rule.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules_create.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules_delete.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules_enable.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules_template.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules_templates.go
  modules/openapi/api/apis/monitor/msp_addon_logs_rules_update.go
  modules/openapi/api/apis/monitor/msp_addon_logs_test_rule.go
Labels: msp, feature, refactor

#4135 feat: project pipeline table add source file field
  conf/dop/i18n/cp/common.yaml
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: feature

#4133 fix: fix alert_source error and add default sort order for alert even…
  modules/core/monitor/alert/alert-apis/adapt/alert.go
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
Labels: msp, bugfix

#4140 fix: convertion
  modules/cmp/resource/class.go
  pkg/http/httpserver/wrapper.go
  pkg/http/httpserver/wrapper_test.go
  pkg/strutil/interpolate_test.go
Labels: bugfix, approved

#4148 feat: use default character set utf8 in sandbox
  pkg/database/sqlparser/migrator/db.go
  pkg/database/sqlparser/snapshot/error.go
Labels: feature, approved

#4151 ci: add daily deploy pipeline
  .erda/pipelines/daily-deploy.yml
Labels: approved

#4149 refactor(cp-project): wrong param when get my apps
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: refactor

#4154 feat: remove project pipeline table source file column
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: feature, approved

#4150 feat: add latest for release
  .erda/migrations/dicehub/20220223-release-latest-1.sql
  .erda/migrations/dicehub/20220223-release-latest-2.py
  api/proto-go/core/dicehub/release/pb/release.form.pb.go
  api/proto-go/core/dicehub/release/pb/release.http.pb.go
  api/proto-go/core/dicehub/release/pb/release.pb.go
  api/proto/core/dicehub/release/release.proto
  apistructs/release.go
  conf/dop/i18n/cp/scenarios/release-manage.yaml
  modules/dicehub/dbclient/release.go
  modules/dicehub/release/db/release.go
  modules/dicehub/release/db/table.go
  modules/dicehub/release/release.go
  modules/dicehub/release/release.service.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/dop/component-protocol/scenarios/release-manage.yml
Labels: feature

#4153 fix: add json name for serviceName field
  api/proto-go/core/dicehub/release/pb/release.pb.go
  api/proto/core/dicehub/release/release.proto
Labels: bugfix

#4156 fix: sourcecov volume config
  modules/orchestrator/services/addon/addon_sourcecov.go
Labels: bugfix

#4159 ci: add ding bot notify
  .erda/msg.jsonnet
  .erda/pipelines/daily-deploy.yml
Labels: approved

#4147 feat: deploy without branch from dice-action
  apistructs/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/utils/parse.go
  modules/orchestrator/utils/parse_test.go
Labels: orchestrator, feature

#4161 feat(dop): Modify the default displayed tab of app and pipeline
  modules/dop/component-protocol/components/app-list-all/tabs/render.go
  modules/dop/component-protocol/components/project-pipeline/common/vars.go
Labels: dop, feature

#4165 fix: release aggregate by branch
  conf/dop/i18n/cp/scenarios/release-manage.yaml
  modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render_test.go
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4166 fix: orchestrator and scheduler i18n error
  conf/orchestrator/i18n/orchestrator-log-trans.yaml
  conf/orchestrator/i18n/scheduler-log-trans.yaml
  conf/orchestrator/orchestrator.yaml
  conf/scheduler/scheduler.yaml
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/endpoints/deployment_order.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/i18n/i18n.go
  modules/orchestrator/initialize.go
  modules/orchestrator/provider.go
  modules/orchestrator/services/deployment_order/deployment_order_render.go
  modules/orchestrator/services/deployment_order/deployment_order_render_test.go
Labels: orchestrator, bugfix

#4164 fix: modify the display_url path
  modules/core/monitor/alert/alert-apis/adapt/alert_route.go
Labels: msp, bugfix, approved

#4169 feat: Replace "recursion" with "loop" to ensure exit
  modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  modules/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
  pkg/strutil/interpolate.go
  pkg/strutil/interpolate_test.go
Labels: orchestrator, feature

#4167 fix: modify add member check permission
  modules/msp/member/mebmer.service.go
Labels: msp, bugfix, approved

#4172 fix: deployment order cron panic error
  modules/orchestrator/services/deployment_order/deployment_order_cron.go
Labels: orchestrator, bugfix

#4171 fix(cp-project): init filter
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
Labels: bugfix

#4174 ci: remove some mirrors
  .erda/msg.jsonnet
  .erda/pipelines/daily-deploy.yml
Labels: approved

#4176 fix: fix get containerID out of range fatal
  modules/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
Labels: bugfix

#4168 fix: unrecover alert count error
  api/proto-go/core/monitor/alert/client/client.go
  api/proto-go/core/monitor/alert/pb/alert.form.pb.go
  api/proto-go/core/monitor/alert/pb/alert.http.pb.go
  api/proto-go/core/monitor/alert/pb/alert.json.pb.go
  api/proto-go/core/monitor/alert/pb/alert.pb.go
  api/proto-go/core/monitor/alert/pb/alert.validator.pb.go
  api/proto-go/core/monitor/alert/pb/alert_grpc.pb.go
  api/proto/core/monitor/alert/alert.proto
  cmd/monitor/monitor/main.go
  conf/monitor/monitor/monitor.yaml
  modules/cmp/alert_monitor_test.go
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/core/monitor/alert/alert-apis/db/alert_event.go
  modules/core/monitor/alert/jobs/unrecover-alerts/provider.go
  modules/msp/apm/alert/alert_monitor_test.go
  modules/msp/apm/alert/components/msp-alert-overview/common/util.go
  modules/msp/apm/alert/components/msp-alert-overview/composite-header/unrecover-alert-chart/model.go
  modules/msp/apm/alert/components/msp-alert-overview/composite-header/unrecover-alert-chart/provider.go
Labels: msp, bugfix

#4111 fix(dop,dicehub): Sync actions updates all fields
  modules/dicehub/extension/action.go
  modules/dicehub/extension/source.go
Labels: dop, bugfix

#4175 refactor(cp-project): ignore name filter case and space
  modules/dop/component-protocol/components/project-runtime/common/common.go
  modules/dop/component-protocol/components/project-runtime/common/common_test.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: refactor

#4177 fix: add json tag for url field in ReleaseResource
  api/proto-go/core/dicehub/release/pb/release.pb.go
  api/proto/core/dicehub/release/release.proto
Labels: bugfix, approved

#4180 fix: fix volume without storage, set default volume type
  modules/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  modules/orchestrator/services/deployment/deployment_context.go
  pkg/k8s/storage/detect_sc.go
  pkg/k8s/storage/detect_sc_test.go
Labels: bugfix, approved

#4183 fix(dop,dicehub): Cancel the http service provided by the extension's protobuf
  api/proto-go/core/dicehub/extension/pb/extension.http.pb.go
  api/proto-go/core/dicehub/extension/pb/extension.pb.go
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto/core/dicehub/extension/extension.proto
  go.mod
  go.sum
Labels: dop, bugfix, approved

#4185 fix(dop): Solve the problem of tab switching when filter event trigger
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
Labels: dop, bugfix

#4186 fix(dop,pipeline): Solve the problem of Chinese character length judgment
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: dop, pipeline, bugfix, approved
