Repository erda-project/erda, pull requests merged in 2022-10, with the labels that each got.

#5547 feat: metric query performance optimization
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail-origin.json
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail.json
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
  internal/apps/cmp/metrics/metrics.go
  internal/apps/msp/apm/alert/components/msp-alert-event-list/table/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-event-list/table/trigger_count.go
  internal/apps/msp/apm/alert/components/msp-alert-event-list/table/trigger_count_test.go
  internal/apps/msp/apm/browser/components/browser-overview/kv_card/statistics.go
  internal/apps/msp/tenant/project/project.service.go
  internal/apps/msp/tenant/project/project.service_test.go
  internal/apps/msp/tenant/project/project_statistics.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/query.go
  internal/tools/monitor/core/metric/query/metricq/routes.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
  internal/tools/monitor/dashboard/org-apis/provider.go
  internal/tools/monitor/dashboard/org-apis/routes.go
Labels: feature, approved

#5548 fix(orchestrator): orchestrator use global msp addr
  erda.yml
Labels: orchestrator, bugfix, approved

#5549 fix: metric query chat view is twist
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse_test.go
Labels: bugfix

#5544 feat(dop): issue table exhibit custom properties
  api/proto/dop/issue/core/core.proto
  internal/apps/devflow/flow/issue_mock.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/issue_query_test.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/props.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/props_test.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render_test.go
  internal/apps/dop/providers/issue/core/common/property.go
  internal/apps/dop/providers/issue/core/common/property_test.go
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/property.go
  internal/apps/dop/providers/issue/core/property_test.go
  internal/apps/dop/providers/issue/core/provider.go
  internal/apps/dop/providers/issue/core/query/paging.go
  internal/apps/dop/providers/issue/core/query/property.go
  internal/apps/dop/providers/issue/core/query/property_test.go
  internal/apps/dop/providers/issue/core/query/provider.go
  internal/apps/dop/providers/issue/core/service.go
  internal/apps/dop/providers/issue/dao/issue_property_value.go
  internal/apps/dop/providers/issue/dao/property_relation.go
  internal/apps/dop/providers/search/search_test.go
  internal/apps/dop/services/apierrors/errors.go
  pkg/common/apis/header.go
  pkg/mock/issue_query_mock.go
Labels: dop, feature, approved

#5552 fix: filter host and container by org_name
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
Labels: bugfix

#5551 fix: make app can exit gracefully
  build/dockerfiles/Dockerfile
Labels: bugfix, approved

#5554 fix(dop): fix paging npe when issue doesn't have custom property
  internal/apps/dop/providers/issue/core/query/paging.go
Labels: dop, bugfix

#5555 fix(pipeline): `AutoRunAtOnce` compatibility logic
  internal/tools/pipeline/providers/pipeline/create_v2.go
Labels: pipeline, bugfix, approved

#5558 fix: pipeline panic due to nil run param
  internal/tools/pipeline/providers/run/run.go
Labels: bugfix

#5559 fix: add node failed in cmp
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  internal/apps/cmp/impl/nodes/add.go
  internal/apps/cmp/impl/nodes/rm.go
Labels: bugfix

#5560 fix(pipeline): pipeline and actionmgr provider transaction session competing mysql connections
  internal/tools/pipeline/providers/pipeline/provider.go
Labels: pipeline, bugfix

#5563 fix: add node failed in cmp (cherry-pick)
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  internal/apps/cmp/impl/nodes/add.go
  internal/apps/cmp/impl/nodes/rm.go
Labels: bugfix

#5564 fix: pipeline try get orgName if empty
  internal/tools/pipeline/providers/cache/impl.go
  internal/tools/pipeline/providers/cache/impl_test.go
  internal/tools/pipeline/providers/cache/interface.go
  internal/tools/pipeline/providers/cache/provider.go
  internal/tools/pipeline/providers/pipeline/create_v2.go
  internal/tools/pipeline/providers/pipeline/create_v2_test.go
Labels: bugfix, approved

#5568 feat: add erda-cli gw debug-auth
  tools/cli/cmd/gw_debug_auth.go
  tools/cli/command/root_cmd.go
Labels: feature

#5569 fix(core-services): websocket route use ** as wildcard
  internal/core/legacy/initialize.go
Labels: bugfix

#5556 feat: support mysql operator 8.0
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_deploy_test.go
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: feature

#5572 chore: pipeline,orchestrator enable pprof debug
  cmd/orchestrator/bootstrap.yaml
  cmd/orchestrator/main.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
Labels: approved

#5573 fix: cmp kubectl shell connect failed on kubernetes >= 1.24
  internal/apps/cmp/steve/middleware/middleware_test.go
  internal/apps/cmp/steve/middleware/shell_handler.go
Labels: bugfix

#5574 feat(orchestrator): o11 suite ingress networking/v1
  apistructs/issue_test.go
  internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/common/parse.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/common/parse_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/extension/v1beta1/ingress.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/extension/v1beta1/ingress_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/ingress.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/networking/v1/ingress.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/networking/v1/ingress_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
  internal/tools/orchestrator/scheduler/executor/util/discovery.go
Labels: orchestrator, feature

#5575 fix: internal server create pipeline with internal header
  internal/apps/cmp/endpoints/org_resource.go
  internal/apps/cmp/impl/clusters/add_edge_cluster.go
  internal/apps/cmp/impl/clusters/upgrade_edge_cluster.go
  internal/apps/cmp/impl/nodes/add.go
  internal/apps/cmp/impl/nodes/rm.go
  internal/apps/dop/endpoints/project_pipeline.go
  internal/apps/dop/endpoints/project_pipeline_test.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/services/application/application.go
  internal/apps/dop/services/autotest_v2/scene.go
  internal/apps/dop/services/autotest_v2/sceneset.go
  internal/apps/dop/services/autotest_v2/testplan_v2.go
  internal/apps/dop/services/cq/analyze.go
  internal/apps/dop/services/pipeline/pipeline.go
  internal/apps/dop/services/testcase/apitest.go
  internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
  internal/tools/monitor/dashboard/report/apis/report-task-apis.go
  internal/tools/monitor/dashboard/report/apis/v1/report.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: bugfix

#5576 fix: event decode error
  internal/tools/monitor/core/event/persist/consume.go
  internal/tools/monitor/core/event/persist/consume_test.go
Labels: bugfix

#5577 fix: hepa get cluster info failed
  internal/tools/orchestrator/hepa/repository/service/gateway_az_info_service.go
Labels: bugfix

#5579 fix(orchestrator): o11 start with admin http-server
  cmd/orchestrator/bootstrap.yaml
Labels: orchestrator, bugfix, approved

#5581 fix: modify pb.event
  api/proto/oap/event/event.proto
  internal/apps/msp/apm/exception/query/source/elasticsearch_source.go
  internal/tools/monitor/core/event/persist/consume.go
  internal/tools/monitor/core/event/query/event.query.service.go
Labels: bugfix, approved

#5580 fix: use kafkago for trace on cassandra
  internal/apps/msp/apm/trace/storage/cassandra_v1/provider.go
Labels: bugfix, approved

#5584 refactor: move addon alert rule to msp
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_slave_status/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_slave_status/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_slave_status/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_redis_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_redis_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_redis_mem/notify_template.yaml
  cmd/monitor/monitor/conf/i18n/alert.yml
Labels: refactor

#5586 fix(gittar): `dice_repo_check_runs` pipelineID filed out of range value
  .erda/migrations/gittar/20221027-gittar-alert-pipeline-id.sql
Labels: bugfix, approved, gittar

#5588 fix: github workflow support pure dbmigration PR
  .github/workflows/ci-it-noneed.yml
Labels: bugfix

#5594 fix: alert `dice_repo_check_runs` pipelineID sql
  .erda/migrations/gittar/20221027-gittar-alert-pipeline-id.sql
Labels: bugfix, approved
