Repository erda-project/erda, pull requests merged in 2022-01, with the labels that each got.

#3589 fix: dicehub extension internationalization change
  apistructs/extention.go
Labels: approved

#3469 feat: Standard issue filter provider, add issue complexity and states
  conf/dop/dop.yaml
  modules/dop/component-protocol/components/all.go
  modules/dop/component-protocol/components/issue-kanban/scenario.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/model.go
  modules/dop/component-protocol/components/issue-manage/issueFilter/state.go
  modules/openapi/component-protocol/components/base/provider.go
  modules/openapi/component-protocol/components/base/register.go
  modules/openapi/component-protocol/components/base/register_test.go
  providers/component-protocol/issueFilter/conditions.go
  providers/component-protocol/issueFilter/filterset.go
  providers/component-protocol/issueFilter/filterset_test.go
  providers/component-protocol/issueFilter/in_params.go
  providers/component-protocol/issueFilter/options.go
  providers/component-protocol/issueFilter/provider.go
Labels: dop, feature, refactor, approved

#3601 fix: add ignore data and debug logs
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3603 fix: Fix issue import with property, skip invalid property relations with empty property id
  modules/dop/dao/issue_property_relation.go
  modules/dop/services/issue/convert.go
Labels: approved

#3597 feat: Member active rank limit and coefficient update
  modules/dop/dao/contribution.go
  modules/dop/providers/contribution/service.go
Labels: dop

#3505 feat: project support soft delete
  .erda/migrations/cmdb/20211227-project-soft-delete.sql
  .erda/migrations/config.yml
  modules/core-services/dao/project.go
  modules/core-services/model/project.go
Labels: dop

#3503 refactor: core services decoupling pipeline
  api/proto-go/all.go
  api/proto-go/core/dop/taskerror/client/client.go
  api/proto-go/core/dop/taskerror/client/provider.go
  api/proto-go/core/dop/taskerror/pb/register.services.pb.go
  api/proto-go/core/dop/taskerror/pb/task_error.form.pb.go
  api/proto-go/core/dop/taskerror/pb/task_error.http.pb.go
  api/proto-go/core/dop/taskerror/pb/task_error.json.pb.go
  api/proto-go/core/dop/taskerror/pb/task_error.pb.go
  api/proto-go/core/dop/taskerror/pb/task_error.validator.pb.go
  api/proto-go/core/dop/taskerror/pb/task_error_grpc.pb.go
  api/proto-go/core/services/errorbox/client/client.go
  api/proto-go/core/services/errorbox/client/provider.go
  api/proto-go/core/services/errorbox/pb/errorbox.form.pb.go
  api/proto-go/core/services/errorbox/pb/errorbox.http.pb.go
  api/proto-go/core/services/errorbox/pb/errorbox.json.pb.go
  api/proto-go/core/services/errorbox/pb/errorbox.pb.go
  api/proto-go/core/services/errorbox/pb/errorbox.validator.pb.go
  api/proto-go/core/services/errorbox/pb/errorbox_grpc.pb.go
  api/proto-go/core/services/errorbox/pb/register.services.pb.go
  api/proto/core/dop/taskerror/task_error.proto
  api/proto/core/services/errorbox/errorbox.proto
  apistructs/errorbox.go
  apistructs/errorbox_test.go
  cmd/dop/main.go
  conf/core-services/core-services.yaml
  conf/dop/dop.yaml
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/endpoints/errorbox.go
  modules/core-services/initialize.go
  modules/core-services/provider.go
  modules/core-services/providers/errorbox/error.box.service.go
  modules/core-services/providers/errorbox/error.box.service_test.go
  modules/core-services/providers/errorbox/errorbox.go
  modules/core-services/providers/errorbox/provider.go
  modules/core-services/services/application/appliation.go
  modules/core-services/services/errorbox/errorbox.go
  modules/core-services/services/errorbox/find_sub_resources.go
  modules/dop/endpoints/application.go
  modules/dop/endpoints/endpoints.go
  modules/dop/initialize.go
  modules/dop/provider.go
  modules/dop/providers/taskerror/provider.go
  modules/dop/providers/taskerror/task.error.service.go
  modules/dop/providers/taskerror/task.error.service_test.go
  modules/dop/providers/taskerror/task_error.go
  modules/dop/services/apierrors/errors.go
  modules/dop/services/application/application.go
  modules/openapi/api/apis/dop/cmdb_application_init.go
Labels: dop, feature

#3602 fix(admin cp): fix msp url
  modules/admin/component-protocol/components/personal-workbench/workCards/provider.go
  modules/admin/component-protocol/components/personal-workbench/workCards/provider_test.go
  modules/admin/component-protocol/components/personal-workbench/workList/provider.go
  modules/dop/component-protocol/scenarios/project-runtime.yml
Labels: approved

#3609 feat: openapi support specify custom k8s svc addr from env
  modules/openapi/conf/conf.go
  modules/openapi/conf/conf_test.go
  modules/openapi/proxy/director.go
  modules/openapi/proxy/director_test.go
  pkg/discover/address.go
  pkg/discover/resolver.go
Labels: feature, openapi

#3608 fix(cluster): show name if display name is empty
  modules/cmp/component-protocol/components/cmp-cluster-list/list/render.go
Labels: approved

#3610 feat: pipeline support bigdata affinity label
  apistructs/service.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  pkg/schedule/schedulepolicy/constraintbuilders/k8s/build.go
  pkg/schedule/schedulepolicy/labelconfig/labelconfig.go
  pkg/schedule/schedulepolicy/labelpipeline/identity.go
  pkg/schedule/schedulepolicy/labelpipeline/identity_test.go
Labels: pipeline, feature, approved

#3587 feat: support enqueue condition
  apistructs/labels.go
  apistructs/pipeline_queue.go
  modules/pipeline/services/pipelinesvc/create_v2.go
  modules/pipeline/services/pipelinesvc/run.go
  modules/pipeline/spec/pipeline.go
  modules/pipeline/spec/pipeline_extra.go
  modules/pipeline/spec/pipeline_test.go
Labels: pipeline, feature, approved

#3612 fix: the newly created application cannot be listed immediately
  apistructs/release.go
  modules/dicehub/dbclient/release.go
  modules/dicehub/endpoints/release.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3614 fix: remove parsing image in list release
  apistructs/release.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
Labels: approved

#3619 fix: add issue email link to dingding group params
  modules/dop/endpoints/issue_callback.go
  modules/dop/endpoints/issue_callback_test.go
Labels: dop

#3622 fix: Fix cache、mq、db chart no data
  modules/msp/apm/service/view/card/avg_duration.go
  modules/msp/apm/service/view/card/error_count.go
  modules/msp/apm/service/view/card/error_rate.go
  modules/msp/apm/service/view/card/req_count.go
  modules/msp/apm/service/view/card/rps.go
  modules/msp/apm/service/view/card/slow_count.go
  modules/msp/apm/service/view/chart/avg_duration.go
  modules/msp/apm/service/view/chart/error_count.go
  modules/msp/apm/service/view/chart/error_rate.go
  modules/msp/apm/service/view/chart/http_code.go
  modules/msp/apm/service/view/chart/rps.go
  modules/msp/apm/service/view/chart/slow_count.go
  modules/msp/apm/service/view/common/sqlutils.go
  modules/msp/apm/service/view/table/transaction.go
Labels: msp, bugfix

#3621 feat: App list component protocol set up
  bundle/app.go
  conf/dop/dop.yaml
  conf/dop/i18n/cp/scenarios/app-list-all.yaml
  conf/openapi/openapi.yaml
  modules/dop/component-protocol/components/all.go
  modules/dop/component-protocol/components/app-list-all/common/gshelper/helper.go
  modules/dop/component-protocol/components/app-list-all/filter/render.go
  modules/dop/component-protocol/components/app-list-all/list/app.go
  modules/dop/component-protocol/components/app-list-all/list/provider.go
  modules/dop/component-protocol/components/app-list-all/scenario.go
  modules/dop/component-protocol/components/app-list-all/tabs/render.go
  modules/dop/component-protocol/scenarios/app-list-all.yml
Labels: dop, feature, approved

#3595 docs: update changelog for 1.5
  CHANGELOG/CHANGELOG-1.x.md
Labels: approved

#3631 feat: workbench parallel enable
  go.mod
  go.sum
  modules/admin/component-protocol/components/personal-workbench/common/gshelper/helper.go
  modules/admin/component-protocol/components/personal-workbench/common/gshelper/helper_test.go
  modules/admin/component-protocol/scenarios/personal-workbench.yml
Labels: admin

#3634 ci: refine ee package
  pipeline.yml
Labels: approved

#3636 fix: solve the panic of closing mr
  modules/gittar/api/merge.go
Labels: bugfix, gittar

#3626 feat: remove eventbox etcd input
  modules/eventbox/api/api.go
  modules/eventbox/dispatcher/dispatcher.go
  modules/eventbox/input/etcd/etcd.go
  modules/eventbox/input/schemonjob/schemonjob.go
  modules/eventbox/input/schemonjob/spec.go
  modules/eventbox/testutil/testutil.go
Labels: msp, feature, approved

#3647 fix: Fix app list updated time format, project service app, tabs order
  conf/dop/i18n/cp/scenarios/app-list-all.yaml
  modules/dop/component-protocol/components/app-list-all/list/app.go
  modules/dop/component-protocol/components/app-list-all/tabs/render.go
Labels: dop, bugfix, approved

#3645 feat: Project collaboration, joined projects, efficiency measure/bug i18n
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/issue-dashboard.yml
  conf/dop/i18n/cp/scenarios/issue-manage.yaml
  modules/dop/component-protocol/components/app-list-all/list/app.go
  modules/dop/component-protocol/components/auto-test-space-list/components/spaceList/render.go
  modules/dop/component-protocol/components/common/text.go
  modules/dop/component-protocol/components/issue-dashboard/bar/assigneeHorizontalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/bar/labelHorizontalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/bar/memberHorizontalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/chartFilter/render.go
  modules/dop/component-protocol/components/issue-dashboard/expired/render.go
  modules/dop/component-protocol/components/issue-dashboard/filter/render.go
  modules/dop/component-protocol/components/issue-dashboard/issueTip/render.go
  modules/dop/component-protocol/components/issue-dashboard/month/render.go
  modules/dop/component-protocol/components/issue-dashboard/open/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/complexityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/priorityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/severityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/stagePieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/reopen/render.go
  modules/dop/component-protocol/components/issue-dashboard/scatterPlot/render.go
  modules/dop/component-protocol/components/issue-dashboard/scatterPlot/render_test.go
  modules/dop/component-protocol/components/issue-dashboard/today/render.go
  modules/dop/component-protocol/components/issue-dashboard/tomorrow/render.go
  modules/dop/component-protocol/components/issue-dashboard/total/render.go
  modules/dop/component-protocol/components/issue-dashboard/trendChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/trendChartFilter/render.go
  modules/dop/component-protocol/components/issue-dashboard/undefined/render.go
  modules/dop/component-protocol/components/issue-dashboard/week/render.go
  modules/dop/component-protocol/components/issue-gantt/filter/render.go
  modules/dop/component-protocol/components/issue-kanban/inputFilter/render.go
  modules/dop/component-protocol/components/issue-manage/issueTable/render.go
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/render.go
  modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go
  modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/render.go
  modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
  modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChartFilter/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go
  pkg/erda-configs/i18n/project_list_all.json
Labels: dop

#3593 feat: project deployment center
  .erda/migrations/orchestrator/20220104-deployment-order.sql
  apistructs/deployment_order.go
  apistructs/runtime.go
  bundle/env_config.go
  modules/orchestrator/dbclient/deployment.go
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/endpoints/deployment_order.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/initialize.go
  modules/orchestrator/services/apierrors/errors.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/deployment/deployment_context_test.go
  modules/orchestrator/services/deployment_order/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order_cancel.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/services/deployment_order/deployment_order_get_test.go
  modules/orchestrator/services/deployment_order/deployment_order_list.go
  modules/orchestrator/services/deployment_order/deployment_order_list_test.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/services/runtime/runtime_context.go
Labels: orchestrator, feature

#3534 feat: openapi auth2 moved to the core service and pipeline decouples openapi
  apistructs/openapi.go
  bundle/openapi_test.go
  bundle/token.go
  modules/action-runner-scheduler/services/runnertask/runner_task.go
  modules/core-services/provider.go
  modules/core/openapi-ng/auth/token/auth_forward.go
  modules/core/openapi-ng/auth/token/provider.go
  modules/openapi/auth/auth.go
  modules/openapi/auth/token.go
  modules/openapi/loginserver.go
  modules/orchestrator/services/addon/addon_sourcecov.go
  modules/orchestrator/services/addon/addon_sourcecov_test.go
  modules/orchestrator/services/addon/mock/addon_sourcecov_mock.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/pipeline/pipengine/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/pipengine/reconciler/taskrun/teardown.go
  modules/pipeline/services/pipelinesvc/task.go
  modules/pipeline/spec/pipeline_task.go
  pkg/oauth2/clientstore/mysqlclientstore/client_store.go
  pkg/oauth2/jwt.go
  pkg/oauth2/server.go
  pkg/oauth2/tokenstore/mysqltokenstore/token_store.go
  pkg/oauth2/tokenstore/mysqltokenstore/token_store_options.go
Labels: approved

#3646 feat: match semver from branch name
  modules/dicehub/endpoints/release.go
  pkg/strutil/regexp.go
  pkg/strutil/regexp_test.go
Labels: feature, approved

#3652 fix: trace_id, request_id compatible
  modules/core/monitor/log/persist/consume.go
  modules/extensions/loghub/exporter/output.go
Labels: msp, approved

#3649 fix: Add app list item description, fix project app text
  conf/admin/i18n/cp/scenarios/personal-workbench.yaml
  conf/dop/i18n/cp/scenarios/app-list-all.yaml
  modules/dop/component-protocol/components/app-list-all/list/provider.go
Labels: dop, bugfix

#3628 feat: sort by all scripts
  pkg/database/sqlparser/migrator/block.go
  pkg/database/sqlparser/migrator/migrator.go
  pkg/database/sqlparser/migrator/migrator_test.go
Labels: approved

#3620 feat: support upload project release
  apistructs/release.go
  modules/dicehub/dbclient/release.go
  modules/dicehub/endpoints/release.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/openapi/api/apis/dicehub/dicehub_releases_parse_version.go
  modules/openapi/api/apis/dicehub/dicehub_releases_upload.go
Labels: approved

#3660 fix: change pb taskerror-list service to dop
  api/proto-go/core/dop/taskerror/pb/task_error.pb.go
  api/proto/core/dop/taskerror/task_error.proto
Labels: dop, bug

#3662 feat: Add new tab my app list in app list scenario
  conf/dop/i18n/cp/scenarios/app-list-all.yaml
  modules/dop/component-protocol/components/app-list-all/common/gshelper/helper.go
  modules/dop/component-protocol/components/app-list-all/list/provider.go
  modules/dop/component-protocol/components/app-list-all/tabs/render.go
Labels: dop, feature, approved

#3658 refactor: Update project table name in contribution join sql
  modules/dop/dao/contribution.go
Labels: dop, refactor, approved

#3661 fix: manual-test recognize member 'unassigned' as id
  modules/dop/dao/testcase.go
  modules/dop/dao/testplan.go
  modules/dop/dao/testplan_testcase_relation.go
  modules/dop/endpoints/testcase.go
  pkg/ucauth/unassigned.go
  pkg/ucauth/unassigned_test.go
  pkg/ucauth/user.go
Labels: dop, bugfix

#3670 fix: release audit and load
  apistructs/audits.go
  apistructs/release.go
  bundle/release.go
  modules/dicehub/endpoints/audit.go
  modules/dicehub/endpoints/release.go
  modules/dicehub/endpoints/release_test.go
  modules/dicehub/endpoints/release_test_data.tar
  modules/dicehub/endpoints/release_test_data.zip
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3687 fix: add get app id by names
  apistructs/application.go
  bundle/app.go
  modules/core-services/dao/application.go
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/services/apierrors/errors.go
  modules/core-services/services/application/appliation.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3686 feat: Make all orgs private
  .erda/migrations/cmdb/20220112-set-org-private.sql
Labels: dop

#3611 refactor: Move project resource query, application publish item related api to dop
  bundle/app.go
  modules/cmp/impl/addons/config.go
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/services/project/project.go
  modules/dop/dao/app_publish_item_relation.go
  modules/dop/endpoints/application_publish_item.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/project.go
  modules/dop/initialize.go
  modules/dop/services/application/application.go
  modules/dop/services/pipeline/pipeline.go
  modules/openapi/api/apis/dop/cmdb_app_publish_item_relation_get.go
  modules/openapi/api/apis/dop/cmdb_app_publish_item_relation_update.go
Labels: refactor, approved

#3692 fix: Fix issue creation request with empty time
  apistructs/issue.go
  modules/dop/services/issue/issue.go
Labels: approved

#3697 fix: update release audit
  apistructs/audits.go
  apistructs/release.go
  modules/dicehub/endpoints/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3698 fix: Add list register operation, update erda infra
  go.mod
  go.sum
  modules/dop/component-protocol/components/app-list-all/list/provider.go
Labels: approved

#3635 feat: support project template import export
  .erda/migrations/qa/20220110-file-record-soft-delete.sql
  apistructs/file_records.go
  apistructs/permission.go
  apistructs/project.go
  modules/dop/dao/file_records.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/file_records.go
  modules/dop/endpoints/project.go
  modules/dop/endpoints/project_test.go
  modules/dop/initialize.go
  modules/dop/services/apierrors/errors.go
  modules/dop/services/project/export_template.go
  modules/dop/services/project/export_template_test.go
  modules/dop/services/project/import_template.go
  modules/dop/services/project/import_template_test.go
  modules/dop/services/project/project.go
  modules/dop/services/project/project_template.go
  modules/dop/services/testcase/file_records.go
  modules/openapi/api/apis/dop/project_template_export.go
  modules/openapi/api/apis/dop/project_template_import.go
  modules/openapi/api/apis/dop/project_template_parse.go
  pkg/erda-configs/permission/backend/sys/org/org.yml
  pkg/erda-configs/permission/backend/sys/org/project/project.yml
Labels: dop, feature

#3704 fix: deployment order started time error
  apistructs/deployment_order.go
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/endpoints/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order_cancel.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/services/deployment_order/deployment_order_list.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/utils/parse.go
  modules/orchestrator/utils/parse_test.go
  modules/scheduler/executor/plugins/k8s/service.go
Labels: orchestrator, bugfix, scheduler

#3705 fix: fix file record migration
  .erda/migrations/qa/20220110-file-record-soft-delete.sql
Labels: dop, bug

#3699 fix: use host ip to query node monitor
  go.mod
  go.sum
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
  modules/msp/apm/service/components/resources-container-monitor/container/provider.go
  modules/msp/apm/service/components/resources-node-monitor/node/provider.go
  modules/msp/apm/service/components/resources-runtime-monitor-java/runtime/provider.go
  modules/msp/apm/service/components/resources-runtime-monitor-nodejs/runtime/provider.go
Labels: msp, bugfix, approved

#3712 feat: project pipeline and pipeline definition review change
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto/core/pipeline/definition/definition.proto
Labels: approved

#3713 fix: Fix register operation return empty function
  go.mod
  go.sum
  modules/dop/component-protocol/components/app-list-all/list/provider.go
Labels: bugfix, approved

#3681 fix: fix duplicated audits of update project
  modules/core-services/services/project/project.go
  modules/openapi/api/apis/core_services/cmdb_projects_update.go
Labels: dop, bug, approved

#3715 fix: Fix/erda file record project name
  apistructs/file_records.go
  apistructs/project.go
  modules/dop/endpoints/project.go
  modules/dop/services/project/export_template.go
  modules/dop/services/project/project_template.go
  modules/dop/services/testcase/file_records.go
Labels: dop, bug, approved

#3714 fix: unit kb -> KB
  modules/msp/apm/service/common/custom/service_inparams.go
  modules/msp/apm/service/components/resources-container-monitor/container/provider.go
  modules/msp/apm/service/components/resources-node-monitor/node/provider.go
  modules/msp/apm/trace/query/commom/custom/trace_inparams.go
Labels: approved

#3676 feat: Extension spec yml support i18n
  modules/dicehub/dbclient/extention.go
  modules/dicehub/service/extension/extension.go
  pkg/expression/expression_reconcile.go
Labels: dop, feature, approved

#3680 feat: Auto test scene and requirement task overview i18n
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/app-list-all.yaml
  conf/dop/i18n/cp/scenarios/auto-test-scenes.yaml
  conf/dop/i18n/cp/scenarios/requirement-task-overview.yaml
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/scenes.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/leftHead/leftHeadTitle/render.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/leftHead/moreOperation/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/fileInfo/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/fileInfoHead/fileInfoTitle/fileInfoTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsForm/inParamsForm.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsTitle/inParamsTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/outPutForm/outPutForm.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/outPutTitle/outPutTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stages/stages.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/addApiButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/addCopyApiFormModal/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/apiEditor.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/configSheetDrawer/configSheetSelect/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/customScriptDrawer/customScriptForm/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/waitEditorDrawer/waitEditor/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesTitle/stagesTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesSetInfo/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesSetTitle/scenesSetTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/operation.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStagesOperations/exportScenesButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStagesOperations/referSceneSetButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStagesTitle/scenesStagesTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/executeHistoryTable/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/refreshButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeInfo/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTable/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTable/transform_test.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTitle/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/tabExecuteButton/executeButton.go
  modules/dop/component-protocol/components/auto-test-space-list/components/filter/render.go
  modules/dop/component-protocol/components/auto-test-space-list/components/moreButton/render.go
  modules/dop/component-protocol/components/auto-test-space-list/components/spaceList/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/statePieChart/render.go
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChartFilter/render.go
  modules/dop/component-protocol/components/requirement-task-overview/container/info/render.go
  modules/dop/component-protocol/components/requirement-task-overview/container/simpleChart/render.go
  modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChart/render.go
  modules/dop/component-protocol/components/requirement-task-overview/stackChartBlock/stackChartFilter/render.go
Labels: dop, feature, approved

#3723 fix: get log request add orgName
  bundle/dashboard.go
  modules/cmp/endpoints/log.go
  modules/cmp/impl/nodes/log.go
  modules/dop/endpoints/apitest.go
  modules/dop/endpoints/cicd.go
  modules/dop/services/cdp/cdp.go
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/endpoints/migration.go
  modules/orchestrator/endpoints/runtime.go
  modules/orchestrator/services/runtime/runtime.go
Labels: msp, bugfix

#3716 feat: project pipeline component
  .erda/migrations/pipeline/20220112-pipeline-definition-and-source.sql
  .erda/migrations/pipeline/20220113-pipeline-definition-change-field.sql
  api/proto-go/dop/projectpipeline/client/client.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.http.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.json.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.validator.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline_grpc.pb.go
  api/proto/dop/projectpipeline/projectpipeline.proto
  bundle/app.go
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/project-pipeline-exec-list.yaml
  conf/openapi/openapi.yaml
  conf/pipeline/pipeline.yaml
  modules/dop/component-protocol/components/all.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/common/commom.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/common/gshelper/helper.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/inparams.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/render.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/inputFilter/model.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/inputFilter/render.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/scenario.go
  modules/dop/component-protocol/components/project-pipeline/common/gshelper/helper.go
  modules/dop/component-protocol/components/project-pipeline/common/vars.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/addPipelineBtn/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/addPipelineBtn/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/inparams.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/inputFilter/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/inputFilter/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/inparams.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline/scenario.go
  modules/dop/component-protocol/scenarios/project-pipeline-exec-list.yml
  modules/dop/component-protocol/scenarios/project-pipeline.yml
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/aop/plugins/pipeline/definitionreport/plugin.go
  modules/pipeline/dbclient/op_pipeline_definition.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: approved

#3725 fix: fix the bug of table sort
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, approved

#3726 fix: table column support hidden
  conf/dop/i18n/cp/common.yaml
  go.mod
  go.sum
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop

#3728 fix: fix the bug of project pipeline table
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/scenarios/project-pipeline.yml
  modules/dop/providers/projectpipeline/service_impl.go
Labels: dop, approved

#3729 fix: fix the bug of pipelineTab
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, approved

#3731 fix: cron project pipeline
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/providers/projectpipeline/service_impl.go
Labels: approved

#3737 fix: Fix i18n json unmarshal
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/leftHead/leftHeadTitle/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/fileInfoHead/fileInfoTitle/fileInfoTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsTitle/inParamsTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/outPutTitle/outPutTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesTitle/stagesTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesSetTitle/scenesSetTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStagesTitle/scenesStagesTitle.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTitle/render.go
Labels: bugfix, approved

#3741 fix: fix the bug of mine pipeline
  modules/dop/component-protocol/components/project-pipeline/common/vars.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, approved

#3742 fix: update the statics of Failed pipeline
  modules/dop/providers/projectpipeline/service_impl.go
Labels: dop, approved

#3748 fix: update the text of table
  conf/dop/i18n/cp/common.yaml
  go.mod
  go.sum
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: approved

#3746 fix: modify the display of the delete button
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, approved

#3749 fix: fix time zone issues
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, approved

#3747 fix: start project pipeline update gittar token and check permission
  modules/dop/providers/projectpipeline/provider.go
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: approved

#3664 feat: add notify_group audit log and alert_customize_alert audit log
  api/proto-go/msp/apm/alert/pb/apm_alert.form.pb.go
  api/proto-go/msp/apm/alert/pb/apm_alert.pb.go
  api/proto-go/msp/apm/notifygroup/pb/notifygroup.form.pb.go
  api/proto-go/msp/apm/notifygroup/pb/notifygroup.pb.go
  api/proto-go/msp/credential/pb/credential.form.pb.go
  api/proto-go/msp/credential/pb/credential.json.pb.go
  api/proto-go/msp/credential/pb/credential.pb.go
  api/proto-go/msp/credential/pb/credential.validator.pb.go
  api/proto-go/msp/member/pb/member.form.pb.go
  api/proto-go/msp/member/pb/member.pb.go
  api/proto-go/msp/tenant/client/client.go
  api/proto-go/msp/tenant/pb/tenant.form.pb.go
  api/proto-go/msp/tenant/pb/tenant.http.pb.go
  api/proto-go/msp/tenant/pb/tenant.json.pb.go
  api/proto-go/msp/tenant/pb/tenant.pb.go
  api/proto-go/msp/tenant/pb/tenant.validator.pb.go
  api/proto-go/msp/tenant/pb/tenant_grpc.pb.go
  api/proto/msp/apm/alert/apm_alert.proto
  api/proto/msp/apm/notifygroup/notifygroup.proto
  api/proto/msp/credential/credential.proto
  api/proto/msp/member/member.proto
  api/proto/msp/tenant/tenant.proto
  apistructs/audits.go
  conf/monitor/monitor/monitor.yaml
  modules/core-services/endpoints/notify_group.go
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/core/monitor/alert/alert-apis/provider.go
  modules/core/monitor/dataview/data.view.service.go
  modules/core/monitor/dataview/provider.go
  modules/core/services/authentication/credentials/accesskey/access.key.service.go
  modules/msp/apm/alert/alert.service.go
  modules/msp/apm/alert/alert.service_test.go
  modules/msp/apm/alert/credential_context_test.go
  modules/msp/apm/alert/provider.go
  modules/msp/apm/alert/tenant_test.go
  modules/msp/apm/metric/provider.go
  modules/msp/apm/metric/proxy.go
  modules/msp/apm/metric/routes.go
  modules/msp/apm/notifygroup/notifygroup.service.go
  modules/msp/apm/notifygroup/provider.go
  modules/msp/credential/credential.service.go
  modules/msp/credential/credential.service_test.go
  modules/msp/credential/provider.go
  modules/msp/credential/tenant_test.go
  modules/msp/member/mebmer.service.go
  modules/msp/member/provider.go
  modules/msp/tenant/tenant.service.go
  modules/openapi/api/apis/monitor/monitor_addon_logs_rules_create.go
  modules/openapi/api/apis/monitor/monitor_addon_logs_rules_delete.go
  modules/openapi/api/apis/monitor/monitor_addon_logs_rules_update.go
  modules/openapi/api/apis/msp/apm/block/create.go
  modules/openapi/api/apis/msp/apm/block/delete.go
  modules/openapi/api/apis/msp/apm/block/update.go
  modules/openapi/api/spec/spec.go
  pkg/ucauth/user_admin.go
  providers/audit/audit.go
  providers/audit/options.go
Labels: msp, feature

#3750 fix: project pipeline exec list begin time panic bugfix
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
Labels: approved

#3752 feat: improve browser-overview
  modules/msp/apm/browser/components/scenarios/browser-overview.yml
Labels: msp

#3754 fix: find tenant by tk
  modules/msp/apm/alert/alert.service.go
Labels: msp, bugfix

#3755 fix: fix transaction table empty bug
  modules/msp/apm/browser/components/browser-overview/models/in_params.go
  modules/msp/apm/service/common/slow-transaction/inparams.go
  modules/msp/apm/service/view/table/transaction.go
Labels: msp

#3756 fix: ak return userIds
  modules/msp/credential/credential.service.go
Labels: approved

#3430 feat: expose clean es disk api
  modules/core/monitor/storekit/elasticsearch/index/cleaner/disk_checker.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/disk_checker_test.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/mock_loader_test.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/provider.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/routes.go
Labels: msp

#3763 fix: clear state of customfilter when switch tab
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
Labels: dop

#3769 fix: project pipeline records add userIDs
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
Labels: dop

#3768 feat: ActionForm and test dashboard trend chart filter ranges i18n
  conf/dop/i18n/cp/common.yaml
  modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/model.go
  modules/dop/component-protocol/components/test-dashboard/at_case_rate_trending_chart_group/filter/render.go
  modules/dop/component-protocol/components/test-dashboard/common/filter.go
  modules/dop/component-protocol/components/test-dashboard/scene_and_api_filter/model.go
  modules/dop/component-protocol/components/test-dashboard/scene_and_api_filter/render.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/mysql-cli.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/mysql-cli_test.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testplan-run_test.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testscene_run.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/testscene_run_test.go
  pkg/erda-configs/i18n/action.json
Labels: dop

#3772 fix: topology node rps metric calculate error
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
Labels: msp, bugfix, approved

#3735 fix: i18n of autotest plan list
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/formModal/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/helper.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/i18n/i18n.go
  pkg/erda-configs/i18n/autotest_plan.json
Labels: approved

#3569 feat: collector refactor
  cmd/monitor/collector/main.go
  conf/monitor/collector/collector.yaml
  conf/monitor/collector/edge/collector.yaml
  conf/resources.go
  erda.yml
  go.mod
  go.sum
  modules/oap/collector/common/compressor/encoder.go
  modules/oap/collector/common/compressor/gziper.go
  modules/oap/collector/common/filter/filter.go
  modules/oap/collector/common/util.go
  modules/oap/collector/core/config/config.go
  modules/oap/collector/core/model/exporter.go
  modules/oap/collector/core/model/model.go
  modules/oap/collector/core/model/plugin.go
  modules/oap/collector/core/model/processor.go
  modules/oap/collector/core/model/receiver.go
  modules/oap/collector/core/pipeline/interface.go
  modules/oap/collector/core/pipeline/pipeline.go
  modules/oap/collector/core/pipeline/pipeline_test.go
  modules/oap/collector/core/provider.go
  modules/oap/collector/plugins/all/all.go
  modules/oap/collector/plugins/exporters/collector/auth/auth.go
  modules/oap/collector/plugins/exporters/collector/auth/basic.go
  modules/oap/collector/plugins/exporters/collector/auth/token.go
  modules/oap/collector/plugins/exporters/collector/provider.go
  modules/oap/collector/plugins/exporters/collector/request.go
  modules/oap/collector/plugins/exporters/stdout/provider.go
  modules/oap/collector/plugins/plugin.go
  modules/oap/collector/plugins/processors/aggregator/function.go
  modules/oap/collector/plugins/processors/aggregator/provider.go
  modules/oap/collector/plugins/processors/aggregator/stream.go
  modules/oap/collector/plugins/processors/aggregator/stream_test.go
  modules/oap/collector/plugins/processors/k8s-tagger/README.md
  modules/oap/collector/plugins/processors/k8s-tagger/cache.go
  modules/oap/collector/plugins/processors/k8s-tagger/metadata/metadata.go
  modules/oap/collector/plugins/processors/k8s-tagger/metadata/node/node.go
  modules/oap/collector/plugins/processors/k8s-tagger/metadata/pod/config.go
  modules/oap/collector/plugins/processors/k8s-tagger/metadata/pod/pod.go
  modules/oap/collector/plugins/processors/k8s-tagger/metadata/pod/pod_test.go
  modules/oap/collector/plugins/processors/k8s-tagger/metadata/service/service.go
  modules/oap/collector/plugins/processors/k8s-tagger/provider.go
  modules/oap/collector/plugins/processors/k8s-tagger/tagger.go
  modules/oap/collector/plugins/processors/k8s-tagger/tagger_test.go
  modules/oap/collector/plugins/processors/modifier/modifier.go
  modules/oap/collector/plugins/processors/modifier/modifier_test.go
  modules/oap/collector/plugins/processors/modifier/provider.go
  modules/oap/collector/plugins/receivers/dummy/provider.go
  modules/oap/collector/plugins/receivers/dummy/testdata/prometheus.json
  modules/oap/collector/plugins/receivers/promremotewrite/parser.go
  modules/oap/collector/plugins/receivers/promremotewrite/provider.go
  modules/oap/collector/receivers/jaeger/provider.go
Labels: msp

#3781 fix: checker i18n
  conf/msp/i18n/msp-i18n.yaml
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/checker.v1.service_test.go
  modules/msp/apm/checker/apis/provider.go
Labels: msp, bugfix, approved

#3782 feat: add deployment order pre check
  apistructs/deployment_order.go
  apistructs/release.go
  modules/orchestrator/dbclient/addon_instance.go
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/endpoints/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order.go
  modules/orchestrator/services/deployment_order/deployment_order_cancel.go
  modules/orchestrator/services/deployment_order/deployment_order_create.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
  modules/orchestrator/services/deployment_order/deployment_order_get.go
  modules/orchestrator/services/deployment_order/deployment_order_list.go
  modules/orchestrator/services/deployment_order/deployment_order_render.go
  modules/orchestrator/services/deployment_order/deployment_order_render_test.go
Labels: orchestrator, feature

#3788 fix: optimize burnchart of efficacy measure
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/model.go
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
Labels: dop, approved

#3785 fix: Optimize project pipeline.
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto/dop/projectpipeline/projectpipeline.proto
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/providers/projectpipeline/service_impl.go
Labels: dop, approved

#3784 fix: Optimize project pipeline customfilter
  go.mod
  go.sum
  modules/dop/component-protocol/components/project-pipeline/common/vars.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
Labels: dop, approved

#3791 feat: microservice menu api add isk8s field
  api/proto-go/msp/menu/pb/menu.form.pb.go
  api/proto-go/msp/menu/pb/menu.pb.go
  api/proto/msp/menu/menu.proto
  modules/msp/menu/menu.service.go
Labels: msp

#3711 fix: agent support limit cache tar file size
  modules/actionagent/agenttool/tar.go
  modules/actionagent/define.go
  modules/actionagent/step_prepare.go
  modules/actionagent/step_restore.go
  modules/actionagent/step_sore_test.go
  modules/actionagent/step_store.go
Labels: approved

#3789 fix: check dedup app when update release
  modules/dicehub/endpoints/release.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3761 feat: optimize the response time of the runtime list
  modules/orchestrator/dbclient/deployment_order.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/services/runtime/runtime_test.go
Labels: approved

#3806 fix: Filter useless associations between topology nodes
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
Labels: msp, bugfix

#3810 feat: notify group member list internationalization
  conf/msp/i18n/msp-i18n.yaml
  modules/msp/member/mebmer.service.go
  modules/msp/member/provider.go
Labels: msp, feature

#3811 fix: DOP failed to initialize mobile app
  modules/dop/conf/conf.go
  modules/dop/services/application/application.go
Labels: dop, bug

#3773 fix: update steve when update cluster
  modules/cmp/component-protocol/components/cmp-dashboard-events-list/eventTable/render.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/steve/aggregator.go
Labels: approved

#3819 fix: add console button
  modules/cmp/component-protocol/components/cmp-dashboard-pods/consoleButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-pods/scenario.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/consoleButton/render.go
  modules/cmp/component-protocol/components/cmp-dashboard-workloads-list/scenario.go
  modules/cmp/component-protocol/scenarios/cmp-dashboard-pods.yml
  modules/cmp/component-protocol/scenarios/cmp-dashboard-workloads-list.yml
Labels: approved

#3813 feat: add jump to application releases
  apistructs/release.go
  conf/dop/i18n/cp/scenarios/release-manage.yaml
  modules/dicehub/dbclient/release.go
  modules/dicehub/endpoints/release.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/inputFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3824 fix: support init config file
  cmd/monitor/collector/main.go
  cmd/monitor/collector/main_test.go
Labels: approved

#3828 fix: fix getfile logic
  cmd/monitor/collector/main.go
  cmd/monitor/collector/main_test.go
Labels: approved

#3829 fix: fix the bug of project pipeline executor
  apistructs/pipeline_page.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/aop/plugins/pipeline/definitionreport/plugin.go
  modules/pipeline/services/pipelinesvc/convert.go
Labels: dop, bugfix, approved

#3835 fix: add rendering to customFilter
  modules/dop/component-protocol/scenarios/project-pipeline.yml
Labels: dop, bugfix, approved

#3817 feat: delete relationship of orchestrator and pipeline
  modules/core-services/services/project/project.go
  modules/orchestrator/services/runtime/runtime.go
Labels: approved

#3816 feat: browser/service-transaction charts support dynamic Y unit
  conf/msp/i18n/msp-i18n.yaml
  go.mod
  go.sum
  modules/msp/apm/browser/components/browser-overview/charts/api_resources_req_count/provider.go
  modules/msp/apm/browser/components/browser-overview/charts/api_resources_req_duration/provider.go
  modules/msp/apm/browser/components/browser-overview/charts/page_req_duration_distribution/provider.go
  modules/msp/apm/browser/components/browser-overview/charts/pv_uv_count/provider.go
  modules/msp/apm/service/components/transaction-cache-analysis/table_filter/provider.go
  modules/msp/apm/service/components/transaction-db-analysis/table_filter/provider.go
  modules/msp/apm/service/components/transaction-http-analysis/table_filter/provider.go
  modules/msp/apm/service/components/transaction-mq-analysis/table_filter/provider.go
  modules/msp/apm/service/components/transaction-rpc-analysis/table_filter/provider.go
  modules/msp/apm/service/datasources/transaction.go
  modules/msp/apm/trace/query/components/trace-query/req_distribution/provider.go
Labels: msp

#3767 fix: records support fuzzy matching and add defaultrendering
  modules/dop/component-protocol/scenarios/project-pipeline-exec-list.yml
  modules/pipeline/dbclient/op_pipeline.go
Labels: dop

#3801 fix: project pipeline Reduce status queries and create precheck
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/util/vars.go
  modules/dop/providers/projectpipeline/service_impl.go
Labels: dop, bugfix, approved

#3818 fix: Update pipeline createRequest commit information and confignamespaces information when the project pipeline executing
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: dop, bug, approved

#3857 feat: Legacy component default render support i18n
  modules/openapi/component-protocol/generate/gen_auto_register.go
  modules/openapi/component-protocol/protocol.go
  modules/openapi/component-protocol/scenario_render.go
Labels: approved

#3866 feat: add project pipeline process and update style
  .erda/migrations/pipeline/20220120-pipeline-definition-actionNum.sql
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto/core/pipeline/definition/definition.proto
  conf/dop/i18n/cp/common.yaml
  conf/pipeline/pipeline.yaml
  modules/dop/component-protocol/components/project-pipeline/common/vars.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/aop/plugins/all.go
  modules/pipeline/aop/plugins/task/definitionreport/plugin.go
  modules/pipeline/dbclient/op_pipeline_definition.go
  modules/pipeline/providers/definition/db/define.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: dop, approved

#3874 fix: fix the bug of definition update
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: approved

#3880 fix: fix the null pointer caused by the abnormal connection of the pipeline
  modules/pipeline/dbclient/op_pipeline.go
Labels: approved

#3881 fix: pipeline slow sql query
  modules/pipeline/pipengine/reconciler/dbgc.go
  modules/pipeline/pipengine/reconciler/pipeline_gc_compensator.go
Labels: approved

#3882 fix(dop): i18n testplan protocol
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesSetInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/addScenesSetButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envBaseInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envBaseInfoTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistory/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryPop/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryRefresh/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfoTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileDetail/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileInfoTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/scenesSetSelect/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/stages/stages.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/stagesTitle/stagesTitle.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/tabExecuteButton/executeButton.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/i18n/transfer.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
  pkg/erda-configs/i18n/autotest_plan.json
Labels: dop, bug

#3886 refactor(cp-nodes): change chart style
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
Labels: approved

#3764 fix: issue import export asynchronous
  apistructs/file_records.go
  apistructs/issue.go
  modules/dop/conf/conf.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/issue.go
  modules/dop/initialize.go
  modules/dop/services/issue/export.go
  modules/dop/services/issue/import.go
  modules/dop/services/issue/issue.go
  modules/dop/services/testcase/file_records.go
Labels: dop, approved

#3883 fix: Fix extension query with menu
  apistructs/extention.go
Labels: bugfix, approved

#3887 fix: project list statistics error
  modules/msp/tenant/project/project.service_test.go
  modules/msp/tenant/project/project_statistics.go
Labels: msp, bugfix

#3876 fix: update project pipeline style
  conf/dop/i18n/cp/common.yaml
  go.mod
  go.sum
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, approved

#3893 fix: 18n testplan protocol
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesSetInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/addScenesSetButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/cancelExecuteButton/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envBaseInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envBaseInfoTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envGlobalTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/envHeaderTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistory/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryPop/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryRefresh/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeInfoTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileDetail/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileInfo/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/fileInfoTitle/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/refreshButton/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/scenesSetSelect/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/stages/stages.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/stagesTitle/stagesTitle.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/tabExecuteButton/executeButton.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/i18n/i18n.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/i18n/transfer.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/protocol.yml
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/protocol.yml
  pkg/erda-configs/i18n/autotest_plan.json
Labels: dop, approved

#3896 revert: "fix: issue import export asynchronous (#3764)"
  apistructs/file_records.go
  apistructs/issue.go
  modules/dop/conf/conf.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/issue.go
  modules/dop/initialize.go
  modules/dop/services/issue/export.go
  modules/dop/services/issue/import.go
  modules/dop/services/issue/issue.go
  modules/dop/services/testcase/file_records.go
Labels: dop, approved

#3878 fix: update msp i18n config
  conf/msp/i18n/msp-i18n.yaml
Labels: msp, bugfix

#3860 fix: Topology related node error
  .erda/migrations/monitor/20220120-sp_metric_expression.sql
  modules/monitor/apm/topology/topology.go
  modules/monitor/apm/topology/topology_test.go
Labels: msp, bugfix

#3894 fix: Fix i18n bugs, add i18n content
  apistructs/issue_stream_locale.go
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/auto-test-scenes.yaml
  conf/dop/i18n/cp/scenarios/auto-test-space-list.yaml
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileSearch/fileSearch.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsForm/inParamsForm.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/outPutForm/outPutForm.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stages/stages.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/addApiButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/addConfigSheetButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/addCustomScriptButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/addWaitButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/apiEditor.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/helper.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/helper_test.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/stagesOperations/apiEditorDrawer/apiEditorContainer/apiEditor/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStagesOperations/addScenesButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/cancelExecuteButton/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/executeHistoryTable/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeInfo/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeTaskTable/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/tabExecuteButton/executeButton.go
  modules/dop/component-protocol/components/issue-dashboard/bar/assigneeHorizontalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/bar/labelHorizontalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/bar/memberHorizontalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/common/chartbuilders/bar.go
  modules/dop/component-protocol/components/issue-dashboard/tomorrow/render.go
  modules/dop/component-protocol/components/issue-dashboard/trendChartFilter/render.go
  modules/dop/component-protocol/scenarios/auto-test-scenes.yml
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryTable/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go
  pkg/erda-configs/i18n/cmdb.json
  pkg/erda-configs/i18n/project_list_all.json
  providers/component-protocol/issueFilter/filterset.go
Labels: bugfix, approved

#3897 feat: add checkToken to config_post url
  modules/openapi/api/apis/dop/config_manage/config_manage_config_post.go
Labels: approved

#3899 fix: fix project pipeline permission issues
  modules/dop/providers/projectpipeline/service_impl.go
Labels: dop, approved

#3905 fix: project pipeline records add userIDs
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
Labels: approved

#3889 fix: add i18n to burnchart and cumulativeFlow
  modules/dop/component-protocol/scenarios/requirement-task-overview.yml
Labels: dop, approved

#3907 fix: update project pipeline style
  conf/dop/i18n/cp/common.yaml
  go.mod
  go.sum
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: approved

#3908 fix: remove app and branch column
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: approved

#3911 fix: i18n of autotest plan list (#3735)
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/filter/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/formModal/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/render_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/components/table/table_test.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/helper.go
  modules/openapi/component-protocol/scenarios/auto-test-plan-list/i18n/i18n.go
Labels: dop, approved

#3912 feat: 1.6 msp member international
  bundle/member.go
  conf/msp/i18n/msp-i18n.yaml
  modules/dop/endpoints/member.go
  modules/msp/member/mebmer.service.go
  modules/msp/member/mebmer.service_test.go
  modules/msp/member/provider.go
Labels: msp, feature

#3916 fix: modify dashboard to custom dashboard in menu
  .erda/migrations/msp/20220124-menu.sql
Labels: msp, approved

#3917 fix: Project pipeline inode access pipeline details access failed
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: approved

#3915 fix: Cherry pick fix: checker i18n #3781
  conf/msp/i18n/msp-i18n.yaml
  modules/msp/apm/checker/apis/checker.v1.service.go
  modules/msp/apm/checker/apis/checker.v1.service_test.go
  modules/msp/apm/checker/apis/provider.go
Labels: msp, bugfix, approved

#3925 feat: access config international
  conf/msp/instrumentationlibrary/jaeger-template.yaml
  modules/msp/apm/adapter/adapter.service.go
  modules/msp/apm/adapter/adapter.service_test.go
  modules/msp/apm/adapter/model.go
Labels: msp, feature, approved

#3930 fix: autotest configsheet datasource addon search
  modules/orchestrator/endpoints/addon.go
Labels: approved

#3931 fix: Fix extension spec i18n replace value instead of text
  modules/dicehub/dbclient/extention.go
Labels: approved

#3921 feat: The deployment status query in runtime is changed to a one-time query
  modules/orchestrator/dbclient/deployment.go
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/services/runtime/runtime_test.go
Labels: approved

#3939 fix: concurrent map writes in get runtime service status
  modules/orchestrator/services/runtime/runtime.go
Labels: approved

#3940 fix: Fix openapi i18n bind, add i18n content
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/auto-test-scenes.yaml
  conf/dop/i18n/cp/scenarios/auto-test-space-list.yaml
  modules/core/openapi-ng/interceptors/common/client_header.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/executeHistoryRefresh/render.go
  modules/dop/component-protocol/components/auto-test-space-list/components/spaceFormModal/render.go
  modules/dop/component-protocol/components/issue-dashboard/chartFilter/render.go
  modules/dop/component-protocol/components/issue-dashboard/common/chartbuilders/bar.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/complexity.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/empty.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/handler.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/priority.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/severity.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/stage.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/state.go
  modules/dop/component-protocol/components/issue-dashboard/common/util.go
  modules/dop/component-protocol/components/issue-dashboard/filter/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/complexityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/priorityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/severityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/stagePieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/statePieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/trendChartFilter/render.go
  modules/dop/component-protocol/components/issue-gantt/filter/render.go
  modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
  modules/dop/endpoints/testplan_v2.go
  modules/openapi/component-protocol/scenarios/project-list-all/components/alert/alert.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/alert/alert.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go
  pkg/erda-configs/i18n/autotest_plan.json
  pkg/erda-configs/i18n/project_list_all.json
  pkg/erda-configs/i18n/qa.json
Labels: dop, openapi, bugfix

#3942 fix: Release i18n
  apistructs/issue_stream_locale.go
  conf/dop/i18n/cp/common.yaml
  conf/dop/i18n/cp/scenarios/auto-test-scenes.yaml
  go.mod
  go.sum
  modules/core/openapi-ng/interceptors/common/client_header.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/executeHistoryRefresh/render.go
  modules/dop/component-protocol/components/issue-dashboard/chartFilter/render.go
  modules/dop/component-protocol/components/issue-dashboard/common/chartbuilders/bar.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/complexity.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/empty.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/handler.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/priority.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/severity.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/stage.go
  modules/dop/component-protocol/components/issue-dashboard/common/stackhandlers/state.go
  modules/dop/component-protocol/components/issue-dashboard/common/util.go
  modules/dop/component-protocol/components/issue-dashboard/filter/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/complexityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/priorityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/severityPieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/stagePieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/pie/statePieChart/render.go
  modules/dop/component-protocol/components/issue-dashboard/trendChartFilter/render.go
  modules/dop/component-protocol/components/issue-gantt/filter/render.go
  modules/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
  modules/dop/component-protocol/components/scenes-import-record/filter/render.go
  modules/dop/endpoints/testplan_v2.go
  modules/openapi/component-protocol/scenarios/auto-test-space-list/components/spaceFormModal/render.go
  modules/openapi/component-protocol/scenarios/project-list-all/components/alert/alert.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/alert/alert.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/list/list.go
  pkg/erda-configs/i18n/autotest.json
  pkg/erda-configs/i18n/autotest_plan.json
  pkg/erda-configs/i18n/project_list_all.json
  pkg/erda-configs/i18n/qa.json
Labels: approved

#3943 feat(dop): add i18n for mysql account
  conf/dop/i18n/cp/scenarios/addon-mysql-account.yaml
  conf/dop/i18n/cp/scenarios/addon-mysql-attachment.yaml
  conf/dop/i18n/cp/scenarios/addon-mysql-consumer.yaml
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render.go
  modules/dop/component-protocol/components/addon-mysql-account/accountTable/render_test.go
  modules/dop/component-protocol/components/addon-mysql-account/addAccountButton/render.go
  modules/dop/component-protocol/components/addon-mysql-account/filter/render.go
  modules/dop/component-protocol/components/addon-mysql-account/viewPassword/render.go
  modules/dop/component-protocol/components/addon-mysql-account/viewPasswordModal/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/config/configCopyParams/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/config/configDrawer/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/editFormModal/render.go
  modules/dop/component-protocol/components/addon-mysql-attachment/filter/render.go
Labels: approved

#3941 feat: aggregate release by git branch
  .erda/migrations/dicehub/20220125-release-branch.py
  .erda/migrations/dicehub/20220125-release-branch.sql
  .erda/migrations/dicehub/requirements.txt
  apistructs/release.go
  conf/dop/i18n/cp/scenarios/release-manage.yaml
  modules/dicehub/dbclient/release.go
  modules/dicehub/endpoints/release.go
  modules/dicehub/service/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/model.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render_test.go
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: approved

#3950 refactor: change charts style
  conf/cmp/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
  modules/cmp/component-protocol/components/cmp-dashboard-nodes/common/chart/model.go
Labels: approved

#3952 fix: rename py migration script
  .erda/migrations/dicehub/20220126-release-branch.py
Labels: approved

#3945 feat: the repeated call interface of automatic test scenario input parameters
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsForm/inParamsForm.go
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesConfig/inParamsForm/render.go
  modules/dop/component-protocol/scenarios/auto-test-scenes.yml
Labels: approved

#3936 feat: project pipeline create name and source pre check
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto-go/dop/projectpipeline/client/client.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.http.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.json.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.validator.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline_grpc.pb.go
  api/proto/core/pipeline/definition/definition.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  conf/dop/dop.yaml
  conf/dop/i18n/project-pipeline.yaml
  modules/dop/endpoints/autotests.http
  modules/dop/providers/projectpipeline/provider.go
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/providers/definition/db/define.go
Labels: approved

#3956 fix(dop,pipeline): only success status will be reported in project pipeline process
  conf/dop/i18n/cp/common.yaml
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/pipeline/aop/plugins/task/definitionreport/plugin.go
Labels: dop, pipeline, bugfix

#3959 fix(dop): unexpected render missing create button when delete mysql addon account
  modules/dop/component-protocol/scenarios/addon-mysql-account.yml
Labels: dop, bugfix, approved

#3955 fix: k8s remotecommand support cluster-dialer
  .licenserc.json
  conf/resources.go
  go.mod
  go.sum
  modules/core/services/filenamager/common.go
  modules/core/services/filenamager/file.manager.service.go
  modules/openapi/api/apis/monitor/monitor_filemanager_download.go
  modules/openapi/api/apis/monitor/monitor_filemanager_upload.go
  pkg/k8s/httpstream/spdy/connection.go
  pkg/k8s/httpstream/spdy/connection_test.go
  pkg/k8s/httpstream/spdy/roundtripper.go
  pkg/k8s/httpstream/spdy/roundtripper_test.go
  pkg/k8s/httpstream/spdy/tls.go
  pkg/k8s/httpstream/spdy/upgrade.go
  pkg/k8s/httpstream/spdy/upgrade_test.go
  pkg/k8s/remotecommand/remotecommand.go
  pkg/k8s/spdy/spdy.go
Labels: bugfix

#3958 fix: Add i18n content, issue stream, contribution
  apistructs/issue.go
  apistructs/issue_stream_locale.go
  conf/dop/dop.yaml
  conf/dop/i18n/contribution.yaml
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileFormModal/render.go
  modules/dop/component-protocol/components/scenes-import-record/filter/render.go
  modules/dop/providers/contribution/provider.go
  modules/dop/providers/contribution/service.go
  modules/openapi/component-protocol/scenarios/project-list-all/components/filter/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/filter/render.go
  pkg/erda-configs/i18n/project_list_all.json
Labels: bugfix, approved

#3961 fix: Release i18n content
  apistructs/issue.go
  apistructs/issue_stream_locale.go
  conf/dop/dop.yaml
  conf/dop/i18n/contribution.yaml
  modules/dop/endpoints/issue.go
  modules/dop/services/issuestream/issue_stream.go
  modules/dop/services/issuestream/issue_stream_template.go
  modules/dop/services/issuestream/issue_stream_template_test.go
  modules/openapi/component-protocol/scenarios/project-list-all/components/filter/render.go
  modules/openapi/component-protocol/scenarios/project-list-my/components/filter/render.go
  pkg/erda-configs/i18n/project_list_all.json
Labels: bugfix, approved

#3962 fix: admin workbench i18n optimize
  modules/admin/component-protocol/components/personal-workbench/i18n/i18n.go
  modules/admin/component-protocol/components/personal-workbench/workList/app.go
Labels: bugfix
