Repository erda-project/erda, pull requests merged in 2022-05, with the labels that each got.

#4676 feat(pipeline): Add edge cluster pipeline reporting
  .erda/migrations/pipeline/20220421-pipeline-edge-report-status.sql
  apistructs/pipeline.go
  bundle/pipeline.go
  conf/pipeline/pipeline.yaml
  modules/pipeline/dbclient/op_pipeline.go
  modules/pipeline/dbclient/op_pipeline_stage.go
  modules/pipeline/dbclient/op_pipeline_task.go
  modules/pipeline/endpoints/callback.go
  modules/pipeline/providers/edgereporter/db/client.go
  modules/pipeline/providers/edgereporter/db/pipeline.go
  modules/pipeline/providers/edgereporter/interface.go
  modules/pipeline/providers/edgereporter/provider.go
  modules/pipeline/providers/edgereporter/reporter.go
  modules/pipeline/providers/edgereporter/reporter_logs_test.go
  modules/pipeline/providers/edgereporter/reporter_test.go
  modules/pipeline/providers/reconciler/pipeline_reconciler.go
  modules/pipeline/providers/reconciler/provider.go
  modules/pipeline/providers/reconciler/reconcile.go
  modules/pipeline/providers/reconciler/task_reconciler.go
  modules/pipeline/services/pipelinesvc/callback.go
  modules/pipeline/spec/pipeline.go
  modules/pipeline/spec/pipeline_base.go
Labels: pipeline, feature, approved

#4739 feat(pipeline): Pipeline action initialization load
  api/proto-go/core/pipeline/action/pb/action.form.pb.go
  api/proto-go/core/pipeline/action/pb/action.pb.go
  api/proto/core/pipeline/action/action.proto
  apistructs/extention.go
  modules/pipeline/providers/actionmgr/action.service.go
  modules/pipeline/providers/actionmgr/action.service_test.go
  modules/pipeline/providers/actionmgr/common_test.go
  modules/pipeline/providers/actionmgr/impl.go
  modules/pipeline/providers/actionmgr/impl_test.go
  modules/pipeline/providers/actionmgr/provider.go
Labels: pipeline, feature, approved

#4730 feat(pipeline): pipeline edge cron
  .erda/migrations/pipeline/20220427-pipeline-edge-cron.sql
  apistructs/pipeline.go
  apistructs/pipeline_cron.go
  bundle/pipeline_cron.go
  modules/pipeline/providers/cron/compensator/provider.go
  modules/pipeline/providers/cron/cron.service.go
  modules/pipeline/providers/cron/cron.service_test.go
  modules/pipeline/providers/cron/daemon/cron_task.go
  modules/pipeline/providers/cron/daemon/provider.go
  modules/pipeline/providers/cron/db/define.go
  modules/pipeline/providers/cron/db/define_test.go
  modules/pipeline/providers/cron/provider.go
  modules/pipeline/spec/pipeline_cron.go
Labels: pipeline, feature, approved

#4711 feat(pipeline): Pipeline center and edge sync action
  api/proto-go/core/pipeline/action/pb/action.http.pb.go
  api/proto-go/core/pipeline/action/pb/action.pb.go
  api/proto/core/pipeline/action/action.proto
  apistructs/pipeline_actions.go
  bundle/pipeline_action.go
  modules/pipeline/providers/actionmgr/action.service.go
  modules/pipeline/providers/actionmgr/action.service_test.go
  modules/pipeline/providers/actionmgr/api_test.http
  modules/pipeline/providers/actionmgr/provider.go
  modules/pipeline/providers/clusterinfo/interface.go
  modules/pipeline/providers/clusterinfo/interface_test.go
  modules/pipeline/providers/cron/cron.service_test.go
  modules/pipeline/providers/edgepipeline_register/interface.go
Labels: pipeline, feature, approved

#4747 feat(pipeline): pipeline support run at edge side
  .erda/migrations/pipeline/20220428-pipeline-edge-base.sql
  apistructs/pipeline.go
  bundle/pipeline.go
  conf/pipeline/pipeline.yaml
  modules/pipeline/endpoints/callback.go
  modules/pipeline/endpoints/v2.go
  modules/pipeline/initialize.go
  modules/pipeline/pkg/action_info/passedDataWhenCreate.go
  modules/pipeline/provider.go
  modules/pipeline/providers/actionmgr/db/client.go
  modules/pipeline/providers/clusterinfo/interface_test.go
  modules/pipeline/providers/cron/compensator/provider.go
  modules/pipeline/providers/cron/cron.service.go
  modules/pipeline/providers/cron/cron.service_test.go
  modules/pipeline/providers/cron/daemon/cron_task.go
  modules/pipeline/providers/cron/daemon/provider.go
  modules/pipeline/providers/cron/db/define.go
  modules/pipeline/providers/cron/provider.go
  modules/pipeline/providers/edgepipeline/create_cron.go
  modules/pipeline/providers/edgepipeline/create_pipeline.go
  modules/pipeline/providers/edgepipeline/interface.go
  modules/pipeline/providers/edgepipeline/provider.go
  modules/pipeline/providers/edgepipeline_register/interface.go
  modules/pipeline/providers/edgepipeline_register/interface_test.go
  modules/pipeline/providers/edgepipeline_register/provider.go
  modules/pipeline/providers/edgereporter/interface.go
  modules/pipeline/providers/edgereporter/provider.go
  modules/pipeline/providers/edgereporter/reporter.go
  modules/pipeline/providers/reconciler/task_reconciler.go
  modules/pipeline/services/pipelinesvc/callback.go
  modules/pipeline/services/pipelinesvc/create.go
  modules/pipeline/services/pipelinesvc/create_v2.go
  modules/pipeline/services/pipelinesvc/define.go
  modules/pipeline/spec/pipeline_base.go
  modules/pipeline/spec/pipeline_cron.go
  modules/pipeline/spec/pipeline_task.go
Labels: pipeline, feature, approved

#4763 fix: fix clickhouse download file size error
  modules/core/monitor/log/query/log.query.service.go
  modules/core/monitor/log/query/log.query.service_test.go
  modules/core/monitor/log/query/routes.go
  modules/core/monitor/log/storage/clickhouse/iterator.go
  modules/core/monitor/log/storage/clickhouse/iterator_test.go
  modules/core/monitor/log/storage/storage.go
  modules/extensions/loghub/index/query/routes.go
  modules/msp/apm/log-service/query/log.service.download.go
Labels: msp, bugfix, approved

#4769 fix(pipeline): typo in edge reporter config
  modules/pipeline/providers/edgereporter/provider.go
Labels: pipeline, bugfix, approved

#4771 fix: ignore pause container
  conf/monitor/monitor/alert/rules/app_resource/app_resource_container_cpu/analyzer_expression.json
  conf/monitor/monitor/alert/rules/app_resource/app_resource_container_mem/analyzer_expression.json
  conf/monitor/monitor/alert/rules/dice_component/dice_component_log_protector/alert_rule.yaml
  conf/monitor/monitor/alert/rules/dice_component/dice_component_log_protector/analyzer_expression.json
  conf/monitor/monitor/alert/rules/dice_component/dice_component_log_protector/notify_template.yaml
Labels: bugfix

#4772 fix(pipeline): remove invalidate oauth2Token after pipeline task tear down
  modules/pipeline/providers/reconciler/task_reconciler.go
Labels: pipeline, bugfix, approved

#4774 polish: add extensions dir to .gitignore
  .gitignore
Labels: approved

#4775 feat(pipeline): edge side pipeline watch secret event
  modules/pipeline/providers/edgepipeline_register/interface.go
  modules/pipeline/providers/edgepipeline_register/interface_test.go
  modules/pipeline/providers/edgepipeline_register/provider.go
Labels: approved

#4708 fix: The TTL of span data
  conf/msp/msp.yaml
  go.mod
  go.sum
  modules/core/monitor/pkg/mock_logger.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/clean.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/clean_test.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/disk_checker.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/disk_checker_test.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/provider.go
  modules/core/monitor/storekit/elasticsearch/index/loader/cache_loader.go
  modules/core/monitor/storekit/elasticsearch/index/loader/cache_sync.go
  modules/core/monitor/storekit/elasticsearch/index/loader/provider.go
Labels: bugfix, approved

#4777 fix(pipeline): Fixed the null pointer problem of edge pipeline execution compensation
  modules/pipeline/providers/cron/compensator/provider.go
Labels: pipeline, bugfix, approved

#4779 polish(pipeline): pipeline edge run
  conf/pipeline/pipeline.yaml
  modules/pipeline/events/event.go
  modules/pipeline/events/manager.go
  modules/pipeline/initialize.go
  modules/pipeline/providers/actionmgr/provider.go
  modules/pipeline/providers/cron/cron.service.go
  modules/pipeline/providers/cron/daemon/cron_task.go
  modules/pipeline/providers/cron/daemon/provider.go
  modules/pipeline/providers/cron/db/define.go
  modules/pipeline/providers/cron/db/define_test.go
  modules/pipeline/providers/edgepipeline/create_pipeline.go
  modules/pipeline/providers/edgepipeline_register/provider.go
  modules/pipeline/providers/edgereporter/provider.go
  modules/pipeline/providers/edgereporter/reporter.go
Labels: pipeline, approved

#4776 fix(pipeline): The edge pipeline does not query the extension on dicehub
  modules/pipeline/providers/actionmgr/common.go
  modules/pipeline/providers/actionmgr/common_test.go
  modules/pipeline/providers/actionmgr/db/client.go
  modules/pipeline/providers/actionmgr/impl.go
  modules/pipeline/providers/actionmgr/impl_test.go
Labels: pipeline, bugfix, approved

#4780 feature(pipeline): run edge-side created pipeline
  modules/pipeline/endpoints/pipeline.go
  modules/pipeline/providers/edgepipeline/interface.go
  modules/pipeline/providers/edgepipeline/provider.go
  modules/pipeline/providers/edgepipeline/run_pipeline.go
Labels: pipeline, approved

#4773 fix: transform request_id query to trace_id
  conf/monitor/monitor/monitor.yaml
  modules/core/monitor/log/storage/clickhouse/aggregate_test.go
  modules/core/monitor/log/storage/clickhouse/converter/field_name_converter.go
  modules/core/monitor/log/storage/clickhouse/provider.go
  modules/core/monitor/log/storage/clickhouse/query_parser/query_parser.go
  modules/core/monitor/log/storage/clickhouse/query_parser/query_parser_test.go
  modules/core/monitor/log/storage/clickhouse/sql_builder.go
Labels: msp, approved

#4781 feat: ck add column index
  conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
  conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
Labels: msp, feature, approved

#4782 fix(pipeline): polish edge pipeline reporter
  modules/pipeline/providers/edgereporter/db/pipeline.go
  modules/pipeline/providers/edgereporter/reporter.go
Labels: pipeline, bugfix, approved

#4785 feat: add list runtime group by my apps
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/openapi/api/apis/orchestrator/orchestrator_runtime_group_by_my_apps.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/endpoints/runtime.go
Labels: feature

#4770 [feature] support running container to real log
  api/proto-go/core/monitor/log/query/pb/query.form.pb.go
  api/proto-go/core/monitor/log/query/pb/query.pb.go
  api/proto/core/monitor/log/query/query.proto
  conf/monitor/monitor/monitor.yaml
  modules/core/monitor/log/query/log.query.service.go
  modules/core/monitor/log/query/log.query.service_test.go
  modules/core/monitor/log/query/provider.go
  modules/core/monitor/log/storage/kubernetes-logs/storage.go
  modules/core/monitor/log/storage/kubernetes-logs/storage_test.go
  modules/core/monitor/log/storage/storage.go
Labels: approved

#4787 fix(dop): dop adds methods to obtain appid and branch
  modules/dop/endpoints/pipelinecron.go
  modules/dop/endpoints/pipelinecron_test.go
  modules/openapi/api/apis/dop/adaptor_cicd_cron_start.go
  modules/openapi/api/apis/dop/adaptor_cicd_cron_stop.go
Labels: approved

#4786 fix(pipeline): Pipeline did not find cron. Cronid should not be set to 0
  modules/pipeline/services/pipelinesvc/create_v2.go
Labels: pipeline, bugfix, approved

#4784 feat(pipeline): edge pipeline store access key in etcd
  conf/pipeline/pipeline.yaml
  modules/pipeline/providers/edgepipeline_register/access_token.go
  modules/pipeline/providers/edgepipeline_register/cluster_access_key.go
  modules/pipeline/providers/edgepipeline_register/cluster_access_key_test.go
  modules/pipeline/providers/edgepipeline_register/interface.go
  modules/pipeline/providers/edgepipeline_register/interface_test.go
  modules/pipeline/providers/edgepipeline_register/provider.go
Labels: pipeline, feature, approved

#4789 fix: add application name in list runtime by my apps
  modules/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  modules/openapi/api/apis/orchestrator/orchestrator_runtime_list_my_runtimes.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/endpoints/runtime.go
Labels: bugfix

#4792 fix: request_cpu greater than max_cpu problems caused by user modifyi…
  modules/orchestrator/utils/deployment_utils.go
Labels: bugfix, approved

#4794 feat: modify blue_green_deploy default value is open
  modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
Labels: feature, approved

#4796 fix: modify replica of cluster-dialer
  erda.yml
Labels: bugfix

#4800 fix: pipeline reduce refresh clusterinfo interval
  conf/pipeline/pipeline.yaml
  modules/pipeline/providers/clusterinfo/provider.go
Labels: bugfix, approved

#4799 fix: delete session if connect failed
  pkg/clusterdialer/tunnel_session.go
Labels: bugfix

#4795 fix(monitor) fix runtime log query is empty
  conf/monitor/monitor/monitor.yaml
  modules/core/monitor/log/query/log.query.service.go
  modules/core/monitor/log/query/log.query.service_test.go
  modules/core/monitor/log/query/provider.go
Labels: approved

#4803 fix: action agent support set file stream timeout by env
  modules/actionagent/callback.go
  modules/actionagent/callback_reporter.go
  modules/actionagent/callback_test.go
  modules/actionagent/define.go
Labels: bugfix, approved

#4797 fix(pipeline): Fix the problem that unmarshal has no value when pipeline tasks do not need to be internationalized
  modules/pipeline/providers/actionmgr/db/client.go
  modules/pipeline/providers/actionmgr/db/client_test.go
Labels: pipeline, bugfix, approved

#4806 refactor: merge action-runner&action-runner-scheduler into pipeline
  cmd/action-runner-scheduler/main.go
  cmd/action-runner/main.go
  cmd/actionagent/main.go
  cmd/actionagent/main_test.go
  modules/pipeline/action-runner-scheduler/conf/conf.go
  modules/pipeline/action-runner-scheduler/dbclient/dbclient.go
  modules/pipeline/action-runner-scheduler/dbclient/runner_task.go
  modules/pipeline/action-runner-scheduler/endpoints/endpoints.go
  modules/pipeline/action-runner-scheduler/endpoints/info.go
  modules/pipeline/action-runner-scheduler/endpoints/runner_task.go
  modules/pipeline/action-runner-scheduler/initialize.go
  modules/pipeline/action-runner-scheduler/provider.go
  modules/pipeline/action-runner-scheduler/services/apierrors/errors.go
  modules/pipeline/action-runner-scheduler/services/runnertask/runner_task.go
  modules/pipeline/action-runner/apis.go
  modules/pipeline/action-runner/conf.go
  modules/pipeline/action-runner/logs.go
  modules/pipeline/action-runner/runner.go
  modules/pipeline/action-runner/task.go
  modules/pipeline/actionagent/agenttool/lock.go
  modules/pipeline/actionagent/agenttool/lock_test.go
  modules/pipeline/actionagent/agenttool/mv.go
  modules/pipeline/actionagent/agenttool/mv_test.go
  modules/pipeline/actionagent/agenttool/tar.go
  modules/pipeline/actionagent/agenttool/tar_test.go
  modules/pipeline/actionagent/callback.go
  modules/pipeline/actionagent/callback_reporter.go
  modules/pipeline/actionagent/callback_test.go
  modules/pipeline/actionagent/define.go
  modules/pipeline/actionagent/execute.go
  modules/pipeline/actionagent/execute_test.go
  modules/pipeline/actionagent/exit.go
  modules/pipeline/actionagent/file_watch.go
  modules/pipeline/actionagent/file_watch_collector.go
  modules/pipeline/actionagent/file_watch_collector_test.go
  modules/pipeline/actionagent/file_watch_test.go
  modules/pipeline/actionagent/filewatch/watch.go
  modules/pipeline/actionagent/openapi.go
  modules/pipeline/actionagent/openapi_test.go
  modules/pipeline/actionagent/prestop.go
  modules/pipeline/actionagent/prestop_test.go
  modules/pipeline/actionagent/pull_bootstrap_info.go
  modules/pipeline/actionagent/signal.go
  modules/pipeline/actionagent/step_logic.go
  modules/pipeline/actionagent/step_prepare.go
  modules/pipeline/actionagent/step_restore.go
  modules/pipeline/actionagent/step_sore_test.go
  modules/pipeline/actionagent/step_store.go
  modules/pipeline/actionagent/step_validate.go
  modules/pipeline/actionagent/step_validate_test.go
  modules/pipeline/actionagent/uploaddir.go
  modules/pipeline/actionagent/uploaddir_test.go
  modules/pipeline/endpoints/pipeline_task.go
  modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/meta.go
  modules/pipeline/pipengine/actionexecutor/plugins/docker/docker.go
  modules/pipeline/pkg/container_provider/container_instance_provider.go
  modules/pipeline/pkg/container_provider/container_provider_test.go
  modules/pipeline/providers/reconciler/taskrun/taskop/prepare.go
Labels: refactor, approved

#4808 fix(pipeline): Solve the problem of reporting the running status of the pipeline
  modules/pipeline/providers/reconciler/pipeline_reconciler_impl.go
  modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
  modules/pipeline/providers/reconciler/reconcile.go
  modules/pipeline/providers/reconciler/reconcile_test.go
Labels: pipeline, bugfix, approved

#4798 feat: modify admin component name to erda-server
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  cmd/erda-server/main.go
  cmd/erda-server/register.go
  conf/erda-server/erda-server.yaml
  erda.yml
  modules/apps/personal-workbench/i18n/common.yaml
  modules/apps/personal-workbench/i18n/cp/common.yaml
  modules/apps/personal-workbench/i18n/cp/scenarios/personal-workbench.yaml
  modules/openapi/api/apis/admin/admin_audits_list.go
  modules/openapi/api/apis/admin/admin_notice_unpublish.go
  modules/openapi/api/apis/admin/admin_user_list.go
  pipeline.yml
  pkg/parser/diceyml/diceyml_test.go
  quick-start/env
Labels: feature, approved

#4807 refactor: merge cluster agent&dialer&manager&ops into cluster dir
  cmd/cluster-agent/main.go
  cmd/cluster-dialer/main.go
  cmd/cluster-manager/main.go
  cmd/cluster-ops/main.go
  modules/cluster/cluster-agent/client/client.go
  modules/cluster/cluster-agent/client/credential.go
  modules/cluster/cluster-agent/config/config.go
  modules/cluster/cluster-agent/provider.go
  modules/cluster/cluster-dialer/auth/auth.go
  modules/cluster/cluster-dialer/config/config.go
  modules/cluster/cluster-dialer/provider.go
  modules/cluster/cluster-dialer/server/client_data.go
  modules/cluster/cluster-dialer/server/client_data_test.go
  modules/cluster/cluster-dialer/server/dialer_test.go
  modules/cluster/cluster-dialer/server/tunnel-server.go
  modules/cluster/cluster-dialer/server/tunnel-server_test.go
  modules/cluster/cluster-manager/conf/conf.go
  modules/cluster/cluster-manager/dbclient/cluster.go
  modules/cluster/cluster-manager/dbclient/dbclient.go
  modules/cluster/cluster-manager/endpoints/cluster.go
  modules/cluster/cluster-manager/endpoints/endpoints.go
  modules/cluster/cluster-manager/endpoints/prehandle.go
  modules/cluster/cluster-manager/initialize.go
  modules/cluster/cluster-manager/model/model.go
  modules/cluster/cluster-manager/provider.go
  modules/cluster/cluster-manager/services/apierrors/errors.go
  modules/cluster/cluster-manager/services/cluster/cluster.go
  modules/cluster/cluster-ops/client/client.go
  modules/cluster/cluster-ops/config/config.go
  modules/cluster/cluster-ops/provider.go
Labels: approved

#4810 feat: refactor clickhouse log table schema
  conf/monitor/streaming/clickhouse/logs_ddl_create_db.sql
  conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
  conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
  modules/core/monitor/log/log.go
  modules/core/monitor/log/storage/clickhouse/iterator.go
  modules/core/monitor/log/storage/clickhouse/writer.go
  modules/core/monitor/log/storage/clickhouse/writer_test.go
Labels: msp, feature, approved

#4813 fix: rollback i18n file for erda-server
  conf/erda-server/erda-server.yaml
  conf/erda-server/i18n/common.yaml
  conf/erda-server/i18n/cp/common.yaml
  conf/erda-server/i18n/cp/scenarios/personal-workbench.yaml
Labels: bugfix, approved

#4812 feat: change some column to low cardinality to reduce storage-size
  conf/monitor/streaming/clickhouse/logs_ddl_create_default_tables.sql
  conf/monitor/streaming/clickhouse/logs_ddl_create_tenant_tables.sql
Labels: msp, feature, approved

#4814 fix: modify addr of personal-workbentch for component-protocol and openapi
  conf/openapi/openapi.yaml
  modules/openapi/api/apis/admin/admin_approve_get.go
  modules/openapi/api/apis/admin/admin_approve_list.go
  modules/openapi/api/apis/admin/admin_approve_update.go
  modules/openapi/api/apis/admin/admin_audits_export.go
  modules/openapi/api/apis/admin/admin_cluster_get.go
  modules/openapi/api/apis/admin/admin_cluster_list.go
  modules/openapi/api/apis/admin/admin_dingtalk.go
  modules/openapi/api/apis/admin/admin_notice_create.go
  modules/openapi/api/apis/admin/admin_notice_delete.go
  modules/openapi/api/apis/admin/admin_notice_list.go
  modules/openapi/api/apis/admin/admin_notice_publish.go
  modules/openapi/api/apis/admin/admin_notice_update.go
  modules/openapi/api/apis/admin/admin_user_search.go
Labels: bugfix, approved

#4758 feat: Personal access token set up, replace gittar member token.
  .erda/migrations/cmdb/20220429-migrate-member-org-token.sql
  api/proto-go/core/token/pb/token.form.pb.go
  api/proto-go/core/token/pb/token.pb.go
  api/proto/core/token/token.proto
  cmd/dop/main.go
  cmd/gittar/main.go
  conf/dop/dop.yaml
  conf/gittar/gittar.yaml
  modules/core-services/endpoints/application.go
  modules/core-services/endpoints/endpoints.go
  modules/core-services/initialize.go
  modules/core-services/provider.go
  modules/core-services/providers/token/dao.go
  modules/core-services/providers/token/service.go
  modules/core-services/providers/token/service_test.go
  modules/core-services/services/application/appliation.go
  modules/core-services/services/member/member.go
  modules/core-services/services/org/org.go
  modules/core-services/services/project/project.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/pipeline.go
  modules/dop/endpoints/pipeline_test.go
  modules/dop/initialize.go
  modules/dop/provider.go
  modules/dop/providers/projectpipeline/provider.go
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/dop/services/application/application.go
  modules/dop/services/project/export_package.go
  modules/dop/services/project/import_package.go
  modules/dop/services/project/option.go
  modules/dop/services/project/project.go
  modules/dop/services/project/project_package.go
  modules/gittar/auth/auth.go
  modules/gittar/initialize.go
  modules/gittar/provider.go
  modules/gittar/webcontext/context.go
  modules/msp/credential/provider.go
  pkg/oauth2/tokenstore/mysqltokenstore/token_store.go
Labels: feature

#4816 fix(pipeline): pipeline status is always running when all tasks are disabled
  modules/pipeline/providers/reconciler/pipeline_reconciler_impl.go
  modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
  modules/pipeline/providers/reconciler/reconcile.go
Labels: pipeline, bugfix, approved

#4819 chore(pipeline): pipeline place bootstrap.yaml beside main.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  go.mod
  go.sum
Labels: pipeline

#4821 chore: action-runner-scheduler place bootstrap.yaml beside main.go
  cmd/action-runner-scheduler/bootstrap.yaml
  cmd/action-runner-scheduler/main.go
  go.mod
  go.sum
Labels: approved

#4823 fix(pipeline): fulfill parent snippet task status stored in processed tasks
  modules/pipeline/providers/reconciler/snippet.go
  modules/pipeline/providers/reconciler/snippet_test.go
  modules/pipeline/providers/reconciler/task_reconciler.go
Labels: pipeline, bugfix, approved

#4825 fix: add ch field for query
  modules/core/monitor/log/storage/clickhouse/iterator.go
Labels: msp, bugfix, approved

#4820 fix: polish export task channel
  modules/core/monitor/dataview/provider.go
  modules/core/monitor/dataview/provider_test.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/clean_test.go
  modules/core/monitor/storekit/elasticsearch/index/cleaner/disk_checker_test.go
  pkg/mock/mock_context_test.go
  pkg/mock/mock_http_router_test.go
  pkg/mock/mock_logger_test.go
Labels: core feature, bugfix

#4827 fix: cluster-manager and dop config
  cmd/cluster-manager/main.go
  conf/dop/dop.yaml
Labels: bugfix, approved

#4822 fix: convert `project_id` to string
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
Labels: bugfix

#4837 feat: *_mock.go files don't run unit test coverage
  .golangci.yml
  go.sum
  pkg/mock/context_mock.go
  pkg/mock/http_router_mock.go
  pkg/mock/logger_mock.go
  tools/gotools/go-test-sum/main.go
Labels: feature, bugfix

#4817 fix: get instance list by cluster-name to avoid dirty data case by sw…
  modules/orchestrator/endpoints/instance.go
Labels: bugfix, approved

#4834 fix: Fix gittar grpc client.
  cmd/gittar/main.go
Labels: bugfix, approved

#4756 feat: add devWorkflow provider
  .erda/migrations/dop/202200428-devflowrule.sql
  .erda/migrations/dop/20220509-devflowrule-migrations.py
  .erda/migrations/dop/requirements.txt
  .gitignore
  api/proto-go/all.go
  api/proto-go/core/monitor/log/query/pb/query.json.pb.go
  api/proto-go/dop/devflowrule/client/client.go
  api/proto-go/dop/devflowrule/client/provider.go
  api/proto-go/dop/devflowrule/pb/devflowrule.form.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.http.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.json.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.validator.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule_grpc.pb.go
  api/proto-go/dop/devflowrule/pb/register.services.pb.go
  api/proto/dop/devflowrule/devflowrule.proto
  cmd/dop/main.go
  conf/dop/dop.yaml
  go.mod
  go.sum
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/project.go
  modules/dop/initialize.go
  modules/dop/provider.go
  modules/dop/providers/devflowrule/db/client.go
  modules/dop/providers/devflowrule/db/define.go
  modules/dop/providers/devflowrule/devflowrule.service.go
  modules/dop/providers/devflowrule/provider.go
  modules/dop/services/apierrors/errors.go
  pkg/erda-configs/permission/backend/sys/org/project/project.yml
Labels: feature, approved

#4839 fix: do not sync pod than cluster is empty
  .erda/migrations/orchestrator/20210528-scheduler-base.sql
  .erda/migrations/orchestrator/20210729-scheduler-index-update.sql
  .erda/migrations/orchestrator/20220511-add-index-for-instance-table.sql
  modules/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
Labels: bugfix, approved

#4754 refactor(dop): add unit-test pb provider
  .erda/migrations/qa/20220519-qa-test-record-report.sql
  api/proto-go/all.go
  api/proto-go/dop/qa/unittest/client/client.go
  api/proto-go/dop/qa/unittest/client/provider.go
  api/proto-go/dop/qa/unittest/pb/register.services.pb.go
  api/proto-go/dop/qa/unittest/pb/unittest.form.pb.go
  api/proto-go/dop/qa/unittest/pb/unittest.http.pb.go
  api/proto-go/dop/qa/unittest/pb/unittest.json.pb.go
  api/proto-go/dop/qa/unittest/pb/unittest.pb.go
  api/proto-go/dop/qa/unittest/pb/unittest.validator.pb.go
  api/proto-go/dop/qa/unittest/pb/unittest_grpc.pb.go
  api/proto/dop/qa/unittest/unittest.proto
  apistructs/code_coverage_exec_record.go
  apistructs/qa.go
  apistructs/qa_test.go
  conf/dop/dop.yaml
  modules/dop/dbclient/dao.go
  modules/dop/dbclient/db.go
  modules/dop/endpoints/apis.go
  modules/dop/endpoints/endpoints.go
  modules/dop/endpoints/sonar.go
  modules/dop/provider.go
  modules/dop/providers/qa/unittest/provider.go
  modules/dop/providers/qa/unittest/unittest-service.go
  pkg/qaparser/manager.go
  pkg/qaparser/surefilexml/ingest.go
  pkg/qaparser/surefilexml/parser.go
  pkg/qaparser/surefilexml/parser_test.go
  pkg/qaparser/testngxml/models.go
  pkg/qaparser/testngxml/parser.go
  pkg/qaparser/testngxml/parser_test.go
  pkg/qaparser/types.go
Labels: dop, refactor, approved

#4838 fix: remove http-client.env.json
  .gitignore
  http-client.env.json
Labels: bugfix, approved

#4842 feat: support set resource limitation on log query on clickhouse
  conf/monitor/monitor/monitor.yaml
  modules/core/monitor/log/storage/clickhouse/iterator.go
  modules/core/monitor/log/storage/clickhouse/iterator_test.go
  modules/core/monitor/log/storage/clickhouse/provider.go
Labels: msp

#4844 fix(openapi): remove qa unittest useless apis
  modules/openapi/api/apis/dop/qa_test_callback.go
  modules/openapi/api/apis/dop/qa_test_detail.go
  modules/openapi/api/apis/dop/qa_test_list.go
  modules/openapi/api/apis/dop/qa_test_types.go
Labels: openapi, bugfix, approved

#4843 feat(dop): update devflowrule api
  api/proto-go/dop/devflowrule/pb/devflowrule.form.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.json.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.validator.pb.go
  api/proto/dop/devflowrule/devflowrule.proto
  modules/dop/providers/devflowrule/db/define.go
  modules/dop/providers/devflowrule/devflowrule.service.go
Labels: dop, feature, approved

#4761 fix(dop): set api-spec-id zero when export scene step
  modules/dop/services/autotest_v2/space_data.go
  modules/dop/services/autotest_v2/space_data_test.go
Labels: dop, bugfix

#4831 fix: Fixed the issue of sending failure when ding talk notify is too long
  modules/messenger/eventbox/subscriber/dingding/dingding.go
  modules/messenger/eventbox/subscriber/dingding/dingding_test.go
  modules/messenger/eventbox/subscriber/dingding_worknotice/dingding_worknotice.go
  modules/messenger/eventbox/subscriber/dingtalk_worknotice/dingtalk_worknotice.go
Labels: bugfix, approved

#4846 feat(dop): return parent code coverage data when list qa unittest
  modules/dop/dbclient/dao.go
  modules/dop/providers/qa/unittest/unittest-service.go
Labels: dop, feature

#4847 fix: fix ck timeout setting bug
  apistructs/dashboard.go
  bundle/dashboard.go
  modules/core/monitor/log/storage/clickhouse/iterator.go
  modules/core/monitor/log/storage/clickhouse/iterator_test.go
  modules/core/monitor/log/storage/kubernetes-logs/provider.go
  modules/dop/endpoints/cicd.go
Labels: msp, bugfix, approved

#4841 feat(dop): Compatible with old project branch rules
  api/proto-go/dop/devflowrule/pb/devflowrule.form.pb.go
  api/proto-go/dop/devflowrule/pb/devflowrule.pb.go
  api/proto/dop/devflowrule/devflowrule.proto
  apistructs/devflowrule.go
  apistructs/devflowrule_test.go
  bundle/branch_rule.go
  bundle/devflowrule.go
  modules/dop/initialize.go
  modules/dop/providers/devflowrule/devflowrule.service.go
  modules/dop/providers/guide/guide.service.go
  modules/dop/services/branchrule/branch_rule.go
  modules/orchestrator/services/deployment_order/deployment_order_create_test.go
Labels: dop, feature, approved

#4848 fix: log_metrics support use tag keys without dice prefix
  modules/msp/apm/log-service/rules/log_metric_config.go
  modules/msp/apm/log-service/rules/log_metric_config_test.go
Labels: msp, bugfix, approved

#4849 fix: list clusters in other org
  api/proto-go/core/clustermanager/cluster/pb/cluster.http.pb.go
  api/proto-go/core/clustermanager/cluster/pb/cluster.pb.go
  api/proto/core/clustermanager/cluster/cluster.proto
  modules/cluster/cluster-manager/cluster/cluster.service.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4850 feat: add appID in list my runtimes
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/orchestrator/endpoints/runtime.go
Labels: feature

#4854 fix(dop): fix the bug of json serialization
  modules/dop/providers/devflowrule/db/define.go
Labels: dop, bugfix, approved

#4836 feat: add unit test for taskop-prepare
  modules/pipeline/endpoints/v2_test.go
  modules/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
Labels: feature, approved

#4852 feat: move i18n file of erda-server from config to apps
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  go.mod
  go.sum
  modules/apps/admin/provider.go
  modules/apps/personal-workbench/i18n/common.yaml
  modules/apps/personal-workbench/i18n/common/common.yaml
  modules/apps/personal-workbench/i18n/cp/common.yaml
  modules/apps/personal-workbench/i18n/cp/scenarios/personal-workbench.yaml
  modules/apps/personal-workbench/i18n/files/common.yaml
  modules/apps/personal-workbench/i18n/files/scenarios/personal-workbench.yaml
  modules/apps/personal-workbench/provider.go
Labels: feature, approved

#4851 fix: Set issue import creator to operator.
  modules/dop/services/issue/import.go
  modules/dop/services/issue/import_test.go
Labels: bugfix

#4858 fix: dop i18n mock caused by infra's upgrade
  go.mod
  go.sum
  modules/dop/provider_test.go
Labels: bugfix, approved

#4859 fix(pipeline): query cron is-existed by transaction session to avoid competing links
  modules/pipeline/endpoints/v2_test.go
  modules/pipeline/providers/cron/cron.service.go
  modules/pipeline/providers/cron/cron.service_test.go
  modules/pipeline/providers/cron/db/define_extra.go
Labels: pipeline, bugfix, approved

#4857 feat: log-service replicas default to 1 for test env
  erda.yml
Labels: msp, feature, approved

#4863 feat: delete history job when create new job for task runtime
  modules/orchestrator/scheduler/executor/plugins/k8s/job.go
Labels: feature, approved

#4864 feat: Update kratos user import.
  modules/core-services/dao/migration.go
  modules/core-services/model/uc_migration.go
  modules/core-services/services/user/user.go
  modules/openapi/api/apis/uc/uc_user_create.go
  pkg/ucauth/kratos.go
  pkg/ucauth/model.go
  pkg/ucauth/user_migration.go
Labels: feature

#4866 fix: select route by option
  modules/hepa/apipolicy/policies/csrf/policy.go
Labels: bugfix

#4868 feat: write to ck use round_robin strategy
  conf/monitor/monitor/monitor.yaml
  conf/monitor/streaming/streaming.yaml
  go.mod
  go.sum
Labels: msp, feature, approved

#4865 fix: dlock failed cause orchestrator panic
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
Labels: orchestrator, bugfix

#4855 refactor: merge cluster-dialer to cluster-manager
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  apistructs/cluster_dialer.go
  apistructs/cluster_dialer_query_ip.go
  bundle/bundle.go
  bundle/cluster_manager.go
  bundle/urls.go
  cmd/cluster-dialer/main.go
  cmd/cluster-manager/main.go
  cmd/core-services/main.go
  cmd/pipeline/bootstrap.yaml
  conf/cluster-agent/cluster-agent.yaml
  conf/cluster-dialer/cluster-dialer.yaml
  conf/cluster-manager/cluster-manager.yaml
  conf/core-services/core-services.yaml
  erda.yml
  modules/cluster/cluster-agent/client/client.go
  modules/cluster/cluster-agent/config/config.go
  modules/cluster/cluster-dialer/provider.go
  modules/cluster/cluster-manager/cluster/apierrors.go
  modules/cluster/cluster-manager/cluster/cluster.go
  modules/cluster/cluster-manager/cluster/cluster.service.go
  modules/cluster/cluster-manager/cluster/provider.go
  modules/cluster/cluster-manager/conf/conf.go
  modules/cluster/cluster-manager/dialer/auth/auth.go
  modules/cluster/cluster-manager/dialer/config/config.go
  modules/cluster/cluster-manager/dialer/server/client_data.go
  modules/cluster/cluster-manager/dialer/server/client_data_test.go
  modules/cluster/cluster-manager/dialer/server/dialer_test.go
  modules/cluster/cluster-manager/dialer/server/tunnel-server.go
  modules/cluster/cluster-manager/dialer/server/tunnel-server_test.go
  modules/cluster/cluster-manager/initialize.go
  modules/cluster/cluster-manager/provider.go
  modules/cluster/cluster-manager/services/cluster/cluster.go
  modules/cluster/cluster-ops/provider.go
  modules/cmp/impl/clusters/add_edge_cluster.go
  modules/core-services/endpoints/organization.go
  modules/core-services/initialize.go
  modules/core-services/services/org/org.go
  modules/orchestrator/scheduler/executor/util/util.go
  modules/pipeline/providers/edgepipeline/provider.go
  modules/pipeline/providers/edgepipeline_register/interface.go
  modules/pipeline/providers/edgepipeline_register/interface_test.go
  modules/pipeline/providers/edgepipeline_register/mock.go
  modules/pipeline/providers/edgepipeline_register/provider.go
  modules/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  pipeline.yml
  pkg/clusterdialer/dialer.go
  pkg/clusterdialer/dialer_test.go
  pkg/clusterdialer/tunnel_session.go
  pkg/discover/address.go
  pkg/http/customhttp/request.go
  pkg/http/customhttp/request_test.go
  pkg/parser/diceyml/diceyml_test.go
  quick-start/docker-compose.yml
  quick-start/env
Labels: refactor

#4869 fix: polish: extensionVersion sql
  modules/dicehub/extension/db/extension.go
Labels: bugfix

#4873 fix: delete dependence of ClusterService in core-services
  modules/core-services/provider.go
Labels: bugfix, approved

#4870 feat(pipeline): pipeline-yml-graph get `disable` field from frontendAction
  pkg/parser/pipelineyml/graph_pipelineyml.go
Labels: pipeline, feature, approved

#4878 chore: update pr lint
  .github/prlint.json
Labels: approved

#4875 fix: add port in cluster manager endpoint in dialer
  modules/cluster/cluster-manager/dialer/server/dialer_test.go
  pkg/clusterdialer/dialer.go
  pkg/clusterdialer/dialer_test.go
  pkg/http/customhttp/request.go
  pkg/http/customhttp/request_test.go
Labels: bugfix, approved

#4876 feat: dice_notify_histories add column index
  .erda/migrations/cmdb/20220517-notify-histories-add-index.sql
Labels: feature, approved

#4880 fix(pipeline): precheck skip disabled task
  modules/pipeline/precheck/precheck.go
  modules/pipeline/services/pipelinesvc/precheck.go
  modules/pipeline/services/pipelinesvc/precheck_test.go
Labels: pipeline, bugfix, approved

#4829 feat(gittar,dop): The DOP issue module supports devflow
  .erda/migrations/dop/202200511-issue-relation.sql
  api/proto-go/all.go
  api/proto-go/apps/devflow/flow/client/client.go
  api/proto-go/apps/devflow/flow/client/provider.go
  api/proto-go/apps/devflow/flow/pb/flow.form.pb.go
  api/proto-go/apps/devflow/flow/pb/flow.http.pb.go
  api/proto-go/apps/devflow/flow/pb/flow.json.pb.go
  api/proto-go/apps/devflow/flow/pb/flow.pb.go
  api/proto-go/apps/devflow/flow/pb/flow.validator.pb.go
  api/proto-go/apps/devflow/flow/pb/flow_grpc.pb.go
  api/proto-go/apps/devflow/flow/pb/register.services.pb.go
  api/proto-go/apps/devflow/issuerelation/client/client.go
  api/proto-go/apps/devflow/issuerelation/client/provider.go
  api/proto-go/apps/devflow/issuerelation/pb/issuerelation.form.pb.go
  api/proto-go/apps/devflow/issuerelation/pb/issuerelation.http.pb.go
  api/proto-go/apps/devflow/issuerelation/pb/issuerelation.json.pb.go
  api/proto-go/apps/devflow/issuerelation/pb/issuerelation.pb.go
  api/proto-go/apps/devflow/issuerelation/pb/issuerelation.validator.pb.go
  api/proto-go/apps/devflow/issuerelation/pb/issuerelation_grpc.pb.go
  api/proto-go/apps/devflow/issuerelation/pb/register.services.pb.go
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto/apps/devflow/flow/flow.proto
  api/proto/apps/devflow/issuerelation/issuerelation.proto
  apistructs/gittar.go
  apistructs/gittar_test.go
  bundle/gittar.go
  cmd/dop/main.go
  conf/dop/dop.yaml
  go.sum
  modules/apps/devflow/flow/api_test.http
  modules/apps/devflow/flow/flow.service.go
  modules/apps/devflow/flow/provider.go
  modules/apps/devflow/issuerelation/db/client.go
  modules/apps/devflow/issuerelation/db/define.go
  modules/apps/devflow/issuerelation/issue.relation.service.go
  modules/apps/devflow/issuerelation/provider.go
  modules/dop/initialize.go
  modules/dop/provider.go
  modules/gittar/api/merge.go
  modules/gittar/models/merge_request.go
  pkg/parser/pipelineyml/pipelineyml.go
  pkg/parser/pipelineyml/pipelineyml_test.go
Labels: dop, feature, gittar

#4867 fix: panic when history job list less than 2
  modules/orchestrator/scheduler/executor/plugins/k8s/job.go
  modules/orchestrator/scheduler/executor/plugins/k8s/job_test.go
Labels: bugfix, approved

#4877 feat: Add soft deleted at and index in audit table.
  .erda/migrations/cmdb/20220517-audit-deleted-at.sql
  .erda/migrations/config.yml
  modules/core-services/dao/audit.go
  modules/core-services/model/audit.go
Labels: feature

#4885 feat: index rollover in max_age
  conf/monitor/streaming/index_rollover.json
Labels: msp

#4882 fix: return error if cluster-manager ip not found for clusterkey
  modules/cluster/cluster-manager/dialer/server/tunnel-server.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4884 fix: add cluster-manager connect path to openapi
  conf/cluster-agent/cluster-agent.yaml
  modules/openapi/api/apis/cluster_manager/connect.go
Labels: bugfix

#4887 ci: add name field for ci
  .erda/pipelines/ci-deploy.yml
Labels: approved

#4888 fix: add replica of cluster-manager
  erda.yml
Labels: bugfix

#4886 feat(dop): gittar merge request table add field join_temp_branch_status
  .erda/migrations/gittar/20220518-gittar-merge-join-branch-status.sql
Labels: dop, feature, gittar

#4892 fix: fix datetime default value on mysql 8.0
  .erda/migrations/dicehub/20220510-opus.sql
  modules/apps/gallery/handler/funcs.go
  modules/apps/gallery/handler/funcs_test.go
  modules/apps/gallery/handler/gallery.go
Labels: bugfix

#4893 fix: build monitor agent-injector
  build/dockerfiles/agent-injector/Dockerfile
  erda.yml
Labels: bugfix, approved

#4894 fix: build cluster-agent
  build/dockerfiles/cluster-agent/Dockerfile
Labels: bugfix, approved

#4895 fix: add quotation marks for time type format
  pkg/mock/mock_test.go
  pkg/mock/time.go
Labels: bugfix, approved

#4897 fix: no need limit the query start time bound
  modules/msp/apm/log-service/query/log.service.search.go
Labels: msp, bugfix, approved

#4900 feat: load root .env file
  build/scripts/build_all/app_handler.sh
  pkg/common/common.go
  pkg/common/common_test.go
  pkg/common/testdata/.env
Labels: feature, approved

#4902 chore: polish Makefile
  .gitignore
  Makefile
Labels: approved

#4905 feat(dop): devflowrule type adjustment
  apistructs/devflowrule.go
  apistructs/devflowrule_test.go
  modules/dop/providers/devflowrule/devflowrule.service.go
Labels: dop, feature, approved

#4907 fix: Makefile: prepare before tidy
  Makefile
Labels: bugfix, approved

#4904 feat(dop): When querying the task workflow, the merged MR is displayed
  modules/apps/devflow/flow/flow.service.go
Labels: dop, feature, approved

#4906 fix: i18n render and paging error
  modules/apps/gallery/dao/option.go
  modules/apps/gallery/dao/tx.go
  modules/apps/gallery/handler/funcs.go
  modules/apps/gallery/handler/funcs_test.go
  modules/apps/gallery/handler/gallery.go
  modules/apps/gallery/provider.go
Labels: bugfix

#4909 feat(pipeline): Total action count does not include disabled
  modules/pipeline/providers/run/run.go
  pkg/parser/pipelineyml/define.go
  pkg/parser/pipelineyml/define_test.go
Labels: pipeline, feature, approved

#4910 fix: cassandra logstore compatibility fix
  modules/core/monitor/log/persist/v1/consumer.go
  modules/core/monitor/log/persist/v1/consumer_test.go
Labels: bugfix

#4901 fix: hide gallery button
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4903 feat(dop): Supports automatic creation of pipelines
  api/proto-go/dop/projectpipeline/client/client.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.http.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.json.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.validator.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline_grpc.pb.go
  api/proto/dop/projectpipeline/projectpipeline.proto
  apistructs/header.go
  apistructs/pipeline.go
  apistructs/pipeline_yml.go
  modules/dop/initialize.go
  modules/dop/providers/guide/guide.service.go
  modules/dop/providers/projectpipeline/deftype/create.go
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/dop/providers/projectpipeline/service_impl_test.go
  modules/dop/services/pipeline/pipeline.go
  modules/gittar/helper/git_hooks.go
  modules/messenger/eventbox/subscriber/http/http.go
  pkg/parser/pipelineyml/define.go
  pkg/parser/pipelineyml/define_test.go
Labels: dop, feature, approved

#4913 feat(dop): Workflow api interface returns workflow without permission
  api/proto-go/apps/devflow/flow/pb/flow.form.pb.go
  api/proto-go/apps/devflow/flow/pb/flow.pb.go
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto/apps/devflow/flow/flow.proto
  bundle/app.go
  go.sum
  modules/apps/devflow/flow/flow.service.go
  modules/dop/initialize.go
  modules/dop/providers/devflowrule/devflowrule.service.go
  pkg/limit_sync_group/work.go
Labels: dop, feature, approved

#4915 feat: i18n of tracing module
  cmd/msp/conf/i18n/msp-i18n.yaml
Labels: msp, feature, approved

#4914 fix(core-services): Solve the panic problem
  modules/messenger/eventbox/subscriber/http/http.go
  modules/messenger/eventbox/subscriber/http/http_test.go
Labels: bugfix

#4908 feat: Issue type ticket in issue manage scenario.
  modules/dop/component-protocol/components/issue-manage/issueTable/render.go
  modules/dop/services/issuestate/issuestate.go
  modules/dop/services/issuestate/issuestate_test.go
  providers/component-protocol/issueFilter/conditions.go
  providers/component-protocol/issueFilter/in_params.go
  providers/component-protocol/issueFilter/provider.go
Labels: feature, approved

#4916 feat: check permission in runtime list
  cmd/dop/conf/i18n/cp/scenarios/project-runtime.yaml
  modules/dop/component-protocol/components/app-runtime/list/list.go
  modules/dop/component-protocol/components/app-runtime/list/list_test.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
  modules/dop/component-protocol/components/project-runtime/list/list_test.go
Labels: feature

#4919 feat: to consider that alter table name in alter permission lint
  pkg/database/sqlparser/migrator/scripts.go
  pkg/database/sqlparser/testdata/alter_permission_test_data3/service_a/318-1.sql
Labels: feature, install

#4918 fix(dop): export autotest failure due to `file_name` length
  .erda/migrations/qa/20220520-file-record-name-length.sql
Labels: dop, bugfix, approved

#4872 feat: text optimization
  .erda/migrations/msp/20220516-menu.sql
  cmd/monitor/monitor/conf/charts/report.yml
  cmd/monitor/monitor/conf/i18n/charts.yml
  cmd/msp/conf/i18n/cp/msp-alert-event-detail.yaml
  cmd/msp/conf/i18n/cp/msp-alert-event-list.yaml
  cmd/msp/conf/i18n/cp/msp-alert-overview.yaml
  cmd/msp/conf/i18n/cp/msp-notify-detail.yaml
  cmd/msp/conf/i18n/cp/msp-notify-list.yaml
  cmd/msp/conf/i18n/msp-i18n.yaml
Labels: feature, approved

#4925 revert: add quotation marks for time type format (#4895)
  pkg/mock/mock_test.go
  pkg/mock/time.go
Labels: approved

#4926 fix: add erda-server env
  pkg/discover/address.go
Labels: bugfix

#4923 fix: fix api test query log failed from cassandra
  modules/core/monitor/log/storage/cassandra/iterator.go
  modules/core/monitor/log/storage/cassandra/iterator_test.go
Labels: msp, bugfix

#4929 fix: skip putting on private extension
  modules/dicehub/extension/extention.service.go
  modules/dicehub/extension/extention.service_test.go
Labels: bugfix

#4930 fix: trace service name
  pkg/common/common.go
  pkg/common/common_test.go
  pkg/common/entrance/entrance.go
  pkg/common/entrance/entrance_test.go
  pkg/common/trace/trace.go
Labels: bugfix, approved

#4933 fix: put on public extension
  modules/dicehub/extension/extention.service.go
Labels: bugfix

#4937 feat: support gen proto-go in local and ci
  Makefile
  api/proto-go/Makefile
  api/proto-go/go.mod
  api/proto-go/go.sum
  go.mod
  go.sum
Labels: feature, approved

#4940 fix: update cache synchronously
  pkg/cache/cache.go
  pkg/clusterdialer/dialer.go
  pkg/http/customhttp/request.go
Labels: bugfix

#4922 feat(dop,pipeline): Project pipeline support appID defined in InParams
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto/core/pipeline/definition/definition.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/inparams.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition_test.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider_test.go
  modules/dop/providers/projectpipeline/deftype/list.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/dop/providers/projectpipeline/service_impl_test.go
  modules/pipeline/providers/definition/db/define.go
Labels: dop, pipeline, feature, approved

#4942 feat: enable put on/off in release list; add i18n for gallery
  api/proto-go/apps/gallery/pb/gallery.form.pb.go
  api/proto-go/apps/gallery/pb/gallery.pb.go
  api/proto/apps/gallery/gallery.proto
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/conf/i18n/gallery.yaml
  modules/apps/gallery/handler/funcs.go
  modules/apps/gallery/handler/funcs_test.go
  modules/apps/gallery/handler/gallery.go
  modules/apps/gallery/provider.go
  modules/apps/gallery/types/gallery.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: feature

#4943 chore: remove proto-go of gallery
  api/proto-go/apps/gallery/pb/gallery.form.pb.go
  api/proto-go/apps/gallery/pb/gallery.pb.go
Labels: approved

#4951 feat: fill `cluster_name` field for pipeline cron table
  .erda/migrations/pipeline/20220525-pipeline-cron-add-cluster-name.sql
  .erda/migrations/pipeline/20220526-fill-cluster-name-for-cron.py
  .erda/migrations/pipeline/requirements.txt
  api/proto/core/pipeline/cron/cron.proto
  api/proto/core/pipeline/cron_pub.proto
  apistructs/pipeline_cron.go
  modules/pipeline/providers/cron/cron.service.go
  modules/pipeline/providers/cron/db/define.go
  modules/pipeline/providers/cron/db/define_extra.go
Labels: feature, approved

#4945 feat(dop): remove appCondition and default branch in app pipeline page
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition_test.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider_test.go
Labels: dop, feature, approved

#4947 fix: fix Internationalized text error
  cmd/monitor/monitor/conf/i18n/alert.yml
  cmd/msp/conf/i18n/cp/msp-notify-list.yaml
  cmd/msp/conf/i18n/msp-i18n.yaml
  modules/core/monitor/metric/meta.go
Labels: bugfix, approved

#4959 fix: escape sql string
  modules/core/monitor/log/storage/clickhouse/query_parser/query_parser.go
  modules/core/monitor/log/storage/clickhouse/query_parser/query_parser_test.go
Labels: msp, bugfix, approved

#4957 fix: reutrn null if opus is null
  api/proto/core/dicehub/release/release.proto
  modules/dicehub/release/release.go
  modules/dicehub/release/release.service.go
  modules/dicehub/release/release_test.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4955 fix: Fix project-level app query in app permission.
  modules/core-services/services/security/process.go
Labels: bugfix, approved

#4962 fix: release list i18n
  cmd/dop/conf/i18n/cp/scenarios/release-manage.yaml
Labels: bugfix

#4965 fix: escape es query string
  modules/core/monitor/log/storage/elasticsearch/iterator.go
Labels: msp, bugfix

#4964 fix: dailer unit test
  modules/cluster/cluster-manager/dialer/server/dialer_test.go
  modules/cluster/cluster-manager/dialer/server/tunnel-server_test.go
Labels: bugfix

#4949 chore: separate go test to several jobs
  .github/workflows/ci-it.yml
  .gitignore
  modules/cluster/cluster-manager/dialer/server/tunnel-server_test.go
  modules/hepa/cache/org/org_test.go
  pkg/cache/cache_test.go
  pkg/database/sqlparser/pygrator/package.go
  pkg/xmind/examples/xmind/a.xmind
  pkg/xmind/xml_test.go
Labels: approved

#4944 feat(hepa): sbac (Server Based Access Control) policy
  modules/hepa/apipolicy/policies/sbac/policy.go
  modules/hepa/apipolicy/policies/sbac/policy_test.go
  modules/hepa/services/api_policy/impl/impl.go
  modules/hepa/services/api_policy/impl/register.go
  pkg/cache/cache.go
  pkg/clusterdialer/dialer.go
  pkg/http/customhttp/request.go
Labels: hepa, feature

#4970 feat: only do code check if go files changed
  .github/workflows/ci-it-noneed.yml
  .github/workflows/ci-it.yml
  .github/workflows/license.yml
Labels: feature, approved

#4971 fix: use changed-files action to handle push event
  .github/workflows/ci-it-noneed.yml
Labels: bugfix, approved

#4973 fix(dialer): unit test timeout error
  modules/cluster/cluster-manager/dialer/server/dialer_test.go
  modules/cluster/cluster-manager/dialer/server/tunnel-server_test.go
Labels: cluster-manager, bugfix, approved

#4972 chore: check codecov.yml for non-go
  .github/workflows/ci-it-noneed.yml
  .github/workflows/ci-it.yml
  pkg/mimetype/mime_test.go
Labels: approved

#4948 feat: bundle monitor migration to grpc
  bundle/monitor.go
  cmd/msp/bootstrap.yaml
  cmd/msp/main.go
  modules/core/monitor/alert/alert-apis/audit.go
  modules/core/monitor/alert/alert-apis/audit_test.go
  modules/core/monitor/alert/alert-apis/provider.go
  modules/msp/apm/alert/audit.go
  modules/msp/apm/alert/audit_test.go
  modules/msp/apm/alert/provider.go
  modules/msp/resource/deploy/handlers/monitor/monitor.go
  modules/msp/resource/deploy/handlers/monitor/provider.go
  modules/openapi/api/apis/monitor/monitor_orgs_alert_create.go
  modules/openapi/api/apis/monitor/monitor_orgs_alert_switch.go
  modules/openapi/api/apis/monitor/monitor_orgs_customize_alert_create.go
  modules/openapi/api/apis/monitor/monitor_orgs_customize_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_create.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_delete.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/apm_alert_update.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_delete.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_switch.go
  modules/openapi/api/apis/msp/apm/alert/apm_customize_alert_update.go
Labels: feature, approved

#4861 feat: Tracing query by clickhouse storage
  cmd/msp/bootstrap.yaml
  modules/msp/apm/trace/query/components/trace-query/req_distribution/provider.go
  modules/msp/apm/trace/query/provider.go
  modules/msp/apm/trace/query/source/cassandra_source.go
  modules/msp/apm/trace/query/source/clickhouse_source.go
  modules/msp/apm/trace/query/source/clickhouse_source_test.go
  modules/msp/apm/trace/query/source/elasticsearch_source.go
  modules/msp/apm/trace/query/source/elasticsearch_source_test.go
  modules/msp/apm/trace/query/source/source.go
  modules/msp/apm/trace/query/trace.service.go
  modules/msp/apm/trace/query/trace.service_test.go
Labels: feature, approved

#4963 feat(dop,pipeline): pipeline exec list support to view all apps in project
  apistructs/pipeline.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/common/commom.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/common/gshelper/helper.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider_test.go
  modules/dop/providers/projectpipeline/deftype/list_exec_history.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/dbclient/op_pipeline.go
Labels: dop, pipeline, feature

#4969 fix(dop): delete guide webhook
  apistructs/webhook.go
  bundle/events.go
  modules/dop/initialize.go
  modules/dop/initialize_test.go
Labels: dop, bugfix
