Repository erda-project/erda, pull requests merged in 2022-03, with the labels that each got.

#4190 fix: search release by version or releaseID
  conf/dop/i18n/cp/scenarios/release-manage.yaml
  modules/dicehub/release/db/release.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4173 feat(dop,gittar): update preReceiveHook and add create pipeline link to remote
  modules/gittar/helper/git_cmd.go
  modules/gittar/helper/git_cmd_test.go
  modules/gittar/helper/git_protocol.go
  modules/gittar/models/push_event.go
Labels: dop, feature, approved, gittar

#4192 fix: deployment order panic error
  modules/orchestrator/services/deployment_order/deployment_order_cron.go
  modules/orchestrator/services/deployment_order/deployment_order_cron_test.go
  modules/orchestrator/services/deployment_order/deployment_order_release_test.go
Labels: orchestrator, bugfix

#4193 fix: bad mysql addon password decryption
  modules/orchestrator/components/addon/mysql/mysql.service.go
  modules/orchestrator/components/addon/mysql/provider.go
Labels: bugfix, approved

#4191 feat: add audit for releaseRule
  apistructs/audits.go
  modules/dicehub/endpoints/endpoints.go
  modules/dicehub/endpoints/release_rule.go
  modules/dicehub/service/apierrors/errors.go
  modules/dicehub/service/release_rule/release_rule.go
  modules/dop/component-protocol/components/release-manage/releaseFilter/render.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: feature

#4179 feat(dop,gittar): Create event box message when new branch is created
  modules/gittar/api/repo.go
  modules/gittar/pkg/gitmodule/repo_branch.go
Labels: dop, feature, approved, gittar

#4208 fix: fix sql difference
  .erda/migrations/.patches/patch-20220121-sp_dashboard_blocks_system.sql
Labels: bugfix, approved

#4207 fix: release branch sem version
  modules/dicehub/endpoints/release.go
  modules/dicehub/endpoints/release_test.go
  modules/dicehub/release/release.service.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix, approved

#4211 chore: bump version
  VERSION
Labels: approved

#4212 chore: start 2.1
  VERSION
Labels: approved

#4213 fix: release changelog and pageNo
  api/proto-go/core/dicehub/release/pb/release.form.pb.go
  api/proto-go/core/dicehub/release/pb/release.http.pb.go
  api/proto-go/core/dicehub/release/pb/release.pb.go
  api/proto/core/dicehub/release/release.proto
  modules/dicehub/release/db/release.go
  modules/dicehub/release/release.service.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/orchestrator/endpoints/runtime.go
Labels: bugfix, approved

#4184 fix: log-service conf
  conf/monitor/log-service/log-service.yaml
Labels: msp, bugfix

#4182 feat: index loader support tenant size
  modules/core/monitor/storekit/elasticsearch/index/loader/routes.go
  modules/core/monitor/storekit/elasticsearch/index/loader/routes_test.go
Labels: feature

#4189 fix(cp-project): add init url
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4215 feat(cp-app): add app deploy component protocol
  conf/dop/i18n/cp/scenarios/app-runtime.yaml
  conf/openapi/openapi.yaml
  modules/dop/component-protocol/components/app-runtime/cleanData/model.go
  modules/dop/component-protocol/components/app-runtime/cleanData/render.go
  modules/dop/component-protocol/components/app-runtime/common/common.go
  modules/dop/component-protocol/components/app-runtime/common/common_test.go
  modules/dop/component-protocol/components/app-runtime/list/list.go
  modules/dop/component-protocol/components/app-runtime/list/list_test.go
  modules/dop/component-protocol/components/app-runtime/page/page.go
  modules/dop/component-protocol/components/app-runtime/scenario.go
  modules/dop/component-protocol/scenarios/app-runtime.yml
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/endpoints/runtime.go
  modules/orchestrator/services/runtime/runtime.go
Labels: dop, feature

#4224 fix: change branch to branchName in list release api
  api/proto-go/core/dicehub/release/pb/release.http.pb.go
  api/proto-go/core/dicehub/release/pb/release.pb.go
  api/proto/core/dicehub/release/release.proto
Labels: bugfix, approved

#4226 fix: fsm request scheduler update servicegroup remove loop
  modules/orchestrator/services/deployment/deployment_context.go
Labels: bugfix

#4227 fix(cp-project): filter by name
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4223 fix: add vms target in customize alert rule
  modules/core/monitor/alert/alert-apis/adapt/expression.go
Labels: bugfix, approved

#4195 fix(eventbox): add json tag for cluster name
  apistructs/notify_history.go
Labels: bugfix, approved

#4218 feat: Batch create issue relations, get issue relations by all types
  apistructs/issue_related.go
  modules/dop/dao/issue.go
  modules/dop/dao/issue_issue_relation.go
  modules/dop/endpoints/issue_related.go
  modules/dop/services/issuerelated/issue_related.go
Labels: feature, approved

#4222 fix(dop): dop remove workspace label
  modules/dop/services/pipeline/pipeline.go
Labels: dop, bugfix

#4202 feat(core-services): add sonar config for application
  .erda/migrations/cmdb/20220301-sonar-config.sql
  apistructs/application.go
  apistructs/sonar.go
  apistructs/sonar_test.go
  modules/core-services/endpoints/application.go
  modules/core-services/model/application.go
  modules/core-services/services/application/appliation.go
Labels: feature

#4231 fix(cp-app): count runtime by app
  modules/orchestrator/endpoints/runtime.go
Labels: bugfix

#4236 feat(gittar): Add a create pipeline link to the push remote information
  modules/gittar/auth/auth.go
  modules/gittar/helper/git_cmd.go
  modules/gittar/pkg/gitmodule/repo.go
Labels: feature, approved, gittar

#4243 fix(cp-dc): get list state when initializing
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4247 fix(cp-deploy): init param of page
  modules/dop/component-protocol/components/app-runtime/advanceFilter/advanceFilter.go
  modules/dop/component-protocol/components/app-runtime/list/list.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4241 fix: fix the bug of eventbox null pointer exception
  conf/eventbox/eventbox.yaml
  modules/eventbox/subscriber/common.go
  modules/eventbox/subscriber/dingding/dingding.go
  modules/eventbox/subscriber/dingtalk_worknotice/dingtalk_worknotice.go
  modules/eventbox/subscriber/email/email.go
  modules/eventbox/subscriber/mbox/mbox.go
  modules/eventbox/subscriber/sms/sms.go
  modules/eventbox/subscriber/vms/vms.go
Labels: approved

#4244 feat: Support jvm process cpu
  conf/monitor/monitor/metricmeta/groups/micro_service.yml
  conf/monitor/monitor/metricmeta/i18n/_group.yml
Labels: monitor-stack, feature, approved

#4240 feat(dop): project pipeline Hide the delete button without permission
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, feature, approved

#4238 fix: Handle fixed iteration value in issue gantt filter operation
  modules/dop/component-protocol/components/issue-gantt/filter/provider.go
Labels: bugfix, approved

#4254 fix: eventbox save notify history is nil pointer dereference
  modules/eventbox/subscriber/common.go
  modules/eventbox/subscriber/dingding/dingding.go
  modules/eventbox/subscriber/dingtalk_worknotice/dingtalk_worknotice.go
  modules/eventbox/subscriber/email/email.go
  modules/eventbox/subscriber/mbox/mbox.go
  modules/eventbox/subscriber/sms/sms.go
  modules/eventbox/subscriber/vms/vms.go
Labels: bugfix, approved

#4256 fix(gittar): Solve the problem of incorrect branch name when sending git push event
  modules/gittar/api/repo.go
Labels: bugfix, approved, gittar

#4255 fix(cp-app): change app target
  modules/dop/component-protocol/components/app-runtime/list/list.go
  modules/dop/component-protocol/components/app-runtime/list/list_test.go
Labels: bugfix

#4206 feat: Approval management setup in personal workstation
  apistructs/manual_review.go
  bundle/review.go
  conf/admin/i18n/cp/scenarios/personal-workbench.yaml
  modules/admin/component-protocol/components/personal-workbench/messageList/approval.go
  modules/admin/component-protocol/components/personal-workbench/messageList/messageList.go
  modules/admin/component-protocol/components/personal-workbench/messageTabs/messageTabs.go
  modules/core-services/services/manual_review/manual_review.go
  pkg/arrays/arrays.go
Labels: feature, approved

#4259 fix(cp-deploy): init page params
  modules/dop/component-protocol/components/app-runtime/list/list.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: bugfix

#4262 fix: eventbox close errsCh
  modules/eventbox/dispatcher/filters/lastfilter.go
Labels: bugfix, approved

#4263 fix: eventbox close errsCh
  modules/eventbox/dispatcher/filters/lastfilter.go
Labels: bugfix, approved

#4260 fix(orchestrator): Modify the error of 'xxx not found' check
  modules/orchestrator/initialize.go
Labels: orchestrator, bugfix, approved

#4268 fix: remove some useless code
  modules/admin/component-protocol/components/personal-workbench/workList/provider.go
  modules/extensions/loghub/sls-import/product_rds.go
  modules/openapi/component-protocol/scenarios/home-page-content/components/title/render.go
Labels: bugfix

#4239 feat(dop): project pipeline decide whether to turn on or off the cron button according to the yml cron expression
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: dop, feature, approved

#4269 refactor(cp-project): add all involved app name in filter
  conf/dop/i18n/cp/scenarios/project-runtime.yaml
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
  modules/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter_test.go
  modules/dop/component-protocol/components/project-runtime/common/common.go
  modules/dop/component-protocol/components/project-runtime/list/list.go
Labels: refactor

#4270 fix: unrecover alert exclude disabled alert ids
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/core/monitor/alert/alert-apis/db/alert.go
  modules/core/monitor/alert/alert-apis/db/alert_event.go
  modules/core/monitor/alert/jobs/unrecover-alerts/provider.go
  modules/msp/apm/log-service/query/log.service.search.go
Labels: msp, bugfix

#4267 feat: Increase size of test case desc column, add length validation
  .erda/migrations/config.yml
  .erda/migrations/qa/20220305-testcase-desc-length.sql
  apistructs/testcase.go
  modules/dop/services/testcase/create.go
  modules/dop/services/testcase/update.go
Labels: feature, approved

#4266 fix: Fix issue gantt parent query without matched children
  modules/dop/dao/issue.go
Labels: bugfix, approved

#4274 fix: log query limit size to 10000
  modules/msp/apm/log-service/query/log.service.search.go
Labels: msp, bugfix, approved

#4273 fix(dop): When the pipeline is GC, if the definition is bound to the pipeline_ ID does not perform GC operations
  modules/pipeline/dbclient/op_pipeline_definition.go
  modules/pipeline/pipengine/reconciler/dbgc.go
Labels: dop, bugfix, approved

#4277 fix: truncate failed task logs
  modules/dop/services/cdp/cdp.go
Labels: bugfix

#4278 fix: Revert fix set volume without storage, set default volume type
  modules/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  modules/orchestrator/services/deployment/deployment_context.go
  pkg/k8s/storage/detect_sc.go
  pkg/k8s/storage/detect_sc_test.go
Labels: bugfix, approved

#4280 fix: Fix issue relation repeat existence validation
  modules/dop/dao/issue_issue_relation.go
Labels: bugfix, approved

#4281 fix: allow share same cluster between diff org for log-service a…
  modules/msp/resource/deploy/handlers/logservice/logservice.go
Labels: msp, bugfix

#4283 feat(openapi): Automatic test plan execution list hidden refresh button
  modules/openapi/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
Labels: feature, openapi, approved

#4257 feat(pipeline): pipeline support action custom eci
  apistructs/extension_test.go
  apistructs/extention.go
  bundle/dicehub.go
  modules/dicehub/endpoints/extention.go
  modules/pipeline/conf/conf.go
  modules/pipeline/pkg/container_provider/container_instance_provider.go
  modules/pipeline/pkg/container_provider/container_provider_test.go
  modules/pipeline/services/extmarketsvc/define.go
  modules/pipeline/services/extmarketsvc/list.go
  modules/pipeline/services/pipelinesvc/create_v2.go
  modules/pipeline/services/pipelinesvc/create_v2_test.go
Labels: pipeline, feature, approved

#4275 fix(dop,pipeline): Solve the problem that the data is incorrect after the execution of the cron pipeline
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/services/pipelinesvc/run.go
  pkg/parser/pipelineyml/define.go
Labels: dop, pipeline, bugfix, approved

#4287 feat: adjust ECI Pod fluent-bit sidecar container Env
  modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
Labels: feature

#4286 refactor: use standard RFC4122 form of uuid with hyphens
  modules/dicehub/service/release_rule/release_rule.go
  modules/dop/services/apidocsvc/ws_upgrade.go
  modules/eventbox/webhook/impl.go
  modules/orchestrator/scheduler/impl/job/job.go
  modules/orchestrator/scheduler/impl/volume/volume.go
  modules/orchestrator/scheduler/impl/volume/volume_test.go
  modules/pipeline/providers/definition/pipeline_definition.go
  modules/pipeline/providers/source/db/source.go
  pkg/crypto/uuid/uuid.go
  pkg/crypto/uuid/uuid_test.go
Labels: refactor

#4291 fix: go short version error
  Makefile
Labels: bugfix, approved

#4292 fix: multiple latest release in one git branch
  modules/dicehub/release/release.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4288 fix(pipeline): add `terminus_define_tag` annotation on k8sjob flink spark
  apistructs/pipeline_task.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/util.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
  modules/pipeline/pkg/containers/task_container.go
Labels: pipeline, bugfix, approved

#4293 fix: spark and flink job on eci, sc specified error
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
Labels: pipeline, bugfix

#4296 fix(pipeline): optimization of pipeline k8s executor initialization
  modules/pipeline/conf/conf.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/type.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob_test.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/type.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
  modules/pipeline/pkg/clusterinfo/clusterinfo.go
Labels: pipeline, bugfix, approved

#4303 fix: notify filter to do internationalization
  conf/msp/i18n/cp/msp-notify-list.yaml
  modules/msp/apm/alert/components/msp-notify-list/configurableFilter/provider.go
Labels: bugfix, approved

#4297 fix(dop): Project pipeline executor search problem repair
  apistructs/labels.go
  modules/dop/providers/projectpipeline/service_impl.go
Labels: dop, bugfix, approved

#4299 feat: support comstom date format
  pkg/mock/mock_test.go
  pkg/mock/time.go
Labels: pipeline, feature, approved

#4304 fix: i18n of alert list
  conf/msp/i18n/cp/msp-alert-event-list.yaml
  modules/msp/apm/alert/components/msp-alert-event-list/configurableFilter/provider.go
Labels: msp, bugfix

#4308 fix: add formal tag for formal release
  conf/dop/i18n/cp/scenarios/release-manage.yaml
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix, approved

#4309 fix: avoid nil reference panic on invalid span-metric data
  modules/msp/apm/trace/persist/consume.go
Labels: msp, bugfix, approved

#4301 fix(dop): OpenAPI search action spec close ymlformat
  modules/openapi/component-protocol/scenarios/action/components/actionForm/action_form.go
Labels: dop, bugfix

#4307 fix(pipeline): idempotent create pvc
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sflink/flink.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugins/k8sspark/k8sspark.go
Labels: pipeline, bugfix, approved

#4311 fix: display NaN% when total number of pod is 0
  modules/cmp/component-protocol/components/cmp-dashboard-pods/podsCharts/render.go
Labels: bugfix, approved

#4302 fix: rm needless fmt
  pkg/database/sqllint/linters/base.go
Labels: bugfix, approved

#4312 fix: pointer mistake bugfix
  modules/oap/collector/common/util_test.go
  modules/oap/collector/core/model/odata/buffer_test.go
  modules/oap/collector/plugins/exporters/kafka/provider.go
  modules/oap/collector/plugins/receivers/collector/post.http
Labels: bugfix

#4313 fix: remove false option in release aggregate operation
  modules/dop/component-protocol/components/release-manage/releaseFilter/provider.go
Labels: bugfix, approved

#4317 chore: set pipeline replicas default to 2
  erda.yml
Labels: approved

#4314 feat: add addons in get project release response
  api/proto-go/core/dicehub/release/pb/release.form.pb.go
  api/proto-go/core/dicehub/release/pb/release.json.pb.go
  api/proto-go/core/dicehub/release/pb/release.pb.go
  api/proto-go/core/dicehub/release/pb/release.validator.pb.go
  api/proto/core/dicehub/release/release.proto
  modules/dicehub/release/provider.go
  modules/dicehub/release/release.service.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: feature, approved

#4321 refactor(dop): Remove setid of automated test scenes stages__urlquery and sceneid__urlquery state
  modules/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileConfig/scenesSetConfig/scenesStages/model.go
Labels: dop, refactor, approved

#4306 refactor(orchestrator): check quota
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  modules/orchestrator/scheduler/executor/plugins/k8s/nodelabel.go
  modules/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
Labels: orchestrator, refactor, approved

#4324 fix: alig the release list
  modules/dop/component-protocol/components/release-manage/releaseTable/model.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render_test.go
Labels: bugfix, approved

#4322 fix(dop): add customerFilter rendering to pipeline exec list
  modules/dop/component-protocol/scenarios/project-pipeline-exec-list.yml
Labels: dop, bugfix, approved

#4327 feat: need not delete ingress if the zone dose not hava ingress
  modules/hepa/repository/orm/gateway_zone.go
  modules/hepa/repository/orm/gateway_zone_test.go
  modules/hepa/services/zone/impl/impl.go
Labels: approved

#4328 feat: delete LogMode
  modules/core/monitor/alert/alert-apis/db/alert_expression.go
  modules/core/monitor/expression/expression.service.go
Labels: msp, feature, bugfix, approved

#4335 fix: check project access if appliction was deleted when write release
  modules/dicehub/endpoints/release.go
  modules/dicehub/release/release.service.go
  modules/dop/component-protocol/components/release-manage/access/check.go
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4336 fix: modify metric expression
  conf/monitor/monitor/analyzer/metrics/apm/application_cache_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_db_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_http_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_mq_service.json
  conf/monitor/monitor/analyzer/metrics/apm/application_rpc_service.json
  conf/monitor/monitor/analyzer/metrics/apm/jvm_service_node.json
  conf/monitor/monitor/analyzer/metrics/apm/mobile_register_user_retention.json
  conf/monitor/monitor/analyzer/metrics/apm/nodejs_service_node.json
  conf/monitor/monitor/analyzer/metrics/apm/trace_tags.json
Labels: msp, bugfix, approved

#4334 feat: default 'v1' for kong path handling
  modules/hepa/gateway/assembler/gateway_kong_assembler.go
  modules/hepa/kong/base/kong_adapter.go
  modules/hepa/kong/dto/kong_route_req_dto.go
  modules/hepa/kong/dto/kong_route_req_dto_test.go
  modules/hepa/services/endpoint_api/impl/impl.go
Labels: hepa, feature, approved

#4332 fix(openapi): the manual review action needs to be added with scopeID props
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
Labels: openapi, bugfix

#4331 fix: bugs in project package
  bundle/gittar.go
  bundle/release.go
  modules/dop/services/project/export_package.go
  modules/dop/services/project/import_package.go
  modules/dop/services/project/project_package.go
Labels: bugfix, approved

#4319 feat: build cli in daily pipeline
  pipeline.yml
Labels: feature, approved

#4290 feat: erda-cli
  apistructs/addon.go
  apistructs/api_asset.go
  apistructs/deployment.go
  apistructs/project.go
  apistructs/runtime.go
  go.mod
  go.sum
  pkg/http/httpclient/request.go
  pkg/terminal/table/table.go
  tools/cli/cmd/build.go
  tools/cli/cmd/check.go
  tools/cli/cmd/clone.go
  tools/cli/cmd/create.go
  tools/cli/cmd/extensions.go
  tools/cli/cmd/extensions_pull.go
  tools/cli/cmd/extensions_push.go
  tools/cli/cmd/extensions_retag.go
  tools/cli/cmd/init.go
  tools/cli/cmd/migrate.go
  tools/cli/cmd/migrate_lint.go
  tools/cli/cmd/migrate_mkpy.go
  tools/cli/cmd/migrate_mkpypkg.go
  tools/cli/cmd/migrate_record.go
  tools/cli/cmd/parse.go
  tools/cli/cmd/push.go
  tools/cli/cmd/status.go
  tools/cli/cmd/version.go
  tools/cli/cmd/view.go
  tools/cli/command/command.go
  tools/cli/command/context.go
  tools/cli/command/erda.go
  tools/cli/command/flag.go
  tools/cli/command/generate/generate.go
  tools/cli/command/root_cmd.go
  tools/cli/common/application.go
  tools/cli/common/build.go
  tools/cli/common/cluster.go
  tools/cli/common/org.go
  tools/cli/common/pipeline.go
  tools/cli/common/project.go
  tools/cli/common/record.go
  tools/cli/common/repo.go
  tools/cli/common/runtime.go
  tools/cli/common/workspace.go
  tools/cli/dicedir/dicedir.go
  tools/cli/status/status.go
  tools/cli/utils/dicedir.go
  tools/cli/utils/dicedir_test.go
  tools/cli/utils/erdautils.go
  tools/cli/utils/format.go
  tools/cli/utils/httputils.go
  tools/cli/utils/prettyjson.go
  tools/cli/utils/workspace.go
Labels: feature, approved

#4338 fix: params in application func
  tools/cli/common/application.go
Labels: bugfix, approved

#4326 feat: Approval list is sorted in reverse chronological order
  modules/admin/component-protocol/components/personal-workbench/messageList/approval.go
Labels: feature

#4343 fix(dop): add pipelineTabs rendering to pipeline list
  modules/dop/component-protocol/scenarios/project-pipeline.yml
Labels: dop, bugfix, approved

#4346 fix(pipeline): snippet pipeline task teardown
  modules/pipeline/providers/reconciler/legacy/reconciler/reconcile_data_process.go
Labels: pipeline, bugfix, approved

#4347 fix: unrecover alerts count error
  modules/core/monitor/alert/alert-apis/alert.service.go
  modules/core/monitor/alert/alert-apis/db/alert.go
  modules/core/monitor/alert/alert-apis/db/alert_event.go
  modules/core/monitor/alert/jobs/unrecover-alerts/provider.go
Labels: msp, bugfix, approved

#4341 fix: cp-person change target and param
  modules/admin/component-protocol/components/personal-workbench/common/common.go
  modules/admin/component-protocol/components/personal-workbench/workList/app.go
Labels: bugfix, approved

#4323 feat: pipengine register cluster hook until success when init
  modules/pipeline/providers/engine/provider.go
Labels: feature

#4330 feat: Issue connection changed to unidirectional relation
  modules/dop/dao/issue_issue_relation.go
  modules/dop/endpoints/issue_related.go
  modules/dop/services/issue/issue.go
Labels: feature, approved

#4318 fix(orchestrator): Solve the addon attachment leak problem
  modules/orchestrator/dbclient/addon_attachment.go
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/initialize.go
  modules/orchestrator/services/addon/addon_attachment.go
Labels: orchestrator, bugfix, approved

#4342 fix(orchestrator): addon quota
  modules/orchestrator/scheduler/executor/plugins/k8s/daemonset.go
  modules/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  modules/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
  modules/orchestrator/services/deployment/deployment_context.go
Labels: orchestrator, bugfix, approved

#4350 fix(pipeline): Fix fdp creation pipeline panic problem
  modules/pipeline/initialize.go
  modules/pipeline/services/pipelinesvc/define.go
Labels: pipeline, bugfix, approved

#4349 feat(dop): Scene set supports drag and drop
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/model.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/render.go
  modules/dop/component-protocol/components/auto-test-scenes/leftPage/fileTree/scenes.go
Labels: dop, feature, approved

#4352 feat: Enchance collector
  cmd/monitor/collector/main.go
  cmd/monitor/collector/main_test.go
  conf/monitor/collector/collector-agent.yaml
  conf/monitor/collector/collector.yaml
  conf/monitor/collector/edge/collector.yaml
  go.mod
  modules/oap/collector/common/filter/filter.go
  modules/oap/collector/common/filter/filter_test.go
  modules/oap/collector/core/model/exporter.go
  modules/oap/collector/core/model/filter.go
  modules/oap/collector/core/model/filter_test.go
  modules/oap/collector/core/model/odata/log.go
  modules/oap/collector/core/model/odata/metric.go
  modules/oap/collector/core/model/odata/odata.go
  modules/oap/collector/core/model/odata/raw.go
  modules/oap/collector/core/model/odata/span.go
  modules/oap/collector/core/model/plugin.go
  modules/oap/collector/core/model/processor.go
  modules/oap/collector/core/model/receiver.go
  modules/oap/collector/core/pipeline/pipeline.go
  modules/oap/collector/core/provider.go
  modules/oap/collector/core/provider_test.go
  modules/oap/collector/plugins/exporters/collector/provider.go
  modules/oap/collector/plugins/exporters/kafka/provider.go
  modules/oap/collector/plugins/exporters/stdout/provider.go
  modules/oap/collector/plugins/processors/k8s-tagger/provider.go
  modules/oap/collector/plugins/processors/modifier/provider.go
  modules/oap/collector/plugins/receivers/collector/clogs.go
  modules/oap/collector/plugins/receivers/collector/provider.go
  modules/oap/collector/plugins/receivers/dummy/provider.go
  modules/oap/collector/plugins/receivers/fluentbit/provider.go
  modules/oap/collector/plugins/receivers/jaeger/provider.go
  modules/oap/collector/plugins/receivers/opentelemetry/provider.go
  modules/oap/collector/plugins/receivers/promremotewrite/provider.go
  pkg/common/common.go
Labels: feature

#4339 fix(openapi): the manual review action needs to be added with scopeID props
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render.go
  modules/openapi/component-protocol/scenarios/action/components/actionForm/render_test.go
Labels: openapi, bugfix, approved

#4354 fix: update erda.yml
  erda.yml
Labels: bugfix

#4300 feat(orchestrator): insert cluster info to database
  .erda/migrations/cmdb/20220307-cluster.sql
  apistructs/cluster.go
  modules/cluster-manager/endpoints/cluster.go
  modules/cluster-manager/model/model.go
  modules/cluster-manager/services/cluster/cluster.go
  modules/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  modules/orchestrator/scheduler/instanceinfo/clusterInfo.go
Labels: orchestrator, feature

#4351 feat: Optimize cache logic in core-services
  Makefile
  go.mod
  go.sum
  modules/core-services/cache/project/project.go
  modules/core-services/cache/project/project_test.go
  modules/core-services/initialize.go
  modules/core-services/services/project/cache.go
  modules/core-services/services/project/cache_test.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
  pkg/cache/cache.go
Labels: feature

#4357 fix: referenced releases options error
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
Labels: bugfix

#4358 refactor: remove expose for uc-adaptor
  erda.yml
Labels: refactor, approved

#4359 fix(dop): add urlQuery param to auto test plan
  modules/dop/component-protocol/components/auto-test-plan-list/components/filter/provider.go
  modules/dop/component-protocol/components/common/urlQuery.go
Labels: dop, bugfix, approved

#4360 fix: adjust runtime page link
  api/proto-go/all.go
  api/proto-go/core/pipeline/base/pb/base.form.pb.go
  api/proto-go/core/pipeline/base/pb/base.pb.go
  api/proto-go/core/pipeline/base/pb/base.validator.pb.go
  api/proto-go/core/pipeline/cron/pb/cron.form.pb.go
  api/proto-go/core/pipeline/cron/pb/cron.http.pb.go
  api/proto-go/core/pipeline/cron/pb/cron.pb.go
  api/proto-go/core/pipeline/cron/pb/cron.validator.pb.go
  api/proto-go/core/pipeline/pb/cron_pub.form.pb.go
  api/proto-go/core/pipeline/pb/cron_pub.http.pb.go
  api/proto-go/core/pipeline/pb/cron_pub.json.pb.go
  api/proto-go/core/pipeline/pb/cron_pub.pb.go
  api/proto-go/core/pipeline/pb/cron_pub.validator.pb.go
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto-go/orchestrator/addon/mysql/pb/mysql.form.pb.go
  api/proto-go/orchestrator/addon/mysql/pb/mysql.pb.go
  api/proto/orchestrator/addon/mysql/mysql.proto
  go.mod
  go.sum
  modules/dop/component-protocol/components/addon-mysql-attachment/attachmentTable/render.go
  modules/orchestrator/components/addon/mysql/mysql.service.go
Labels: bugfix, approved

#4353 fix: token expire when runtime download env of file type
  .erda/migrations/orchestrator/20220314-add-runtime-filetoken.sql
  modules/orchestrator/dbclient/runtime.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/runtime/runtime.go
Labels: bugfix, approved

#4362 fix(pipeline): set latest-version extension as default
  apistructs/extention.go
  bundle/dicehub.go
  modules/dicehub/dbclient/extention.go
  modules/dicehub/service/extension/extension.go
  modules/pipeline/services/extmarketsvc/list.go
Labels: pipeline, bugfix, approved

#4365 fix: Return the total number of alert expressions
  modules/core/monitor/alert/alert-apis/db/alert_expression.go
  modules/core/monitor/expression/expression.service.go
  modules/core/monitor/expression/expression.service_test.go
Labels: bugfix, approved

#4364 refactor: adjust erda-cli config and project-deployment logic
  tools/cli/cmd/clone.go
  tools/cli/cmd/config_delete.go
  tools/cli/cmd/config_get.go
  tools/cli/cmd/config_set.go
  tools/cli/cmd/config_update.go
  tools/cli/cmd/create.go
  tools/cli/cmd/project_deployment_start.go
  tools/cli/cmd/project_deployment_stop.go
  tools/cli/cmd/push.go
  tools/cli/common/config.go
  tools/cli/common/org.go
  tools/cli/common/project.go
Labels: refactor

#4368 feat: only set `path_handling` on Kong 2.x to be compatible with different versions of Kong
  modules/hepa/kong/base/kong_adapter.go
  modules/hepa/kong/dto/kong_route_req_dto.go
  modules/hepa/kong/dto/kong_route_req_dto_test.go
Labels: hepa, feature, approved

#4370 fix: collector-agent config fix
  conf/monitor/collector/collector-agent.yaml
Labels: bugfix

#4376 fix: remove test nfs_root config for erda.yaml
  erda.yml
Labels: bugfix, approved

#4340 refactor(pipeline): split scheduler executor
  .erda/migrations/pipeline/20220311-pipeline-delete-scheduler-config.sql
  modules/pipeline/dbclient/op_pipeline_config.go
  modules/pipeline/endpoints/clusterinfo.go
  modules/pipeline/endpoints/engine.go
  modules/pipeline/pipengine/actionexecutor/k8s_helper.go
  modules/pipeline/pipengine/actionexecutor/k8s_helper_test.go
  modules/pipeline/pipengine/actionexecutor/logic/dcos.go
  modules/pipeline/pipengine/actionexecutor/logic/errorsx.go
  modules/pipeline/pipengine/actionexecutor/logic/events.go
  modules/pipeline/pipengine/actionexecutor/logic/job.go
  modules/pipeline/pipengine/actionexecutor/logic/shceduleinfo.go
  modules/pipeline/pipengine/actionexecutor/logic/status.go
  modules/pipeline/pipengine/actionexecutor/logic/status_test.go
  modules/pipeline/pipengine/actionexecutor/logic/toleration.go
  modules/pipeline/pipengine/actionexecutor/manager.go
  modules/pipeline/pipengine/actionexecutor/plugin_init.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/type.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/error.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/msg.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/type.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/util.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/manager.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/plugin_init.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/executor/types/define.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler.go
  modules/pipeline/pipengine/actionexecutor/plugins/scheduler/scheduler_test.go
  modules/pipeline/pipengine/actionexecutor/types/define.go
  modules/pipeline/pipengine/actionexecutor/types/define_test.go
  modules/pipeline/pipengine/actionexecutor/types/k8s_executor.go
  modules/pipeline/pkg/clusterinfo/clusterinfo.go
  modules/pipeline/pkg/containers/task_container.go
  modules/pipeline/providers/engine/provider.go
  modules/pipeline/providers/reconciler/legacy/reconciler/gc.go
  modules/pipeline/providers/reconciler/legacy/reconciler/reconcile.go
  modules/pipeline/providers/reconciler/legacy/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/services/pipelinesvc/cancel.go
  modules/pipeline/services/pipelinesvc/clusterinfo.go
  modules/pipeline/services/pipelinesvc/create_task.go
  modules/pipeline/services/pipelinesvc/create_task_test.go
  modules/pipeline/spec/pipeline_configs.go
  modules/pipeline/spec/pipeline_task.go
  modules/pipeline/spec/pipeline_task_test.go
Labels: pipeline, refactor, approved

#4367 fix: support no repo in application
  bundle/gittar.go
  modules/dop/services/project/import_package.go
  modules/dop/services/project/project_package.go
  tools/cli/cmd/create.go
Labels: bugfix, approved

#4377 feat(dop): count runtime by env
  modules/openapi/api/apis/orchestrator/orchestrator_projectruntime_count.go
  modules/orchestrator/endpoints/runtime.go
Labels: dop, feature

#4378 fix: remove metricq-client in dicehub conf
  conf/dicehub/dicehub.yaml
Labels: bugfix, approved

#4383 fix: panic in pubilsh item metrics
  modules/dop/component-protocol/components/release-manage/releaseTable/render.go
  modules/dop/services/publish_item/item_statistic.go
Labels: bugfix

#4371 fix: getSpanCount() bug fix and code polish
  modules/msp/apm/trace/query/provider.go
  modules/msp/apm/trace/query/source/cassandra_source.go
  modules/msp/apm/trace/query/source/cassandra_source_test.go
  modules/msp/apm/trace/query/source/elasticsearch_source.go
  modules/msp/apm/trace/query/source/elasticsearch_source_test.go
  modules/msp/apm/trace/query/source/source.go
  modules/msp/apm/trace/query/trace.service.go
  modules/msp/apm/trace/query/trace.service_test.go
  modules/msp/apm/trace/storage/elasticsearch/statistics.go
Labels: msp, bugfix, polish

#4384 feat: cast userID to String
  .erda/migrations/cmdb/20220307-quota-user-id.sql
  apistructs/project_quota.go
  apistructs/project_test.go
  modules/core-services/services/project/project.go
  modules/core-services/services/project/project_test.go
Labels: feature, approved

#4390 fix: duplicate addon in different release
  modules/dop/services/project/export_package.go
Labels: bugfix, approved

#4385 fix(dop): Solve the problem that the urlQuery does not take effect
  modules/dop/component-protocol/components/auto-test-plan-list/components/filter/provider.go
  modules/dop/component-protocol/components/common/urlQuery.go
Labels: dop, bugfix, approved

#4392 fix(pipeline): sleep 30 second to delay next reconcile that caused by cluster offline exception
  modules/pipeline/providers/reconciler/legacy/reconciler/reconcile.go
Labels: pipeline, bugfix, approved

#4379 feat: Update kratos yml with email and sms config
  modules/core/openapi-ng/auth/ory-kratos/user.go
  pkg/ucauth/kratos.go
  pkg/ucauth/kratos/identity.schema.json
  pkg/ucauth/kratos/kratos.yml
  pkg/ucauth/kratos/sms.request.jsonnet
  pkg/ucauth/model.go
Labels: feature

#4391 feat(dop,pipeline): Project pipeline supports branch search
  .erda/migrations/pipeline/20220318-pipeline-definition-add-ref.sql
  api/proto-go/core/pipeline/definition/client/client.go
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.http.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.json.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.validator.pb.go
  api/proto-go/core/pipeline/definition/pb/definition_grpc.pb.go
  api/proto/core/pipeline/definition/definition.proto
  conf/dop/i18n/cp/common.yaml
  modules/dop/component-protocol/components/project-pipeline/common/gshelper/helper.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/providers/projectpipeline/deftype/list.go
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/dop/services/apierrors/errors.go
  modules/pipeline/providers/definition/db/define.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: dop, pipeline, feature

#4395 fix: reduce cmp resource
  erda.yml
Labels: bugfix, approved

#4397 fix(quota): check quota with different workspace
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
Labels: bugfix

#4400 fix: cmp workloadDetail panic
  modules/cmp/component-protocol/components/cmp-dashboard-workload-detail/podsTable/render.go
Labels: bugfix

#4402 fix: typo in log module
  modules/core/monitor/log/log.go
  modules/core/monitor/log/persist/v1/consumer.go
  modules/core/monitor/log/persist/v1/consumer_test.go
  modules/core/monitor/log/persist/v1/storage.go
  modules/core/monitor/log/persist/v1/storage_test.go
  modules/core/monitor/log/storage/elasticsearch/iterator.go
  modules/core/monitor/log/storage/kubernetes-logs/storage.go
Labels: core feature, bugfix, approved

#4401 feat: error request analyzer for request monitor
  api/proto-go/msp/apm/service/pb/service.pb.go
  api/proto/msp/apm/service/service.proto
  modules/msp/apm/service/common/error-transaction/inparams.go
  modules/msp/apm/service/common/error-transaction/table.go
  modules/msp/apm/service/components/all.go
  modules/msp/apm/service/components/transaction-cache-error/error_req_distribution/provider.go
  modules/msp/apm/service/components/transaction-cache-error/metric_table/provider.go
  modules/msp/apm/service/components/transaction-cache-error/metric_table_filter/provider.go
  modules/msp/apm/service/components/transaction-cache-error/scenario.go
  modules/msp/apm/service/components/transaction-db-error/error_req_distribution/provider.go
  modules/msp/apm/service/components/transaction-db-error/metric_table/provider.go
  modules/msp/apm/service/components/transaction-db-error/metric_table_filter/provider.go
  modules/msp/apm/service/components/transaction-db-error/scenario.go
  modules/msp/apm/service/components/transaction-http-error/error_req_distribution/provider.go
  modules/msp/apm/service/components/transaction-http-error/metric_table/provider.go
  modules/msp/apm/service/components/transaction-http-error/metric_table_filter/provider.go
  modules/msp/apm/service/components/transaction-http-error/scenario.go
  modules/msp/apm/service/components/transaction-mq-error/error_req_distribution/provider.go
  modules/msp/apm/service/components/transaction-mq-error/metric_table/provider.go
  modules/msp/apm/service/components/transaction-mq-error/metric_table_filter/provider.go
  modules/msp/apm/service/components/transaction-mq-error/scenario.go
  modules/msp/apm/service/components/transaction-rpc-error/error_req_distribution/provider.go
  modules/msp/apm/service/components/transaction-rpc-error/metric_table/provider.go
  modules/msp/apm/service/components/transaction-rpc-error/metric_table_filter/provider.go
  modules/msp/apm/service/components/transaction-rpc-error/scenario.go
  modules/msp/apm/service/datasources/provider.go
  modules/msp/apm/service/datasources/transaction.go
  modules/msp/apm/service/scenarios/transaction-cache-error.yml
  modules/msp/apm/service/scenarios/transaction-db-error.yml
  modules/msp/apm/service/scenarios/transaction-http-error.yml
  modules/msp/apm/service/scenarios/transaction-mq-error.yml
  modules/msp/apm/service/scenarios/transaction-rpc-error.yml
  modules/msp/apm/service/view/chart/chart.go
  modules/msp/apm/service/view/chart/error_duration_distribution.go
  modules/msp/apm/service/view/table/error_transaction.go
Labels: msp, feature

#4396 refactor: change orchestrator inside API calls into inside method
  apistructs/k8s.go
  apistructs/service.go
  bundle/servicegroup.go
  bundle/urls.go
  modules/dop/providers/autotest/testplan/testplan.service_test.go
  modules/dop/services/issue/issue_test.go
  modules/orchestrator/components/runtime/mock/mock_sg.go
  modules/orchestrator/components/runtime/provider.go
  modules/orchestrator/components/runtime/runtime.service.go
  modules/orchestrator/components/runtime/runtime.service_test.go
  modules/orchestrator/endpoints/addon.go
  modules/orchestrator/endpoints/addon_test.go
  modules/orchestrator/endpoints/endpoints.go
  modules/orchestrator/endpoints/instance.go
  modules/orchestrator/endpoints/server_handler.go
  modules/orchestrator/initialize.go
  modules/orchestrator/scheduler/endpoints/endpoints.go
  modules/orchestrator/scheduler/endpoints/endpoints_test.go
  modules/orchestrator/scheduler/endpoints/job_endpoints.go
  modules/orchestrator/scheduler/endpoints/job_endpoints_test.go
  modules/orchestrator/scheduler/endpoints/servicegroup_endpoints.go
  modules/orchestrator/scheduler/endpoints/servicegroup_endpoints_test.go
  modules/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
  modules/orchestrator/scheduler/impl/instanceinfo/instanceinfo.go
  modules/orchestrator/scheduler/impl/instanceinfo/instanceinfo_test.go
  modules/orchestrator/scheduler/impl/servicegroup/operations.go
  modules/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  modules/orchestrator/scheduler/scheduler.go
  modules/orchestrator/scheduler/scheduler_service_endpoints.go
  modules/orchestrator/services/addon/addon.go
  modules/orchestrator/services/addon/addon_deploy.go
  modules/orchestrator/services/addon/addon_deploy_test.go
  modules/orchestrator/services/addon/addon_handler.go
  modules/orchestrator/services/addon/addon_handler_test.go
  modules/orchestrator/services/addon/addon_resource_sync.go
  modules/orchestrator/services/addon/addon_status.go
  modules/orchestrator/services/addon/addon_test.go
  modules/orchestrator/services/addon/middleware.go
  modules/orchestrator/services/deployment/deployment.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/deployment/deployment_context_test.go
  modules/orchestrator/services/deployment/deployment_stages.go
  modules/orchestrator/services/instance/instance.go
  modules/orchestrator/services/migration/migration.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/services/runtime/runtime_test.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  quick-start/docker-compose.yml
  tools/cli/cmd/project_deployment_start.go
  tools/cli/cmd/project_deployment_stop.go
Labels: refactor

#4399 fix(dop): Deal with situations that tasks have been completed before the iteration begins
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render.go
  modules/dop/component-protocol/components/requirement-task-overview/chartBlock/burnoutChart/render_test.go
Labels: dop, bugfix, approved

#4405 feat: Update openapi
  conf/msp/i18n/msp-i18n.yaml
  conf/openapi/openapi.yaml
  modules/msp/apm/service/components/all.go
Labels: msp

#4406 feat: update go-mod
  go.mod
  go.sum
Labels: msp, feature

#4410 fix(pipeline): use pointer instead of passing by value when constructAllActions
  modules/pipeline/services/extmarketsvc/list.go
Labels: approved

#4408 feat: dice.yaml support type of job
  api/proto-go/orchestrator/runtime/pb/runtime.form.pb.go
  api/proto-go/orchestrator/runtime/pb/runtime.pb.go
  api/proto/orchestrator/runtime/runtime.proto
  apistructs/runtime_dto.go
  modules/orchestrator/components/runtime/runtime.service.go
  modules/orchestrator/scheduler/executor/plugins/k8s/job.go
  modules/orchestrator/scheduler/executor/plugins/k8s/job/job.go
  modules/orchestrator/scheduler/executor/plugins/k8s/job_test.go
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  modules/orchestrator/scheduler/executor/plugins/k8s/runtime.go
  modules/orchestrator/scheduler/executor/plugins/k8s/type.go
  modules/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  modules/orchestrator/scheduler/impl/servicegroup/servicegroup_test.go
  modules/orchestrator/services/deployment/deployment_context.go
  modules/orchestrator/services/deployment/deployment_context_test.go
  modules/orchestrator/services/runtime/runtime.go
  modules/orchestrator/services/runtime/runtime_test.go
  pkg/parser/diceyml/define.go
Labels: feature, approved

#4409 feat: download apis4
  .erda/migrations/apim/20220317-export-records.sql
  .erda/migrations/config.yml
  api/proto-go/all.go
  api/proto-go/dop/apim/client/client.go
  api/proto-go/dop/apim/client/provider.go
  api/proto-go/dop/apim/pb/apim.form.pb.go
  api/proto-go/dop/apim/pb/apim.http.pb.go
  api/proto-go/dop/apim/pb/apim.json.pb.go
  api/proto-go/dop/apim/pb/apim.pb.go
  api/proto-go/dop/apim/pb/apim.validator.pb.go
  api/proto-go/dop/apim/pb/apim_grpc.pb.go
  api/proto-go/dop/apim/pb/register.services.pb.go
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto/dop/apim/apim.proto
  cmd/dop/main.go
  conf/dop/dop.yaml
  go.mod
  go.sum
  modules/dop/endpoints/asset_version.go
  modules/dop/endpoints/asset_version_test.go
  modules/dop/providers/api-management/.http/export-records.http
  modules/dop/providers/api-management/apierr/errors.go
  modules/dop/providers/api-management/model/models.go
  modules/dop/providers/api-management/provider.go
  modules/dop/services/assetsvc/get.go
  modules/dop/services/assetsvc/get_test.go
  pkg/swagger/oasconv/oasconv.go
  pkg/swagger/oasconv/oasconv_test.go
Labels: feature

#4363 feat(dop): Project pipeline supports name modification
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto-go/dop/projectpipeline/client/client.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.http.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.json.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.validator.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline_grpc.pb.go
  api/proto/core/pipeline/definition/definition.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  conf/dop/i18n/cp/common.yaml
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/providers/projectpipeline/deftype/update.go
  modules/dop/providers/projectpipeline/service.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/pipeline/providers/definition/db/define.go
Labels: dop, feature, approved

#4380 refactor(pipeline): impl cluster info provider
  apistructs/cluster.go
  apistructs/cluster_info.go
  apistructs/cluster_info_test.go
  cmd/pipeline/main.go
  conf/pipeline/pipeline.yaml
  modules/cluster-manager/services/cluster/cluster.go
  modules/pipeline/endpoints/clusterinfo.go
  modules/pipeline/endpoints/endpoints.go
  modules/pipeline/endpoints/engine.go
  modules/pipeline/initialize.go
  modules/pipeline/pipengine/actionexecutor/k8s_helper.go
  modules/pipeline/pipengine/actionexecutor/logic/job.go
  modules/pipeline/pipengine/actionexecutor/manager.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
  modules/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
  modules/pipeline/pkg/clusterinfo/clusterinfo.go
  modules/pipeline/pkg/container_provider/container_instance_provider.go
  modules/pipeline/pkg/container_provider/container_provider_test.go
  modules/pipeline/provider.go
  modules/pipeline/providers/clusterinfo/cache.go
  modules/pipeline/providers/clusterinfo/interface.go
  modules/pipeline/providers/clusterinfo/notifier.go
  modules/pipeline/providers/clusterinfo/provider.go
  modules/pipeline/providers/engine/provider.go
  modules/pipeline/providers/reconciler/legacy/reconciler/define.go
  modules/pipeline/providers/reconciler/legacy/reconciler/reconcile.go
  modules/pipeline/providers/reconciler/legacy/reconciler/taskrun/taskop/prepare.go
  modules/pipeline/providers/reconciler/legacy/reconciler/taskrun/taskrun.go
  modules/pipeline/services/pipelinesvc/clusterinfo.go
  modules/pipeline/services/pipelinesvc/define.go
Labels: pipeline, refactor, approved

#4375 feat: Verify issue planned end time and issue state with iteration
  modules/dop/services/issue/adjust.go
  modules/dop/services/issue/cache.go
  modules/dop/services/issue/issue.go
  modules/dop/services/issue/validate.go
Labels: feature, approved

#4418 fix: paging
  modules/dop/providers/api-management/provider.go
Labels: dop, bugfix

#4415 fix(pipeline): update and delete k8s executor by factory
  modules/pipeline/pipengine/actionexecutor/k8s_helper.go
Labels: pipeline, bugfix, approved

#4420 fix(pipeline): fix copy issue of handlers, which cause task never done
  modules/pipeline/providers/leaderworker/worker/worker.go
Labels: pipeline, bugfix

#4423 fix(pipeline): allow the handler to be null when the worker is not used to process logical task
  modules/pipeline/providers/leaderworker/worker/worker.go
Labels: pipeline, bugfix, approved

#4348 refactor(pipeline): Refactored pipeline cron daemon and cron compensation
  apistructs/pipeline_cron.go
  cmd/pipeline/main.go
  conf/pipeline/pipeline.yaml
  modules/dop/initialize_test.go
  modules/pipeline/endpoints/crond.go
  modules/pipeline/endpoints/endpoints.go
  modules/pipeline/initialize.go
  modules/pipeline/provider.go
  modules/pipeline/providers/cron/compensator/interface.go
  modules/pipeline/providers/cron/compensator/provider.go
  modules/pipeline/providers/cron/cron.service.go
  modules/pipeline/providers/cron/daemon/cron_task.go
  modules/pipeline/providers/cron/daemon/interface.go
  modules/pipeline/providers/cron/daemon/provider.go
  modules/pipeline/providers/cron/db/define_extra.go
  modules/pipeline/providers/cron/db/op_ci_v3_build_cache.go
  modules/pipeline/providers/cron/provider.go
  modules/pipeline/providers/reconciler/legacy/reconciler/cron_strategy_compensator.go
  modules/pipeline/providers/reconciler/legacy/reconciler/define.go
  modules/pipeline/providers/reconciler/provider.go
  modules/pipeline/services/crondsvc/crond.go
  modules/pipeline/services/crondsvc/crond_test.go
  modules/pipeline/services/crondsvc/func_clean_build_cache.go
  modules/pipeline/services/pipelinesvc/cron.go
  modules/pipeline/services/pipelinesvc/cron_compensate_test.go
  modules/pipeline/services/pipelinesvc/define.go
Labels: pipeline, refactor, approved

#4403 feat(dop,pipeline): pipeline list support category filter
  api/proto-go/core/pipeline/definition/client/client.go
  api/proto-go/core/pipeline/definition/pb/definition.form.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.http.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.json.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.pb.go
  api/proto-go/core/pipeline/definition/pb/definition.validator.pb.go
  api/proto-go/core/pipeline/definition/pb/definition_grpc.pb.go
  api/proto-go/dop/projectpipeline/client/client.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.form.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.http.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.json.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline.validator.pb.go
  api/proto-go/dop/projectpipeline/pb/projectpipeline_grpc.pb.go
  api/proto/core/pipeline/definition/definition.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  apistructs/project_pipeline.go
  apistructs/unified_filetree.go
  bundle/gittar.go
  conf/dop/i18n/project-pipeline.yaml
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/model.go
  modules/dop/component-protocol/components/project-pipeline/myPage/pageHeader/pipelineTabs/render.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/inparams.go
  modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  modules/dop/endpoints/projectpipelinefiletree.go
  modules/dop/providers/projectpipeline/deftype/list.go
  modules/dop/providers/projectpipeline/service_impl.go
  modules/dop/providers/projectpipeline/service_impl_test.go
  modules/dop/services/apidocsvc/api_docs.go
  modules/dop/services/apidocsvc/funcs.go
  modules/dop/services/apierrors/errors.go
  modules/dop/services/filetree/filetree.go
  modules/pipeline/providers/definition/db/define.go
  modules/pipeline/providers/definition/pipeline_definition.go
Labels: dop, pipeline, feature, approved

#4419 fix: deployment exit when job failed
  modules/orchestrator/scheduler/executor/plugins/k8s/job.go
  modules/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  modules/orchestrator/scheduler/executor/plugins/k8s/runtime.go
  modules/orchestrator/services/deployment/deployment_context.go
Labels: bugfix, approved
