Repository erda-project/erda, pull requests merged in 2022-06, with the labels that each got.

#4989 fix: add logs for httpHandler failure
  modules/msp/apm/checker/plugins/http/provider.go
Labels: bugfix, approved

#4981 feat: handle high cardinality tag
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
  modules/msp/apm/trace/span.go
  modules/oap/collector/README.md
  modules/oap/collector/core/provider.go
  modules/oap/collector/lib/common/common.go
  modules/oap/collector/lib/common/unmarshalwork/unmarshalwork.go
  modules/oap/collector/lib/protoparser/common/marshalwork/marshalwork.go
  modules/oap/collector/lib/protoparser/jsonmarshal/jsonmarshal.go
  modules/oap/collector/lib/protoparser/oapspan/span.go
  modules/oap/collector/lib/protoparser/oapspan/span_test.go
  modules/oap/collector/lib/protoparser/spotspan/span.go
  modules/oap/collector/lib/protoparser/spotspan/span_test.go
  modules/oap/collector/plugins/exporters/clickhouse/provider.go
  modules/oap/collector/plugins/exporters/clickhouse/span/writer.go
  modules/oap/collector/plugins/exporters/clickhouse/span/writer_test.go
  modules/oap/collector/plugins/receivers/collector/clogs.go
  modules/oap/collector/plugins/receivers/collector/kafka.go
  modules/oap/collector/plugins/receivers/jaeger/jaeger.service.go
  modules/oap/collector/plugins/receivers/opentelemetry/otlp.service.go
Labels: feature, approved

#4994 chore: remove useless tools code
  .github/workflows/ci-it.yml
  go.sum
  modules/tools/kafka-mirror/consumer.go
  modules/tools/kafka-mirror/provider.go
  modules/tools/kafka-push/provider.go
  modules/tools/make-chart-files/provider.go
  modules/tools/make-metric-meta-files/provider.go
  modules/tools/utils/kubernetes.go
  modules/tools/utils/provider.go
Labels: approved

#4999 fix: fix error-req count error
  modules/msp/apm/service/view/table/transaction.go
Labels: msp, bugfix, approved

#5007 refactor: move action-runner-scheduler to pipeline
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_collect_log.go
  modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_create.go
  modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_fetch.go
  modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_get.go
  modules/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_update.go
Labels: refactor, approved

#5009 fix: zero length pattern in SBAC config
  modules/hepa/apipolicy/policies/sbac/policy.go
  modules/hepa/apipolicy/policies/sbac/policy_test.go
Labels: bugfix

#5011 fix: add build-routers to common openapi
  api/proto/core/pipeline/build/build.proto
Labels: bugfix, approved

#5012 feat: trigger go check if proto file changed
  .github/workflows/ci-it-noneed.yml
  .github/workflows/ci-it.yml
Labels: feature, approved

#4984 fix(pipeline): end listening log lines use context done instead of end tail flag
  modules/tools/pipeline/actionagent/execute.go
  modules/tools/pipeline/actionagent/file_watch.go
  modules/tools/pipeline/actionagent/file_watch_collector.go
  modules/tools/pipeline/actionagent/filewatch/watch.go
Labels: pipeline, bugfix, approved

#5016 fix: upload release
  internal/apps/dop/component-protocol/components/release-manage/releaseTable/render.go
  internal/apps/dop/dicehub/release/release.go
Labels: bugfix

#5018 chore: upgrade gjson
  go.mod
  go.sum
Labels: approved

#5014 feat: globalization text optimization
  cmd/monitor/monitor/conf/i18n/alert.yml
  cmd/msp/conf/i18n/cp/msp-notify-detail.yaml
Labels: feature, approved

#4997 feat(pipeline): pipeline k8sjob-task collect oomkilled reason
  apistructs/pipeline_status.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/error.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait_test.go
Labels: pipeline, feature, approved

#5024 chore: specify gohub image tag to 1.0.5
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  api/proto-go/Makefile
  pipeline.yml
Labels: approved

#5021 feat: Use protoc-gen-validate as protobuf validator plugin.
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  api/proto-go/Makefile
  api/proto/admin/dingtalk_test.proto
  api/proto/core/messenger/eventbox/eventbox.proto
  api/proto/core/messenger/notify/notify.proto
  api/proto/core/messenger/notifychannel/channel.proto
  api/proto/core/messenger/notifygroup/notify_group.proto
  api/proto/core/monitor/alert/alert.proto
  api/proto/core/monitor/alertdetail/details.proto
  api/proto/core/monitor/dataview/dataview.proto
  api/proto/core/monitor/diagnotor/diagnotor.proto
  api/proto/core/monitor/diagnotor/diagnotor_agent.proto
  api/proto/core/monitor/expression/expression.proto
  api/proto/core/monitor/metric/meta.proto
  api/proto/core/monitor/settings/settings.proto
  api/proto/core/pipeline/base/base.proto
  api/proto/core/pipeline/build/build.proto
  api/proto/core/pipeline/cluster/cluster.proto
  api/proto/core/pipeline/cms/cms.proto
  api/proto/core/pipeline/definition/definition.proto
  api/proto/core/pipeline/label/label.proto
  api/proto/core/pipeline/queue/queue.proto
  api/proto/core/pipeline/report/report.proto
  api/proto/core/pipeline/source/source.proto
  api/proto/core/services/filemanager/filemanager.proto
  api/proto/dop/devflowrule/devflowrule.proto
  api/proto/dop/guide/guide.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  api/proto/msp/apm/adapter/adapter.proto
  api/proto/msp/apm/alert/apm_alert.proto
  api/proto/msp/apm/checker/checker.proto
  api/proto/msp/apm/checker/checker_v1.proto
  api/proto/msp/apm/diagnotor/apm_diagnotor.proto
  api/proto/msp/apm/exception/exception.proto
  api/proto/msp/apm/expression/expression.proto
  api/proto/msp/apm/service/service.proto
  api/proto/msp/apm/trace/trace.proto
  api/proto/msp/configcenter/configcenter.proto
  api/proto/msp/menu/menu.proto
  api/proto/msp/registercenter/registercenter.proto
  api/proto/msp/resource/resource.proto
  api/proto/msp/tenant/project/project.proto
  api/proto/msp/tenant/tenant.proto
  api/proto/oap/entity/entity.proto
  go.mod
  go.sum
  pipeline.yml
  pkg/common/apis/response.go
Labels: feature, approved

#5019 refactor: refactor action-runner-scheduler to pb provider
  api/proto/core/pipeline/action_runner_scheduler/runner_task.proto
  cmd/action-runner-scheduler/bootstrap.yaml
  cmd/action-runner-scheduler/common-conf
  cmd/action-runner-scheduler/conf/.gitkeep
  cmd/action-runner-scheduler/main.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  erda.yml
  internal/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_collect_log.go
  internal/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_create.go
  internal/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_fetch.go
  internal/tools/openapi/legacy/api/apis/runner_scheduler/runner_task_update.go
  internal/tools/pipeline/action-runner-scheduler/conf/conf.go
  internal/tools/pipeline/action-runner-scheduler/dbclient/dbclient.go
  internal/tools/pipeline/action-runner-scheduler/endpoints/endpoints.go
  internal/tools/pipeline/action-runner-scheduler/endpoints/info.go
  internal/tools/pipeline/action-runner-scheduler/endpoints/runner_task.go
  internal/tools/pipeline/action-runner-scheduler/initialize.go
  internal/tools/pipeline/action-runner-scheduler/provider.go
  internal/tools/pipeline/action-runner-scheduler/services/apierrors/errors.go
  internal/tools/pipeline/action-runner-scheduler/services/runnertask/runner_task.go
  internal/tools/pipeline/providers/action_runner_scheduler/db/dbclient.go
  internal/tools/pipeline/providers/action_runner_scheduler/db/runner_task.go
  internal/tools/pipeline/providers/action_runner_scheduler/provider.go
  internal/tools/pipeline/providers/action_runner_scheduler/runner.task.service.go
  internal/tools/pipeline/services/apierrors/errors.go
Labels: refactor, approved

#5027 fix: allows accessControlAPI be empty while switch is false
  api/proto-go/go.mod
  api/proto-go/go.sum
  go.mod
  go.sum
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
Labels: bugfix

#5026 fix(pipeline): task op always begin queue due to `fetchLatestTask` when user click cancel
  internal/tools/pipeline/providers/reconciler/taskrun/framework.go
Labels: pipeline, bugfix, approved

#5020 feat(dop): Provide pipeline execution record api
  api/proto/dop/projectpipeline/projectpipeline.proto
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/providers/projectpipeline/service.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
  pkg/common/apis/context.go
  pkg/common/apis/header.go
Labels: dop, feature, approved

#5028 feat(orchestrator): refactor ecp to orchestrator
  .github/workflows/ci-it.yml
  bundle/bundle.go
  bundle/ecp.go
  bundle/urls.go
  cmd/ecp/bootstrap.yaml
  cmd/ecp/common-conf
  cmd/ecp/conf/.gitkeep
  cmd/ecp/main.go
  erda.yml
  internal/apps/ecp/conf/conf.go
  internal/apps/ecp/initialize.go
  internal/tools/orchestrator/ecp/dbclient/dbclient.go
  internal/tools/orchestrator/ecp/dbclient/edge_app.go
  internal/tools/orchestrator/ecp/dbclient/edge_configset.go
  internal/tools/orchestrator/ecp/dbclient/edge_configset_item.go
  internal/tools/orchestrator/ecp/dbclient/edge_site.go
  internal/tools/orchestrator/ecp/dbclient/models.go
  internal/tools/orchestrator/ecp/endpoints/common.go
  internal/tools/orchestrator/ecp/endpoints/edge_app.go
  internal/tools/orchestrator/ecp/endpoints/edge_configset.go
  internal/tools/orchestrator/ecp/endpoints/edge_configset_item.go
  internal/tools/orchestrator/ecp/endpoints/edge_site.go
  internal/tools/orchestrator/ecp/endpoints/endpoints.go
  internal/tools/orchestrator/ecp/provider.go
  internal/tools/orchestrator/ecp/services/apierrors/errors.go
  internal/tools/orchestrator/ecp/services/edge/addon_mysql_edge.go
  internal/tools/orchestrator/ecp/services/edge/application.go
  internal/tools/orchestrator/ecp/services/edge/configset.go
  internal/tools/orchestrator/ecp/services/edge/configset_item.go
  internal/tools/orchestrator/ecp/services/edge/edge.go
  internal/tools/orchestrator/ecp/services/edge/site.go
  internal/tools/orchestrator/ecp/services/kubernetes/configmap.go
  internal/tools/orchestrator/ecp/services/kubernetes/deployment.go
  internal/tools/orchestrator/ecp/services/kubernetes/kubernetes.go
  internal/tools/orchestrator/ecp/services/kubernetes/namespace.go
  internal/tools/orchestrator/ecp/services/kubernetes/node.go
  internal/tools/orchestrator/ecp/services/kubernetes/nodepool.go
  internal/tools/orchestrator/ecp/services/kubernetes/pod.go
  internal/tools/orchestrator/ecp/services/kubernetes/secret.go
  internal/tools/orchestrator/ecp/services/kubernetes/service.go
  internal/tools/orchestrator/ecp/services/kubernetes/statefulset.go
  internal/tools/orchestrator/ecp/services/kubernetes/uniteddeployment.go
  internal/tools/orchestrator/initialize.go
  internal/tools/orchestrator/initialize_test.go
  pkg/discover/address.go
Labels: orchestrator, feature

#5030 refactor: optimeze trace storage code
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
  internal/apps/msp/apm/trace/span.go
  internal/tools/monitor/oap/collector/core/model/processor.go
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/log/log.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/cache.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/span.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/span_test.go
  internal/tools/monitor/oap/collector/plugins/processors/aggregator/provider.go
  internal/tools/monitor/oap/collector/plugins/processors/k8s-tagger/provider.go
  internal/tools/monitor/oap/collector/plugins/processors/modifier/provider.go
  internal/tools/monitor/oap/collector/plugins/processors/stdout/provider.go
Labels: refactor

#5032 fix: logging, add trace_id tag if missing
  internal/tools/monitor/core/log/persist/consume.go
  internal/tools/monitor/core/log/persist/consume_test.go
Labels: msp, bugfix, approved

#5031 fix: globalization text
  cmd/monitor/monitor/conf/i18n/charts.yml
  cmd/monitor/monitor/conf/i18n/org-resource.yml
  cmd/msp/conf/i18n/cp/msp-alert-overview.yaml
Labels: bugfix, approved

#5037 chore: set wait-for-ci to false in codecov
  codecov.yml
Labels: approved

#5039 feat: log file download support k8s log
  internal/tools/monitor/core/log/query/log.query.service.go
  internal/tools/monitor/core/log/query/routes.go
  internal/tools/monitor/core/log/query/routes_test.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/provider.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/storage_test.go
  internal/tools/monitor/core/log/storage/storage.go
Labels: feature, approved

#5033 fix: change action-runner-scheduler auth check
  api/proto/core/pipeline/action_runner_scheduler/runner_task.proto
Labels: bugfix, approved

#5041 fix: chart text optimization
  cmd/monitor/monitor/conf/i18n/charts.yml
Labels: bugfix, approved

#5040 fix: Query support high cardinality
  cmd/monitor/streaming/bootstrap.yaml
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/span/cache.go
Labels: bugfix, approved

#5034 fix(pipeline): Solve data consistency problems of pipeline cron
  internal/tools/pipeline/providers/cron/cron.service.go
  internal/tools/pipeline/providers/cron/cron.service_test.go
  internal/tools/pipeline/providers/cron/daemon/cron_task.go
  internal/tools/pipeline/providers/cron/daemon/cron_task_test.go
  internal/tools/pipeline/providers/cron/daemon/provider.go
  internal/tools/pipeline/providers/cron/daemon/provider_test.go
  internal/tools/pipeline/providers/edgepipeline_register/cluster_access_key_test.go
  internal/tools/pipeline/providers/edgepipeline_register/interface_test.go
  internal/tools/pipeline/providers/edgepipeline_register/mock.go
Labels: pipeline, bugfix, approved

#5043 fix: cancel query all projects
  internal/apps/dop/component-protocol/components/release-manage/releaseTable/render.go
  internal/apps/dop/dicehub/release/release.go
  internal/apps/dop/dicehub/release/release_test.go
Labels: bugfix

#5044 fix(pipeline): overwrite current task with latest when status is ending
  internal/tools/pipeline/providers/reconciler/task_reconciler.go
  internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
Labels: pipeline, bugfix, approved

#4991 feat(cluster-manager): provider cluster dialer
  bundle/cluster_manager.go
  bundle/urls.go
  cmd/cluster-manager/bootstrap.yaml
  cmd/cluster-manager/main.go
  cmd/cluster-manager/register.go
  erda.yml
  internal/core/cluster-manager/conf/conf.go
  internal/core/cluster-manager/dbclient/cluster.go
  internal/core/cluster-manager/dialer/auth/auth.go
  internal/core/cluster-manager/dialer/provider.go
  internal/core/cluster-manager/dialer/server/dialer_test.go
  internal/core/cluster-manager/dialer/server/tunnel-server.go
  internal/core/cluster-manager/dialer/server/tunnel-server_test.go
  internal/core/cluster-manager/model/model.go
  internal/tools/cluster-agent/client/client.go
  internal/tools/openapi/legacy/api/apis/cluster_manager/connect.go
  internal/tools/pipeline/providers/edgepipeline_register/interface.go
  pkg/clusterdialer/dialer.go
  pkg/clusterdialer/dialer_test.go
  pkg/discover/address.go
  pkg/http/customhttp/request.go
  pkg/http/customhttp/request_test.go
Labels: cluster-manager, feature, approved

#5046 chore: update gohub
  api/proto-go/Makefile
  api/proto-go/go.mod
  api/proto-go/go.sum
  go.mod
  go.sum
Labels: approved

#5050 feat: created_at timestamp
  internal/apps/dop/dicehub/release/release.service.go
  internal/tools/orchestrator/hepa/kong/dto/kong_credential_resp_dto.go
  internal/tools/orchestrator/hepa/kong/dto/kong_credential_resp_dto_test.go
  internal/tools/orchestrator/hepa/kong/v2/kong_adapter.go
Labels: hepa, bugfix

#5047 fix(pipeline): The pipeline aop calls the scenario test adopts Internal-Client verification
  bundle/autotest_scene.go
Labels: pipeline, bugfix, approved

#5042 fix(pipeline): Solve the problem that the pipeline records of timed execution cannot be queried according to the executor
  apistructs/pipeline_page.go
  apistructs/pipeline_page_test.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/tools/pipeline/providers/run/run.go
  internal/tools/pipeline/providers/run/run_test.go
  internal/tools/pipeline/services/pipelinesvc/create_v2.go
Labels: pipeline, bugfix, approved

#5049 fix: use global in to query trace
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
Labels: bugfix, approved

#5051 chore: remove duplicated pexep pkg
  internal/tools/pipeline/pexpr/eval.go
  internal/tools/pipeline/pexpr/eval_test.go
  internal/tools/pipeline/pexpr/placeholder.go
  internal/tools/pipeline/pexpr/placeholder_test.go
  internal/tools/pipeline/providers/actionmgr/db/client.go
  internal/tools/pipeline/providers/reconciler/taskrun/task_loop.go
Labels: approved

#4961 feat(pipeline): edge-side pipeline support register webhook and dispatch events
  apistructs/event_request.go
  apistructs/event_request_test.go
  internal/core/messenger/eventbox/dispatcher/dispatcher.go
  internal/tools/pipeline/events/event.go
  internal/tools/pipeline/events/event_pipeline.go
  internal/tools/pipeline/events/event_task.go
  internal/tools/pipeline/events/event_task_runtime.go
  internal/tools/pipeline/providers/edgepipeline_register/interface.go
  internal/tools/pipeline/providers/edgepipeline_register/mock.go
  internal/tools/pipeline/providers/edgepipeline_register/provider.go
  internal/tools/pipeline/providers/edgepipeline_register/webhook.go
  internal/tools/pipeline/providers/edgepipeline_register/webhook_test.go
Labels: pipeline, feature, approved

#4960 feat(pipeline): support dispatch cron to edge when edge side pipeline registered
  api/proto/core/pipeline/cron/cron.proto
  apistructs/cluster_dialer.go
  apistructs/event.go
  bundle/cluster_manager.go
  internal/core/cluster-manager/dialer/provider.go
  internal/core/cluster-manager/dialer/server/client_data.go
  internal/core/cluster-manager/dialer/server/client_data_test.go
  internal/core/cluster-manager/dialer/server/dialer_test.go
  internal/core/cluster-manager/dialer/server/tunnel-server.go
  internal/core/cluster-manager/dialer/server/tunnel-server_test.go
  internal/tools/pipeline/providers/cron/cron.service.go
  internal/tools/pipeline/providers/cron/db/define_extra.go
  internal/tools/pipeline/providers/edgepipeline_register/cluster_access_key.go
  internal/tools/pipeline/providers/edgepipeline_register/edge_client.go
  internal/tools/pipeline/providers/edgepipeline_register/edge_client_test.go
  internal/tools/pipeline/providers/edgepipeline_register/interface.go
  internal/tools/pipeline/providers/edgepipeline_register/mock.go
  internal/tools/pipeline/providers/edgepipeline_register/provider.go
  pkg/k8sclient/client.go
Labels: pipeline, feature, approved

#5053 fix: sql template fix
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
Labels: bugfix, approved

#5052 fix: ref op wrap quote typo
  pkg/parser/pipelineyml/visitor_ref_op.go
  pkg/parser/pipelineyml/visitor_ref_op_test.go
Labels: bugfix, approved

#5058 fix(monitor): Unreliable kubernetes log, Skip empty interval
  internal/tools/monitor/core/log/storage/kubernetes-logs/provider.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
Labels: bugfix

#5061 fix(dop): Special Handling 1970 Time
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
Labels: dop, bugfix, approved

#5060 refactor: make metadata as a pkg
  apistructs/elf.go
  apistructs/pipeline_actions.go
  apistructs/pipeline_task.go
  internal/tools/pipeline/actionagent/callback.go
  internal/tools/pipeline/actionagent/callback_test.go
  internal/tools/pipeline/actionagent/uploaddir.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/apitest/logic/meta.go
  internal/tools/pipeline/pipengine/pvolumes/cache.go
  internal/tools/pipeline/pipengine/pvolumes/dicefiles.go
  internal/tools/pipeline/pipengine/pvolumes/generate.go
  internal/tools/pipeline/pipengine/pvolumes/workdir.go
  internal/tools/pipeline/providers/reconciler/snippet.go
  internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
  internal/tools/pipeline/services/pipelinesvc/callback.go
  internal/tools/pipeline/services/pipelinesvc/detail.go
  internal/tools/pipeline/spec/pipeline_extra.go
  internal/tools/pipeline/spec/pipeline_task.go
  internal/tools/pipeline/spec/pipeline_task_test.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  pkg/parser/pipelineyml/pipelineymlv1/evaluate.go
  pkg/parser/pipelineyml/pipelineymlv1/options.go
  pkg/parser/pipelineyml/pipelineymlv1/pipelineyml.go
  pkg/parser/pipelineyml/pipelineymlv1/pipelineyml_test.go
  pkg/parser/pipelineyml/pipelineymlv1/util.go
  pkg/parser/pipelineyml/pipelineymlv1/util_test.go
  pkg/syncmap/string_interface_map_test.go
Labels: refactor, approved

#5022 feat(dop,gittar): Support for multi-branch merge
  .erda/migrations/gittar/20220525-gittar-merge-is-join-temp-branch.sql
  api/proto/apps/devflow/flow/flow.proto
  apistructs/gittar.go
  apistructs/gittar_test.go
  bundle/gittar.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/provider.go
  internal/apps/dop/provider.go
  internal/apps/dop/providers/devflowrule/devflowrule.service.go
  internal/apps/dop/providers/devflowrule/provider.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
  internal/tools/gittar/api/merge.go
  internal/tools/gittar/api/repo.go
  internal/tools/gittar/initialize.go
  internal/tools/gittar/models/merge_request.go
  internal/tools/gittar/pkg/gitmodule/repo_merge.go
Labels: dop, feature, approved, gittar

#5063 chore: polish codecov ignore rule
  codecov.yml
Labels: approved

#5062 refactor: split task result/inspect/error from apistructs
  apistructs/pipeline_actions.go
  apistructs/pipeline_report_basic.go
  apistructs/pipeline_task.go
  apistructs/pipeline_task_test.go
  internal/apps/cmp/impl/clusters/add_edge_cluster.go
  internal/tools/pipeline/actionagent/define.go
  internal/tools/pipeline/actionagent/step_validate.go
  internal/tools/pipeline/dbclient/op_pipeline_task.go
  internal/tools/pipeline/events/event_task.go
  internal/tools/pipeline/pkg/taskerror/err.go
  internal/tools/pipeline/pkg/taskerror/err_test.go
  internal/tools/pipeline/pkg/taskerror/ordered.go
  internal/tools/pipeline/pkg/taskerror/ordered_test.go
  internal/tools/pipeline/pkg/taskinspect/inspect.go
  internal/tools/pipeline/pkg/taskinspect/inspect_test.go
  internal/tools/pipeline/pkg/taskinspect/machine.go
  internal/tools/pipeline/pkg/taskresult/result.go
  internal/tools/pipeline/providers/reconciler/snippet.go
  internal/tools/pipeline/providers/reconciler/snippet_test.go
  internal/tools/pipeline/providers/reconciler/task_reconciler.go
  internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/framework.go
  internal/tools/pipeline/providers/reconciler/taskrun/framework_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/reconciler/taskrun/update.go
  internal/tools/pipeline/services/pipelinesvc/callback.go
  internal/tools/pipeline/services/pipelinesvc/callback_test.go
  internal/tools/pipeline/services/pipelinesvc/detail.go
  internal/tools/pipeline/spec/pipeline_task.go
  internal/tools/pipeline/spec/pipeline_task_test.go
Labels: refactor, approved

#5066 fix(dop): register devflowrule service
  internal/apps/dop/providers/devflowrule/provider.go
Labels: approved

#5064 refactor: Optimize distribute
  cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/source.go
  internal/apps/msp/apm/trace/query/source/source_test.go
Labels: refactor

#5070 fix: groutinepool pkg `WaitGroup is reused before previous Wait has returned`
  pkg/goroutinepool/goroutinepool.go
Labels: bugfix, approved

#5067 refactor: cherry-pick tracing optimize
  cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/source.go
  internal/apps/msp/apm/trace/query/source/source_test.go
Labels: refactor

#5068 refactor: task.result for external use, task.inspect for internal use
  apistructs/pipeline_actions.go
  apistructs/pipeline_task.go
  internal/apps/cmp/impl/clusters/add_edge_cluster.go
  internal/tools/pipeline/actionagent/define.go
  internal/tools/pipeline/dbclient/op_pipeline_task.go
  internal/tools/pipeline/events/event_task.go
  internal/tools/pipeline/pkg/taskerror/err.go
  internal/tools/pipeline/pkg/taskerror/err_test.go
  internal/tools/pipeline/pkg/taskerror/ordered.go
  internal/tools/pipeline/pkg/taskerror/ordered_test.go
  internal/tools/pipeline/pkg/taskinspect/inspect.go
  internal/tools/pipeline/pkg/taskinspect/inspect_test.go
  internal/tools/pipeline/pkg/taskresult/result.go
  internal/tools/pipeline/providers/reconciler/snippet.go
  internal/tools/pipeline/providers/reconciler/snippet_test.go
  internal/tools/pipeline/providers/reconciler/task_reconciler.go
  internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/framework.go
  internal/tools/pipeline/providers/reconciler/taskrun/framework_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/reconciler/taskrun/update.go
  internal/tools/pipeline/services/pipelinesvc/callback.go
  internal/tools/pipeline/services/pipelinesvc/callback_test.go
  internal/tools/pipeline/services/pipelinesvc/detail.go
  internal/tools/pipeline/spec/pipeline_task.go
  internal/tools/pipeline/spec/pipeline_task_test.go
Labels: refactor, approved

#5071 feat(dop): update devflow api
  api/proto/apps/devflow/flow/flow.proto
  apistructs/devflowrule.go
  apistructs/devflowrule_test.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/dop/providers/devflowrule/devflowrule.service.go
Labels: dop, feature, approved

#5072 feat(pipeline): do not fetch latest task from db at reconcile side
  internal/tools/pipeline/providers/reconciler/taskrun/framework.go
  internal/tools/pipeline/providers/reconciler/taskrun/update.go
Labels: pipeline, feature, approved

#5056 fix: overwrite current task with latest when status is ending
  modules/pipeline/providers/reconciler/task_reconciler.go
  modules/pipeline/providers/reconciler/task_reconciler_test.go
Labels: bugfix, approved

#5069 refactor: use grpc for msp tenant
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/orchestrator/bootstrap.yaml
  cmd/orchestrator/main.go
  internal/apps/admin/personal-workbench/provider.go
  internal/apps/admin/personal-workbench/services/workbench/project.go
  internal/apps/admin/personal-workbench/services/workbench/workbench.go
  internal/apps/dop/component-protocol/components/release-manage/releaseTable/render.go
  internal/tools/orchestrator/hepa/providers/global/provider.go
  internal/tools/orchestrator/hepa/services/global/impl/impl.go
  internal/tools/orchestrator/initialize.go
  internal/tools/orchestrator/provider.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: refactor

#5076 fix(pipeline): switch buildkitd certs namespace from default to erda namespace
  internal/apps/cmp/component-protocol/components/cmp-cluster-list/common/model.go
  internal/apps/cmp/component-protocol/components/cmp-cluster-list/list/render.go
  internal/apps/cmp/impl/clusters/clusterinfo.go
  internal/apps/cmp/impl/clusters/credential.go
  internal/apps/cmp/impl/clusters/credential_test.go
  internal/tools/orchestrator/hepa/k8s/k8s_adapter.go
  internal/tools/pipeline/conf/conf.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
  pkg/k8s-client-manager/provider.go
  pkg/k8s/interface_factory/discover.go
  pkg/k8s/interface_factory/ingress.go
  pkg/k8sclient/client.go
Labels: cmp, pipeline, hepa, orchestrator, bugfix

#5078 fix: reconciler dowatch-func memory leak
  modules/pipeline/pipengine/reconciler/listen.go
  modules/pipeline/pipengine/reconciler/teardown.go
Labels: bugfix, approved

#5080 fix: remove msp general ability
  cmd/msp/bootstrap.yaml
  cmd/msp/main.go
Labels: bugfix

#5079 fix(pkg): k8s-client-manager interface caller error
  internal/tools/monitor/core/diagnotor/controller/diagnotor.service.go
  internal/tools/monitor/core/diagnotor/controller/schedule.go
  pkg/k8s-client-manager/provider.go
Labels: monitor-stack, bugfix

#5059 feat: Add batch convert project, optimize project list query.
  internal/core/legacy/dao/application.go
  internal/core/legacy/dao/member.go
  internal/core/legacy/services/project/project.go
  internal/core/legacy/services/project/project_test.go
Labels: feature, approved

#5083 fix: add tenantService in hepa
  cmd/hepa/bootstrap.yaml
  cmd/hepa/main.go
Labels: bugfix

#5084 fix: Fix issue stream uc client, reorder issue table columns, code refactor.
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/props.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/props_test.go
  internal/apps/dop/providers/issue/core/provider.go
  internal/apps/dop/providers/issue/core/service.go
  internal/apps/dop/providers/issue/stream/common/model.go
  internal/apps/dop/providers/issue/stream/core/build.go
  internal/apps/dop/providers/issue/stream/core/event.go
  internal/apps/dop/providers/issue/stream/core/provider.go
Labels: bugfix

#5087 fix(pipeline): adjust custom script cpu request
  pipeline.yml
Labels: pipeline, bugfix, approved

#5074 fix(dop): Resolve permission issues
  internal/apps/devflow/flow/flow.service.go
Labels: dop, bugfix, approved

#5086 fix(dop,gittar): fix some bug of dev work flow
  internal/apps/devflow/flow/flow.service.go
  internal/tools/gittar/api/merge.go
Labels: dop, bugfix, approved, gittar

#5089 chore: codecov ignore legacy openapi specs
  codecov.yml
Labels: approved

#5091 fix(pipeline): Modify the notification link triggered by the pipeline execution
  conf/erda-configs/i18n/notify_item.yml
Labels: pipeline, bugfix, approved

#5093 fix: Fix issue type ticket and property instance convert.
  api/proto/dop/issue/core/core.proto
  internal/apps/dop/providers/issue/core/property.go
  internal/apps/dop/providers/issue/core/query/property.go
  internal/pkg/component-protocol/issueFilter/in_params.go
Labels: bugfix, approved

#5095 feat(protobuf): openapi proto add doc field for old spec migration
  api/proto/common/openapi.proto
Labels: feature, approved

#5090 fix(pipeline): Solve the problem of automatically opening the timing when on push
  internal/tools/pipeline/providers/cron/cron.service.go
  internal/tools/pipeline/providers/cron/cron.service_test.go
Labels: pipeline, bugfix, approved

#5100 fix(proto-go): cleanup generated proto-go code when dir structure adjusted
  .github/workflows/ci-it.yml
  api/proto-go/build.sh
Labels: bugfix, approved

#5099 chore: polish dingtalktest protobuf
  api/proto/pkg/dingtalktest/dingtalktest.proto
  cmd/erda-server/bootstrap.yaml
  internal/pkg/dingtalktest/dingtalktest.service.go
  internal/pkg/dingtalktest/provider.go
  internal/tools/openapi/legacy/api/apis/admin/admin_dingtalk.go
Labels: approved

#5097 fix(dop): Handling some special cases and bugs of R&D workflow
  internal/apps/devflow/flow/flow.service.go
  internal/apps/dop/providers/devflowrule/db/define.go
  internal/apps/dop/providers/devflowrule/devflowrule.service.go
  internal/apps/dop/providers/devflowrule/devflowrule.service_test.go
Labels: dop, bugfix, approved

#5103 fix: Fix issue mr relation, issue stream, get next issue state.
  internal/apps/dop/providers/issue/core/provider.go
  internal/apps/dop/providers/issue/core/provider_test.go
  internal/apps/dop/providers/issue/core/query/button.go
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/issue/stream/core/template.go
  internal/apps/dop/providers/issue/stream/core/template_test.go
  internal/apps/dop/providers/issue/stream/service.go
Labels: bugfix, approved

#5104 fix(proto): add missing service in proto of dingtalktest
  api/proto/pkg/dingtalktest/dingtalktest.proto
Labels: bugfix, approved

#5081 feat: Optimization Downgrade log
  internal/tools/monitor/core/log/query/log.query.service.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/storage_test.go
Labels: feature, approved

#5108 fix: Update work bench msp project target.
  internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/common/common.go
  internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workCards/provider.go
  internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workList/project.go
  internal/apps/admin/personal-workbench/component-protocol/components/personal-workbench/workList/provider.go
Labels: bugfix

#5106 feat(cluster-agent): support leader election
  cmd/cluster-agent/bootstrap.yaml
  internal/apps/cmp/conf/conf.go
  internal/apps/cmp/impl/clusters/proxy-deploy.go
  internal/core/cluster-manager/dialer/server/dialer_test.go
  internal/core/cluster-manager/dialer/server/tunnel-server_test.go
  internal/tools/cluster-agent/config/config.go
  internal/tools/cluster-agent/pkg/client/client.go
  internal/tools/cluster-agent/pkg/client/credential.go
  internal/tools/cluster-agent/pkg/leaderelection/leaderelection.go
  internal/tools/cluster-agent/provider.go
Labels: cluster-manager, feature

#5116 feat(dop): Pipeline execution records support branch filtering
  api/proto/dop/projectpipeline/projectpipeline.proto
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
Labels: dop, feature, approved

#5112 fix: Fix issue update in issue table, code refactor.
  bundle/issue.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/issue_query_test.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render_test.go
  internal/apps/dop/providers/issue/core/query/button.go
  internal/pkg/component-protocol/issueFilter/conditions.go
Labels: bugfix, approved

#5110 refactor: move common pipeline env to pkg
  internal/tools/pipeline/actionagent/define.go
  internal/tools/pipeline/actionagent/openapi.go
  internal/tools/pipeline/actionagent/openapi_test.go
  internal/tools/pipeline/actionagent/step_validate.go
  internal/tools/pipeline/actionagent/step_validate_test.go
  internal/tools/pipeline/pipengine/pvolumes/mesos.go
  internal/tools/pipeline/pkg/env/envs.go
  internal/tools/pipeline/pkg/env/envs_test.go
  internal/tools/pipeline/providers/edgepipeline_register/provider.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
Labels: refactor, approved

#5113 feat: pipeline display task param detail
  apistructs/pipeline_task.go
  internal/tools/pipeline/services/pipelinesvc/detail.go
  internal/tools/pipeline/spec/pipeline_task.go
  internal/tools/pipeline/spec/pipeline_task_test.go
Labels: feature, approved

#5107 fix: tips of finished time parse error
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/file_test.go
Labels: bugfix, approved

#5111 refactor: make resource pkg calculate pipeline task
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/tools/pipeline/initialize.go
  internal/tools/pipeline/pkg/action_info/passedDataWhenCreate.go
  internal/tools/pipeline/pkg/action_info/passedDataWhenCreate_test.go
  internal/tools/pipeline/provider.go
  internal/tools/pipeline/providers/cache/impl.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/resource/calcuate_test.go
  internal/tools/pipeline/providers/resource/calculate.go
  internal/tools/pipeline/providers/resource/interface.go
  internal/tools/pipeline/providers/resource/mock.go
  internal/tools/pipeline/providers/resource/provider.go
  internal/tools/pipeline/services/pipelinesvc/create.go
  internal/tools/pipeline/services/pipelinesvc/create_task.go
  internal/tools/pipeline/services/pipelinesvc/create_task_test.go
  internal/tools/pipeline/services/pipelinesvc/create_test.go
  internal/tools/pipeline/services/pipelinesvc/define.go
  internal/tools/pipeline/services/pipelinesvc/pipeline_resources.go
  internal/tools/pipeline/services/pipelinesvc/pipeline_resources_test.go
  internal/tools/pipeline/services/pipelinesvc/precheck_test.go
Labels: refactor, approved

#5114 fix(dop): Solve the problem that the new project pipeline cannot be timed
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
Labels: dop, bugfix, approved

#5122 revert: end listening log lines use context done instead of end tailflag (#4984)
  internal/tools/pipeline/actionagent/execute.go
  internal/tools/pipeline/actionagent/file_watch.go
  internal/tools/pipeline/actionagent/file_watch_collector.go
  internal/tools/pipeline/actionagent/filewatch/watch.go
Labels: approved

#5121 fix(dop): Cancel the scheduled task of the guide
  internal/apps/dop/providers/guide/provider.go
Labels: dop, bugfix, approved

#5119 fix(cluster-manager): retrywatcher resource version reference error
  internal/tools/cluster-agent/pkg/client/credential.go
  internal/tools/cluster-agent/pkg/client/credential_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/pipeline/providers/edgepipeline_register/cluster_access_key.go
Labels: cluster-manager, bugfix

#5123 fix: Set time location in issue update request for time comparison.
  internal/apps/dop/providers/issue/core/query/update.go
  internal/apps/dop/providers/issue/core/query/update_test.go
Labels: bugfix, approved

#5120 refactor(core-services): change org to grpc
  api/proto/core/org/org.proto
  cmd/core-services/bootstrap.yaml
  internal/core/legacy/endpoints/application.go
  internal/core/legacy/endpoints/endpoints.go
  internal/core/legacy/endpoints/notify.go
  internal/core/legacy/endpoints/organization.go
  internal/core/legacy/initialize.go
  internal/core/legacy/provider.go
  internal/core/org/db/client.go
  internal/core/org/db/org.go
  internal/core/org/db/org_cluster_relation.go
  internal/core/org/org.go
  internal/core/org/org.service.go
  internal/core/org/org.service_test.go
  internal/core/org/org_test.go
  internal/core/org/provider.go
  pkg/common/apis/context.go
  pkg/common/apis/header.go
Labels: refactor, approved

#5126 fix: Fix issue dashboard issue model import.
  internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/complexity.go
  internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/priority.go
  internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/severity.go
  internal/apps/dop/component-protocol/components/issue-dashboard/common/stackhandlers/stage.go
Labels: bugfix, approved

#5134 fix: Fix issue event create request, template default locale.
  internal/apps/dop/providers/issue/stream/core/event.go
  internal/apps/dop/providers/issue/stream/core/event_test.go
  internal/apps/dop/providers/issue/stream/core/template.go
  internal/apps/dop/providers/issue/stream/core/template_test.go
Labels: bugfix, approved

#5137 fix: use regexp2
  go.mod
  go.sum
  internal/apps/msp/apm/log-service/analysis/processors/regex/regex.go
Labels: bugfix

#5138 fix(dop): Solve the problem of getting org without permission
  internal/core/legacy/endpoints/application.go
  internal/core/legacy/endpoints/application_test.go
  internal/core/legacy/endpoints/mock_org_test.go
  internal/core/legacy/endpoints/notify.go
  internal/core/legacy/initialize.go
  internal/core/org/org.service.go
  internal/core/org/provider.go
Labels: dop, bugfix, approved

#5136 feat: transfer pipeline status to analyzed failed when precheck fails
  apistructs/pipeline_status.go
  internal/tools/pipeline/providers/run/can_manual_run.go
  internal/tools/pipeline/services/pipelinesvc/convert.go
  internal/tools/pipeline/services/pipelinesvc/convert_test.go
  internal/tools/pipeline/services/pipelinesvc/precheck.go
Labels: feature, approved

#5144 chore(protobuf): sort generated openapiv1 messages
  api/proto/openapiv1/admin/admin.proto
  api/proto/openapiv1/api_gateway/api.proto
  api/proto/openapiv1/cmp/cmp.proto
  api/proto/openapiv1/core_services/core.proto
  api/proto/openapiv1/dicehub/dicehub.proto
  api/proto/openapiv1/dop/dop.proto
  api/proto/openapiv1/dop_config_manage/dop.proto
  api/proto/openapiv1/dop_filetree/dop.proto
  api/proto/openapiv1/elf/elf.proto
  api/proto/openapiv1/fdp/fdp.proto
  api/proto/openapiv1/gittar/gittar.proto
  api/proto/openapiv1/hepa/hepa.proto
  api/proto/openapiv1/monitor/monitor.proto
  api/proto/openapiv1/msp/msp.proto
  api/proto/openapiv1/msp_apm_alert/msp.proto
  api/proto/openapiv1/msp_apm_block/msp.proto
  api/proto/openapiv1/msp_apm_exception/msp.proto
  api/proto/openapiv1/msp_apm_log_service/msp.proto
  api/proto/openapiv1/msp_apm_metric/msp.proto
  api/proto/openapiv1/msp_apm_trace/msp.proto
  api/proto/openapiv1/msp_tenant_project/msp.proto
  api/proto/openapiv1/officer/officer.proto
  api/proto/openapiv1/onedata/onedata.proto
  api/proto/openapiv1/openapi/openapi.proto
  api/proto/openapiv1/openapi_component_protocol/openapi.proto
  api/proto/openapiv1/orchestrator/orchestrator.proto
  api/proto/openapiv1/pipeline/pipeline.proto
  api/proto/openapiv1/testplatform_autotest/testplatform.proto
  api/proto/openapiv1/testplatform_testcase/testplatform.proto
  api/proto/openapiv1/testplatform_testplan/testplatform.proto
  api/proto/openapiv1/testplatform_testplan_rel/testplatform.proto
  api/proto/openapiv1/testplatform_testset/testplatform.proto
  api/proto/openapiv1/uc/uc.proto
  internal/tools/openapi/legacy/api/generate/generate_proto.go
Labels: approved

#5145 fix: openapi transport
  api/proto/core/hepa/endpoint_api/endpoint_api.proto
  internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/provider.go
  internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
  pkg/common/errors/data.go
Labels: hepa, openapi, bugfix, approved

#5143 feat(orchestrator,pipeline): custom registry credential secret name
  apistructs/k8s.go
  erda.yml
  internal/tools/orchestrator/conf/conf.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/namespace.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/secret.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/secret_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/type.go
  internal/tools/pipeline/conf/conf.go
  internal/tools/pipeline/pipengine/actionexecutor/logic/secret.go
  internal/tools/pipeline/pipengine/actionexecutor/logic/secret_test.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
  internal/tools/volume-provisioner/deploy/all-in-one.yaml
Labels: pipeline, orchestrator, feature

#5147 refactor: switch to kafka-v2
  cmd/monitor/collector/bootstrap.yaml
  internal/tools/monitor/core/collector/routes.go
  internal/tools/monitor/oap/collector/lib/compressor/reader.go
  internal/tools/monitor/oap/collector/lib/compressor/writer.go
  internal/tools/monitor/oap/collector/lib/protoparser/rawparser/parse.go
  internal/tools/monitor/oap/collector/lib/protoparser/rawparser/parse_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/stdout/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/auth.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/auth_test.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/clogs.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/collector.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/collector_validator_test.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/post.http
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
Labels: refactor

#4874 refactor(pipeline): query any match labels only once instead of multiple queries
  internal/tools/pipeline/dbclient/op_pipeline_labels.go
  internal/tools/pipeline/dbclient/op_pipeline_test.go
Labels: pipeline, refactor, approved

#5149 feat(devflow): devFlowNode add mergeRequestInfo
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/flow.service.go
Labels: feature, approved

#5151 chore: polish code to gen openapiv1 proto
  internal/tools/openapi/legacy/api/generate/generate_proto.go
  internal/tools/openapi/legacy/api/generate/generate_proto_test.go
Labels: approved

#5154 fix(openapi): solve path mismatch caused by case
  internal/tools/openapi/legacy/auth/token.go
  internal/tools/openapi/legacy/auth/token_test.go
Labels: openapi, bugfix, approved

#5152 feat: update version to 2.3
  VERSION
Labels: feature, approved
