Repository erda-project/erda, pull requests merged in 2022-11, with the labels that each got.

#5587 fix: cross-project leak; desensitize userinfo
  apistructs/member.go
  internal/apps/dop/providers/project/home/provider.go
  internal/apps/dop/providers/project/home/service.go
  internal/core/legacy/endpoints/member.go
  internal/core/legacy/endpoints/member_test.go
  internal/core/legacy/services/approve/approve.go
  internal/core/legacy/services/member/member.go
  internal/core/legacy/services/member/member_test.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: bugfix, approved

#5583 feat(dop): exported test case excel file add updatedAt filed
  conf/erda-configs/i18n/qa.json
  internal/apps/dop/services/i18n/i18n.go
  internal/apps/dop/services/testcase/export_excel.go
  internal/apps/dop/services/testcase/import_excel.go
Labels: dop, feature, approved

#5557 feat(pipeline): pipeline add canceling status
  apistructs/pipeline_status.go
  apistructs/pipeline_status_test.go
  cmd/erda-server/conf/i18n/cp/common.yaml
  conf/erda-configs/i18n/autotest_plan.json
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider_test.go
  internal/apps/dop/component-protocol/components/util/vars.go
  internal/apps/dop/component-protocol/components/util/vars_test.go
  internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/components/executeTaskTable/render.go
  internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/i18n/i18n.go
  internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/i18n/transfer.go
  internal/tools/pipeline/providers/leaderworker/impl_worker.go
  internal/tools/pipeline/providers/reconciler/pipeline_reconciler.go
Labels: pipeline, feature, approved

#5595 fix: rename alert rules index
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_cpu_ms/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_cpu_ms/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_cpu_ms/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_mem_ms/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_mem_ms/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_elasticsearch_mem_ms/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_cpu_ms/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_cpu_ms/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_cpu_ms/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_mem_ms/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_mem_ms/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_mem_ms/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_slave_status_ms/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_slave_status_ms/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_mysql_slave_status_ms/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_redis_mem_ms/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_redis_mem_ms/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon_micro_service/addon_redis_mem_ms/notify_template.yaml
Labels: bugfix

#5596 fix(orchestrator): create api-gateway ingress error
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/extension/v1beta1/ingress.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/ingress/networking/v1/ingress.go
Labels: orchestrator, bugfix

#5598 fix(dop): state issue event add labels
  apistructs/issue_stream_locale.go
  internal/apps/dop/endpoints/issue_callback.go
  internal/apps/dop/providers/issue/stream/common/model.go
  internal/apps/dop/providers/issue/stream/core/build.go
Labels: dop, bugfix

#5597 fix: modify default ttl
  internal/tools/monitor/core/settings/monitor.go
  internal/tools/monitor/core/settings/monitor_test.go
Labels: bugfix

#5600 fix: erda-cli need org Header and openapi host
  tools/cli/cmd/project_deployment_start.go
  tools/cli/cmd/project_deployment_stop.go
  tools/cli/command/context.go
  tools/cli/common/org.go
  tools/cli/common/project.go
Labels: bugfix

#5603 fix: format pipeline time in local
  internal/apps/dop/component-protocol/components/auto-test-plan-list/components/table/render.go
  internal/apps/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeHead/executeHistory/executeHistoryPop/executeHistoryTable/render.go
  internal/apps/dop/component-protocol/components/auto-test-scenes/rightPage/fileDetail/fileExecute/executeInfo/render.go
  internal/apps/dop/component-protocol/components/auto-test-space-list/components/recordTable/render.go
  internal/apps/dop/component-protocol/components/auto-test-space-list/components/spaceList/render.go
  internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/components/executeHistoryTable/render.go
  internal/core/openapi/legacy/component-protocol/scenarios/auto-test-plan-detail/components/executeInfo/render.go
  internal/tools/pipeline/actionagent/step_prepare.go
  internal/tools/pipeline/actionagent/step_prepare_test.go
  internal/tools/pipeline/actionagent/step_validate.go
Labels: bugfix, approved

#5602 fix: alert overview null output `%!s(<nil>)` error
  pkg/common/errors/server.go
  pkg/common/errors/server_test.go
Labels: bugfix

#5553 refactor: extension provider
  .gitignore
  api/proto/apps/gallery/gallery.proto
  api/proto/common/event.proto
  api/proto/core/extension/extension.proto
  api/proto/core/pipeline/action/action.proto
  apistructs/extention.go
  apistructs/pipeline_actions.go
  bundle/pipeline_action.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/apps/dop/dicehub/extension/extention.service.go
  internal/apps/dop/dicehub/extension/provider.go
  internal/apps/dop/dicehub/extension/provider_test.go
  internal/apps/dop/dicehub/extension/source_test.go
  internal/apps/dop/dicehub/release/provider.go
  internal/apps/dop/dicehub/release/release.service.go
  internal/apps/dop/services/apierrors/errors.go
  internal/apps/gallery/handler/funcs.go
  internal/apps/gallery/handler/funcs_test.go
  internal/apps/gallery/handler/gallery.go
  internal/apps/gallery/provider.go
  internal/pkg/extension/action.go
  internal/pkg/extension/action_test.go
  internal/pkg/extension/apierrors/errors.go
  internal/pkg/extension/db/client.go
  internal/pkg/extension/db/extension.go
  internal/pkg/extension/db/table.go
  internal/pkg/extension/extension.service.go
  internal/pkg/extension/extension.service_test.go
  internal/pkg/extension/interface.go
  internal/pkg/extension/menu.go
  internal/pkg/extension/provider.go
  internal/pkg/extension/source.go
  internal/pkg/extension/source_test.go
  internal/tools/pipeline/pkg/action_info/passedDataWhenCreate.go
  internal/tools/pipeline/pkg/action_info/passedDataWhenCreate_test.go
  internal/tools/pipeline/providers/actionmgr/action.service.go
  internal/tools/pipeline/providers/actionmgr/action.service_test.go
  internal/tools/pipeline/providers/actionmgr/common.go
  internal/tools/pipeline/providers/actionmgr/common_test.go
  internal/tools/pipeline/providers/actionmgr/db/client.go
  internal/tools/pipeline/providers/actionmgr/db/client_test.go
  internal/tools/pipeline/providers/actionmgr/impl.go
  internal/tools/pipeline/providers/actionmgr/impl_test.go
  internal/tools/pipeline/providers/actionmgr/interface.go
  internal/tools/pipeline/providers/actionmgr/mock.go
  internal/tools/pipeline/providers/actionmgr/provider.go
  internal/tools/pipeline/providers/actionmgr/refresh.go
  internal/tools/pipeline/providers/pipeline/create_v2.go
  internal/tools/pipeline/providers/pipeline/precheck.go
  internal/tools/pipeline/providers/pipeline/precheck_test.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  pkg/mock/extension_mock.go
Labels: refactor, approved

#5601 feat: update elasticsearch addon dashboard
  cmd/monitor/monitor/conf/chartview/runtime/addon-es.json
Labels: feature

#5607 feat: metric query optimize slow query
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_tenant_tables.sql.tpl
Labels: feature

#5609 feat: metric query optimize slow query
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_tenant_tables.sql.tpl
Labels: feature

#5608 feature: canal operator
  apistructs/service.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/canal_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/canal_validate.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/groupversion_info.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/zz_generated.deepcopy.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: approved

#5610 fix: set runtime domain successfully but invisible
  internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
  internal/tools/orchestrator/hepa/repository/service/gateway_package_api_service.go
  internal/tools/orchestrator/hepa/services/domain/impl/impl.go
Labels: bugfix

#5611 feat: metric query optimize slow query
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_tenant_tables.sql.tpl
Labels: feature, approved

#5599 feat(orchestrator): upgrade es operator and add metric exporter
  go.mod
  go.sum
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/groupversion_info.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/cr.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/interface.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_status_test.go
  pkg/k8sclient/scheme/register.go
Labels: orchestrator, feature

#5614 feat: addon-mysql monitor
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
Labels: feature

#5616 feat: Update DingTalk QR code
  docs/assets/dingtalk.png
Labels: feature, approved

#5613 fix: extension record not found type judgment error
  internal/pkg/extension/db/extension.go
  internal/pkg/extension/extension.service.go
Labels: bugfix

#5618 fix: create addon alert error
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/alert_rule.yaml
Labels: bugfix

#5606 feat(pipeline): pipeline support debug on failure
  api/proto/core/pipeline/base/base.proto
  internal/tools/pipeline/actionagent/define.go
  internal/tools/pipeline/actionagent/execute.go
  internal/tools/pipeline/actionagent/exit.go
  internal/tools/pipeline/actionagent/file_watch_test.go
  internal/tools/pipeline/actionagent/filewatch/watch.go
  internal/tools/pipeline/actionagent/pull_bootstrap_info.go
  internal/tools/pipeline/actionagent/step_prepare.go
  internal/tools/pipeline/pkg/debug/breakpoint.go
  internal/tools/pipeline/pkg/debug/breakpoint_test.go
  internal/tools/pipeline/providers/pipeline/convert.go
  internal/tools/pipeline/providers/pipeline/create_v2.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
  internal/tools/pipeline/providers/task/task.service.go
  internal/tools/pipeline/spec/pipeline_extra.go
  internal/tools/pipeline/spec/pipeline_task.go
  pkg/parser/pipelineyml/define.go
Labels: pipeline, feature, approved

#5620 fix(msp): WRITE_LOG_TO_CLICKHOUSE_ENABLE default set to true
  cmd/erda-server/bootstrap.yaml
Labels: msp, bugfix

#5617 fix: over permission
  api/proto/common/openapi.proto
  api/proto/core/monitor/dataview/dataview.proto
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  internal/core/openapi/openapi-ng/auth/auth.go
  internal/core/openapi/openapi-ng/auth/over_permission/match/query_value.go
  internal/core/openapi/openapi-ng/auth/over_permission/match/registry.go
  internal/core/openapi/openapi-ng/auth/over_permission/match/registry_test.go
  internal/core/openapi/openapi-ng/auth/over_permission/org/org.go
  internal/core/openapi/openapi-ng/auth/over_permission/org/org_test.go
  internal/core/openapi/openapi-ng/auth/over_permission/org/provider.go
  internal/core/openapi/openapi-ng/routes/proto/proto.go
Labels: bugfix, approved

#5619 fix: internal client request pipeline grpc interface with bundle context
  internal/apps/dop/endpoints/pipeline.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
Labels: bugfix, approved
