Repository erda-project/erda, pull requests merged in 2022-08, with the labels that each got.

#5310 feat: config uc migration lint
  .erda/migrations/config.yml
Labels: feature, install

#5306 refactor: Merge uc-adaptor with erda-server, initial when uc is used.
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/uc-adaptor/bootstrap.yaml
  cmd/uc-adaptor/common-conf
  cmd/uc-adaptor/conf/.gitkeep
  cmd/uc-adaptor/main.go
  erda.yml
  internal/core/user/impl/uc/uc-adaptor/provider.go
  pipeline.yml
Labels: refactor, approved

#5304 refactor: Move standard issue filter to dop.
  internal/apps/dop/component-protocol/components/all.go
  internal/apps/dop/component-protocol/components/app-runtime/advanceFilter/advanceFilter.go
  internal/apps/dop/component-protocol/components/issue-manage/common/gshelper/helper.go
  internal/apps/dop/component-protocol/components/issue-manage/issueFilter/provider.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/condition.go
  internal/apps/dop/component-protocol/components/project-runtime/advanceFilter/advanceFilter.go
  internal/apps/dop/component-protocol/components/requirement-task-overview/common/gshelper/helper.go
  internal/apps/dop/component-protocol/components/requirement-task-overview/container/info/render.go
  internal/apps/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
  internal/apps/dop/component-protocol/standard-components/condition/input.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/filterset.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/filterset_test.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/gshelper/helper.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/in_params.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/options.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
Labels: refactor, approved

#5302 refactor: Remove issue deprecated service and dao, code refactor.
  bundle/workbench.go
  internal/apps/dop/dao/issue.go
  internal/apps/dop/dao/issue_app_relation.go
  internal/apps/dop/dao/issue_issue_relation.go
  internal/apps/dop/dao/issue_stage.go
  internal/apps/dop/dao/issue_state.go
  internal/apps/dop/dao/issue_state_circulation.go
  internal/apps/dop/dao/issue_stream.go
  internal/apps/dop/dao/issue_subscriber.go
  internal/apps/dop/dao/issue_testplancaserel_rel.go
  internal/apps/dop/endpoints/application.go
  internal/apps/dop/endpoints/endpoints.go
  internal/apps/dop/endpoints/organization.go
  internal/apps/dop/endpoints/project.go
  internal/apps/dop/endpoints/workbench.go
  internal/apps/dop/initialize.go
  internal/apps/dop/providers/issue/dao/stream.go
  internal/apps/dop/services/issue/button.go
  internal/apps/dop/services/issue/convert.go
  internal/apps/dop/services/issue/issue.go
  internal/apps/dop/services/issue/state.go
  internal/apps/dop/services/issuestate/issue_state_relation.go
  internal/apps/dop/services/issuestate/issuestate.go
  internal/apps/dop/services/issuestate/issuestate_mock.go
  internal/apps/dop/services/issuestate/issuestate_test.go
  internal/apps/dop/services/iteration/iteration.go
  internal/apps/dop/services/testcase/recycle.go
  internal/apps/dop/services/testcase/service.go
  internal/apps/dop/services/testcase/update.go
  internal/apps/dop/services/testplan/testlan_case_rel.go
  internal/apps/dop/services/testplan/testlan_case_rel_test.go
  internal/apps/dop/services/testplan/testplan.go
Labels: refactor, approved

#5303 fix(dop): set `isUpdate` false value when add test
  internal/apps/dop/component-protocol/components/auto-test-plan-list/components/addButton/render.go
  internal/apps/dop/component-protocol/scenarios/auto-test-plan-list.yml
Labels: dop, bugfix, approved

#5312 refactor: metrics query from ck
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
  internal/tools/monitor/dashboard/org-apis/clickhouse_source_test.go
  internal/tools/monitor/dashboard/org-apis/const.go
  internal/tools/monitor/dashboard/org-apis/host.go
  internal/tools/monitor/dashboard/org-apis/provider.go
  internal/tools/monitor/dashboard/org-apis/routes.go
  internal/tools/monitor/dashboard/org-apis/source.go
Labels: refactor

#5317 fix: deplicate config
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
  internal/tools/monitor/dashboard/org-apis/clickhouse_source_test.go
Labels: bugfix

#5319 feat(cluster-manager): cluster-manager move from core to tools
  .github/workflows/ci-it.yml
  cmd/cluster-manager/register.go
  internal/tools/cluster-manager/cluster/apierrors.go
  internal/tools/cluster-manager/cluster/cluster.go
  internal/tools/cluster-manager/cluster/cluster.service.go
  internal/tools/cluster-manager/cluster/db/cluster.go
  internal/tools/cluster-manager/cluster/db/table.go
  internal/tools/cluster-manager/cluster/provider.go
  internal/tools/cluster-manager/dialer/auth/auth.go
  internal/tools/cluster-manager/dialer/config/config.go
  internal/tools/cluster-manager/dialer/provider.go
  internal/tools/cluster-manager/dialer/server/client_data.go
  internal/tools/cluster-manager/dialer/server/client_data_test.go
  internal/tools/cluster-manager/dialer/server/dialer_test.go
  internal/tools/cluster-manager/dialer/server/tunnel-server.go
  internal/tools/cluster-manager/dialer/server/tunnel-server_test.go
Labels: cluster-manager, feature

#5320 feat: remove pkg clientgo
  internal/tools/orchestrator/ecp/services/edge/addon_mysql_edge.go
  internal/tools/orchestrator/ecp/services/edge/application.go
  internal/tools/orchestrator/ecp/services/edge/edge.go
  internal/tools/orchestrator/ecp/services/edge/site.go
  internal/tools/orchestrator/ecp/services/kubernetes/nodepool.go
  internal/tools/orchestrator/ecp/services/kubernetes/uniteddeployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/event/event.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/scaledobject.go
  pkg/clientgo/apis/flinkoperator/v1beta1/doc.go
  pkg/clientgo/apis/flinkoperator/v1beta1/register.go
  pkg/clientgo/apis/flinkoperator/v1beta1/types.go
  pkg/clientgo/apis/flinkoperator/v1beta1/zz_generated.deepcopy.go
  pkg/clientgo/clientset.go
  pkg/clientgo/clientset/clientset.go
  pkg/clientgo/clientset/versioned/doc.go
  pkg/clientgo/clientset/versioned/scheme/doc.go
  pkg/clientgo/clientset/versioned/scheme/register.go
  pkg/clientgo/clientset/versioned/typed/config/v1alpha2/config_client.go
  pkg/clientgo/clientset/versioned/typed/flinkoperator/v1beta1/doc.go
  pkg/clientgo/clientset/versioned/typed/flinkoperator/v1beta1/flinkcluster.go
  pkg/clientgo/clientset/versioned/typed/flinkoperator/v1beta1/flinkoperator_client.go
  pkg/clientgo/clientset/versioned/typed/flinkoperator/v1beta1/generated_expansion.go
  pkg/clientgo/clientset/versioned/typed/networking/v1alpha3/networking_client.go
  pkg/clientgo/clientset/versioned/typed/networking/v1beta1/networking_client.go
  pkg/clientgo/clientset/versioned/typed/openyurt/v1alpha1/apps_client.go
  pkg/clientgo/clientset/versioned/typed/openyurt/v1alpha1/doc.go
  pkg/clientgo/clientset/versioned/typed/openyurt/v1alpha1/generated_expansion.go
  pkg/clientgo/clientset/versioned/typed/openyurt/v1alpha1/nodepool.go
  pkg/clientgo/clientset/versioned/typed/openyurt/v1alpha1/uniteddeployment.go
  pkg/clientgo/clientset/versioned/typed/rbac/v1alpha1/rbac_client.go
  pkg/clientgo/clientset/versioned/typed/security/v1beta1/security_client.go
  pkg/clientgo/customclient/clientset.go
  pkg/clientgo/discovery/discovery_client.go
  pkg/clientgo/kubernetes/apps/v1/apps_client.go
  pkg/clientgo/kubernetes/batch/v1/batch_client.go
  pkg/clientgo/kubernetes/clientset.go
  pkg/clientgo/kubernetes/core/v1/core_client.go
  pkg/clientgo/kubernetes/extensions/v1beta1/extensions_client.go
  pkg/clientgo/kubernetes/policy/v1beta1/policy_client.go
  pkg/clientgo/restclient/config.go
  pkg/clientgo/restclient/inet_rest_client.go
  pkg/k8sclient/apis/keda/v1alpha1/condition_types.go
  pkg/k8sclient/apis/keda/v1alpha1/groupversion_info.go
  pkg/k8sclient/apis/keda/v1alpha1/gvkr_types.go
  pkg/k8sclient/apis/keda/v1alpha1/readme_before_edit_this_package.md
  pkg/k8sclient/apis/keda/v1alpha1/scaledjob_types.go
  pkg/k8sclient/apis/keda/v1alpha1/scaledobject_types.go
  pkg/k8sclient/apis/keda/v1alpha1/triggerauthentication_types.go
  pkg/k8sclient/apis/keda/v1alpha1/withtriggers_types.go
  pkg/k8sclient/apis/keda/v1alpha1/zz_generated.deepcopy.go
  pkg/k8sclient/apis/openyurt/v1alpha1/doc.go
  pkg/k8sclient/apis/openyurt/v1alpha1/groupversion_info.go
  pkg/k8sclient/apis/openyurt/v1alpha1/nodepool_types.go
  pkg/k8sclient/apis/openyurt/v1alpha1/uniteddeployment_types.go
  pkg/k8sclient/apis/openyurt/v1alpha1/well_known_labels_annotations.go
  pkg/k8sclient/apis/openyurt/v1alpha1/zz_generated.deepcopy.go
  pkg/k8sclient/scheme/register.go
Labels: feature

#5313 feat: write bool type metric
  internal/tools/monitor/oap/collector/lib/typeconvert/convertor.go
Labels: feature

#5311 feat(dop): Modify R&D Workflow
  .erda/migrations/dop/20220801-devflow.sql
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/db/client.go
  internal/apps/devflow/flow/db/define.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
  internal/apps/devflow/flow/provider.go
Labels: dop, feature, approved

#5254 feat(orchestrator): refactor pod module in scheduler with client-go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/pod/pod.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/pod/pod_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/resourceinfo/resourceinfo.go
  internal/tools/orchestrator/services/runtime/runtime_test.go
Labels: orchestrator, feature

#5298 refactor(dicehub): pipeline template to dop provider
  api/proto/dop/pipelinetemplate/template.proto
  api/proto/openapiv1/dicehub/dicehub.proto
  apistructs/pipeline_templates.go
  bundle/dicehub.go
  cmd/dop/bootstrap.yaml
  cmd/dop/main.go
  internal/apps/dop/dicehub/endpoints/endpoints.go
  internal/apps/dop/dicehub/endpoints/pipeline_template.go
  internal/apps/dop/dicehub/initialize.go
  internal/apps/dop/dicehub/service/apierrors/errors.go
  internal/apps/dop/dicehub/service/template/pipeline_template.go
  internal/apps/dop/dicehub/service/template/pipeline_template_test.go
  internal/apps/dop/providers/pipelinetemplate/db/client.go
  internal/apps/dop/providers/pipelinetemplate/db/pipeline_template.go
  internal/apps/dop/providers/pipelinetemplate/interface.go
  internal/apps/dop/providers/pipelinetemplate/pipeline_template.go
  internal/apps/dop/providers/pipelinetemplate/pipeline_template_test.go
  internal/apps/dop/providers/pipelinetemplate/provider.go
  internal/apps/dop/services/apierrors/errors.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_pipeline_template_apply.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_pipeline_template_version_get.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_pipeline_template_version_query.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_pipeline_template_version_render.go
  pkg/parser/pipelineyml/visitor_snippet.go
Labels: refactor, approved

#5260 feat: Rule executors set up in callback, add dev flow callback func.
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
  internal/apps/devflow/flow/flow_callback.go
  internal/apps/devflow/flow/provider.go
  internal/apps/dop/endpoints/endpoints.go
  internal/apps/dop/endpoints/issue_callback.go
  internal/apps/dop/endpoints/mock_rule_test.go
  internal/apps/dop/endpoints/pipeline_callback.go
  internal/apps/dop/endpoints/repo_callback.go
  internal/apps/dop/endpoints/rule.go
  internal/apps/dop/endpoints/rule_test.go
  internal/apps/dop/initialize.go
  internal/apps/dop/provider.go
Labels: feature, approved

#5324 fix: pod chartview config
  cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
Labels: bugfix, approved

#5326 fix(dop): idempotent create devFlow and fix some bugs
  internal/apps/devflow/flow/db/define.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
Labels: dop, bugfix, approved

#5329 fix: charview of runtime
  cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
Labels: bugfix, approved

#5265 refactor: pipeline custom command line support for newlines
  apistructs/pipeline_yml.go
  internal/apps/dop/services/migrate/scene_step.go
  internal/tools/pipeline/actionagent/define.go
  internal/tools/pipeline/actionagent/pull_bootstrap_info.go
  internal/tools/pipeline/actionagent/step_logic.go
  internal/tools/pipeline/actionagent/step_prepare.go
  internal/tools/pipeline/actionagent/step_prepare_test.go
  internal/tools/pipeline/actionagent/step_validate.go
  internal/tools/pipeline/actionagent/step_validate_test.go
  internal/tools/pipeline/endpoints/pipeline_task.go
  pkg/parser/pipelineyml/define.go
  pkg/parser/pipelineyml/define_test.go
  pkg/parser/pipelineyml/visitor_ref_op.go
Labels: refactor, approved

#5325 refactor(core): file service
  api/proto/common/http.proto
  api/proto/core/file/file.proto
  api/proto/openapiv1/core/services/core_services.proto
  apistructs/file.go
  bundle/audit.go
  bundle/dicefile.go
  bundle/dicefile_test.go
  bundle/utils.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  go.mod
  go.sum
  internal/apps/dop/dicehub/service/publish_item/offline_helper.go
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/services/apierrors/errors.go
  internal/apps/dop/services/autotest_v2/export.go
  internal/apps/dop/services/autotest_v2/import.go
  internal/apps/dop/services/autotest_v2/import_test.go
  internal/apps/dop/services/certificate/certificate.go
  internal/apps/dop/services/project/export_template_test.go
  internal/apps/dop/services/project/project_package.go
  internal/apps/dop/services/project/project_template.go
  internal/apps/dop/services/testcase/export.go
  internal/apps/dop/services/testcase/import.go
  internal/core/file/cleanup.go
  internal/core/file/db/db.go
  internal/core/file/db/file.go
  internal/core/file/example/normal.png
  internal/core/file/example/xss-svg.svg
  internal/core/file/file.http
  internal/core/file/file.service.go
  internal/core/file/file.service_delete.go
  internal/core/file/file.service_download.go
  internal/core/file/file.service_download_test.go
  internal/core/file/file.service_test.go
  internal/core/file/file.service_upload.go
  internal/core/file/file.service_upload_test.go
  internal/core/file/filetype.go
  internal/core/file/filetype_test.go
  internal/core/file/filetypes/types.go
  internal/core/file/http.go
  internal/core/file/kms.go
  internal/core/file/provider.go
  internal/core/legacy/conf/conf.go
  internal/core/legacy/endpoints/coreservices.http
  internal/core/legacy/endpoints/endpoints.go
  internal/core/legacy/initialize.go
  internal/core/legacy/services/filesvc/svc.go
  internal/tools/gittar/api/backup.go
  internal/tools/gittar/models/backup.go
  internal/tools/monitor/core/dataview/dashboard_file.go
  internal/tools/monitor/core/dataview/dashboard_file_test.go
  internal/tools/pipeline/action-runner/apis.go
  internal/tools/pipeline/actionagent/callback_reporter.go
  internal/tools/pipeline/actionagent/uploaddir.go
  pkg/http/httpserver/errorresp/response.go
  pkg/http/httpserver/response.go
Labels: refactor

#5322 feat: Add api config jsonnet snippet, issue participants in event data.
  api/proto/dop/issue/core/core.proto
  apistructs/event.go
  cmd/dop/conf/i18n/cp/common.yaml
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/filterset.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
  internal/apps/dop/providers/issue/core/property.go
  internal/apps/dop/providers/issue/core/relation.go
  internal/apps/dop/providers/issue/core/subscribe.go
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/issue/stream/common/model.go
  internal/apps/dop/providers/issue/stream/core/event.go
  internal/apps/dop/providers/issue/stream/core/event_test.go
  internal/apps/dop/providers/rule/actions/api/api.go
  internal/apps/dop/providers/rule/actions/api/api_test.go
  internal/apps/dop/providers/rule/db/record.go
  internal/apps/dop/providers/rule/db/rule.go
  internal/apps/dop/providers/rule/executor/execute.go
  internal/apps/dop/providers/rule/executor/expr.go
  internal/apps/dop/providers/rule/executor/expr_test.go
  internal/apps/dop/providers/rule/provider.go
  internal/apps/dop/providers/rule/rule.service.go
Labels: feature

#5327 feat: add clickhouse metric to trace instrumentation
  cmd/monitor/monitor/bootstrap.yaml
  internal/apps/msp/apm/trace/query/trace.service.go
  internal/tools/monitor/core/metric/model/result.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_elasticsearch_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/query.go
  internal/tools/monitor/core/metric/query/es-tsql/tsql-test/main.go
  internal/tools/monitor/core/metric/query/metricmeta/metric_group.go
  internal/tools/monitor/core/metric/query/metricq/provider.go
  internal/tools/monitor/core/metric/query/metricq/routes.go
  internal/tools/monitor/core/metric/query/query/search.go
  internal/tools/monitor/core/metric/storage/clickhouse/provider.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
  internal/tools/monitor/core/metric/storage/elasticsearch/query.go
  internal/tools/monitor/core/metric/storage/elasticsearch/query_test.go
  pkg/common/trace/tool.go
  pkg/common/trace/tracing.go
Labels: feature

#5281 feat(dop): support org-level search
  api/proto/dop/search/search.proto
  cmd/dop/bootstrap.yaml
  cmd/dop/main.go
  internal/apps/dop/providers/issue/core/query/paging.go
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/rule/provider.go
  internal/apps/dop/providers/search/handlers/define.go
  internal/apps/dop/providers/search/handlers/issue/issue.go
  internal/apps/dop/providers/search/handlers/issue/issue_test.go
  internal/apps/dop/providers/search/provider.go
  internal/apps/dop/providers/search/search.go
  internal/apps/dop/providers/search/search_test.go
  internal/apps/dop/services/apierrors/errors.go
  pkg/mock/issue_query_mock.go
Labels: dop, feature, approved

#5330 chore: golangci-lint skip cache
  .github/workflows/ci-it.yml
  internal/tools/pipeline/actionagent/callback.go
Labels: approved

#5331 fix(files): recover lost files routes for openapi proxy use
  internal/core/openapi/legacy/api/apis/files/download.go
  internal/core/openapi/legacy/api/apis/files/download_v2.go
  internal/core/openapi/legacy/api/apis/files/head.go
  internal/core/openapi/legacy/api/apis/files/upload.go
Labels: bugfix, approved

#5332 fix: fix metric query nil point error
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
Labels: bugfix

#5328 fix(dop): Solve the problem that the merge request page fails to get the workflow
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/db/define.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
Labels: dop, bugfix, approved

#5334 fix: agent change dir to task workdir before run commands
  internal/tools/pipeline/actionagent/step_logic.go
  internal/tools/pipeline/actionagent/step_logic_test.go
Labels: bugfix

#5336 fix: pipelineyml graph display action shell
  apistructs/pipeline_yml.go
  pkg/parser/pipelineyml/graph_pipelineyml.go
Labels: bugfix, approved

#5335 fix: Add api action is https, add output for empty nodes.
  internal/apps/dop/providers/rule/actions/api/api.go
  internal/apps/dop/providers/rule/executor/execute.go
  internal/apps/dop/providers/rule/executor/execute_test.go
Labels: bugfix, approved

#5337 fix: httpserver response userid
  internal/core/file/http.go
  pkg/http/httpserver/response.go
Labels: bugfix, approved

#5338 fix: pipelineyml parse fronted action add shell field
  pkg/parser/pipelineyml/graph_pipelineyml.go
Labels: bugfix

#5341 feat: update git-sync.yml
  .github/workflows/git-sync.yml
Labels: feature, approved

#5339 fix: agent shell commands failed to load variables
  internal/tools/pipeline/actionagent/step_prepare.go
  internal/tools/pipeline/actionagent/step_prepare_test.go
Labels: bugfix, approved

#5340 fix: add i18n for runtime-container-detail charview
  cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
Labels: bugfix, approved

#5333 refactor: query alert pod info from ck
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/alert/details-apis/alertdetail.service.go
  internal/tools/monitor/core/alert/details-apis/clickhouse_source.go
  internal/tools/monitor/core/alert/details-apis/clickhouse_source_test.go
  internal/tools/monitor/core/alert/details-apis/provider.go
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
Labels: refactor

#5347 feat: update git-sync.yml
  .github/workflows/git-sync.yml
Labels: feature

#5346 feat(dop): qa sonar store quality gate result
  .erda/migrations/qa/20220805-qa-sonar-gate-result.sql
  apistructs/qa.go
  internal/apps/dop/dbclient/sonar.go
  internal/apps/dop/endpoints/sonar.go
  internal/apps/dop/endpoints/sonar_test.go
Labels: dop, feature

#5342 feat(orchestrator): optimize k8s plugin resourceinfo and namespace
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/daemonset/daemonset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/interface.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/sourcecov/mock/namespaceutil_mock.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/sourcecov/sourcecov_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/namespace.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/namespace/namespace.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/namespace/namespace_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/node/node.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/resourceinfo/resourceinfo.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/resourceinfo/resourceinfo_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/role/role.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/rolebinding/rolebinding.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
Labels: orchestrator, feature

#5353 feat: support open-telemetry trace event
  api/proto/oap/trace/tracing.proto
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
  internal/apps/msp/apm/trace/query/trace.service.go
  internal/tools/monitor/core/metric/query/query/search.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/oap/collector/lib/protoparser/oapspan/event.go
  internal/tools/monitor/oap/collector/lib/protoparser/oapspan/event_test.go
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/interceptor.go
Labels: feature

#5356 feat: remove manifest of quick-start
  quick-start/docker-compose.yml
  quick-start/env
  quick-start/kratos/identity.schema.json
  quick-start/kratos/kratos.yml
  quick-start/nginx.conf
  quick-start/quick-start.sh
Labels: feature

#5354 fix: Fix internal user nil response when request is empty.
  internal/core/user/impl/kratos/service.go
  internal/core/user/impl/kratos/service_test.go
  internal/core/user/impl/uc/service.go
  internal/core/user/provider.go
Labels: bugfix, approved

#5360 fix: chartview of node detail
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail-origin.json
Labels: bugfix

#5361 fix: charview of addon-mysql
  cmd/monitor/monitor/conf/chartview/runtime/addon-mysql.json
Labels: bugfix, approved

#5318 feat(orchestrator): merge runtime serviceinstance and podinstance
  apistructs/container.go
  apistructs/service_job_status.go
  internal/tools/orchestrator/components/podscaler/manual_scale.go
  internal/tools/orchestrator/components/runtime/mock/mock_sg.go
  internal/tools/orchestrator/components/runtime/runtime.service.go
  internal/tools/orchestrator/dbclient/vpa.go
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
  internal/tools/orchestrator/endpoints/server_handler.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/job.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: orchestrator, feature, approved

#5362 fix: chartview of redis and es
  cmd/monitor/monitor/conf/chartview/runtime/addon-es.json
  cmd/monitor/monitor/conf/chartview/runtime/addon-redis.json
Labels: bugfix

#5364 chore: add `TRACE_HOOK_ENABLE` env for trace hook
  erda.yml
  go.mod
  go.sum
Labels: approved

#5358 fix(dop): fix the bug of rejoin temp branch
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/db/define.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
Labels: dop, bugfix, safe to sync

#5366 fix: worker set timeout when report heartbeat
  internal/tools/pipeline/providers/leaderworker/heartbeat.go
Labels: bugfix, approved

#5369 fix(dop): Compatible with temporary branches being deleted
  .erda/migrations/dop/20220809-devflow-index.sql
  internal/apps/devflow/flow/db/define.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
Labels: dop, bugfix, approved

#5370 feat(dop): R&D workflow support deletion
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
Labels: dop, feature, approved

#5374 chore: remove some outdated components in release
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  pipeline.yml
Labels: approved

#5372 fix: kill pod then call get_service_pods immediately may panic
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
Labels: bugfix, approved

#5359 refactor: manual trigger mode pipeline use run-user permission
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/endpoints/pipeline.go
  internal/tools/pipeline/spec/pipeline.go
  internal/tools/pipeline/spec/pipeline_test.go
Labels: refactor, approved

#5375 feat: add frontend chartview
  cmd/monitor/monitor/conf/chartview/frontend/ajax_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/page_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/page_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/page_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/script_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/script_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/script_top_cpm.json
Labels: feature, approved

#5376 fix: number of nodes is less than actual
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
Labels: bugfix

#5371 fix: fix rateps filter by zero
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/storage/clickhouse/provider.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
Labels: bugfix

#5378 fix: openapi check injected redis field when initializing
  go.mod
  go.sum
  internal/core/openapi/openapi-ng/auth/uc-session/provider.go
Labels: bugfix, approved

#5383 fix: unite i18n configs for dop and personal-workbench
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/personal-workbench.yaml
  internal/apps/admin/personal-workbench/i18n/common/common.yaml
  internal/apps/admin/personal-workbench/i18n/files/common.yaml
  internal/apps/admin/personal-workbench/provider.go
  internal/apps/dop/provider.go
  internal/apps/dop/providers/issue/stream/core/provider.go
Labels: bugfix, approved

#5377 feat: Add rule actor, call outgoing api by actor.
  .erda/migrations/config.yml
  .erda/migrations/dop/20220808-erda_rule_actor.sql
  api/proto/dop/rule/rule.proto
  internal/apps/dop/endpoints/issue_callback.go
  internal/apps/dop/providers/rule/actions/api/api.go
  internal/apps/dop/providers/rule/actions/api/api_test.go
  internal/apps/dop/providers/rule/db/record.go
  internal/apps/dop/providers/rule/db/rule.go
  internal/apps/dop/providers/rule/executor/execute.go
  internal/apps/dop/providers/rule/executor/execute_test.go
  internal/apps/dop/providers/rule/executor/expr.go
  internal/apps/dop/providers/rule/rule.service.go
Labels: feature, approved

#5387 fix: pod & node chartview of cmp
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-nodeDetail.json
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
Labels: bugfix, approved

#5388 fix: Fix rule api reset headers when header is nil.
  internal/apps/dop/providers/rule/actions/api/api.go
  internal/apps/dop/providers/rule/actions/api/api_test.go
Labels: bugfix, approved

#5382 refactor: add clickhouse source for topology
  cmd/monitor/monitor/bootstrap.yaml
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/tools/monitor/apm/topology/clickhousesource/clickhouse_source.go
  internal/tools/monitor/apm/topology/clickhousesource/clickhouse_source_test.go
  internal/tools/monitor/apm/topology/provider.go
  internal/tools/monitor/apm/topology/topology.go
  internal/tools/monitor/apm/topology/topology_v2.go
  internal/tools/monitor/apm/topology/topology_v2_test.go
  pkg/ckhelper/sqlbuilder.go
  pkg/ckhelper/sqlbuilder_test.go
Labels: refactor

#5389 fix: number of nodes and pod is less than actual
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
Labels: bugfix

#5384 fix(dop): add transaction to devflow delete
  internal/apps/devflow/flow/db/define.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
  internal/apps/devflow/flow/provider.go
Labels: dop, bugfix, approved

#5379 fix(orchestrator): failed deploy release from gallery with cross project
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/endpoints/deployment_order.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_cancel.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_cancel_test.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_create.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_create_test.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_cron.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_cron_test.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_get.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_get_test.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_list.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_release_test.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_render.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_render_test.go
Labels: orchestrator, bugfix

#5391 fix(erda-server): erda-server missing route
  api/proto/core/dicehub/image/image.proto
  api/proto/core/dicehub/release/getdice.proto
  api/proto/core/org/org.proto
  internal/apps/admin/provider.go
  internal/apps/dop/dicehub/initialize.go
  internal/apps/dop/initialize.go
  internal/core/legacy/initialize.go
  pkg/http/httpserver/router.go
Labels: bugfix

#5386 fix: exinclude cmp org condition
  internal/tools/monitor/core/metric/query/es-tsql/functions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/dashboard/org-apis/routes.go
Labels: bugfix

#5398 fix: add permisson of monitor_org_center to DEV TEST role
  conf/erda-configs/permission/backend/sys/org/org.yml
Labels: bugfix, approved

#5399 fix: legacyhttpserver try to get muxVars from infrahttpserver
  pkg/http/httpserver/server.go
  pkg/http/httpserver/vars.go
  pkg/http/httpserver/vars_test.go
Labels: bugfix, approved

#5400 fix: compatible org_name is empty, compatible metric name contains `-`
  internal/apps/msp/apm/alert/components/msp-alert-event-detail/event-history-table/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-event-detail/event-overview-info/command.go
  internal/apps/msp/apm/alert/components/msp-alert-event-detail/monitor-data-chart/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-event-list/table/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-overview/alert-duration-analysis/alert-duration-distribution/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-level-count/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-overview/alert-event-charts/groupby-type-count/provider.go
  internal/apps/msp/apm/alert/components/msp-alert-overview/composite-header/cards/statistics.go
  internal/apps/msp/apm/alert/components/msp-alert-overview/composite-header/unrecover-alert-chart/provider.go
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/oap/collector/lib/protoparser/spotmetric/spotmetric.go
Labels: bugfix

#5402 fix: add permisson of monitor_org_center to DEV TEST role
  conf/erda-configs/permission/backend/sys/org/org.yml
Labels: bugfix

#5404 feat: update gatewayApi if exists
  internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
Labels: feature

#5406 refactor: add frontend chartview
  cmd/monitor/monitor/conf/chartview/frontend/ajax_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/page_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/page_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/page_top_cpm.json
  cmd/monitor/monitor/conf/chartview/frontend/script_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/script_top_avg_time.json
  cmd/monitor/monitor/conf/chartview/frontend/script_top_cpm.json
Labels: refactor

#5405 fix: cmp alert coditions 404
  api/proto/cmp/alert/cmp_alert.proto
  cmd/cmp/bootstrap.yaml
  cmd/erda-server/bootstrap.yaml
  erda.yml
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  internal/apps/cmp/initialize.go
  internal/apps/cmp/provider.go
  internal/core/openapi/legacy/api/apis/cmp/cmp_alert_condition.go
  internal/core/openapi/legacy/api/apis/cmp/cmp_alert_conditions_value.go
Labels: bugfix

#5408 chore: make org-publisher-nexus process non block
  internal/apps/dop/services/publisher/publisher.go
Labels: approved

#5407 fix: metric origin colum append timestamp, fixcomponent is missing org
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
  internal/apps/msp/apm/service/components/service-overview/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-analysis/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-analysis/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-detail/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-detail/error_count/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-detail/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-detail/slow_count/provider.go
  internal/apps/msp/apm/service/components/transaction-db-analysis/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-db-analysis/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-db-analysis/table/provider.go
  internal/apps/msp/apm/service/components/transaction-db-detail/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-db-detail/error_count/provider.go
  internal/apps/msp/apm/service/components/transaction-db-detail/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-db-detail/slow_count/provider.go
  internal/apps/msp/apm/service/components/transaction-http-analysis/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-http-analysis/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-http-analysis/table/provider.go
  internal/apps/msp/apm/service/components/transaction-http-detail/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-http-detail/error_count/provider.go
  internal/apps/msp/apm/service/components/transaction-http-detail/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-http-detail/slow_count/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-analysis/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-analysis/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-analysis/table/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-detail/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-detail/error_count/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-detail/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-detail/slow_count/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-analysis/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-analysis/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-analysis/table/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-detail/avg_duration/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-detail/error_count/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-detail/rps/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-detail/slow_count/provider.go
  internal/tools/monitor/apm/topology/routes.go
  internal/tools/monitor/apm/topology/topology.go
  internal/tools/monitor/core/metric/query/es-tsql/functions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/query/search.go
Labels: bugfix

#5403 fix: chartview of addon-mysql
  cmd/monitor/monitor/conf/chartview/runtime/addon-mysql.json
Labels: bugfix

#5401 fix: get_services_pods for running pods exclude terminated Pod
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
Labels: bugfix

#5411 fix(orchestrator): delete runtime failed
  internal/tools/orchestrator/components/runtime/mock/mock.go
  internal/tools/orchestrator/components/runtime/mock/mock_sg.go
  internal/tools/orchestrator/endpoints/addon.go
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/scheduler/endpoints/servicegroup_endpoints.go
  internal/tools/orchestrator/scheduler/endpoints/servicegroup_endpoints_test.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations_test.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/deployment/deployment_context.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: orchestrator, bugfix

#5415 fix(orchestrator): release not found when redeploy
  internal/tools/orchestrator/dbclient/dbmock.go
  internal/tools/orchestrator/dbclient/deployment.go
  internal/tools/orchestrator/dbclient/deployment_test.go
  internal/tools/orchestrator/services/runtime/runtime.go
  internal/tools/orchestrator/services/runtime/runtime_test.go
Labels: orchestrator, bugfix

#5419 fix(erda-server): query publish item timeout
  bundle/publish_item.go
Labels: bugfix, approved

#5416 fix: cannot translate terminuskey to tenant_id
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
  internal/apps/msp/apm/checker/apis/checker.v1.service_test.go
  internal/apps/msp/apm/service/apm.service.service.go
  internal/apps/msp/apm/service/apm.service.service_test.go
  internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
  internal/apps/msp/apm/service/components/resources-container-monitor/container/provider_test.go
  internal/apps/msp/apm/service/components/transaction-cache-analysis/req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-detail/kv_grid/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-error/error_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-error/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-slow/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-cache-slow/slow_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-db-analysis/req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-db-analysis/table/provider.go
  internal/apps/msp/apm/service/components/transaction-db-detail/kv_grid/provider.go
  internal/apps/msp/apm/service/components/transaction-db-error/error_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-db-error/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-db-slow/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-db-slow/slow_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-http-analysis/req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-http-detail/kv_grid/provider.go
  internal/apps/msp/apm/service/components/transaction-http-error/error_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-http-error/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-http-slow/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-http-slow/slow_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-analysis/req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-detail/kv_grid/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-error/error_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-error/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-slow/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-mq-slow/slow_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-analysis/req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-detail/kv_grid/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-error/error_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-error/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-slow/metric_table/provider.go
  internal/apps/msp/apm/service/components/transaction-rpc-slow/slow_req_distribution/provider.go
  internal/apps/msp/apm/trace/query/trace.service.go
  internal/apps/msp/apm/trace/query/trace.service_test.go
  internal/tools/monitor/apm/topology/topology.go
  internal/tools/monitor/apm/topology/topology_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix

#5421 fix: chartview of frontend
  cmd/monitor/monitor/conf/chartview/frontend/ajax_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_detail.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
Labels: approved

#5423 fix: fix case when no tenant_id
  cmd/monitor/monitor/conf/analyzer/metrics/apm/application_db_service.json
  cmd/monitor/monitor/conf/analyzer/metrics/apm/application_mq_service.json
  internal/tools/monitor/apm/topology/topology_v2.go
  internal/tools/monitor/apm/topology/topology_v2_test.go
Labels: bugfix, approved

#5424 fix: check service is no data
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
Labels: bugfix, approved

#5417 fix: Use system local time instead of UTC in issue export.
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/query/convert.go
Labels: bugfix, approved

#5422 feat(orchestrator): optimal pod message
  apistructs/container.go
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
Labels: orchestrator, feature, approved

#5425 fix(erda-server): gallery operation auth failed
  internal/apps/dop/component-protocol/components/release-manage/releaseTable/release_gallery.go
  internal/apps/dop/dicehub/release/release.service.go
  internal/apps/dop/dicehub/release/release.service_test.go
  pkg/common/apis/header.go
  pkg/common/apis/header_test.go
Labels: admin, bugfix, approved

#5323 refactor(dicehub): refactor publish-item to dop provider
  api/proto/dop/publishitem/publishitem.proto
  api/proto/openapiv1/dicehub/dicehub.proto
  api/proto/openapiv1/dop/dop.proto
  bundle/dicehub.go
  bundle/publish_item.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  internal/apps/dop/dicehub/endpoints/endpoints.go
  internal/apps/dop/dicehub/endpoints/endpoints_test.go
  internal/apps/dop/dicehub/endpoints/publish_item.go
  internal/apps/dop/dicehub/endpoints/publish_item_test.go
  internal/apps/dop/dicehub/initialize.go
  internal/apps/dop/dicehub/service/publish_item/item.go
  internal/apps/dop/dicehub/service/publish_item/item_security.go
  internal/apps/dop/dicehub/service/publish_item/item_statistics.go
  internal/apps/dop/dicehub/service/publish_item/item_version.go
  internal/apps/dop/endpoints/endpoints.go
  internal/apps/dop/endpoints/publisher.go
  internal/apps/dop/providers/publishitem/artifact_statistics_test.go
  internal/apps/dop/providers/publishitem/db/blacklist.go
  internal/apps/dop/providers/publishitem/db/client.go
  internal/apps/dop/providers/publishitem/db/erase.go
  internal/apps/dop/providers/publishitem/db/publish_item.go
  internal/apps/dop/providers/publishitem/db/publish_item_h5_targets.go
  internal/apps/dop/providers/publishitem/db/publish_item_version.go
  internal/apps/dop/providers/publishitem/gray_level.go
  internal/apps/dop/providers/publishitem/gray_level_test.go
  internal/apps/dop/providers/publishitem/item_version.go
  internal/apps/dop/providers/publishitem/item_version_test.go
  internal/apps/dop/providers/publishitem/offline_helper.go
  internal/apps/dop/providers/publishitem/offline_helper_test.go
  internal/apps/dop/providers/publishitem/provider.go
  internal/apps/dop/providers/publishitem/public_version.go
  internal/apps/dop/providers/publishitem/public_version_test.go
  internal/apps/dop/providers/publishitem/publish.item.service.go
  internal/apps/dop/providers/publishitem/publish.item.service_test.go
  internal/apps/dop/services/apierrors/errors.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_publish_item_blacklist_create.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_publish_item_blacklist_delete.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_publish_item_blacklist_list.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_publish_item_erase_create.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_publish_item_erase_list.go
  internal/core/openapi/legacy/api/apis/dicehub/dicehub_publish_item_monitor_keys_list.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_create.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_delete.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_distribution.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_get_h5_packagename.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_query.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_update.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_version_create.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_version_get_latest.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_version_get_public.go
  internal/core/openapi/legacy/api/apis/dicehub/publish_item_version_set_status.go
  internal/core/openapi/legacy/api/apis/dop/publish_item_create_offline_version.go
  internal/core/openapi/legacy/api/apis/dop/publish_item_distribution.go
  internal/core/openapi/legacy/api/apis/dop/publish_item_query_my.go
  internal/core/openapi/legacy/api/apis/dop/publish_item_version_get_latest.go
Labels: refactor, approved

#5380 fix: action agent display eventbox log
  apistructs/pipeline.go
  internal/tools/pipeline/actionagent/openapi.go
  internal/tools/pipeline/actionagent/openapi_test.go
  internal/tools/pipeline/providers/edgepipeline_register/provider.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
Labels: bugfix, approved

#5420 feat: support get source from log message
  internal/tools/monitor/oap/collector/plugins/receivers/collector/collector.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/collector_test.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
Labels: feature, approved

#5427 fix: transaction timeout
  internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
Labels: hepa, bugfix

#5390 feat: Add pipeline action in rule, on push fire rule in release callback.
  api/proto/dop/rule/rule.proto
  cmd/erda-server/bootstrap.yaml
  internal/apps/dop/endpoints/release.go
  internal/apps/dop/initialize.go
  internal/apps/dop/provider.go
  internal/apps/dop/provider_test.go
  internal/apps/dop/providers/rule/actions/pipeline/provider.go
  internal/apps/dop/providers/rule/actions/pipeline/provider_test.go
  internal/apps/dop/providers/rule/executor/execute.go
  internal/apps/dop/providers/rule/executor/execute_test.go
  internal/apps/dop/providers/rule/provider.go
Labels: feature, approved

#5431 feat: Add DingTalk work notice action, issue state and assignee update.
  cmd/erda-server/bootstrap.yaml
  internal/apps/dop/providers/issue/stream/core/event.go
  internal/apps/dop/providers/rule/actions/dingtalkworknotice/provider.go
  internal/apps/dop/providers/rule/actions/dingtalkworknotice/provider_test.go
  internal/apps/dop/providers/rule/executor/execute.go
  internal/apps/dop/providers/rule/provider.go
Labels: feature, approved

#5430 fix: query group hosts
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
  internal/tools/monitor/dashboard/org-apis/clickhouse_source_test.go
Labels: bugfix

#5433 fix: export dashboard file without ext
  internal/tools/monitor/core/dataview/dashboard_file.go
Labels: bugfix, approved

#5432 fix: query container 404
  internal/pkg/bundle-ex/cmdb/cmdb.go
  internal/pkg/bundle-ex/cmdb/org_cluster.go
  internal/tools/monitor/common/permission/permission.go
  internal/tools/monitor/core/alert/alert-apis/alert.service.go
  internal/tools/monitor/core/alert/alert-apis/provider.go
  internal/tools/monitor/core/alert/details-apis/permission.go
  internal/tools/monitor/core/alert/details-apis/provider.go
  internal/tools/monitor/core/alert/details-apis/routes.go
  internal/tools/monitor/core/log/query/provider.go
  internal/tools/monitor/core/log/query/routes.go
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
  internal/tools/monitor/dashboard/org-apis/permission.go
  internal/tools/monitor/dashboard/org-apis/provider.go
  internal/tools/monitor/dashboard/report/apis/provider.go
  internal/tools/monitor/dashboard/report/apis/v1/provider.go
  internal/tools/monitor/notify/template/query/provider.go
Labels: bugfix

#5429 fix: add QUERY_LOG_FROM_CLICKHOUSE_LOAD_MODE env
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
  cmd/msp/bootstrap.yaml
Labels: bugfix

#5435 fix: config adjust
  cmd/monitor/streaming/bootstrap.yaml
Labels: bugfix

#5437 fix: publish response missing `success` field
  internal/apps/dop/providers/publishitem/provider.go
Labels: bugfix, approved

#5428 fix: no stabilize test
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/storage/clickhouse/provider.go
  internal/tools/monitor/core/metric/storage/clickhouse/provider_test.go
Labels: bugfix

#5438 feat: no err if no api
  internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
Labels: hepa, feature, bugfix

#5439 fix: get service_pods return different runtime's pods
  internal/tools/orchestrator/components/runtime/mock/mock_sg.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: bugfix

#5434 fix: fix topology logic
  internal/tools/monitor/apm/topology/clickhousesource/clickhouse_source.go
  internal/tools/monitor/apm/topology/topology_v2.go
  internal/tools/monitor/apm/topology/topology_v2_test.go
Labels: bugfix

#5440 fix: publish item download failed
  internal/apps/dop/providers/publishitem/db/publish_item_version.go
  internal/apps/dop/providers/publishitem/provider.go
Labels: bugfix

#5436 fix: Fix get pipeline yml path.
  internal/apps/dop/endpoints/release.go
Labels: bugfix

#5441 fix: Fix invalid issue plan time.
  internal/apps/dop/providers/issue/core/query/relation.go
  internal/apps/dop/providers/issue/core/query/relation_test.go
Labels: bugfix, approved

#5444 chore: prlint support cherry-pick
  .github/prlint.json
Labels: approved

#5446 feat: get record order by create_tiime desc
  internal/tools/orchestrator/hepa/context/context.go
  internal/tools/orchestrator/hepa/providers/legacy_upstream/upstream.service.go
  internal/tools/orchestrator/hepa/repository/service/gateway_upstream_register_record_service.go
  internal/tools/orchestrator/hepa/services/legacy_upstream/impl/impl.go
Labels: hepa, feature, bugfix

#5448 fix(erda-server): delete sonar tickets no rows affected
  apistructs/ticket.go
  apistructs/ticket_test.go
  internal/apps/dop/endpoints/sonar.go
  internal/apps/dop/endpoints/ticket.go
  internal/apps/dop/services/ticket/ticket.go
Labels: approved

#5451 fix: span storage source configure adjust
  cmd/msp/bootstrap.yaml
Labels: bugfix

#5450 fix(orchestrator): order render application repeated
  internal/tools/orchestrator/services/deployment_order/deployment_order_create.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_create_test.go
Labels: orchestrator, bugfix

#5453 fix: metric write configurable
  cmd/monitor/streaming/bootstrap.yaml
Labels: bugfix

#5454 feat: update ci-build-ce.yml
  .erda/pipelines/ci-build-ce.yml
Labels: feature

#5455 fix: add missing org provider
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/main.go
Labels: bugfix

#5452 fix(dop): update edge gittar repo proto to avoid 302
  internal/apps/dop/utils/gittar.go
  internal/apps/dop/utils/gittar_test.go
Labels: dop, bugfix, approved

#5458 fix(cmp): cluster import cpu subscribe ratio error
  internal/apps/cmp/impl/clusters/import_cluster.go
  internal/apps/cmp/impl/clusters/import_cluster_test.go
Labels: cmp, bugfix

#5456 feat(orchestrator): optimize k8s plugin nodelabel
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/nodelabel.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/nodelabel/nodelabel.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/nodelabel_test.go
Labels: orchestrator, feature

#5457 fix: translator fix
  cmd/monitor/monitor/conf/i18n/topology.yml
  internal/tools/monitor/apm/topology/topology.go
  internal/tools/monitor/apm/topology/topology_test.go
Labels: bugfix

#5459 fix: metric org name, and condition no tag
  internal/apps/msp/apm/service/components/transaction-http-slow/metric_table/provider.go
  internal/apps/msp/apm/trace/query/trace.service.go
  internal/apps/msp/apm/trace/query/trace.service_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
Labels: bugfix

#5460 feat: log
  internal/tools/orchestrator/hepa/context/context.go
  internal/tools/orchestrator/hepa/kong/base/kong_adapter.go
  internal/tools/orchestrator/hepa/kong/v2/kong_adapter.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.http
  internal/tools/orchestrator/hepa/repository/orm/base_ability.go
  internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
Labels: feature

#5461 feat(orchestrator): optimize k8s plugin deployment
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/interface.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment/deployment_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
Labels: orchestrator, feature

#5462 fix: replace value of the autotest step if needed after it is created
  internal/apps/dop/services/autotest_v2/scene.go
  internal/apps/dop/services/autotest_v2/scene_test.go
Labels: bugfix, approved

#5463 fix: remove useless code
  internal/apps/msp/apm/log-service/rules/cloud_metrics_test.go
  internal/tools/monitor/extensions/loghub/index/query/tags_tree_test.go
Labels: bugfix

#5466 fix(dicehub): import release repeat in mode
  internal/apps/dop/dicehub/release/release.go
  internal/apps/dop/dicehub/release/release_test.go
Labels: admin, bugfix, approved

#5465 chore: pkg time/ticker support execAtBegin configurable
  internal/apps/cmp/initialize.go
  pkg/time/ticker/ticker.go
  pkg/time/ticker/ticker_test.go
Labels: approved
