Repository erda-project/erda, pull requests merged in 2022-07, with the labels that each got.

#5077 feat: support keda HPA
  .erda/migrations/orchestrator/20220704-runtime-service-hpa-rule.sql
  api/proto/orchestrator/horizontalpodscaler/horizontalpodscaler.proto
  api/proto/orchestrator/runtime/runtime.proto
  apistructs/audits.go
  apistructs/runtime_dto.go
  cmd/orchestrator/bootstrap.yaml
  cmd/orchestrator/conf/i18n/scheduler-log-trans.yaml
  internal/tools/orchestrator/components/all.go
  internal/tools/orchestrator/components/horizontalpodscaler/bundle.service.go
  internal/tools/orchestrator/components/horizontalpodscaler/bundle.service.impl.go
  internal/tools/orchestrator/components/horizontalpodscaler/db.service.go
  internal/tools/orchestrator/components/horizontalpodscaler/db.service.impl.go
  internal/tools/orchestrator/components/horizontalpodscaler/hp.scaler.service.go
  internal/tools/orchestrator/components/horizontalpodscaler/hp.scaler.service_test.go
  internal/tools/orchestrator/components/horizontalpodscaler/provider.go
  internal/tools/orchestrator/components/horizontalpodscaler/types/types.go
  internal/tools/orchestrator/components/horizontalpodscaler/utils/apierror.go
  internal/tools/orchestrator/components/runtime/db.service.go
  internal/tools/orchestrator/components/runtime/db.service.impl.go
  internal/tools/orchestrator/components/runtime/mock/mock.go
  internal/tools/orchestrator/components/runtime/mock/mock_sg.go
  internal/tools/orchestrator/components/runtime/runtime.service.go
  internal/tools/orchestrator/components/runtime/runtime.service_test.go
  internal/tools/orchestrator/dbclient/hpa.go
  internal/tools/orchestrator/ecp/services/kubernetes/uniteddeployment.go
  internal/tools/orchestrator/endpoints/addon.go
  internal/tools/orchestrator/endpoints/server_handler.go
  internal/tools/orchestrator/events/types.go
  internal/tools/orchestrator/scheduler/endpoints/servicegroup_endpoints.go
  internal/tools/orchestrator/scheduler/endpoints/servicegroup_endpoints_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/event/event.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/hpa/hpa.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/hpa.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/condition_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/groupversion_info.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/gvkr_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/readme_before_edit_this_package.md
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/scaledjob_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/scaledobject_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/triggerauthentication_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/withtriggers_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/keda/v1alpha1/zz_generated.deepcopy.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/scaledobject.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  internal/tools/orchestrator/scheduler/instanceinfo/hpa.go
  internal/tools/orchestrator/scheduler/task/task.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_test.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: feature

#5153 feat(openapi): survey check required fields
  internal/tools/openapi/legacy/api/apis/presale_survey.go
  internal/tools/openapi/legacy/api/apis/presale_survey_test.go
Labels: feature, openapi, approved

#5098 fix: Fix bug count query, excludes deleted issues.
  internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
  internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
  internal/apps/dop/component-protocol/types/const.go
  internal/apps/dop/initialize.go
  internal/apps/dop/providers/issue/core/service.go
  internal/apps/dop/providers/issue/core/service_test.go
  internal/apps/dop/providers/issue/dao/core.go
Labels: bugfix, approved

#5135 feat(dop): R&D workflow settings optimization
  .erda/migrations/dop/20220626-devflowrule-branchpolicies.sql
  .erda/migrations/dop/20220628-devflowrule-migrations.py
  api/proto/dop/devflowrule/devflowrule.proto
  apistructs/devflowrule.go
  apistructs/devflowrule_test.go
  internal/apps/devflow/flow/flow.service.go
  internal/apps/dop/providers/devflowrule/db/define.go
  internal/apps/dop/providers/devflowrule/devflowrule.service.go
  internal/apps/dop/providers/devflowrule/devflowrule.service_test.go
  internal/apps/dop/services/branchrule/branch_rule.go
Labels: dop, feature, approved

#5156 fix(pipeline): solve status of task is reset to running due to cancel timeout
  internal/tools/pipeline/providers/reconciler/taskrun/framework.go
  internal/tools/pipeline/providers/reconciler/taskrun/framework_test.go
Labels: pipeline, bugfix, approved

#5159 fix(dop): rename the sql file name
  .erda/migrations/dop/20220428-devflowrule.sql
  .erda/migrations/dop/20220511-issue-relation.sql
Labels: dop, bugfix, approved

#5157 feat(pipeline): pipeline detail display action spec
  apistructs/extension_test.go
  apistructs/extention.go
  apistructs/pipeline_dto.go
  apistructs/pipeline_task.go
  internal/tools/pipeline/services/pipelinesvc/detail.go
Labels: pipeline, feature, approved

#5161 feat(orchestrator): optimize pod event watcher
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/event/event.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
Labels: orchestrator, feature

#5163 fix: update py script of devflowrule
  .erda/migrations/dop/20220628-devflowrule-migrations.py
Labels: approved

#5162 refactor: span storage model change
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
  cmd/monitor/streaming/conf/clickhouse/spans/ddl_create_default_tables.sql.tpl
  cmd/msp/bootstrap.yaml
  internal/apps/msp/apm/trace/query/commom/custom/trace_inparams.go
  internal/apps/msp/apm/trace/query/provider.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
  internal/apps/msp/apm/trace/span.go
  internal/tools/monitor/core/metric/metric.go
  internal/tools/monitor/oap/collector/lib/protoparser/oapspan/span.go
  internal/tools/monitor/oap/collector/lib/protoparser/oapspan/span_test.go
  internal/tools/monitor/oap/collector/lib/protoparser/spotspan/span.go
  internal/tools/monitor/oap/collector/lib/protoparser/spotspan/span_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/builder.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/storage.go
  internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider.go
Labels: refactor

#5155 fix: kafka write bugfix
  internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider_test.go
Labels: bugfix

#5165 chore: Fixed title column width and search placeholder in issue table.
  cmd/dop/conf/i18n/cp/common.yaml
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/props.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/props_test.go
  internal/pkg/component-protocol/issueFilter/conditions.go
Labels: approved

#5166 feat(http-server): http-endpoints support singleton mode
  pkg/http/httpserver/router.go
  pkg/http/httpserver/singleton.go
  pkg/http/httpserver/singleton_test.go
Labels: feature, approved

#5164 feat: add parse regexp
  api/proto/msp/apm/log-service/log_query.proto
  internal/apps/msp/apm/log-service/query/log.service.go
  internal/apps/msp/apm/log-service/query/log.service_test.go
Labels: feature

#5169 fix: hpa support min replicas to 0
  internal/tools/orchestrator/components/horizontalpodscaler/hp.scaler.service.go
Labels: bugfix, approved

#5170 fix: add service field
  api/proto/msp/apm/log-service/log_query.proto
Labels: bugfix

#5171 feat(dop): add devFlowRuleName to info and add tempBranch to brach rule
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/flow.service.go
  internal/apps/dop/services/branchrule/branch_rule.go
Labels: dop, feature, approved

#5172 fix: fix erda-server
  cmd/cluster-manager/bootstrap.yaml
  cmd/cmp/bootstrap.yaml
  cmd/dicehub/bootstrap.yaml
  cmd/dop/bootstrap.yaml
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/msp/bootstrap.yaml
Labels: bugfix, approved

#5181 fix: add auth for log_query
  api/proto/msp/apm/log-service/log_query.proto
Labels: bugfix

#5167 feat: project pipeline display existed running link when runs repeatedly
  bundle/utils.go
  internal/apps/dop/endpoints/endpoints.go
  internal/apps/dop/endpoints/pipeline.go
  internal/apps/dop/initialize.go
  internal/apps/dop/providers/projectpipeline/provider.go
  internal/apps/dop/providers/projectpipeline/service.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
  pkg/common/apis/response.go
  pkg/common/apis/response_test.go
Labels: feature, approved

#5184 fix: spans from cassandra as default
  cmd/msp/bootstrap.yaml
Labels: bugfix

#5185 fix: remove tags.dice_cluster_name when query logs
  internal/tools/monitor/core/log/query/log.query.service.go
Labels: bugfix

#5188 feat: remove custom registry credential
  erda.yml
Labels: feature

#5183 fix: adjust trace sql
  internal/apps/msp/apm/trace/query/components/trace-query/req_distribution/provider.go
  internal/apps/msp/apm/trace/query/provider.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
Labels: bugfix

#5190 fix(dop): Fix bugs caused by org refactoring
  internal/apps/admin/manager/cluster.go
  internal/apps/admin/provider.go
  internal/apps/dop/endpoints/organization.go
  internal/apps/dop/endpoints/organization_test.go
Labels: dop, bugfix, approved

#5175 feat: find invalid kong route and service by redirect inner address
  .github/workflows/ci-it.yml
  api/proto/core/hepa/endpoint_api/endpoint_api.proto
  internal/tools/orchestrator/hepa/k8s/k8s_adapter.go
  internal/tools/orchestrator/hepa/k8s/k8s_adapter_test.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/provider.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
Labels: hepa, feature

#5173 fix(dop): Merge R&D workflow into target branch
  api/proto/apps/devflow/flow/flow.proto
  internal/apps/devflow/flow/flow.service.go
  internal/apps/dop/providers/devflowrule/devflowrule.service.go
  internal/apps/dop/providers/devflowrule/devflowrule.service_test.go
Labels: dop, bugfix, approved

#5192 chore: update erda-server resource for daily env
  erda.yml
Labels: approved

#5189 refactor(pipeline): refactor pipeline report service to provider
  apistructs/pipeline_report.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/tools/pipeline/aop/aoptypes/context.go
  internal/tools/pipeline/aop/initialize.go
  internal/tools/pipeline/aop/plugins/pipeline/apitest_report/plugin.go
  internal/tools/pipeline/aop/plugins/pipeline/basic/plugin.go
  internal/tools/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
  internal/tools/pipeline/aop/plugins/pipeline/testplan_before/plugin_test.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_after/plugin.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
  internal/tools/pipeline/aop/plugins/task/unit_test_report/plugin.go
  internal/tools/pipeline/aop/tune_test.go
  internal/tools/pipeline/dbclient/op_pipeline_report.go
  internal/tools/pipeline/endpoints/endpoints.go
  internal/tools/pipeline/endpoints/report.go
  internal/tools/pipeline/initialize.go
  internal/tools/pipeline/provider.go
  internal/tools/pipeline/providers/report/interface.go
  internal/tools/pipeline/providers/report/mock.go
  internal/tools/pipeline/providers/report/provider.go
  internal/tools/pipeline/providers/report/report.service.go
  internal/tools/pipeline/providers/report/report.service_test.go
  internal/tools/pipeline/services/reportsvc/report.go
  internal/tools/pipeline/spec/pipeline_report.go
  internal/tools/pipeline/spec/pipeline_report_test.go
Labels: pipeline, refactor, approved

#5193 fix(dop): Handling the case when a branch is deleted
  internal/apps/devflow/flow/flow.service.go
Labels: dop, bugfix, approved

#5195 fix: test log rule error
  internal/apps/msp/apm/log-service/analysis/processors/regex/regex.go
Labels: bugfix

#5196 refactor: handle dup api for admin and core-services
  bundle/approve.go
  bundle/audit.go
  bundle/notice.go
  bundle/user.go
  internal/apps/admin/provider.go
  internal/apps/dop/dicehub/initialize.go
  internal/core/legacy/endpoints/endpoints.go
  internal/core/legacy/initialize.go
  pkg/http/httpserver/router.go
  pkg/http/httpserver/router_test.go
Labels: refactor, approved

#5197 fix(dop): tempBranch checkout from sourceBranch
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
  internal/apps/devflow/flow/mock_devflowRule.go
Labels: dop, bugfix, approved

#5194 fix: User search authorization at admin, desensitize email and phone in us…
  internal/apps/admin/manager/user.go
  internal/core/user/impl/kratos/service.go
  internal/core/user/impl/kratos/user_admin_test.go
  internal/core/user/impl/uc/service.go
  internal/core/user/impl/uc/user.go
  internal/core/user/util/desensitize.go
  internal/core/user/util/desensitize_test.go
  internal/core/user/util/handle.go
  internal/tools/openapi/legacy/api/apis/uc/uc_user_export.go
  internal/tools/openapi/legacy/api/apis/uc/uc_user_paging.go
Labels: bugfix, approved

#5198 fix: Fix Public app click operation authorized.
  internal/apps/dop/component-protocol/components/app-list-all/list/provider.go
  internal/apps/dop/component-protocol/components/app-list-all/list/provider_test.go
Labels: bugfix, approved

#5200 fix: use org.Interface at erda-server side
  internal/apps/admin/manager/manager.go
  internal/apps/dop/dicehub/release/provider.go
  internal/apps/dop/dicehub/release/release.service.go
  internal/apps/dop/dicehub/release/release.service_test.go
  internal/apps/gallery/cache/provider.go
  internal/pkg/mock/mock_org.go
Labels: bugfix, approved

#5202 fix: add cache_key_prefix in clickhouse table loader config
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
  cmd/msp/bootstrap.yaml
Labels: bugfix

#5205 fix: add cache_key_prefix in clickhouse table loader config
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
Labels: bugfix

#5204 fix: add proper skewing timing
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
Labels: bugfix

#5203 fix: collector agent config fix
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
  erda.yml
  internal/tools/monitor/oap/collector/plugins/receivers/collector/post.http
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider_test.go
Labels: bugfix

#5199 refactor(pipeline): refactor queue management to pb provider
  api/proto/core/pipeline/queue/queue.proto
  apistructs/pipeline.go
  apistructs/pipeline_queue.go
  apistructs/pipeline_queue_test.go
  internal/tools/openapi/legacy/api/apis/pipeline/pipeline_queue_create.go
  internal/tools/openapi/legacy/api/apis/pipeline/pipeline_queue_delete.go
  internal/tools/openapi/legacy/api/apis/pipeline/pipeline_queue_get.go
  internal/tools/openapi/legacy/api/apis/pipeline/pipeline_queue_list.go
  internal/tools/openapi/legacy/api/apis/pipeline/pipeline_queue_update.go
  internal/tools/pipeline/dbclient/op_pipeline_queue.go
  internal/tools/pipeline/endpoints/endpoints.go
  internal/tools/pipeline/endpoints/queue_management.go
  internal/tools/pipeline/initialize.go
  internal/tools/pipeline/providers/queuemanager/interface.go
  internal/tools/pipeline/providers/queuemanager/manager/pipeline.go
  internal/tools/pipeline/providers/queuemanager/manager/queue.go
  internal/tools/pipeline/providers/queuemanager/manager/usage.go
  internal/tools/pipeline/providers/queuemanager/pipeline_queue_test.go
  internal/tools/pipeline/providers/queuemanager/provider.go
  internal/tools/pipeline/providers/queuemanager/queue.service.go
  internal/tools/pipeline/providers/queuemanager/queue/define.go
  internal/tools/pipeline/providers/queuemanager/queue/mode.go
  internal/tools/pipeline/providers/queuemanager/queue/update.go
  internal/tools/pipeline/providers/queuemanager/types/manager.go
  internal/tools/pipeline/providers/queuemanager/types/queue.go
  internal/tools/pipeline/services/pipelinesvc/define.go
  internal/tools/pipeline/services/pipelinesvc/queue.go
  internal/tools/pipeline/services/queuemanage/create.go
  internal/tools/pipeline/services/queuemanage/define.go
  internal/tools/pipeline/services/queuemanage/delete.go
  internal/tools/pipeline/services/queuemanage/get.go
  internal/tools/pipeline/services/queuemanage/paging.go
  internal/tools/pipeline/services/queuemanage/update.go
  internal/tools/pipeline/spec/pipeline_extra.go
Labels: pipeline, refactor, approved

#5191 refactor(orchestartor): refactor orchestartor manual scale API to proto
  api/proto/orchestrator/horizontalpodscaler/horizontalpodscaler.proto
  internal/tools/openapi/legacy/api/apis/orchestrator/orchestrator_pre_dice_overlay_update.go
  internal/tools/openapi/legacy/api/apis/orchestrator/orchestrator_pre_dice_overlay_update_test.go
  internal/tools/orchestrator/components/horizontalpodscaler/db.service.go
  internal/tools/orchestrator/components/horizontalpodscaler/db.service.impl.go
  internal/tools/orchestrator/components/horizontalpodscaler/hp.scaler.service.go
  internal/tools/orchestrator/components/horizontalpodscaler/manual_scale.go
  internal/tools/orchestrator/components/horizontalpodscaler/manual_scale_test.go
  internal/tools/orchestrator/endpoints/endpoints.go
  internal/tools/orchestrator/endpoints/server_handler.go
Labels: refactor

#5206 refactor(pipeline): refactor pipeline app svc to provider
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/tools/pipeline/endpoints/endpoints.go
  internal/tools/pipeline/initialize.go
  internal/tools/pipeline/provider.go
  internal/tools/pipeline/providers/app/provider.go
  internal/tools/pipeline/providers/app/workspace_app.go
  internal/tools/pipeline/services/appsvc/define.go
  internal/tools/pipeline/services/pipelinesvc/define.go
Labels: pipeline, refactor, approved

#5208 fix(orchestrator): process hpa event may get nil from orgCache
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
Labels: orchestrator, bugfix

#5209 feat: check idOrName for org bundle
  bundle/org.go
  bundle/org_test.go
Labels: feature, approved

#5211 fix(dop): Fix bugs caused by org refactoring
  internal/apps/dop/cache/org/org.go
  internal/apps/dop/providers/api-management/provider.go
  internal/apps/gallery/cache/cache.go
  internal/apps/gallery/handler/gallery.go
Labels: dop, bugfix, approved

#5216 fix(erda-server): use org.Interface in erda-server
  internal/apps/dop/dicehub/endpoints/endpoints.go
  internal/apps/dop/dicehub/provider.go
Labels: bugfix

#5207 fix: get span count fix
  cmd/msp/bootstrap.yaml
  erda.yml
  internal/apps/msp/apm/trace/query/source/clickhouse_source.go
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/collector/provider.go
  pipeline.yml
Labels: bugfix

#5218 fix: msp default to cassandra
  cmd/msp/bootstrap.yaml
Labels: bugfix

#5065 feat: pipeline benchmark test of reconciler and queuemanager
  cmd/pipeline/bootstrap.yaml
  internal/tools/pipeline/endpoints/v2_test.go
  internal/tools/pipeline/providers/edgereporter/mock.go
  internal/tools/pipeline/services/pipelinesvc/create_v2.go
  internal/tools/pipeline/services/pipelinesvc/create_v2_test.go
Labels: feature

#5219 feat: upgrade libgit2 git2go
  .github/workflows/ci-it.yml
  .golangci.yml
  Makefile
  build/dockerfiles/Dockerfile
  build/dockerfiles/Dockerfile-cli
  build/dockerfiles/Dockerfile-cluster-ops
  build/dockerfiles/Dockerfile-golangci-lint
  build/dockerfiles/Dockerfile-volume-provisioner
  build/dockerfiles/agent-injector/Dockerfile
  build/dockerfiles/base/Dockerfile
  build/dockerfiles/base/deploy.sh
  build/dockerfiles/cluster-agent/Dockerfile
  build/dockerfiles/gittar-resource/GitGolangImage
  build/dockerfiles/gittar-resource/GitImage
  build/dockerfiles/reportengine/Dockerfile
  build/scripts/base_image.sh
  build/scripts/docker_image.sh
  go.mod
  go.sum
  internal/tools/gittar/helper/git_hooks.go
  internal/tools/gittar/pkg/gitmodule/commit.go
  internal/tools/gittar/pkg/gitmodule/repo.go
  internal/tools/gittar/pkg/gitmodule/repo_blame.go
  internal/tools/gittar/pkg/gitmodule/repo_branch.go
  internal/tools/gittar/pkg/gitmodule/repo_commit.go
  internal/tools/gittar/pkg/gitmodule/repo_diff.go
  internal/tools/gittar/pkg/gitmodule/repo_edit.go
  internal/tools/gittar/pkg/gitmodule/repo_edit_test.go
  internal/tools/gittar/pkg/gitmodule/repo_merge.go
  internal/tools/gittar/pkg/gitmodule/repo_tag.go
  internal/tools/gittar/pkg/gitmodule/repo_tree.go
  internal/tools/gittar/pkg/gitmodule/tree.go
  internal/tools/gittar/pkg/gitmodule/tree_entry.go
  tools/gotools/go-test-sum/main.go
Labels: feature

#5221 chore: fix build image of cluster-agent
  build/dockerfiles/cluster-agent/Dockerfile
  pipeline.yml
Labels: approved

#5213 feat: erda-cli gw commands
  internal/tools/orchestrator/cache/org/org.go
  pkg/http/httpclient/request.go
  pkg/http/httpclient/request_test.go
  tools/cli/cmd/gw.go
  tools/cli/cmd/gw_del.go
  tools/cli/cmd/gw_del_test.go
  tools/cli/cmd/gw_ls.go
  tools/cli/cmd/gw_ls_test.go
  tools/cli/command/generate/collect/collect.go
Labels: hepa, feature

#5224 fix(orchestrator): manual pod scaler failed when other services in th…
  internal/tools/orchestrator/components/horizontalpodscaler/manual_scale.go
  internal/tools/orchestrator/components/horizontalpodscaler/manual_scale_test.go
  internal/tools/orchestrator/endpoints/server_handler.go
Labels: orchestrator, bugfix, approved

#5223 fix: aop `autotest_cookie_keep_before` plugin merge all cookies from report
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie_test.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
Labels: bugfix, approved

#5215 fix(pipeline): use batched queries instead of loading full data in dbgc
  apistructs/pipeline.go
  internal/tools/pipeline/dbclient/op_pipeline.go
  internal/tools/pipeline/dbclient/op_pipeline_test.go
  internal/tools/pipeline/providers/dbgc/dbgc.go
  internal/tools/pipeline/providers/dbgc/dbgc_test.go
Labels: pipeline, bugfix, approved

#5227 fix: cms batch query configs remain the same order as namespaces
  internal/tools/pipeline/providers/cms/cms.service.go
  internal/tools/pipeline/providers/cms/pipeline_cms.go
  internal/tools/pipeline/providers/cms/pipeline_cms_test.go
Labels: bugfix, approved

#5148 fix(dop,pipeline): Deleting pipeline definitions and sources when deleting application
  .erda/migrations/pipeline/20220629-pipeline-definition-add-remote.sql
  api/proto/core/pipeline/definition/definition.proto
  api/proto/core/pipeline/source/source.proto
  api/proto/dop/projectpipeline/projectpipeline.proto
  internal/apps/dop/endpoints/application.go
  internal/apps/dop/endpoints/project_test.go
  internal/apps/dop/providers/projectpipeline/service.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
  internal/pkg/mock/mock_cron.go
  internal/tools/pipeline/providers/definition/db/define.go
  internal/tools/pipeline/providers/definition/db/define_extra.go
  internal/tools/pipeline/providers/definition/pipeline_definition.go
  internal/tools/pipeline/providers/source/db/source.go
  internal/tools/pipeline/providers/source/pipeline_source.go
Labels: dop, pipeline, bugfix, approved

#5226 fix(dop): Fix bugs in project pipeline
  api/proto/dop/projectpipeline/projectpipeline.proto
  apistructs/pipeline.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider_test.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/tools/pipeline/dbclient/op_pipeline.go
Labels: dop, bugfix, approved

#5222 fix(dop): Modify the description of the auto submitted mr
  cmd/dop/bootstrap.yaml
  codecov.yml
  internal/apps/devflow/flow/flow.service.go
  internal/apps/devflow/flow/flow.service_test.go
  internal/apps/devflow/flow/issue_mock.go
  internal/apps/devflow/flow/provider.go
  internal/pkg/mock/org_mock.go
Labels: dop, bugfix, approved

#5228 feat: add script lint
  .erda/migrations/config.yml
  pkg/database/sqllint/linters/scritp_checksum_linter.go
  pkg/database/sqllint/linters/scritp_checksum_linter_test.go
  pkg/database/sqllint/linters/scritp_name_linter.go
  pkg/database/sqllint/linters/scritp_name_linter_test.go
  pkg/database/sqllint/rule.go
  pkg/database/sqllint/script/script.go
  pkg/database/sqllint/visitors.go
Labels: feature, install

#5233 feat: support addon plan check when deploy
  cmd/orchestrator/conf/i18n/deployment-order-precheck.yaml
  cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
  internal/tools/orchestrator/initialize.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/deployment/deployment_context.go
  internal/tools/orchestrator/services/deployment/deployment_context_test.go
  internal/tools/orchestrator/services/deployment_order/deployment_order.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_render.go
  internal/tools/orchestrator/services/deployment_order/deployment_order_render_test.go
  internal/tools/orchestrator/services/runtime/runtime.go
  internal/tools/orchestrator/services/runtime/runtime_test.go
Labels: feature

#5231 fix: Fix user export and and org list api spec CheckLogin.
  internal/core/openapi/legacy/api/apis/dop/cmdb_orgs_search.go
  internal/core/openapi/legacy/api/apis/uc/uc_user_export.go
Labels: bugfix

#5236 fix: manual scale not update addon attachment
  internal/tools/orchestrator/components/horizontalpodscaler/manual_scale.go
  internal/tools/orchestrator/endpoints/server_handler.go
Labels: bugfix

#5239 fix: Add Joined org list, remove org params.
  api/proto/core/org/org.proto
  internal/apps/dop/endpoints/organization.go
  internal/apps/dop/endpoints/organization_test.go
  internal/core/org/org.service.go
  internal/core/org/org.service_test.go
Labels: bugfix, approved

#5238 refactor(pipeline): refactor actionagentSvc,permissionSvc to provider
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/tools/pipeline/endpoints/endpoints.go
  internal/tools/pipeline/initialize.go
  internal/tools/pipeline/provider.go
  internal/tools/pipeline/providers/actionagent/download.go
  internal/tools/pipeline/providers/actionagent/ensure.go
  internal/tools/pipeline/providers/actionagent/ensure_test.go
  internal/tools/pipeline/providers/actionagent/interface.go
  internal/tools/pipeline/providers/actionagent/provider.go
  internal/tools/pipeline/providers/actionagent/script.go
  internal/tools/pipeline/providers/permission/interface.go
  internal/tools/pipeline/providers/permission/permission.go
  internal/tools/pipeline/providers/permission/permission_test.go
  internal/tools/pipeline/providers/permission/provider.go
  internal/tools/pipeline/providers/reconciler/interface.go
  internal/tools/pipeline/providers/reconciler/pipeline_reconciler.go
  internal/tools/pipeline/providers/reconciler/provider.go
  internal/tools/pipeline/providers/reconciler/task_reconciler.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskrun.go
  internal/tools/pipeline/services/actionagentsvc/define.go
  internal/tools/pipeline/services/pipelinesvc/define.go
Labels: pipeline, refactor, approved

#5235 feat: add owner user for pipeline
  api/proto/dop/projectpipeline/projectpipeline.proto
  apistructs/labels.go
  apistructs/pipeline.go
  apistructs/pipeline_dto.go
  apistructs/pipeline_page.go
  apistructs/pipeline_page_test.go
  cmd/dop/conf/i18n/cp/common.yaml
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/common/commom.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/common/gshelper/helper.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/condition_test.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/filterContainer/customFilter/provider.go
  internal/apps/dop/component-protocol/components/project-pipeline-exec-list/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/component-protocol/components/util/vars.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
  internal/apps/dop/services/pipeline/pipeline.go
  internal/apps/dop/services/pipeline/pipeline_test.go
  internal/tools/pipeline/initialize.go
  internal/tools/pipeline/providers/cron/daemon/cron_task.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/secret/platform_secret.go
  internal/tools/pipeline/services/pipelinesvc/convert.go
  internal/tools/pipeline/services/pipelinesvc/create_v2.go
  internal/tools/pipeline/spec/pipeline.go
  internal/tools/pipeline/spec/pipeline_extra.go
  internal/tools/pipeline/spec/pipeline_test.go
Labels: feature, approved

#5243 fix: project runtime list deploy time error when deploy failed
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: orchestrator, bugfix

#5241 refactor: erda-server bootstrap openapi
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  bundle/urls.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/openapi/bootstrap.yaml
  cmd/openapi/common-conf
  cmd/openapi/conf/.gitkeep
  cmd/openapi/main.go
  erda.yml
  go.mod
  go.sum
  internal/core/openapi/legacy/reverseproxy.go
  internal/core/openapi/openapi-ng/provider.go
  internal/core/openapi/openapi-ng/routes/dynamic/provider.go
  pipeline.yml
  pkg/discover/address.go
Labels: refactor, approved

#5249 feat: skip_lint
  pipeline.yml
Labels: feature, approved, install

#5250 chore: adjust exposed port order for erda-server
  erda.yml
Labels: approved

#5251 fix(dop): filter empty string when query pipelines
  internal/apps/dop/endpoints/pipeline.go
  internal/apps/dop/endpoints/pipeline_test.go
Labels: dop, bugfix, approved

#5252 fix(openapi): fix "index out of range" issue of orgNameRetriever when domain is empty
  internal/core/openapi/legacy/util/org.go
  internal/core/openapi/legacy/util/org_test.go
Labels: openapi, bugfix, approved

#5248 fix: limit response header content-type to prevent xss
  internal/core/legacy/services/filesvc/download.go
  internal/core/legacy/services/filesvc/download_test.go
  internal/core/legacy/services/filesvc/example/normal.png
  internal/core/legacy/services/filesvc/example/xss-svg.svg
Labels: bugfix, approved

#5240 fix: attachment records leak
  .erda/migrations/orchestrator/20220715-01-fix-tb-addon-attachment-leak.py
Labels: bugfix

#5257 fix(hepa): inject org to hepa
  cmd/hepa/bootstrap.yaml
  cmd/hepa/main.go
Labels: approved

#5256 fix: check pipeline owner has permission to get app
  internal/apps/dop/services/pipeline/pipeline.go
  internal/apps/dop/services/pipeline/pipeline_test.go
Labels: bugfix

#5255 fix: tenant template fix
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_tenant_tables.sql.tpl
Labels: bugfix

#5242 feat(pipeline): Application pipeline auto binding definition
  api/proto/core/pipeline/cron/cron.proto
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
  internal/apps/dop/endpoints/pipeline.go
  internal/apps/dop/endpoints/release.go
  internal/apps/dop/providers/projectpipeline/provider.go
  internal/apps/dop/providers/projectpipeline/provider_test.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/pkg/mock/cron_mock.go
  internal/pkg/mock/definition_mock.go
  internal/tools/pipeline/providers/cron/db/define_extra.go
  internal/tools/pipeline/providers/definition/db/define.go
  internal/tools/pipeline/providers/definition/pipeline_definition.go
Labels: pipeline, feature, approved

#5258 fix: no python package generated
  pkg/database/sqlparser/pygrator/package.go
Labels: bugfix

#5259 fix: missing reource type when check owner permission
  internal/apps/dop/services/pipeline/pipeline.go
Labels: bugfix

#5262 fix(orchestrator): remove deploy condition precheck
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/runtime/runtime_test.go
Labels: orchestrator, bugfix

#5264 fix: handle the case that the name characters is too long
  api/proto/core/pipeline/definition/definition.proto
  internal/apps/dop/endpoints/release.go
  internal/apps/dop/providers/projectpipeline/provider.go
  internal/apps/dop/providers/projectpipeline/provider_test.go
  internal/tools/pipeline/providers/definition/pipeline_definition.go
Labels: bugfix, approved

#5261 feat(openapi): reverseproxy modifyresponse handle duplicate header
  go.mod
  go.sum
  internal/core/openapi/legacy/proxy/http/http.go
  internal/core/openapi/legacy/proxy/http/http_test.go
  internal/core/openapi/legacy/proxy/http/modifyresponse.go
  internal/core/openapi/legacy/proxy/http/modifyresponse_test.go
  internal/core/openapi/legacy/reverseproxy.go
  internal/core/openapi/legacy/reverseproxy_test.go
  internal/pkg/mock/httpresponsewriter.go
  internal/tools/monitor/core/collector/provider.go
  internal/tools/monitor/core/dataview/provider.go
  internal/tools/monitor/core/metric/query/metricq/provider.go
  internal/tools/monitor/core/settings/retention-strategy/provider.go
  internal/tools/monitor/core/storekit/elasticsearch/index/cleaner/provider.go
  internal/tools/monitor/core/storekit/elasticsearch/index/loader/provider.go
  internal/tools/monitor/core/storekit/elasticsearch/index/rollover/provider.go
  internal/tools/monitor/notify/template/query/provider.go
Labels: feature, openapi, approved

#5268 chore: move unused containerfilemanager to internal pkg
  api/proto/pkg/containerfilemanager/filemanager.proto
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/monitor/main.go
  internal/pkg/containerfilemanager/common.go
  internal/pkg/containerfilemanager/common_test.go
  internal/pkg/containerfilemanager/file.manager.service.go
  internal/pkg/containerfilemanager/file.manager.service_test.go
  internal/pkg/containerfilemanager/permission.go
  internal/pkg/containerfilemanager/provider.go
  internal/pkg/containerfilemanager/test.http
  internal/pkg/containerfilemanager/upload.html
Labels: approved

#5266 fix(monitor): Solve value conversion problems
  internal/tools/monitor/core/alert/alert-apis/alert.service.go
  internal/tools/monitor/core/alert/alert-apis/alert.service_test.go
Labels: bugfix, approved

#5272 chore: specify image for erda pipeline build step (Go 1.17)
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  pipeline.yml
Labels: approved

#5273 chore: fix build erda agents
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  pipeline.yml
Labels: approved

#5271 refactor: pod scaler include hpa/vpa/manual scaler
  .erda/migrations/orchestrator/20220729-runtime-service-vpa.sql
  api/proto/orchestrator/podscaler/podscaler.proto
  cmd/orchestrator/bootstrap.yaml
  internal/tools/orchestrator/components/horizontalpodscaler/hp.scaler.service.go
  internal/tools/orchestrator/components/podscaler/bundle.service.go
  internal/tools/orchestrator/components/podscaler/bundle.service.impl.go
  internal/tools/orchestrator/components/podscaler/common.go
  internal/tools/orchestrator/components/podscaler/db.service.go
  internal/tools/orchestrator/components/podscaler/db.service.impl.go
  internal/tools/orchestrator/components/podscaler/hpa_scale.go
  internal/tools/orchestrator/components/podscaler/manual_scale.go
  internal/tools/orchestrator/components/podscaler/manual_scale_test.go
  internal/tools/orchestrator/components/podscaler/podscaler.service.go
  internal/tools/orchestrator/components/podscaler/podscaler.service_test.go
  internal/tools/orchestrator/components/podscaler/provider.go
  internal/tools/orchestrator/components/podscaler/types/types.go
  internal/tools/orchestrator/components/podscaler/utils/apierror.go
  internal/tools/orchestrator/components/podscaler/vpa_scale.go
  internal/tools/orchestrator/components/runtime/runtime.service.go
  internal/tools/orchestrator/dbclient/hpa.go
  internal/tools/orchestrator/events/types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/hpa.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/sync.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: refactor

#5274 fix: erda-server service addr env inject error
  erda.yml
Labels: bugfix

#5275 fix(openapi-legacy-proto): mismatch between 'go_package option' and 'proto file dir structure'
  api/proto/openapiv1/api/gateway/api_gateway.proto
  api/proto/openapiv1/cluster/manager/cluster_manager.proto
  api/proto/openapiv1/core/services/core_services.proto
  api/proto/openapiv1/dicehub/dicehub.proto
  api/proto/openapiv1/dop/config/manage/dop_config_manage.proto
  api/proto/openapiv1/dop/dop.proto
  api/proto/openapiv1/dop/filetree/dop_filetree.proto
  api/proto/openapiv1/msp/apm/alert/msp_apm_alert.proto
  api/proto/openapiv1/msp/apm/block/msp_apm_block.proto
  api/proto/openapiv1/msp/apm/exception/msp_apm_exception.proto
  api/proto/openapiv1/msp/apm/log/service/msp_apm_log_service.proto
  api/proto/openapiv1/msp/apm/metric/msp_apm_metric.proto
  api/proto/openapiv1/msp/apm/trace/msp_apm_trace.proto
  api/proto/openapiv1/msp/tenant/msp_tenant.proto
  api/proto/openapiv1/msp/tenant/project/msp_tenant_project.proto
  api/proto/openapiv1/openapi/component/protocol/openapi_component_protocol.proto
  api/proto/openapiv1/orchestrator/orchestrator.proto
  api/proto/openapiv1/pipeline/pipeline.proto
  api/proto/openapiv1/testplatform/autotest/testplatform_autotest.proto
  api/proto/openapiv1/testplatform/testcase/testplatform_testcase.proto
  api/proto/openapiv1/testplatform/testplan/rel/testplatform_testplan_rel.proto
  api/proto/openapiv1/testplatform/testplan/testplatform_testplan.proto
  api/proto/openapiv1/testplatform/testset/testplatform_testset.proto
  api/proto/openapiv1/uc/uc.proto
  internal/core/openapi/legacy/api/generate/generate_proto.go
  internal/core/openapi/legacy/api/generate/generate_proto_test.go
Labels: openapi, bugfix, approved

#5253 feat: Rule engine set up, add expr ruleset executor, outgoing API, jsonnet …
  .erda/migrations/dop/20220713-erda_rule_set-base.sql
  api/proto/dop/rule/rule.proto
  cmd/dop/bootstrap.yaml
  cmd/dop/main.go
  go.mod
  go.sum
  internal/apps/dop/providers/rule/actions/api/api.go
  internal/apps/dop/providers/rule/db/record.go
  internal/apps/dop/providers/rule/db/ruleset.go
  internal/apps/dop/providers/rule/executor/execute.go
  internal/apps/dop/providers/rule/executor/expr.go
  internal/apps/dop/providers/rule/executor/expr_test.go
  internal/apps/dop/providers/rule/jsonnet/jsonnet.go
  internal/apps/dop/providers/rule/provider.go
  internal/apps/dop/providers/rule/rule.service.go
Labels: feature, approved

#5280 fix: cluster agent token expire in kubernetes >= 1.21
  cmd/cluster-agent/bootstrap.yaml
  go.mod
  go.sum
  internal/tools/cluster-agent/config/config.go
  internal/tools/cluster-agent/pkg/client/client.go
  internal/tools/cluster-agent/pkg/client/client_test.go
Labels: cluster-manager, bugfix

#5282 chore: update erda base image
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  build/dockerfiles/base/Dockerfile
  build/scripts/base_image.sh
  build/scripts/docker_image.sh
  pipeline.yml
Labels: approved

#5269 fix: add apk content-type `application/vnd.android.package-archive` to whitelist
  internal/core/legacy/services/filesvc/download.go
  internal/core/legacy/services/filesvc/download_test.go
Labels: bugfix, approved

#5284 chore: erda-base image use node lts; generate Software Bill Of Materials (SBOM)
  build/dockerfiles/base/Dockerfile
  build/dockerfiles/base/deploy.sh
  build/dockerfiles/base/sbom.txt
Labels: approved

#5279 fix: too many conditions to save
  .erda/migrations/monitor/20220726-sp_alert.sql
Labels: bugfix

#5278 feat: append meta to metric query
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/metric/query/es-tsql/functions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/functions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/query.go
  internal/tools/monitor/core/metric/query/metricmeta/manager.go
  internal/tools/monitor/core/metric/query/metricmeta/metric_meta.go
  internal/tools/monitor/core/metric/query/metricq/provider.go
  internal/tools/monitor/core/metric/query/metricq/routes.go
  internal/tools/monitor/core/metric/query/provider.go
  internal/tools/monitor/core/metric/query/query/search.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
Labels: feature

#5244 feat: clear invalid endpoints in crontab
  api/proto/core/hepa/endpoint_api/endpoint_api.proto
  cmd/hepa/bootstrap.yaml
  internal/pkg/cron/controller.go
  internal/pkg/cron/provider.go
  internal/pkg/cron/status.go
  internal/pkg/cron/task.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/provider.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/requirements.go
  internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
Labels: feature

#5283 feat(orchestrator): edas support msp annotations
  go.mod
  go.sum
  internal/apps/cmp/endpoints/aliyun_resources.go
  internal/apps/cmp/impl/aliyun-resources/ack/ack.go
  internal/apps/cmp/impl/aliyun-resources/es/es.go
  internal/apps/cmp/impl/aliyun-resources/nas/nas.go
  internal/apps/cmp/impl/aliyun-resources/redis/list.go
  internal/apps/cmp/impl/ess/ess.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/util/util.go
  internal/tools/orchestrator/scheduler/executor/util/util_test.go
Labels: orchestrator, feature

#5286 fix: entity-storage-writer modify citations storage interface
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/entity/persist/provider.go
Labels: bugfix

#5287 feat: replace mysql addon to mysql-operator, codecov
  go.mod
  go.sum
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/dbclient/addon_instance_tenant.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/cr.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/env.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/groupversion_info.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/mysql_group.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/mysql_solo.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/mysql_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/mysql_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/mysql_validate.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/mysql_version.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/v1/zz_generated.deepcopy.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_deploy_test.go
  internal/tools/orchestrator/services/addon/addon_mysql.go
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_test.go
  internal/tools/orchestrator/services/addon/mysql_operator.go
  internal/tools/orchestrator/services/addon/mysql_operator_test.go
Labels: feature

#5292 chore: specify required lowest go version is 1.17 in go.mod
  api/proto-go/go.mod
  api/proto-go/go.sum
  go.mod
Labels: approved

#5291 fix(dop): Solve the problem that the encrypted value is empty when batch update
  internal/apps/dop/providers/cms/cicdcmsservice.go
  internal/apps/dop/providers/cms/cicdcmsservice_test.go
Labels: dop, bugfix, approved

#5293 chore: go mod tidy
  go.mod
  go.sum
Labels: approved

#5294 chore: delete outdated OWNERS
  OWNERS
Labels: approved

#5296 fix: panic in audit
  internal/pkg/audit/interceptor.go
Labels: bugfix

#5297 fix: openapi lost Content-Type header after proxy
  cmd/erda-server/bootstrap.yaml
  internal/core/openapi/legacy/proxy/http/modifyresponse.go
  internal/core/openapi/legacy/proxy/http/modifyresponse_test.go
Labels: bugfix, approved

#5300 feat: delete some useless code
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/monitor/main.go
  internal/tools/monitor/core/metric/query/metricq/export.go
  internal/tools/monitor/core/metric/query/metricq/routes.go
  internal/tools/monitor/dashboard/node-topo/provider.go
  internal/tools/monitor/dashboard/node-topo/routes.go
  internal/tools/monitor/dashboard/org-apis/container.go
  internal/tools/monitor/dashboard/org-apis/routes.go
Labels: feature, approved

#5301 fix: cluster-agent doesn't exit when start failed
  internal/tools/cluster-agent/provider.go
Labels: bugfix

#5305 fix: metrics panic fix
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
Labels: bugfix
