Repository erda-project/erda, pull requests merged in 2022-09, with the labels that each got.

#5471 refactor: move events and entities to ck
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/monitor/main.go
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/entities_ddl_create_db.sql
  cmd/monitor/streaming/conf/clickhouse/entities_ddl_create_default_tables.sql
  cmd/monitor/streaming/conf/clickhouse/entities_ddl_create_tenant_tables.sql
  cmd/monitor/streaming/conf/clickhouse/events_ddl_create_db.sql
  cmd/monitor/streaming/conf/clickhouse/events_ddl_create_default_tables.sql
  cmd/monitor/streaming/conf/clickhouse/events_ddl_create_tenant_tables.sql
  cmd/monitor/streaming/main.go
  cmd/msp/bootstrap.yaml
  internal/apps/msp/apm/exception/query/source/elasticsearch_source.go
  internal/tools/monitor/core/alert/alert-apis/adapt/record.go
  internal/tools/monitor/core/alert/alert-apis/adapt/record_test.go
  internal/tools/monitor/core/alert/alert-apis/provider.go
  internal/tools/monitor/core/entity/entity.go
  internal/tools/monitor/core/entity/persist/consume.go
  internal/tools/monitor/core/entity/persist/provider.go
  internal/tools/monitor/core/entity/persist/statistics.go
  internal/tools/monitor/core/entity/persist/validate.go
  internal/tools/monitor/core/entity/query/entity.service.go
  internal/tools/monitor/core/entity/query/provider.go
  internal/tools/monitor/core/entity/storage/clickhouse/provider.go
  internal/tools/monitor/core/entity/storage/clickhouse/storage.go
  internal/tools/monitor/core/entity/storage/clickhouse/storage_test.go
  internal/tools/monitor/core/entity/storage/elasticsearch/provider.go
  internal/tools/monitor/core/entity/storage/elasticsearch/storage.go
  internal/tools/monitor/core/entity/storage/elasticsearch/writer.go
  internal/tools/monitor/core/entity/storage/elasticsearch/writer_test.go
  internal/tools/monitor/core/entity/storage/storage.go
  internal/tools/monitor/core/event/event.go
  internal/tools/monitor/core/event/persist/consume.go
  internal/tools/monitor/core/event/persist/provider.go
  internal/tools/monitor/core/event/query/event.query.service.go
  internal/tools/monitor/core/event/query/provider.go
  internal/tools/monitor/core/event/storage/clickhouse/provider.go
  internal/tools/monitor/core/event/storage/clickhouse/query.go
  internal/tools/monitor/core/event/storage/clickhouse/query_test.go
  internal/tools/monitor/core/event/storage/elasticsearch/provider.go
Labels: refactor

#5473 fix: panic in entity count
  internal/tools/monitor/core/entity/storage/clickhouse/storage.go
Labels: bugfix

#5472 fix(pipeline): skip cancel if worker not found logic task due to user frequent click
  internal/tools/pipeline/providers/leaderworker/impl_worker.go
Labels: pipeline, bugfix, approved

#5467 refactor: cmp on erda-server
  .erda/pipelines/ci-deploy.yml
  cmd/cmp/bootstrap.yaml
  cmd/cmp/common-conf
  cmd/cmp/conf/.gitkeep
  cmd/cmp/main.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/conf/i18n/cp/cmp-common.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-cluster-list.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-events-list.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-nodeDetail.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-nodes.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-podDetail.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-pods.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-resource.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-workload-detail.yaml
  cmd/erda-server/conf/i18n/cp/scenarios/cmp-dashboard-workloads-list.yaml
  cmd/erda-server/main.go
  erda.yml
  internal/apps/cmp/conf/conf.go
  internal/apps/cmp/initialize.go
  internal/apps/cmp/provider.go
  internal/apps/cmp/steve/aggregator.go
  internal/apps/cmp/steve/handler.go
  pipeline.yml
  pkg/http/httpserver/router.go
Labels: refactor, approved

#5470 refactor: pipeline graph to pb provider
  api/proto/core/pipeline/base/base.proto
  api/proto/core/pipeline/graph/graph.proto
  apistructs/pipeline_yml.go
  bundle/pipeline.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/apps/dop/dao/autotest_filetree_extras.go
  internal/apps/dop/initialize.go
  internal/apps/dop/provider.go
  internal/apps/dop/services/autotest/filetree_save_pipeline.go
  internal/apps/dop/services/autotest/service.go
  internal/apps/dop/services/filetree/filetree.go
  internal/core/openapi/legacy/api/apis/pipeline/pipeline_yml_graph.go
  internal/tools/pipeline/endpoints/endpoints.go
  internal/tools/pipeline/endpoints/pipeline.go
  internal/tools/pipeline/providers/cron/compensator/provider.go
  internal/tools/pipeline/providers/cron/cron.service.go
  internal/tools/pipeline/providers/cron/cron.service_test.go
  internal/tools/pipeline/providers/cron/db/define.go
  internal/tools/pipeline/providers/cron/db/define_test.go
  internal/tools/pipeline/providers/graph/graph.service.go
  internal/tools/pipeline/providers/graph/graph.service_test.go
  internal/tools/pipeline/providers/graph/provider.go
  internal/tools/pipeline/services/pipelinesvc/snippet.go
  pkg/parser/pipelineyml/define.go
  pkg/parser/pipelineyml/define_test.go
  pkg/parser/pipelineyml/graph_pipelineyml.go
  pkg/parser/pipelineyml/graph_pipelineyml_test.go
Labels: refactor, approved

#5477 fix(cmp): cmp steve route use ** as wildcard
  internal/apps/cmp/initialize.go
Labels: cmp, bugfix, approved

#5478 fix: openapi miss pipeline-yml-graph route
  api/proto/core/pipeline/graph/graph.proto
Labels: bugfix

#5480 refactor: add error_count chartview
  cmd/monitor/monitor/conf/chartview/error/error_count.json
Labels: refactor

#5479 fix: issue export set empty value for custom property column if value not set
  internal/apps/dop/providers/issue/core/query/convert.go
  internal/apps/dop/providers/issue/core/query/convert_test.go
Labels: bugfix, approved

#5481 refactor: modify the replica of log-service
  erda.yml
Labels: refactor

#5483 feat: global kong policy
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
Labels: feature

#5475 feat: alert template add workspace
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_oom/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_error/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_error/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_rt/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_path_rt/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_error/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_error/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_rt/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/app_transaction/app_transaction_http_service_rt/notify_template.yaml
Labels: feature

#5485 fix: typo
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
Labels: bugfix

#5486 fix: dop invoke cmp resource service failed
  cmd/erda-server/bootstrap.yaml
  internal/apps/cmp/provider.go
Labels: bugfix, approved

#5488 refactor: set monitor env to ck
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
  cmd/msp/bootstrap.yaml
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  internal/apps/msp/resource/provider.go
  internal/apps/msp/resource/runtime.go
  internal/tools/monitor/apm/runtime/provider.go
  internal/tools/monitor/apm/topology/provider.go
  internal/tools/monitor/core/alert/details-apis/provider.go
  internal/tools/monitor/core/metric/query/metricq/provider.go
  internal/tools/monitor/core/metric/query/provider.go
  internal/tools/monitor/dashboard/org-apis/provider.go
  internal/tools/monitor/extensions/loghub/index/query/clients.go
  internal/tools/monitor/extensions/loghub/index/query/provider.go
Labels: refactor

#5484 fix: org center permission of cross-project leak
  internal/apps/dop/component-protocol/components/issue-dashboard/filter/render.go
  internal/apps/dop/component-protocol/components/requirement-task-overview/distributePage/topFilter/render.go
  internal/apps/dop/endpoints/project.go
  internal/apps/dop/endpoints/project_test.go
Labels: bugfix, approved

#5490 fix: modify enable env of clickhouse.table.initializer@log
  cmd/monitor/streaming/bootstrap.yaml
Labels: bugfix

#5489 fix: kafka dependency fix
  cmd/monitor/extensions/cloud-import/bootstrap.yaml
  cmd/monitor/extensions/loghub/conf/output/bootstrap-elasticsearch-rollover.yaml
  cmd/monitor/extensions/loghub/conf/output/bootstrap-elasticsearch.yaml
  cmd/monitor/extensions/loghub/conf/output/bootstrap-stdout.yaml
  cmd/monitor/extensions/loghub/conf/output/bootstrap-udp.yaml
  cmd/monitor/extensions/loghub/log-metrics.yaml
  cmd/monitor/log-service/bootstrap.yaml
  internal/apps/msp/apm/log-service/analysis/provider.go
  internal/tools/monitor/extensions/loghub/exporter/provider.go
  internal/tools/monitor/extensions/loghub/sls-import/provider.go
Labels: bugfix

#5491 fix: modify LOG_STORAGE_WRITER_SERVICE default value
  cmd/monitor/streaming/bootstrap.yaml
Labels: bugfix

#5493 fix: cmp pod metric chartview
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
Labels: bugfix

#5494 fix(cmp): cmp use org.Interface because it bootstrapped on erda-server
  internal/apps/cmp/endpoints/endpoints.go
  internal/apps/cmp/impl/clusters/upgrade_edge_cluster.go
  internal/apps/cmp/impl/mns/mns.go
  internal/apps/cmp/provider.go
Labels: cmp, bugfix, approved

#5492 feat: support metrics meta
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
  internal/tools/monitor/core/metric/metric.go
  internal/tools/monitor/oap/collector/lib/kafka/batchreader.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: feature

#5496 fix: streaming config fix
  cmd/monitor/monitor/conf/chartview/error/error_count.json
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/metrics/ddl_create_default_tables.sql.tpl
Labels: bugfix

#5497 fix: retention not effect fix
  cmd/monitor/streaming/bootstrap.yaml
  internal/tools/monitor/core/settings/retention-strategy/provider.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/provider.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
  internal/tools/monitor/core/storekit/clickhouse/table/loader/provider.go
  internal/tools/monitor/core/storekit/clickhouse/table/loader/table_loader.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go
Labels: bugfix

#5474 refactor(pipeline): pipeline label service to provider
  api/proto/core/pipeline/label/label.proto
  apistructs/pipeline_label.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  internal/tools/pipeline/dbclient/op_pipeline_labels.go
  internal/tools/pipeline/endpoints/endpoints.go
  internal/tools/pipeline/endpoints/pipeline_label.go
  internal/tools/pipeline/providers/label/label.service.go
  internal/tools/pipeline/providers/label/label.service.impl.go
  internal/tools/pipeline/providers/label/label.service_test.go
  internal/tools/pipeline/providers/label/provider.go
Labels: pipeline, refactor, approved

#5500 fix: add es enable env for log-service
  cmd/monitor/log-service/bootstrap.yaml
Labels: bugfix

#5501 fix: add enable config for log-service
  cmd/monitor/log-service/bootstrap.yaml
  internal/tools/monitor/extensions/loghub/exporter/output/elasticsearch/elasticsearch.go
Labels: bugfix

#5505 fix: specify grpc addr for merged-apps in erda.yml
  erda.yml
Labels: bugfix, approved

#5507 fix: log-service start failed
  cmd/monitor/log-service/bootstrap.yaml
Labels: bugfix

#5508 fix: pipeline cron compensator nil pointer
  internal/tools/pipeline/providers/cron/compensator/provider.go
Labels: bugfix, approved

#5509 fix: add clickhouse config for streaming
  cmd/monitor/streaming/bootstrap.yaml
Labels: bugfix

#5510 feat: query pipeline log by k8s storage first
  api/proto/core/monitor/log/query/query.proto
  apistructs/dashboard.go
  bundle/dashboard.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/podsTable/render.go
  internal/apps/dop/endpoints/cicd.go
  internal/tools/monitor/core/log/query/log.query.service.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/provider.go
  internal/tools/monitor/core/log/storage/kubernetes-logs/storage.go
  internal/tools/monitor/core/log/storage/storage.go
Labels: feature

#5511 feat: add chartview of api-gateway
  cmd/monitor/monitor/conf/chartview/api-gateway/consumer-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/error-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/hotspot-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/package-analyze.json
Labels: feature, approved

#5513 fix(openapi): enable openapiv1 hooks
  internal/core/openapi/openapi-ng/routes/openapi-v1/provider.go
Labels: openapi, bugfix, approved

#5514 fix: adjust time config for api-gateway chartview
  cmd/monitor/monitor/conf/chartview/api-gateway/consumer-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/package-analyze.json
Labels: bugfix, approved

#5512 feat: offline update meta cache
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_meta_test.go
  internal/tools/monitor/core/metric/query/es-tsql/query.go
  internal/tools/monitor/core/metric/query/metricmeta/manager.go
  internal/tools/monitor/core/metric/query/metricmeta/provider_meta_clickhouse.go
  internal/tools/monitor/core/metric/query/metricmeta/provider_meta_clickhouse_test.go
  internal/tools/monitor/core/metric/query/metricq/provider.go
  internal/tools/monitor/core/metric/query/provider.go
  internal/tools/monitor/core/metric/query/query/search.go
  internal/tools/monitor/core/metric/storage/elasticsearch/mock_query_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/cache.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/interface.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/mock_clickhouse_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
Labels: feature

#5516 fix: modify entity-storage-elasticsearch provider service
  internal/tools/monitor/core/entity/storage/elasticsearch/provider.go
Labels: bugfix

#5515 fix: test-dashboard & code-coverage cross-project leak
  internal/apps/dop/component-protocol/components/code-coverage/envFilter/render.go
  internal/apps/dop/component-protocol/components/test-dashboard/filter/model.go
Labels: bugfix, approved

#5517 fix: msp 404
  cmd/erda-server/bootstrap.yaml
  internal/apps/msp/resource/provider.go
Labels: bugfix

#5518 fix: msp 404
  cmd/msp/bootstrap.yaml
  internal/apps/msp/resource/provider.go
Labels: bugfix

#5525 fix: save pipeline invalid memory address
  internal/apps/dop/services/autotest/filetree_save_pipeline.go
Labels: bugfix, approved

#5529 fix: engine worker actively trigger panic when context canceled
  internal/tools/pipeline/providers/engine/worker.go
  internal/tools/pipeline/providers/leaderworker/impl_general.go
Labels: bugfix, approved

#5527 fix: scenes file record download url
  internal/apps/dop/component-protocol/components/scenes-import-record/table/render.go
Labels: bugfix, approved

#5532 fix: cluster-agent collect token after k8s version 1.24
  cmd/cluster-agent/bootstrap.yaml
  internal/tools/cluster-agent/config/config.go
  internal/tools/cluster-agent/pkg/client/client.go
Labels: bugfix

#5524 fix: fix offline cache no update and append trace
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/metric/query/es-tsql/influxql/SQLQuery.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_meta_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/query/metricmeta/provider_meta_clickhouse_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/cache.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/interface.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/mock_clickhouse_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
Labels: bugfix

#5533 fix: adjust posation of api-gateway chartview
  cmd/monitor/monitor/conf/chartview/api-gateway/consumer-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/error-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/hotspot-analyze.json
  cmd/monitor/monitor/conf/chartview/api-gateway/package-analyze.json
Labels: bugfix, approved

#5530 feat: file.proto download rpc declare as pure http
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  api/proto-go/Makefile
  api/proto-go/go.mod
  api/proto-go/go.sum
  api/proto/core/file/file.proto
  go.mod
  go.sum
  internal/core/openapi/legacy/api/apis/files/download_v2.go
  pipeline.yml
Labels: feature, approved

#5534 chore: update go mod for proto-go's update-gohub
  api/proto-go/go.mod
  api/proto-go/go.sum
Labels: approved

#5535 feat(openapi): openapi proto route support pure http
  api/proto/core/file/file.proto
  go.mod
  internal/core/file/http.go
  internal/core/openapi/legacy/api/apis/files/download.go
  internal/core/openapi/legacy/api/apis/files/head.go
  internal/core/openapi/legacy/api/apis/files/upload.go
  internal/core/openapi/openapi-ng/routes/proto/proto.go
Labels: feature, openapi, approved

#5531 fix: optimize k8s resource gc logic
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob_test.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sspark/k8sspark.go
  internal/tools/pipeline/pipengine/actionexecutor/types/k8s_executor.go
  internal/tools/pipeline/pipengine/actionexecutor/types/k8s_executor_test.go
Labels: approved

#5539 fix: some fields of pipeline provider
  internal/tools/pipeline/dbclient/op_pipeline.go
  internal/tools/pipeline/providers/pipeline/detail.go
  pkg/common/pbutil/pbutil.go
  pkg/common/pbutil/pbutil_test.go
Labels: bugfix, approved

#5537 fix: chart view disorder
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_meta_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/query_clickhouse_test.go
Labels: bugfix

#5538 feat: erda-cli gw dump/del/create hub
  pkg/http/httpclient/request.go
  pkg/http/httpclient/request_test.go
  tools/cli/cmd/clone.go
  tools/cli/cmd/gw_create.go
  tools/cli/cmd/gw_del.go
  tools/cli/cmd/gw_dump.go
  tools/cli/cmd/gw_gc.go
  tools/cli/cmd/gw_gc_test.go
  tools/cli/cmd/gw_ls.go
  tools/cli/cmd/gw_ls_test.go
  tools/cli/cmd/push.go
  tools/cli/command/context.go
  tools/cli/command/root_cmd.go
  tools/cli/common/browser.go
Labels: feature

#5540 fix(dicehub): registry gc failed
  apistructs/cluster_info.go
  bundle/cluster.go
  internal/apps/cmp/endpoints/endpoints.go
  internal/apps/cmp/endpoints/officer.go
  internal/apps/dop/dicehub/conf/conf.go
  internal/apps/dop/dicehub/endpoints/gc.go
  internal/apps/dop/dicehub/initialize.go
  internal/apps/dop/dicehub/recycle/cron.go
  internal/apps/dop/dicehub/registry/cluster_service_test.go
  internal/apps/dop/dicehub/registry/manifests.go
  internal/apps/dop/dicehub/registry/manifests_test.go
  internal/apps/dop/dicehub/release/provider.go
  internal/apps/dop/dicehub/release/release.go
  internal/apps/dop/dicehub/release/release.service.go
  internal/apps/dop/dicehub/service/release/release.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
  pkg/http/httpclient/client.go
  pkg/registryhelper/manifests.go
Labels: bugfix

#5545 fix: project-pipeline add orgName label for monitor collector
  internal/apps/dop/endpoints/project_pipeline.go
  internal/apps/dop/endpoints/project_pipeline_test.go
Labels: bugfix, approved
