Repository erda-project/erda, pull requests merged in 2023-05, with the labels that each got.

#5836 feat: hepa support MSE Ingress annotation-based policy
  internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
  internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/cors/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy_test.go
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/custom/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/custom/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/proxy/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
  internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/waf/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/waf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/common/annotations.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_openapi.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth.go
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/service.go
Labels: feature, approved

#5839 feat: loghttp
  internal/apps/ai-proxy/filters/audit/filter_test.go
  internal/apps/ai-proxy/filters/log-http/filter.go
Labels: feature, approved

#5841 feat: hepa support mse erda-ip plugined policy
  internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy_test.go
  internal/tools/orchestrator/hepa/apipolicy/policies/proxy/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_ip.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_ip_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_hmac_auth.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_hmac_auth_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_key_auth.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_key_auth_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth.go
  internal/tools/orchestrator/hepa/providers/endpoint_api/endpoint.api.service.go
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/global/impl/impl.go
  internal/tools/orchestrator/hepa/services/legacy_consumer/impl/impl.go
  internal/tools/orchestrator/hepa/services/legacy_upstream/impl/impl.go
  internal/tools/orchestrator/hepa/services/legacy_upstream_lb/impl/impl.go
  internal/tools/orchestrator/hepa/services/micro_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
  internal/tools/orchestrator/hepa/services/zone/impl/impl.go
Labels: feature, approved

#5843 feat: multiarch pipeline
  Makefile
  build/dockerfiles/Dockerfile
  build/dockerfiles/cli/Dockerfile
  build/dockerfiles/cluster-agent/Dockerfile
  build/scripts/buildkit_image.sh
  pipeline.yml
Labels: feature

#5832 feat(monitor): collect and consume profile
  .erda/migrations/config.yml
  .erda/migrations/monitor/20230506-sp-profile-apps.sql
  .erda/migrations/msp/20230510-menu.sql
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/monitor/main.go
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/profiles_ddl_create_db.sql
  cmd/monitor/streaming/conf/clickhouse/profiles_ddl_create_default_tables.sql
  cmd/monitor/streaming/main.go
  go.mod
  go.sum
  internal/core/openapi/legacy/api/apis/monitor/monitor_profile_app_list.go
  internal/core/openapi/legacy/api/apis/monitor/monitor_profile_label_list.go
  internal/core/openapi/legacy/api/apis/monitor/monitor_profile_label_value_list.go
  internal/core/openapi/legacy/api/apis/monitor/monitor_profile_render.go
  internal/core/openapi/legacy/api/apis/monitor/monitor_profile_render_diff.go
  internal/tools/monitor/core/profile/profile.go
  internal/tools/monitor/core/profile/query/app.go
  internal/tools/monitor/core/profile/query/label.go
  internal/tools/monitor/core/profile/query/provider.go
  internal/tools/monitor/core/profile/query/render-diff.go
  internal/tools/monitor/core/profile/query/render.go
  internal/tools/monitor/oap/collector/core/config/config.go
  internal/tools/monitor/oap/collector/core/model/exporter.go
  internal/tools/monitor/oap/collector/core/model/odata/buffer.go
  internal/tools/monitor/oap/collector/core/model/odata/odata.go
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
  internal/tools/monitor/oap/collector/core/provider.go
  internal/tools/monitor/oap/collector/lib/protoparser/spotprofile/profile.go
  internal/tools/monitor/oap/collector/plugins/all/all.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/collector/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/pyroscope/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/stdout/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/collector.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/kafka.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/profile.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: feature

#5842 feat: reverse proxy for text/event-stream
  .erda/ai/migrations/ai-proxy/20230425-filter-audit.sql
  cmd/ai-proxy/bootstrap.yml
  cmd/ai-proxy/conf/providers.yml
  cmd/ai-proxy/conf/routes.yml
  internal/apps/ai-proxy/dependent_filters.go
  internal/apps/ai-proxy/dependent_providers.go
  internal/apps/ai-proxy/filters/audit/filter.go
  internal/apps/ai-proxy/filters/audit/filter_test.go
  internal/apps/ai-proxy/filters/log-http/filter.go
  internal/apps/ai-proxy/filters/prometheus-collector/dependent.go
  internal/apps/ai-proxy/filters/prometheus-collector/filter.go
  internal/apps/ai-proxy/filters/protocol-translator/filter.go
  internal/apps/ai-proxy/filters/protocol-translator/filter_test.go
  internal/apps/ai-proxy/filters/reverse-proxy/filter.go
  internal/apps/ai-proxy/metrics/collector.go
  internal/apps/ai-proxy/metrics/metrics.go
  internal/apps/ai-proxy/metrics/prvider.go
  internal/apps/ai-proxy/provider.go
  internal/pkg/ai-proxy/filter/filter.go
  internal/pkg/ai-proxy/filter/header_body_getter.go
  internal/pkg/ai-proxy/route/route.go
  internal/pkg/ai-proxy/route/route_test.go
  pkg/http/httputil/mediatype.go
  pkg/reverseproxy/context.go
  pkg/reverseproxy/context_test.go
  pkg/reverseproxy/director.go
  pkg/reverseproxy/filter.go
  pkg/reverseproxy/filter_test.go
  pkg/reverseproxy/filters.go
  pkg/reverseproxy/register.go
  pkg/reverseproxy/reverseproxy.go
  pkg/reverseproxy/transport.go
  pkg/strutil/strutil.go
  pkg/strutil/strutil_test.go
Labels: feature, approved

#5820 feat(orchestrator): add exporter sidecar for kafka cluster addon
  cmd/monitor/monitor/conf/chartview/runtime/addon-kafka.json
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_status_test.go
Labels: orchestrator, feature

#5850 feat(dop): issue-manager default show unfinished state tickets
  internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/provider_test.go
Labels: dop, feature, approved

#5853 fix: use taobao npm registry install jackson-converter
  build/dockerfiles/Dockerfile
Labels: bugfix, approved

#5854 fix: use aliyun pypi to install package
  build/dockerfiles/Dockerfile
  pipeline.yml
Labels: bugfix, approved

#5855 fix: use tsinghua pypi to install package
  build/dockerfiles/Dockerfile
Labels: bugfix, approved

#5851 feat: Pass in logger from the reverse proxy framework level; delete *reverseproxy.Context
  internal/apps/ai-proxy/filters/audit/filter.go
  internal/apps/ai-proxy/filters/log-http/filter.go
  internal/apps/ai-proxy/filters/prometheus-collector/filter.go
  internal/apps/ai-proxy/filters/protocol-translator/filter.go
  internal/apps/ai-proxy/provider.go
  internal/pkg/ai-proxy/route/route.go
  pkg/reverseproxy/context.go
  pkg/reverseproxy/context_test.go
  pkg/reverseproxy/filter.go
  pkg/reverseproxy/filter_test.go
  pkg/reverseproxy/register.go
  pkg/reverseproxy/reverseproxy.go
Labels: feature, approved

#5856 fix: enable monitor-injector
  pipeline.yml
Labels: bugfix, approved

#5857 chore(monitor): set profile data 1day ttl
  .erda/migrations/config.yml
  .erda/migrations/monitor/20230515-sp-profile-apps.sql
  cmd/monitor/streaming/bootstrap.yaml
  go.mod
  go.sum
Labels: approved

#5860 feat(orchestrator): add collector env to dice service
  internal/tools/orchestrator/conf/conf.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
Labels: orchestrator, feature

#5861 feat: add profile provider for continuous profiling
  .erda/migrations/msp/20230516-menu.sql
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/monitor/main.go
  cmd/orchestrator/bootstrap.yaml
  cmd/orchestrator/main.go
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  go.mod
  go.sum
  internal/pkg/profileagent/provider.go
Labels: feature, approved

#5859 chore(pipeline): pipeline, task processing metrics
  internal/tools/pipeline/providers/reconciler/pipeline_reconciler.go
Labels: pipeline, approved

#5862 fix(monitor): query profile app missing url query
  internal/tools/monitor/core/profile/query/app.go
Labels: bugfix, approved

#5869 fix: fix streaming no data
  internal/tools/monitor/core/settings/retention-strategy/ttl.go
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
Labels: bugfix

#5867 fix: clickhouse parse timestamp desc invalid
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5858 feat: hepa support mse erda-sbac
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_ip.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_sbac.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_sbac_test.go
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
Labels: feature, approved

#5874 fix: fix drop future metric data
  cmd/monitor/streaming/bootstrap.yaml
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: bugfix, approved

#5876 fix(monitor): no need to do orderby on selected-column, in the case of already sorted by time
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5875 fix: fix receiver_droped metric error
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: bugfix, approved

#5871 feat: add manHour to iteration API
  .erda/migrations/cmdb/20230522-interation-man-hour.sql
  .github/workflows/ci-it.yml
  apistructs/issue.go
  apistructs/issue_test.go
  apistructs/iteration.go
  internal/apps/dop/dao/iteration.go
  internal/apps/dop/services/iteration/iteration.go
Labels: feature, approved

#5873 fix(orchestrator): cluster recreate executor cause goroutine pool panic
  internal/tools/orchestrator/scheduler/executor/executor.go
  internal/tools/orchestrator/scheduler/task/sched.go
  pkg/goroutinepool/goroutinepool.go
  pkg/goroutinepool/goroutinepool_test.go
Labels: orchestrator, bugfix

#5883 feat: hepa support mse erda-csrf
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_csrf.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_csrf_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_erda_sbac.go
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
Labels: approved

#5881 fix(cmp): the surge in the number of goroutines caused by api change in erda-server
  internal/apps/cmp/steve/schemas.go
Labels: cmp, bugfix, approved

#5885 fix: fix streaming no write
  internal/apps/msp/apm/trace/span.go
  internal/tools/monitor/core/log/log.go
  internal/tools/monitor/core/log/storage/clickhouse/writer.go
  internal/tools/monitor/core/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/storage.go
Labels: bugfix, approved

#5884 fix(pipeline): agent missing logs when logic quickly
  build/dockerfiles/Dockerfile-action-agent
  internal/tools/pipeline/actionagent/exit.go
  internal/tools/pipeline/actionagent/file_watch.go
  internal/tools/pipeline/actionagent/file_watch_test.go
  internal/tools/pipeline/actionagent/prestop.go
Labels: pipeline, bugfix

#5886 fix(hepa): mse csrf validate allow RefreshTTL<=0
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/dto.go
Labels: hepa, bugfix

#5868 feat(monitor): add profiling query metrics
  go.mod
  go.sum
  internal/tools/monitor/core/profile/query/metrics.go
  internal/tools/monitor/core/profile/query/render-diff.go
  internal/tools/monitor/core/profile/query/render.go
Labels: feature, approved

#5882 fix: fix clickhouse parser sql no order
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved
