Repository erda-project/erda, pull requests merged in 2023-04, with the labels that each got.

#5746 fix: kong data field created_at unmarshal
  internal/tools/orchestrator/hepa/gateway-providers/kong/dto/kong_target_dto.go
  internal/tools/orchestrator/hepa/gateway-providers/kong/dto/kong_target_dto_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
  internal/tools/orchestrator/hepa/services/legacy_upstream_lb/impl/impl.go
Labels: bugfix

#5780 fix(orchestrator): create service failure due to invalid label or selector
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/service.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/service_test.go
Labels: orchestrator, bugfix, approved

#5783 feat: multi-arch image for erda-base:20230130
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  build/scripts/docker_image.sh
  pipeline.yml
Labels: feature, approved

#5748 fix(collector): missing `oomkilled` metric after collect metrics from cadvisor
  cmd/monitor/collector/bootstrap.yaml
  internal/tools/monitor/oap/collector/plugins/processors/aggregator/functions.go
  internal/tools/monitor/oap/collector/plugins/processors/aggregator/provider_test.go
Labels: bugfix, approved

#5770 feat: Support for deploying Nacos on MySQL using the MySQL Operator process
  .erda/migrations/msp/20230321-tmc-version.sql
  Makefile
  api/proto/orchestrator/addon/mysql/mysql.proto
  apistructs/addon.go
  build/dockerfiles/Dockerfile
  build/scripts/docker_image.sh
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/conf/msp/init_sqls/tmc/migrate_nacos1.x_2.x.sql
  cmd/erda-server/conf/msp/init_sqls/tmc/nacos2.2.sql
  internal/apps/dop/dicehub/registry/manifests_test.go
  internal/apps/msp/resource/deploy/coordinator/coordinator.go
  internal/apps/msp/resource/deploy/coordinator/provider.go
  internal/apps/msp/resource/deploy/handlers/mysql/mysql.go
  internal/apps/msp/resource/deploy/handlers/mysql/mysql_cli_adapter.go
  internal/apps/msp/resource/deploy/handlers/mysql/mysql_cli_adapter_test.go
  internal/apps/msp/resource/deploy/handlers/mysql/mysql_test.go
  internal/apps/msp/resource/deploy/handlers/mysql/provider.go
  internal/apps/msp/resource/deploy/handlers/postgresql/postgresql.go
  internal/tools/orchestrator/components/addon/mysql/mysql.service.go
  internal/tools/orchestrator/components/addon/mysql/mysql.service_test.go
  internal/tools/orchestrator/components/addon/mysql/provider.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/operations.go
  internal/tools/orchestrator/scheduler/impl/servicegroup/servicegroup.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_deploy_test.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_status.go
  pkg/mysqlhelper/mysql.go
  pkg/strutil/json.go
Labels: feature, approved

#5792 feat: nacos grpc port
  Makefile
  internal/apps/msp/resource/deploy/handlers/configcenter/configcenter.go
  internal/apps/msp/resource/deploy/handlers/nacos/nacos.go
  internal/apps/msp/resource/deploy/handlers/registercenter/registercenter.go
Labels: feature

#5797 fix: workbench contribution permission leak
  internal/apps/dop/providers/contribution/provider.go
Labels: bugfix

#5800 fix: fix tail suffix container id not match
  cmd/monitor/collector/bootstrap.yaml
Labels: bugfix, approved

#5803 fix: create table tb_gateway_credential if not exist
  .erda/migrations/hepa/20230331-hepa-gateway-consumer-credential.sql
Labels: bugfix

#5802 fix(dop): issues states always be default after refresh
  internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/conditions_test.go
  internal/apps/dop/component-protocol/standard-components/issueFilter/provider.go
Labels: dop, bugfix, approved

#5806 fix(orchestrator): rocketmq resource missing replicas definition
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_status_test.go
Labels: orchestrator, bugfix, approved

#5775 fix: alert over permission
  api/proto/core/monitor/alert/alert.proto
  internal/apps/msp/apm/alert/alert.service.go
  internal/tools/monitor/core/alert/alert-apis/adapt/alert.go
  internal/tools/monitor/core/alert/alert-apis/alert.service.go
  internal/tools/monitor/core/alert/alert-apis/db/alert.go
Labels: bugfix, approved

#5807 fix: fix checker table no data
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
  internal/apps/msp/apm/checker/apis/checker.v1.service_test.go
Labels: bugfix, approved

#5811 fix: fix check monitor detail no data
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
Labels: bugfix

#5815 fix: domain-policy regex
  internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
Labels: bugfix, approved

#5818 feat: hepa support mse para-sign-auth plugin
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/gateway-providers/dto/credential_resp_dto.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/common/constant.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/dto/mse_plugin_configuration.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_adapter_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/mse_openapi.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_hmac_auth.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_hmac_auth_test.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_key_auth.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth.go
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/mse_para_sign_auth_test.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl_test.go
  internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_rule/interface.go
Labels: feature

#5822 feat: erda-cli hmac client
  tools/cli/cmd/gw_debug_auth.go
Labels: feature, approved

#5824 fix: fix collect metric concurrent read map
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
Labels: bugfix, approved

#5823 fix: otlp metrics proto type error
  Makefile
  api/proto-go/Makefile
  api/proto/.gitignore
  api/proto/README.md
  api/proto/oap/collector/receiver/opentelemetry/opentelemetry.proto
  api/proto/oap/common/common.proto
  api/proto/oap/opentelemetry/metrics.proto
  api/proto/proto_fetcher.sh
Labels: bugfix, approved

#5835 fix(pipeline): flinkcluster job missing log due to org annotations
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
Labels: pipeline, bugfix, approved
