Repository erda-project/erda, pull requests merged in 2023-01, with the labels that each got.

#5654 feat: rocketmq operator support all versions
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/rocketmq/rocketmq.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_test.go
  internal/tools/orchestrator/services/addon/middleware.go
  internal/tools/orchestrator/services/addon/middleware_test.go
Labels: feature

#5655 fix(erda-server): project label permission leak
  internal/core/legacy/endpoints/label.go
  internal/core/legacy/endpoints/label_test.go
Labels: bugfix, approved

#5657 fix(dop): issue-stream's compatibility with label types
  apistructs/issue_stream_locale.go
  internal/apps/dop/providers/issue/core/service.go
  internal/apps/dop/providers/issue/stream/common/model.go
Labels: dop, bugfix

#5658 fix: addon alert not append
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/notify_template.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/notify_template.yaml
Labels: bugfix

#5659 fix(dop): issue-import stage value
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/file_test.go
Labels: dop, bugfix, approved

#5660 fix(erda-server): sysadmin permission leak
  internal/apps/cmp/endpoints/cluster.go
  internal/core/legacy/endpoints/notify_item.go
  internal/core/legacy/endpoints/permission.go
  internal/tools/monitor/core/settings/settings.service.go
  internal/tools/monitor/core/settings/settings.service_test.go
Labels: bugfix, approved

#5666 fix: general user query notify-items access denied
  internal/core/legacy/endpoints/notify_item.go
Labels: bugfix, approved

#5664 feat(orchestrator): redis addon sts add exporter sidecar
  apistructs/addon.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_status_test.go
Labels: orchestrator, feature

#5662 fix: memory chart no incorrect
  internal/apps/msp/apm/service/components/resources-runtime-monitor-java/runtime/provider.go
Labels: bugfix, approved

#5661 fix: fix sort no orderly
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5667 fix: fix get pod status from k8s failed due pod without runtimeId label
  apistructs/container.go
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
Labels: bugfix, approved

#5670 fix: error-analysis chart is empty
  internal/apps/msp/apm/exception/query/source/elasticsearch_source.go
  internal/tools/monitor/core/event/persist/consume.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5669 fix(dop): issue detail missing property instances
  internal/apps/dop/providers/issue/core/query/convert.go
  internal/apps/dop/providers/issue/core/query/convert_test.go
  internal/apps/dop/providers/issue/core/service.go
Labels: dop, bugfix, approved

#5671 feat: addon rocketmq monitor chart
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/monitor/conf/chartview/runtime/addon-rocketmq.json
  internal/tools/monitor/core/storekit/clickhouse/table/meta/interface.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
Labels: feature, approved

#5673 fix: fix status_page metric not ttl
  internal/apps/msp/apm/checker/apis/checker.v1.service.go
  pkg/common/apis/header.go
Labels: bugfix

#5674 fix(dop): optimize user and time display of custom properties in issue export
  internal/apps/dop/providers/issue/core/query/convert.go
  internal/apps/dop/providers/issue/core/query/convert_test.go
  internal/tools/pipeline/providers/edgepipeline_register/edge_client.go
Labels: dop, bugfix, approved

#5672 fix(orchestrator): o11 edas executor delete application error
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_event.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/utils.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/utils_test.go
Labels: orchestrator, bugfix

#5675 fix(cmp): cmp server panic due to steveServer not initialized
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/podTable/render_test.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/table/render.go
Labels: cmp, bugfix, approved

#5663 fix: clickhouse query agg column should be exist
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix

#5668 fix: project release addon render error
  apistructs/addon.go
  internal/apps/dop/dicehub/release/release.service.go
  internal/pkg/addonutil/addonutil.go
  internal/pkg/addonutil/addonutil_test.go
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: bugfix

#5678 fix: service list no otel data
  cmd/monitor/collector/bootstrap.yaml
Labels: bugfix, approved
