Repository erda-project/erda, pull requests merged in 2023-12, with the labels that each got.

#6149 fix: fix issue excel_export_template i18n
  cmd/erda-server/conf/i18n/issue-excel.yaml
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export_template.go
Labels: bugfix, approved

#6152 feat: add pod finished time
  apistructs/container.go
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
Labels: feature, approved

#6164 fix(monitor): transaction avg duration inconsistency
  internal/apps/msp/apm/service/view/table/transaction.go
Labels: bugfix, approved

#6155 feat: set ErrorStyle=information for cell DropList to avoid warning opening by Microsoft-Excel
  pkg/excel/multi_sheet.go
  pkg/excel/multi_sheet_test.go
Labels: feature

#6158 feat(gittar): polish ai code review
  internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/snippet.go
  internal/tools/gittar/ai/cr/impl/cr_mr_file/file.go
  internal/tools/gittar/models/note.go
  internal/tools/gittar/models/note_cr.go
Labels: feature, gittar

#6168 fix(monitor): entity grpc client exceed default recv bytes
  internal/apps/msp/apm/exception/query/provider.go
Labels: bugfix

#6162 fix(cmp): failed to sync records due to bundle missing error msg
  bundle/pipeline.go
Labels: cmp, bugfix, approved

#6170 fix: fix repeat source/definition records
  internal/tools/pipeline/providers/source/db/source.go
Labels: bugfix, approved

#6173 chore: change init container image registry to erda
  internal/tools/orchestrator/conf/conf.go
Labels: approved

#6174 fix(heap): acl rule leak
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_consumer/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_consumer/interface.go
Labels: bugfix, approved

#6176 fix(ai-function): optimal prompt
  internal/pkg/ai-functions/functions/test-case/function.go
  internal/pkg/ai-functions/functions/test-case/group.go
Labels: bugfix

#6175 perf(monitor): optimize writing logic and accelerate query logic to optimize user experience
  cmd/monitor/streaming/conf/clickhouse/profiles_ddl_create_default_tables.sql
  go.mod
  go.sum
  internal/tools/monitor/oap/collector/plugins/processors/profile/provider.go
Labels: approved

#6177 feat(gittar): AI MR CR support AI-Proxy Session
  api/proto/apps/aiproxy/audit/audit.proto
  api/proto/apps/aiproxy/client/client.proto
  api/proto/apps/aiproxy/client/rich_client/rich_client.proto
  api/proto/apps/aiproxy/client_model_relation/client_model_relation.proto
  api/proto/apps/aiproxy/client_token/client_token.proto
  api/proto/apps/aiproxy/message/message.proto
  api/proto/apps/aiproxy/metadata/metadata.proto
  api/proto/apps/aiproxy/model/model.proto
  api/proto/apps/aiproxy/model_provider/model_provider.proto
  api/proto/apps/aiproxy/prompt/prompt.proto
  api/proto/apps/aiproxy/session/session.proto
  apistructs/gittar.go
  cmd/gittar/bootstrap.yaml
  go.mod
  go.sum
  internal/apps/ai-proxy/sdk/client/provider.go
  internal/apps/gallery/handler/funcs_test.go
  internal/core/project/dao/option.go
  internal/tools/gittar/ai/cr/util/aiutil/invoke.go
  internal/tools/gittar/api/error_data.go
  internal/tools/gittar/api/merge.go
  internal/tools/gittar/conf/conf.go
  internal/tools/gittar/models/note.go
  internal/tools/gittar/provider.go
  pkg/common/apis/context.go
Labels: feature, gittar

#6154 fix: fix get action props i18n
  apistructs/extention.go
  bundle/dicehub.go
  internal/core/openapi/legacy/component-protocol/scenarios/action/components/actionForm/action_form.go
  internal/core/openapi/legacy/component-protocol/scenarios/action/components/actionForm/render.go
  internal/pkg/extension/provider.go
Labels: bugfix, approved

#6183 fix: Ignore pipeline source creation logic if the source already exists when creating a pipeline
  api/proto/dop/projectpipeline/projectpipeline.proto
  internal/apps/dop/providers/projectpipeline/project_source.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
Labels: bugfix, approved

#6172 fix: fix create cron logic when create pipeline
  api/proto/core/pipeline/cron/cron.proto
  internal/apps/dop/endpoints/pipelinecron.go
  internal/apps/dop/providers/projectpipeline/service_impl.go
  internal/apps/dop/providers/projectpipeline/service_impl_test.go
  internal/tools/pipeline/providers/cron/cron.service.go
Labels: bugfix, approved

#6184 fix: optimal prompt
  internal/pkg/ai-functions/functions/test-case/function.go
  internal/pkg/ai-functions/functions/test-case/group.go
  internal/pkg/ai-functions/provider.go
Labels: approved

#6182 fix: gc deprecated release
  internal/apps/dop/dicehub/release/cron.go
  internal/apps/dop/dicehub/release/release.go
  internal/apps/dop/dicehub/release/release.service.go
  internal/apps/dop/dicehub/release/release_test.go
Labels: bugfix, approved

#6186 fix(monitor): transaction table sort by avgDuration failed
  internal/apps/msp/apm/service/view/table/transaction.go
Labels: bugfix, approved

#6180 refactor(gittar): adjust find section logic
  internal/tools/gittar/models/note.go
  internal/tools/gittar/models/note_test.go
Labels: refactor, gittar

#6179 feat: reduce orchestrator HealthCheckDuration
  apistructs/service_job_status.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/healthcheck.go
Labels: feature, approved

#6187 fix(ai-proxy): stt audit empty responseBody
  internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
  pkg/reverseproxy/reverseproxy.go
Labels: bugfix

#6181 feat: metrics addition item IDs
  apistructs/iteration.go
  internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render.go
  internal/apps/dop/component-protocol/components/test-dashboard/overview_group/quality_chart/render_test.go
  internal/apps/dop/providers/efficiency_measure/calculate.go
  internal/apps/dop/providers/efficiency_measure/metric.go
  internal/apps/dop/providers/efficiency_measure/metric_test.go
  internal/apps/dop/providers/efficiency_measure/provider.go
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/issue/dao/issue_relation.go
  internal/apps/dop/providers/issue/dao/performance_measure.go
  internal/apps/dop/providers/project_report/calculate.go
  internal/apps/dop/providers/project_report/calculate_test.go
  internal/apps/dop/providers/project_report/metrics.go
  internal/apps/dop/providers/project_report/prometheus.go
  internal/apps/dop/providers/project_report/provider.go
  pkg/arrays/arrays.go
  pkg/arrays/arrays_test.go
Labels: feature, approved

#6188 fix(gittar): skip find diff section if all line numbers is 0 (e.g. MR_FILE type ai code-review)
  internal/tools/gittar/models/note.go
  internal/tools/gittar/models/note_test.go
Labels: bugfix, gittar

#6189 feat(ai-proxy): support proxy image API (dall-e)
  api/proto/apps/aiproxy/audit/audit.proto
  cmd/ai-proxy/conf/routes.yml
  go.mod
  go.sum
  internal/apps/ai-proxy/common/ctxhelper/image.go
  internal/apps/ai-proxy/dependent_filters.go
  internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
  internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
  internal/apps/ai-proxy/filters/context-image/filter.go
  internal/apps/ai-proxy/models/audit/dbclient.go
  internal/apps/ai-proxy/models/metadata/meta_audit.go
  internal/apps/ai-proxy/vars/consts.go
Labels: feature

#6191 fix: migration interrupted due to requests version
  .erda/migrations/cmdb/requirements.txt
Labels: bugfix, approved

#6193 fix(gittar): AI code-review restore diff-lines from old-diff-note in one discussion
  internal/tools/gittar/models/note.go
Labels: bugfix, gittar

#6196 feat: remove the check on the Key of the environment variable
  internal/tools/orchestrator/scheduler/executor/plugins/edas/utils/runtime.go
Labels: feature, approved

#6198 perf(orchestrator): optimize the sql statement to get the last api id
  internal/tools/orchestrator/hepa/repository/service/gateway_upstream_api_service.go
Labels: orchestrator, approved

#6199 feat: remove the check on the Key of the environment variable in addon
  internal/tools/orchestrator/endpoints/addon.go
Labels: feature, approved

#6147 feat: add license agent openapi proxy
  .erda/migrations/license-agent/20230927-license-base.sql
  apistructs/license_agent.go
  internal/core/openapi/legacy/api/apis/license_agent/agent_license_feature_get.go
  internal/core/openapi/legacy/api/apis/license_agent/agent_license_get.go
  internal/core/openapi/legacy/api/apis/license_agent/agent_register_license_post.go
Labels: feature, approved

#6202 fix(orchestrator): edas list application multi response error
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go
Labels: orchestrator, bugfix, approved

#6204 fix(hepa): hepa `EOF` due to client not found
  internal/tools/orchestrator/hepa/services/org_client/impl/impl.go
Labels: hepa, bugfix, approved
