Repository erda-project/erda, pull requests merged in 2023-08, with the labels that each got.

#6008 fix(monitor): frontend chart overview wrong timestamp order
  cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
Labels: bugfix, approved

#6007 fix(streaming): external-metric missing non-need retention provider
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go
Labels: bugfix, approved

#6000 feat: erda-cli gorm gen
  api/proto/apps/aiproxy/chatlog.proto
  cmd/ai-proxy/bootstrap.yml
  cmd/ai-proxy/conf/.gitkeep
  cmd/ai-proxy/conf/providers.yml
  cmd/ai-proxy/conf/routes.yml
  go.sum
  internal/apps/ai-proxy/.http
  internal/apps/ai-proxy/filters/acl/filter.go
  internal/apps/ai-proxy/filters/audit/filter.go
  internal/apps/ai-proxy/filters/audit/filter_test.go
  internal/apps/ai-proxy/filters/erda-auth/filter.go
  internal/apps/ai-proxy/filters/session-context/filter.go
  internal/apps/ai-proxy/handlers/errors.go
  internal/apps/ai-proxy/handlers/handler_chatlogs.go
  internal/apps/ai-proxy/handlers/handler_credentials.go
  internal/apps/ai-proxy/handlers/handler_sessions.go
  internal/apps/ai-proxy/models/ai_proxy_credentials.go
  internal/apps/ai-proxy/models/ai_proxy_credentials_curd.go
  internal/apps/ai-proxy/models/ai_proxy_credentials_protobuf.go
  internal/apps/ai-proxy/models/ai_proxy_filter_audit.go
  internal/apps/ai-proxy/models/ai_proxy_filter_audit_curd.go
  internal/apps/ai-proxy/models/ai_proxy_filter_audit_curd_test.go
  internal/apps/ai-proxy/models/ai_proxy_filter_audit_protobuf.go
  internal/apps/ai-proxy/models/ai_proxy_sessions.go
  internal/apps/ai-proxy/models/ai_proxy_sessions_curd.go
  internal/apps/ai-proxy/models/ai_proxy_sessions_protobuf.go
  internal/apps/ai-proxy/models/crud.go
  internal/apps/ai-proxy/models/where.go
  internal/apps/ai-proxy/provider.go
  internal/apps/ai-proxy/providers/dao/provider.go
  internal/apps/ai-proxy/providers/metrics/collector.go
  internal/apps/ai-proxy/vars/consts.go
  pkg/http/httputil/header.go
  pkg/reverseproxy/filter.go
  pkg/reverseproxy/filter_test.go
  pkg/reverseproxy/reverseproxy.go
  tools/cli/cmd/gorm.go
  tools/cli/cmd/gorm_gen.go
  tools/cli/command/root_cmd.go
Labels: feature, approved

#6012 fix(monitor): domain overview chart timestamp error
  cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
Labels: bugfix, approved

#5991 feat: make project delivery management report basic provider
  apistructs/issue.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/monitor/collector/bootstrap.yaml
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/issue/dao/issue_relation.go
  internal/apps/dop/providers/project_report/cache.go
  internal/apps/dop/providers/project_report/calculate.go
  internal/apps/dop/providers/project_report/calculate_test.go
  internal/apps/dop/providers/project_report/metrics.go
  internal/apps/dop/providers/project_report/metrics_test.go
  internal/apps/dop/providers/project_report/prometheus.go
  internal/apps/dop/providers/project_report/prometheus_test.go
  internal/apps/dop/providers/project_report/provider.go
Labels: feature, approved

#6014 fix: executor goroutine pool empty when update
  internal/core/messenger/eventbox/dispatcher/filters/webhookfilter.go
  internal/core/messenger/eventbox/dispatcher/filters/webhookfilter_test.go
  internal/tools/orchestrator/scheduler/executor/executor.go
  internal/tools/orchestrator/scheduler/executor/executortypes/types.go
Labels: bugfix

#6015 feat(dop): support for associating project with labels
  apistructs/issue.go
  apistructs/label.go
  apistructs/project.go
  bundle/label.go
  internal/apps/dop/endpoints/project.go
  internal/apps/dop/providers/project_report/calculate.go
  internal/apps/dop/providers/project_report/prometheus.go
  internal/core/legacy/dao/label_relation.go
  internal/core/legacy/endpoints/project.go
  pkg/mock/mock.go
  pkg/mock/mock_test.go
Labels: dop, feature, approved

#6018 fix(heap): nginx with modules
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  build/dockerfiles/Dockerfile
  build/dockerfiles/base/Dockerfile
  build/scripts/buildkit_image.sh
  build/scripts/docker_image.sh
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  pipeline.yml
Labels: bugfix, approved

#6016 feat(monitor): query external metrics by clickhouse storage
  apistructs/project_report.go
  bundle/project.go
  cmd/erda-server/main.go
  conf/erda-configs/permission/backend/sys/org/org.yml
  conf/erda-configs/permission/front/org/org.yml
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/issue/dao/issue_relation.go
  internal/apps/dop/providers/project_report/calculate.go
  internal/apps/dop/providers/project_report/metrics.go
  internal/apps/dop/providers/project_report/provider.go
  internal/apps/dop/providers/project_report/query.go
  internal/apps/dop/providers/project_report/query_test.go
  internal/core/legacy/endpoints/project.go
  internal/core/legacy/services/project/project.go
  internal/core/legacy/services/project/project_test.go
  internal/core/openapi/legacy/api/apis/dop/project_report_query.go
  internal/tools/monitor/apm/topology/topology_test.go
  internal/tools/monitor/core/alert/alert-apis/adapt/alert_metricq_test.go
  internal/tools/monitor/core/metric/query/metricq/metricq.go
  internal/tools/monitor/core/metric/query/metricq/provider.go
  internal/tools/monitor/core/metric/query/metricq/routes.go
  internal/tools/monitor/core/metric/query/query/query.go
  internal/tools/monitor/core/metric/query/query/search.go
  internal/tools/monitor/core/metric/storage/clickhouse/provider.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
  internal/tools/monitor/core/metric/storage/elasticsearch/query.go
  internal/tools/monitor/core/metric/storage/storage.go
  internal/tools/monitor/dashboard/org-apis/routes.go
  pkg/http/httpserver/response.go
Labels: feature, approved

#6023 fix: project report metric randomly take values from daily data
  internal/apps/dop/providers/project_report/query.go
Labels: bugfix, approved

#6022 fix(hepa): nginx custom validating support set more add_header
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
Labels: hepa, bugfix, approved

#6026 fix(monitor): browser overview timeline error
  cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
Labels: bugfix, approved

#6025 fix: report project support display name
  internal/apps/dop/providers/project_report/calculate.go
  internal/apps/dop/providers/project_report/metrics.go
  internal/apps/dop/providers/project_report/query.go
Labels: bugfix, approved

#6024 feat: canal admin
  build/dockerfiles/Dockerfile-action-agent
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/canal_types.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/canal_validate.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/v1/zz_generated.deepcopy.go
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: feature

#6029 feat(dop): add estimated metrics for task
  apistructs/issue.go
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/providers/project_report/calculate.go
  internal/apps/dop/providers/project_report/metrics.go
  internal/apps/dop/providers/project_report/query.go
Labels: dop, feature, approved

#6030 polish(dop): log print issueID&propertyID when custom-field errors occurred
  internal/apps/dop/providers/issue/core/query/property.go
Labels: dop
