Repository erda-project/erda, pull requests merged in 2023-02, with the labels that each got.

#5677 fix: metric query head time bucket not full, time is not true
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5680 fix: fix service list no data
  cmd/monitor/collector/bootstrap.yaml
  internal/apps/msp/apm/service/components/service-list/provider.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
Labels: bugfix, approved

#5682 fix(orchestrator): edas runtime replicas show error
  internal/tools/orchestrator/components/runtime/runtime.service.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go
Labels: orchestrator, bugfix

#5683 fix(orchestrator): o11 edas pod status show error
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/utils.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/utils_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
Labels: orchestrator, bugfix

#5691 fix: fix org metric not show meta
  internal/tools/monitor/core/storekit/clickhouse/table/meta/provider.go
Labels: approved

#5694 feat: volume-provisioner and cluster-agent support arm arch
  build/dockerfiles/Dockerfile-volume-provisioner
  build/dockerfiles/cluster-agent/Dockerfile
  build/scripts/docker_image.sh
Labels: feature, approved

#5693 feat: topology merge TargetOtherNode by httpUrl
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/apm/topology/provider.go
  internal/tools/monitor/apm/topology/routes.go
  internal/tools/monitor/apm/topology/topology.go
  internal/tools/monitor/apm/topology/topology_test.go
  internal/tools/monitor/apm/topology/topology_v2.go
  internal/tools/monitor/apm/topology/topology_v2_test.go
Labels: feature

#5698 feat: compatible the span data from erda java-agent to otlp java-agent
  internal/tools/monitor/oap/collector/interceptor/constants.go
  internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/interceptor.go
Labels: feature, approved

#5700 fix: autotest download url
  internal/apps/dop/component-protocol/components/auto-test-space-list/components/recordTable/render.go
Labels: bugfix, approved

#5712 feat: declare pprof port for continuous profiling in erda.yaml
  erda.yml
Labels: feature

#5709 feat: clickhouse cold hot ddl
  cmd/monitor/streaming/bootstrap.yaml
  internal/apps/cmp/metrics/metrics.go
  internal/tools/monitor/core/log/persist/v1/provider_test.go
  internal/tools/monitor/core/settings/retention-strategy/provider.go
  internal/tools/monitor/core/settings/retention-strategy/ttl.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/init.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/mock_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/provider.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/loader/provider.go
  internal/tools/monitor/core/storekit/clickhouse/table/loader/table_loader.go
  internal/tools/monitor/core/storekit/clickhouse/table/loader/table_meta.go
  internal/tools/monitor/core/storekit/clickhouse/table/loader/table_meta_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/table.go
  internal/tools/monitor/core/storekit/clickhouse/table/table_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
Labels: feature, approved

#5714 fix: optimize streaming resource
  cmd/monitor/streaming/bootstrap.yaml
  erda.yml
Labels: bugfix, approved

#5713 feat: add otlp metric api
  api/proto/oap/collector/receiver/opentelemetry/opentelemetry.proto
  api/proto/oap/common/common.proto
  api/proto/oap/opentelemetry/metrics.proto
  internal/tools/monitor/oap/collector/plugins/receivers/collector/collector.go
  internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/otlp.service.go
  internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/provider.go
Labels: feature, approved

#5715 feat: add hot ttl config
  cmd/monitor/monitor/conf/i18n/settings.yml
  internal/tools/monitor/core/settings/monitor.go
  internal/tools/monitor/core/settings/monitor_test.go
  internal/tools/monitor/core/settings/ttl.go
  internal/tools/monitor/core/settings/ttl_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
Labels: feature, approved

#5721 feat: canal zk to global
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal.go
Labels: feature

#5724 feat(orchestrator): dice yml support platforminfo visitor
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/clusterinfo/clusterinfo.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  pkg/parser/diceyml/define.go
  pkg/parser/diceyml/diceyml.go
  pkg/parser/diceyml/env_visitor.go
  pkg/parser/diceyml/platform_visitor.go
  pkg/parser/diceyml/platform_visitor_test.go
Labels: orchestrator, feature

#5725 fix(orchestrator): dice yml platform visitor match error
  pkg/parser/diceyml/platform_visitor.go
  pkg/parser/diceyml/platform_visitor_test.go
Labels: orchestrator, bugfix, approved

#5723 fix: fix ddl sync nil point
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/init.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/mock_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/provider.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync_test.go
Labels: bugfix, approved

#5726 fix: ddl in high frequency execution
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
Labels: bugfix, approved
