Repository erda-project/erda, pull requests merged in 2023-07, with the labels that each got.

#5962 perf(streaming): cahce for applications
  go.mod
  go.sum
  internal/tools/monitor/oap/collector/plugins/exporters/pyroscope/provider.go
Labels: approved

#5964 fix(dop): issue still be created instead of updated when import with correct id
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/dao/core.go
Labels: dop, bugfix

#5966 fix(dop): issue dashboard bug EOF
  internal/apps/dop/component-protocol/components/issue-dashboard/bar/stateVerticalBarChart/render.go
Labels: dop, bugfix

#5975 chore: upgrade clickhouse go pkg
  go.mod
  go.sum
Labels: approved

#5961 fix: ignore api_doc error
  internal/apps/dop/services/apidocsvc/api_docs.go
  internal/apps/dop/services/apidocsvc/funcs.go
Labels: bugfix, approved

#5943 feat: trim all utf8mb3
  pkg/database/sqlparser/ddlreverser/reverser.go
  pkg/database/sqlparser/snapshot/snapshot.go
  pkg/database/sqlparser/snapshot/snapshot_test.go
Labels: feature, approved

#5976 fix(hepa): fix key-auth for mse and nginx check for kong
  internal/tools/orchestrator/hepa/gateway-providers/mse/plugins/common.go
  internal/tools/orchestrator/hepa/providers/legacy_upstream/upstream.service.go
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl_test.go
Labels: hepa, bugfix, approved

#5977 fix(streaming): acquire conn timeout
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  build/dockerfiles/base/Dockerfile
  build/dockerfiles/base/deploy.sh
  build/dockerfiles/base/sbom-amd64.txt
  build/dockerfiles/base/sbom-arm64.txt
  build/scripts/buildkit_image.sh
  build/scripts/docker_image.sh
  cmd/monitor/monitor/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/main.go
  go.mod
  go.sum
  internal/tools/monitor/apm/topology/topology_v2.go
  internal/tools/monitor/core/alert/alert-apis/db/alert_rule.go
  internal/tools/monitor/core/alert/details-apis/clickhouse_source.go
  internal/tools/monitor/core/log/storage/clickhouse/iterator.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/meta_loader.go
  internal/tools/monitor/dashboard/org-apis/clickhouse_source.go
  pipeline.yml
Labels: bugfix, approved

#5983 fix(dop): export only related iterations if not exporting all issues
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/query/issueexcel/data.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_baseinfo.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion.go
Labels: dop, bugfix

#5984 fix(dop): treat TICKET as a valid type at createIssueCustomFieldRelation w…
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_custom_field.go
Labels: dop, bugfix

#5987 feat: change default org audit retention days to 30
  internal/core/legacy/conf/conf.go
  internal/core/legacy/conf/conf_test.go
  internal/core/legacy/dao/audit.go
  internal/core/legacy/services/audit/audit.go
Labels: feature, approved

#5979 feat: add mysql 5.7 to tmc; deploy mysql with operator only when it h…
  go.sum
  internal/apps/msp/resource/deploy/handlers/mysql/mysql.go
  internal/apps/msp/resource/deploy/handlers/mysql/mysql_cli_adapter.go
Labels: feature

#5981 chore: remove refs to deprecated io/ioutil
  internal/apps/cmp/steve/proxy/proxy_store.go
  internal/apps/dop/services/signauth/sign_auth.go
  internal/apps/msp/apm/browser/ipdb/ipdb.go
  internal/core/openapi/legacy/component-protocol/generate/gen_auto_register.go
  internal/pkg/dcos/dcos.go
  internal/pkg/metrics/query/query.go
  internal/tools/cluster-agent/pkg/leaderelection/leaderelection.go
  internal/tools/gittar/pkg/gc/gc.go
  internal/tools/gittar/pkg/util/http_test.go
  internal/tools/monitor/common/ext.go
  internal/tools/monitor/core/agent-injector/admission_review.go
  internal/tools/monitor/core/metric/query/chartmeta/files.go
  internal/tools/monitor/core/storekit/clickhouse/table/creator/creator.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/init.go
  internal/tools/monitor/core/storekit/elasticsearch/index/cleaner/provider.go
  internal/tools/monitor/core/storekit/elasticsearch/index/initializer/init.go
  internal/tools/monitor/core/storekit/elasticsearch/index/rollover/provider.go
  internal/tools/monitor/extensions/loghub/index/manager/index_rollover.go
  internal/tools/monitor/extensions/loghub/index/manager/index_template.go
  internal/tools/orchestrator/hepa/common/wrapper/http_wrapper.go
  internal/tools/pipeline/actionagent/agenttool/mv_test.go
  internal/tools/pipeline/actionagent/filewatch/watch.go
  pkg/cloudstorage/minioclient/minioclient.go
  pkg/cloudstorage/ossclient/ossclient.go
  pkg/common/httpapi/model.go
  pkg/database/sqllint/config.go
  pkg/database/sqlparser/migrator/script.go
  pkg/database/sqlparser/migrator/scripts.go
  pkg/encoding/jsonpath/jackson.go
  pkg/encoding/jsonpath/jq.go
  pkg/helm/helm.go
  pkg/http/httpclient/request.go
  pkg/http/httpclient/request_test.go
  pkg/http/httpclient/trace.go
  pkg/i18n/locale_loader.go
  pkg/k8s/httpstream/spdy/roundtripper.go
  pkg/license/license_test.go
  pkg/swagger/oas3/expand_schema_test.go
  pkg/swagger/oas3/expand_test.go
  pkg/swagger/oasconv/oasconv_test.go
  tools/cli/utils/dicedir.go
  tools/cli/utils/format.go
  tools/cli/utils/workspace.go
  tools/gotools/go-copyright/main.go
  tools/gotools/go-imports-order/main.go
  tools/gotools/go-test-sum/cover/profile.go
  tools/gotools/go-test-sum/main.go
Labels: approved

#5992 feat(dop): iteration support label relation
  apistructs/iteration.go
  apistructs/label.go
  internal/apps/dop/dao/iteration.go
  internal/apps/dop/dao/iteration_test.go
  internal/apps/dop/endpoints/iteration.go
  internal/apps/dop/endpoints/iteration_test.go
Labels: dop, feature, approved

#5973 feat(monitor): add rx,tx_bytes usage for fix container network alert
  cmd/monitor/collector/bootstrap.yaml
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/notify_template.yaml
Labels: feature, approved

#5994 fix(monitor): closing lastResp in defer causes `fetch` func to be executed limit(pageSize) times
  internal/tools/monitor/core/log/query/log.query.service.go
  internal/tools/monitor/core/log/storage/clickhouse/iterator.go
Labels: bugfix

#5993 fix: remove log-service startTime for msp restart
  internal/apps/msp/apm/log-service/query/log.service.download.go
  internal/apps/msp/apm/log-service/query/log.service.go
  internal/apps/msp/apm/log-service/query/log.service.histogram.go
  internal/apps/msp/apm/log-service/query/log.service.search.go
  internal/apps/msp/apm/log-service/query/log.service.terms.go
  internal/apps/msp/apm/log-service/query/provider.go
  internal/apps/msp/apm/log-service/query/utils.go
  internal/apps/msp/apm/log-service/query/utils_test.go
Labels: bugfix

#5995 fix: log-analytics interface not exist
  internal/apps/msp/menu/menu.service.go
Labels: bugfix, approved

#5989 fix: failed to render project namespace on cmp
  internal/apps/cmp/component-protocol/components/cmp-dashboard-events-list/filter/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/addPodFilter/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/filter/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/filter/render_test.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFilter/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/filter/render_test.go
  internal/apps/cmp/component-protocol/cputil/util.go
  internal/apps/cmp/component-protocol/cputil/util_test.go
Labels: cmp, bugfix

#5718 fix: addon list by runtime auth fail
  internal/tools/orchestrator/components/podscaler/db.service.go
  internal/tools/orchestrator/components/podscaler/db.service.impl.go
  internal/tools/orchestrator/components/podscaler/manual_scale_test.go
  internal/tools/orchestrator/dbclient/addon_attachment.go
  internal/tools/orchestrator/endpoints/addon.go
  internal/tools/orchestrator/endpoints/server_handler.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_test.go
Labels: orchestrator, bugfix

#5980 fix: fix page orderview no order
  cmd/monitor/monitor/conf/chartview/frontend/page_overview.json
Labels: bugfix, approved

#5998 fix(orchestrator): init-container download file failed due to openapi url
  internal/tools/orchestrator/conf/conf.go
  internal/tools/orchestrator/services/deployment/deployment_context.go
  internal/tools/orchestrator/services/deployment/deployment_context_test.go
Labels: orchestrator, bugfix, approved

#5997 feat(streaming): external business metrics provider
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
  cmd/monitor/streaming/bootstrap.yaml
  cmd/monitor/streaming/conf/clickhouse/external_metrics/ddl_create_db.sql.tpl
  cmd/monitor/streaming/conf/clickhouse/external_metrics/ddl_create_default_tables.sql.tpl
  internal/tools/monitor/oap/collector/core/config/config.go
  internal/tools/monitor/oap/collector/core/model/exporter.go
  internal/tools/monitor/oap/collector/core/model/odata/buffer.go
  internal/tools/monitor/oap/collector/core/model/odata/odata.go
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
  internal/tools/monitor/oap/collector/core/pipeline/pipeline_test.go
  internal/tools/monitor/oap/collector/core/provider.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/kafka.go
  internal/tools/monitor/oap/collector/plugins/receivers/promremotewrite/provider.go
Labels: feature, approved

#6001 fix: pipeline job dns policy in host network mode
  internal/tools/pipeline/pipengine/actionexecutor/logic/job.go
  internal/tools/pipeline/pipengine/actionexecutor/logic/job_test.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
Labels: pipeline, bugfix

#6005 fix: edas application group list error
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_test.go
Labels: orchestrator, bugfix

#6006 fix: service multi container order error
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/endpoints/instance_test.go
Labels: orchestrator, bugfix
