Repository erda-project/erda, pull requests merged in 2023-03, with the labels that each got.

#5729 fix: skip addon dice.yml validate
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: bugfix, approved

#5720 feat(pipeline): pipeline render extension image for different architecture
  apistructs/cluster_info.go
  internal/tools/pipeline/providers/actionmgr/impl.go
  internal/tools/pipeline/providers/actionmgr/interface.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/secret/platform_secret.go
Labels: pipeline, feature, approved

#5731 fix: fix micro dashboard error, orderby column should by select
  internal/tools/monitor/core/dataview/db/db.go
Labels: bugfix, approved

#5732 fix: add addon id for mysql label
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: bugfix

#5734 fix(dop): permission leak for project home
  internal/apps/dop/providers/project/home/service.go
  internal/apps/dop/services/apierrors/errors.go
Labels: dop, bugfix, approved

#5739 fix(orchestrator): redis mysql operator deployment failure
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: orchestrator, bugfix

#5738 fix: fix append debug logs ttl sync
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/ttl_sync.go
Labels: bugfix, approved

#5737 fix: fix msp/tenant/project over permission
  internal/apps/msp/tenant/project/project.service.go
Labels: bugfix, approved

#5743 feat: upgrade kubectl version
  build/dockerfiles/cluster-agent/Dockerfile
Labels: feature, approved

#5747 fix: jvm gc time unit should be ms
  internal/apps/msp/apm/service/components/resources-runtime-monitor-java/runtime/provider.go
Labels: bugfix

#5740 fix: fix metric query time function no order
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5728 fix: fix metric model not stand,invoke agg column hits
  internal/apps/msp/apm/service/apm.service.service.go
Labels: bugfix, approved

#5753 feat(orchestrator): support lifecycle prestop in prod env
  apistructs/application.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle_test.go
  internal/tools/orchestrator/scheduler/executor/util/util.go
Labels: orchestrator, feature

#5752 fix: fix metric aggr function parse error
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5750 feat: collect metric append org tag
  cmd/monitor/collector/bootstrap.yaml
  internal/tools/monitor/oap/collector/core/pipeline/pipeline.go
  internal/tools/monitor/oap/collector/plugins/receivers/promremotewrite/provider.go
Labels: feature, approved

#5745 fix: kong sbac and csrf plugin parse for specified routeId
  internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/cors/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/custom/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/ip/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/proxy/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/server-guard/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/waf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policy_engine.go
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
Labels: bugfix

#5756 fix: fix collector pool run out frequently
  cmd/monitor/streaming/bootstrap.yaml
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/storage.go
Labels: bugfix, approved

#5758 fix: fix error count table no order
  internal/apps/msp/apm/service/view/table/transaction.go
Labels: bugfix, approved

#5742 fix(monitor): rocketmq chart no data due to startTime and EndTime
  cmd/monitor/monitor/conf/chartview/runtime/addon-rocketmq.json
Labels: bugfix

#5764 chore: default pipeline.yml use ((target_arch)) instead of ((arch))
  pipeline.yml
Labels: approved

#5765 fix: sometime time colum no orderly
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
Labels: bugfix, approved

#5767 fix(pipeline): flinkcluster executor idempotent deletion task failure due to the returned type error
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
Labels: pipeline, bugfix, approved

#5766 fix(orchestrator): addons deployment failure due to failed to get clusterinfo
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_test.go
Labels: orchestrator, bugfix

#5769 feat(orchestrator): set podSecurityContext for es addon
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_status_test.go
Labels: orchestrator, feature, approved

#5771 fix: fix application_service_node no target_service_id
  internal/apps/msp/apm/service/apm.service.service.go
Labels: bugfix, approved

#5776 fix(pipeline): the waiting time of taskOP.Wait overflows when the declineRatio to loopedTimes power bigger than int64
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait_test.go
Labels: pipeline, bugfix, approved

#5761 fix: arm containerd no match container id
  cmd/monitor/collector/bootstrap.yaml
Labels: bugfix, approved
