Repository erda-project/erda, pull requests merged in 2023-11, with the labels that each got.

#6111 feat: add performance measurement range value
  internal/apps/dop/providers/efficiency_measure/efficiency_query.go
Labels: feature, approved

#6116 fix(dop): efficiency measure route no token check
  internal/core/openapi/legacy/api/apis/dop/efficiency_measure_query.go
  internal/core/openapi/legacy/api/apis/dop/func_pooints_query.go
  internal/core/openapi/legacy/api/apis/dop/personal_contribution_query.go
  internal/core/openapi/legacy/api/apis/dop/project_report_query.go
Labels: dop, bugfix, approved

#6110 fix(orchestrator): only redis versions greater than 6.0 are deployed using the operator
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_deploy_test.go
Labels: orchestrator, bugfix, approved

#6119 feat: add log execute loop termination
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go
Labels: feature

#6126 fix: collector-agent docker_container_summary modifier processor get container id error
  cmd/monitor/collector/bootstrap-agent.yaml
  internal/tools/monitor/oap/collector/lib/util_test.go
Labels: bugfix

#6127 feat(ai-proxy): auto del accept-encoding for bailian lllm
  internal/apps/ai-proxy/filters/bailian-director/filter.go
  pkg/http/httputil/mediatype.go
Labels: feature

#6129 fix: use getOperations
  internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
Labels: bugfix

#6117 fix: convert ProjectIDs type to []string
  internal/apps/dop/providers/efficiency_measure/contributor_query.go
  internal/apps/dop/providers/efficiency_measure/efficiency_query.go
  internal/apps/dop/providers/efficiency_measure/func_points_trend.go
  internal/apps/dop/providers/project_report/query.go
  internal/apps/dop/providers/project_report/query_test.go
  pkg/strutil/convert.go
  pkg/strutil/convert_test.go
Labels: bugfix, approved

#6132 feat(dop): issue-gantt component support filter state conditions
  internal/apps/dop/component-protocol/components/issue-gantt/filter/model.go
  internal/apps/dop/component-protocol/components/issue-gantt/filter/provider.go
  internal/apps/dop/component-protocol/components/issue-gantt/gantt/render.go
  internal/apps/dop/providers/issue/dao/core.go
Labels: approved

#6133 feat(dop): contribution supports display of trends by day
  apistructs/performance_measure.go
  internal/apps/dop/providers/efficiency_measure/contributor_query.go
Labels: approved

#6131 feat(collector): retag component_name from label dice/component
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
Labels: monitor-stack, feature, approved

#6134 fix(dop): parent issue not filter by state id
  internal/apps/dop/providers/issue/dao/core.go
Labels: dop, bugfix, approved

#6136 fix(collector): collector exporter compress panic due to index out of range
  internal/tools/monitor/oap/collector/lib/compressor/writer.go
  internal/tools/monitor/oap/collector/lib/compressor/writer_test.go
Labels: bugfix, approved

#6137 feat: optimize cluster-agent kubectl source
  build/dockerfiles/cluster-agent/Dockerfile
Labels: feature, approved

#6140 fix(ai-proxy): get audit identity from client token
  api/proto/apps/aiproxy/audit/audit.proto
  internal/apps/ai-proxy/common/ctxhelper/client_token.go
  internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
  internal/apps/ai-proxy/models/audit/dbclient.go
  internal/apps/ai-proxy/models/audit/table.go
Labels: bugfix

#6142 fix(monitor): runtime container no metric detail due to container id missing
  cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
Labels: bugfix, approved

#6144 fix(dop): gantt children issues not filtered by states
  internal/apps/dop/providers/issue/dao/core.go
Labels: dop, bugfix, approved

#6145 fix(monitor): container `mem_limit` value same with machine mem
  cmd/monitor/monitor/conf/chartview/runtime/runtime-container-detail.json
Labels: bugfix, approved

#6143 feat(ai-function): ai create testcase by groups and and export in fileType xmind
  api/proto/apps/aifunction/ai-function.proto
  api/proto/dop/ai/ai.proto
  apistructs/testcase.go
  apistructs/testset.go
  bundle/issue.go
  bundle/testset.go
  cmd/erda-server/bootstrap.yaml
  internal/apps/dop/dao/file_records.go
  internal/apps/dop/endpoints/endpoints.go
  internal/apps/dop/endpoints/testcase.go
  internal/apps/dop/services/testcase/export.go
  internal/apps/dop/services/testcase/export_test.go
  internal/pkg/ai-functions/functions/function.go
  internal/pkg/ai-functions/functions/test-case/function.go
  internal/pkg/ai-functions/functions/test-case/function_test.go
  internal/pkg/ai-functions/functions/test-case/group-messages.yml
  internal/pkg/ai-functions/functions/test-case/group-schema.yaml
  internal/pkg/ai-functions/functions/test-case/group.go
  internal/pkg/ai-functions/functions/test-case/schema.yaml
  internal/pkg/ai-functions/handler/handler_ai_function.go
  internal/pkg/ai-functions/handler/handler_ai_function_create_testcase.go
  internal/pkg/ai-functions/handler/handler_ai_function_create_testcase_test.go
  internal/pkg/ai-functions/handler/utils/handler_function_utils.go
  internal/pkg/ai-functions/provider.go
Labels: feature, approved

#6141 feat(pipeline): add action i18n support
  internal/tools/pipeline/providers/pipeline/provider.go
Labels: pipeline, feature, approved

#6151 fix(ai-function): need verify chatcompletions return results
  internal/pkg/ai-functions/functions/test-case/function.go
  internal/pkg/ai-functions/functions/test-case/function_test.go
  internal/pkg/ai-functions/functions/test-case/group.go
Labels: bugfix, approved

#6148 fix(orchestrator): edas update kubernetes service error
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/provider.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go
Labels: orchestrator, bugfix, approved

#6146 fix(pipeline): fix action i18n issue
  apistructs/extension_test.go
  apistructs/extention.go
  cmd/erda-server/conf/i18n/issue-manage.yaml
  cmd/erda-server/conf/i18n/msp-i18n.yaml
  internal/tools/pipeline/providers/graph/graph.service.go
  internal/tools/pipeline/providers/graph/graph.service_test.go
  internal/tools/pipeline/providers/pipeline/detail.go
  internal/tools/pipeline/providers/pipeline/interface.go
  internal/tools/pipeline/providers/pipeline/provider.go
  internal/tools/pipeline/providers/pipeline/task_view.go
  internal/tools/pipeline/providers/task/task.service.go
Labels: pipeline, bugfix, approved

#6139 fix(orchestrator): addon detail show not found instance error
  apistructs/addon.go
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/endpoints/middleware.go
Labels: orchestrator, bugfix

#6153 feat(ai-function): export xmind with fileUUID for download directly
  internal/apps/dop/endpoints/testcase.go
Labels: feature

#6156 feat(ai-proxy): add rich-client management API
  api/proto/apps/aiproxy/client/rich_client/rich_client.proto
  api/proto/apps/aiproxy/client_model_relation/client_model_relation.proto
  api/proto/apps/aiproxy/client_token/client_token.proto
  api/proto/apps/aiproxy/model/model.proto
  api/proto/apps/aiproxy/model_provider/model_provider.proto
  internal/apps/ai-proxy/handlers/common/akutil/ak.go
  internal/apps/ai-proxy/handlers/common/auth/auth.go
  internal/apps/ai-proxy/handlers/handler_rich_client/handler.go
  internal/apps/ai-proxy/handlers/permission/method.go
  internal/apps/ai-proxy/models/model/dbclient.go
  internal/apps/ai-proxy/models/model_provider/dbclient.go
  internal/apps/ai-proxy/provider.go
  internal/apps/ai-proxy/vars/consts.go
Labels: feature

#6157 fix(msp): the consistency problem of table and chart data in micro service monitor
  internal/apps/msp/apm/service/view/table/error_transaction.go
  internal/apps/msp/apm/service/view/table/slow_transaction.go
Labels: msp, bugfix, approved

#6161 fix(ai-function): optimal prompt
  internal/pkg/ai-functions/functions/test-case/function.go
  internal/pkg/ai-functions/functions/test-case/group.go
Labels: bugfix
