Repository erda-project/erda, pull requests merged in 2023-06, with the labels that each got.

#5889 fix: gateway policy csrf and sbac added config for mse not allowed for kong
  internal/tools/orchestrator/hepa/apipolicy/policies/csrf/policy.go
  internal/tools/orchestrator/hepa/apipolicy/policies/sbac/dto.go
Labels: bugfix

#5891 feat: add field config.enableAI to org
  api/proto/core/org/org.proto
  internal/core/org/db/org.go
  internal/core/org/org.go
Labels: feature, approved

#5892 chore(monitor): go mod repo address
  go.mod
  go.sum
Labels: approved

#5895 fix: hepa check nginx custom config err when kong version is 0.14.1
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
Labels: bugfix, approved

#5888 feat(monitor): add pod network alert-rule
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/alert_rule.yaml
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/app_resource/app_resource_container_network/notify_template.yaml
  cmd/monitor/monitor/conf/charts/report.yml
  cmd/monitor/monitor/conf/i18n/alert.yml
  cmd/monitor/monitor/conf/notify/monitor/app_resource/app_resource_container_network.yaml
  internal/tools/monitor/core/alert/alert-apis/adapt/expression.go
Labels: feature, approved

#5896 fix: single column no order
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
  cmd/monitor/monitor/conf/chartview/frontend/ajax_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/browser_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/domain_overview.json
  cmd/monitor/monitor/conf/chartview/frontend/script_overview.json
  internal/apps/msp/apm/service/components/resources-node-monitor/node/provider.go
  internal/tools/monitor/apm/topology/topology.go
  internal/tools/monitor/apm/topology/topology_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/column.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
  internal/tools/monitor/core/metric/storage/clickhouse/query.go
Labels: bugfix

#5900 fix: hepa check nginx custom config error when set return
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
Labels: bugfix, approved

#5903 fix(dop): issue import
  api/proto/dop/issue/core/core.proto
  apistructs/scope.go
  bundle/member.go
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/provider.go
  internal/apps/dop/providers/issue/core/query/issueexcel/data.go
  internal/apps/dop/providers/issue/core/query/issueexcel/export.go
  internal/apps/dop/providers/issue/core/query/issueexcel/model_sample.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_export.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_export_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_user.go
  internal/core/legacy/services/permission/permission.go
  internal/core/legacy/services/permission/permission_test.go
Labels: dop, bugfix

#5905 fix(orchestrator): addon mysql missing cluster name label
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql_test.go
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: orchestrator, bugfix, approved

#5702 feat: pipeline job support network mode
  apistructs/job.go
  apistructs/job_test.go
  apistructs/service.go
  internal/tools/pipeline/pipengine/actionexecutor/logic/job.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
  internal/tools/pipeline/pkg/container_provider/container_instance_provider.go
  internal/tools/pipeline/providers/pipeline/create_task.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/spec/pipeline_task.go
  pkg/parser/pipelineyml/generate_test.go
  pkg/parser/pipelineyml/graph_pipelineyml.go
Labels: feature, approved

#5909 fix(pipeline): failed to clean build cache images due to bundle initialization
  internal/tools/pipeline/providers/build/provider.go
Labels: pipeline, bugfix, approved

#5911 fix(orchestrator): redis-operator deploy failure due to arm64-cow-bug
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis.go
Labels: orchestrator, bugfix

#5915 fix(monitor): extend profile name field length
  .erda/migrations/monitor/20230609-profile-name-length.sql
Labels: bugfix, approved

#5918 feat: add ai-proxy to pipeline.yml release action
  pipeline.yml
Labels: feature

#5912 fix(dop): issue import
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/query/convert.go
  internal/apps/dop/providers/issue/core/query/convert_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/import.go
  internal/apps/dop/providers/issue/core/query/issueexcel/import_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_custom_field.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_export.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_old.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_label.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_user.go
  internal/apps/dop/providers/issue/dao/label_relation.go
Labels: dop, bugfix

#5922 fix: miglint for ai-proxy
  .erda/migrations/ai-proxy/20230425-filter-audit.sql
  .erda/migrations/config.yml
Labels: bugfix, approved

#5920 fix(dop): issue import refactor member&state&custom-field
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/query/issueexcel/data.go
  internal/apps/dop/providers/issue/core/query/issueexcel/export.go
  internal/apps/dop/providers/issue/core/query/issueexcel/import.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_custom_field.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_export_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_old.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_old_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_issue_import_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_iteraion_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_state.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_state_test.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheet_user.go
  internal/apps/dop/providers/issue/dao/state.go
Labels: dop, bugfix

#5887 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/yamlFileEditor/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-podDetail/yamlFileEditor/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/addPodFileEditor/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-pods/yamlFileEditor/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workload-detail/yamlFileEditor/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/yamlFileEditor/render.go
  internal/apps/cmp/steve/predefined/init.go
  internal/apps/dop/endpoints/task.go
  internal/apps/dop/pipeline/pipelineyml/pipeline.go
  internal/apps/dop/providers/publishitem/db/publish_item_version.go
  internal/apps/msp/resource/deploy/handlers/generalability/general_ability.go
  internal/pkg/extension/db/extension.go
  internal/tools/monitor/core/alert/alert-apis/provider.go
  pkg/k8s/node/drain/node_test.go
  pkg/parser/pipelineyml/pipelineymlv1/gogenerate/builtin_action_spec.go
  pkg/parser/pipelineyml/pipelineymlv1/pipelineyml.go
  pkg/parser/pipelineyml/pipelineymlv1/taskconfig_decode.go
  tools/cli/cmd/extensions_push.go
  tools/cli/cmd/extensions_retag.go
Labels: approved

#5925 fix: ai-proxy resource
  erda.yml
Labels: bugfix

#5926 fix: typo
  erda.yml
Labels: bugfix

#5902 fix: fix avg rps single point no consistency
  internal/apps/msp/apm/service/view/card/avg_duration.go
Labels: bugfix, approved

#5899 fix: fix overview error rate no true
  internal/apps/msp/apm/service/components/service-list/provider.go
Labels: bugfix

#5929 fix: etcd mutex context leak on deploying addon
  internal/apps/msp/resource/deploy/coordinator/coordinator.go
Labels: bugfix, approved

#5930 fix: CheckIfNeedTmcInstance: try to get the first RUNNING addon
  internal/apps/msp/instance/db/instance.go
  internal/apps/msp/resource/deploy/handlers/handler.go
  internal/apps/msp/resource/deploy/handlers/mysql/mysql.go
Labels: bugfix, approved

#5937 feat: add dice.yml schema and pipeline.yml schema
  .erda/schemas/dice.yaml.json
  .erda/schemas/pipeline.yaml.json
  cmd/erda-server/bootstrap.yaml
  erda.yml
  pkg/discover/address.go
Labels: feature, approved

#5944 fix: file record add timeout logic
  internal/apps/dop/conf/conf.go
  internal/apps/dop/dao/file_records.go
  internal/apps/dop/initialize.go
  internal/apps/dop/services/testcase/file_records.go
Labels: bugfix

#5940 feat(monitor): apm experience improvement
  api/proto/msp/apm/log-service/log_query.proto
  apistructs/profile.go
  bundle/profile.go
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/conf/i18n/msp-i18n.yaml
  cmd/monitor/streaming/bootstrap.yaml
  go.mod
  go.sum
  internal/apps/msp/apm/log-service/query/log.service.go
  internal/apps/msp/apm/log-service/query/log.service.histogram.go
  internal/apps/msp/apm/service/common/slow-transaction/inparams.go
  internal/apps/msp/apm/service/components/all.go
  internal/apps/msp/apm/service/components/service-profile-overview/provider.go
  internal/apps/msp/apm/service/components/transaction-http-slow/slow_req_distribution/provider.go
  internal/apps/msp/apm/service/components/transaction-http-table/scenario.go
  internal/apps/msp/apm/service/components/transaction-http-table/table/provider.go
  internal/apps/msp/apm/service/components/transaction-http-table/table_filter/provider.go
  internal/apps/msp/apm/service/scenarios/service-profile-overview.yml
  internal/apps/msp/apm/service/scenarios/transaction-http-table.yml
  internal/apps/msp/menu/menu.service.go
  internal/tools/monitor/core/profile/query/render-diff.go
  internal/tools/monitor/core/profile/query/render.go
Labels: feature, approved

#5947 feat: make openapi-ng reloadable
  cmd/erda-server/bootstrap.yaml
Labels: feature

#5946 refactor(gittar): refactor GetUserInfoByTokenOrBasicAuth; print err when get user from uc failed
  internal/core/user/common/model.go
  internal/core/user/common/model_test.go
  internal/tools/gittar/auth/auth.go
Labels: refactor, approved, gittar

#5948 fix: fix metric seconds no order
  internal/tools/monitor/core/metric/query/es-tsql/influxql/column.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse.go
Labels: bugfix, approved

#5951 fix(monitor): profile, transaction http table component
  cmd/erda-server/conf/i18n/msp-i18n.yaml
  internal/apps/msp/apm/service/components/service-profile-overview/provider.go
  internal/apps/msp/apm/service/components/transaction-http-table/table/provider.go
Labels: bugfix, approved

#5942 feat(pipeline): flinkcluster add optional for enable ui
  apistructs/bigdata.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
Labels: pipeline, feature, approved

#5954 fix: fix/fix tag expr use exprString
  internal/tools/monitor/core/metric/query/es-tsql/influxql/column.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#5959 feat: change version to 2.4
  VERSION
  pipeline.yml
Labels: feature, approved

#5793 chore(gittar): print some error logs to stderr for troubleshooting
  internal/tools/gittar/pkg/gitmodule/repo.go
Labels: approved, gittar

#5960 fix(orchestrator): redis addon deployed by operator missing exporter
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis_test.go
Labels: orchestrator, bugfix, approved
