Repository erda-project/erda, pull requests merged in 2024-10, with the labels that each got.

#6450 chore: baseline dice_member user_id change to varchar(36)
  .erda/migrations/.patches/patch-20210528-cmdb-base.sql
  .erda/migrations/cmdb/20210528-cmdb-base.sql
  .erda/migrations/cmdb/20211221-dice-member-userID-varchar.sql
  .erda/migrations/config.yml
Labels: approved

#6451 chore: change pipeline.yml migration database from pipeline env
  pipeline.yml
Labels: approved

#6453 fix: init controller-runtime logger
  go.mod
  go.sum
  pkg/k8sclient/client.go
Labels: bugfix, approved

#6454 fix(monitor): redis cpu(sys,user,children) percent
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
Labels: bugfix, approved

#6456 fix(ai-proxy): dashscope non-stream mode for ds response_type works now
  internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
  internal/apps/ai-proxy/filters/dashscope-director/sdk/resp.go
Labels: bugfix

#6455 fix: add status as a condition for searching registercenter
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
Labels: bugfix, approved

#6460 chore(eventbox): print human-readable error log
  internal/core/messenger/eventbox/dispatcher/filters/lastfilter.go
  internal/core/messenger/eventbox/types/types.go
Labels: approved

#6462 fix(cmp): node details render EOF
  bundle/steve.go
  go.mod
  go.sum
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoDetail/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/infoMapTable/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/nodeStatus/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/nodeTitle/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodeDetail/statusBadge/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-nodes/nodeFilter/render_test.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-podDetail/containerTable/render.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workload-detail/operationButton/render_test.go
  internal/apps/cmp/component-protocol/components/cmp-dashboard-workloads-list/addWorkloadFileEditor/render.go
  internal/apps/cmp/component-protocol/cputil/util_test.go
  internal/apps/cmp/steve/dynamiccolumns.go
  internal/apps/cmp/steve/handler_test.go
  internal/apps/cmp/steve/proxy/proxy_store.go
  internal/apps/cmp/steve/schema.go
Labels: cmp, bugfix, approved
