Repository erda-project/erda, pull requests merged in 2024-07, with the labels that each got.

#6379 fix(go.mod): add missing deps in replace part
  .github/prlint.json
  go.mod
Labels: bugfix

#6382 feat(streaming): add offset and partition id for log record
  internal/tools/monitor/oap/collector/lib/protoparser/spotlog/spotlog.go
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: feature, approved

#6296 feat: correlation between different versions of cluster-level Addon deployments under different projects.
  internal/tools/orchestrator/dbclient/tmc_instance.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_extension_cache.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_test.go
Labels: feature, approved

#6278 feat: refactoring steve cache
  cmd/erda-server/bootstrap.yaml
  internal/apps/cmp/endpoints/endpoints.go
  internal/apps/cmp/initialize.go
  internal/apps/cmp/provider.go
  internal/apps/cmp/steve/aggregator.go
Labels: feature, bugfix, approved

#6371 fix: collector-agent failed to report raw metrics
  cmd/monitor/collector/bootstrap-agent.yaml
  internal/tools/monitor/oap/collector/plugins/exporters/collector/provider.go
Labels: bugfix, approved

#6387 chore(pipeline): extend post life cycle hook timeout
  internal/tools/pipeline/providers/lifecycle_hook_client/life.cycle.service.go
Labels: pipeline, approved

#6388 chore: update baseline checksum
  .erda/migrations/config.yml
Labels: approved

#6386 feat(ios-build): dispatch runner task by org id
  .erda/migrations/pipeline/20240702-runner-scheduler-add-orgid.sql
  api/proto/core/pipeline/action_runner_scheduler/runner_task.proto
  apistructs/runner_task.go
  cmd/action-runner/build.sh
  cmd/action-runner/config.json
  cmd/action-runner/main.go
  internal/tools/pipeline/action-runner/apis.go
  internal/tools/pipeline/action-runner/conf.go
  internal/tools/pipeline/providers/action_runner_scheduler/db/runner_task.go
  internal/tools/pipeline/providers/action_runner_scheduler/runner.task.service.go
Labels: feature

#6389 feat(ai-proxy): add chat completion usage for dashscope director
  go.mod
  go.sum
  internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
  internal/apps/ai-proxy/filters/dashscope-director/sdk/resp.go
Labels: feature

#6390 fix(orchestrator): use precompiled sql to avoid sql injection
  internal/tools/orchestrator/scheduler/instanceinfo/pod.go
Labels: orchestrator, bugfix

#6392 chore: set docker syntax using erda registry
  Makefile
  build/dockerfiles/Dockerfile
  build/dockerfiles/Dockerfile-action-agent
  build/dockerfiles/Dockerfile-cluster-ops
  build/dockerfiles/Dockerfile-volume-provisioner
  build/dockerfiles/agent-injector/Dockerfile
  build/dockerfiles/base/Dockerfile
  build/dockerfiles/cli/Dockerfile
  build/dockerfiles/cluster-agent/Dockerfile
  build/dockerfiles/reportengine/Dockerfile
  build/scripts/buildkit_image.sh
  pipeline.yml
Labels: approved

#6395 fix: container memory usage/limit metric
  internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
Labels: bugfix, approved

#6396 fix: cmp cfg nil pointer
  internal/apps/cmp/provider.go
Labels: bugfix, approved

#6394 feat: push 'use operator or not' to collector
  cmd/erda-server/bootstrap.yaml
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: feature, approved

#6400 fix(orchestrator): pod info sync duplicate
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
  internal/tools/orchestrator/scheduler/instanceinfo/pod.go
Labels: orchestrator, bugfix, approved

#6401 feat: support auto test exec history info database gc
  cmd/erda-server/bootstrap.yaml
  internal/apps/dop/providers/autotest/testplan/db/testplan.go
  internal/apps/dop/providers/autotest/testplan/provider.go
  internal/apps/dop/providers/autotest/testplan/testplan.service.go
Labels: feature, approved

#6402 fix(monitor): char/card,slow/error avg duration mistake
  internal/apps/msp/apm/service/view/card/avg_duration.go
  internal/apps/msp/apm/service/view/chart/avg_duration.go
  internal/apps/msp/apm/service/view/chart/avg_duration_distribution.go
  internal/apps/msp/apm/service/view/chart/error_duration_distribution.go
  internal/apps/msp/apm/service/view/chart/slow_duration_distribution.go
Labels: bugfix, approved

#6397 fix(dop): project report sql injection
  internal/apps/dop/providers/project_report/provider.go
  internal/apps/dop/providers/project_report/query.go
  internal/apps/dop/providers/project_report/query_test.go
Labels: dop, bugfix, approved

#6391 fix: release wrong gc
  internal/tools/orchestrator/dbclient/deployment.go
  internal/tools/orchestrator/services/deployment/deployment_context.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: bugfix, approved

#6290 feat(monitor): auto create monitor default ttl config for orgs
  cmd/monitor/monitor/bootstrap.yaml
  internal/tools/monitor/core/settings/provider.go
  internal/tools/monitor/core/settings/sync_config.go
  internal/tools/monitor/oap/collector/lib/const.go
Labels: feature, approved

#6399 feat: interlink deployed versions, whether deprecated or not
  internal/tools/orchestrator/dbclient/tmc_instance.go
  internal/tools/orchestrator/services/addon/addon.go
Labels: feature, approved

#6403 fix(monitor): downgrade pyroscope-go client to avoid useless `session-id` tag
  go.mod
  go.sum
Labels: bugfix, approved

#6404 fix(monitor): log-service timestamp order
  internal/tools/monitor/core/log/storage/clickhouse/iterator.go
Labels: bugfix, approved

#6406 fix(ai-proxy): dashscope non-stream mode works now
  internal/apps/ai-proxy/common/image/image.go
  internal/apps/ai-proxy/filters/dashscope-director/resp.go
  internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
  internal/apps/ai-proxy/filters/dashscope-director/sdk/resp.go
Labels: bugfix

#6409 fix(orchestrator): terminal command make panic due to index out of range
  go.mod
  go.sum
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/terminal.go
Labels: orchestrator, bugfix, approved
