Repository erda-project/erda, pull requests merged in 2024-01, with the labels that each got.

#6207 fix(parser): resolve panic when parsing invalid data in diceyml
  pkg/parser/diceyml/diceyml.go
  pkg/parser/diceyml/diceyml_test.go
  pkg/parser/diceyml/errors.go
  pkg/parser/diceyml/fieldname_validate_visitor.go
  pkg/parser/diceyml/fieldname_validate_visitor_test.go
Labels: bugfix, approved

#6197 feat(ai-proxy): support multimodal GPT-4V
  api/proto/apps/aiproxy/model/model.proto
Labels: feature

#6210 fix(monitor): resource-container-monitor no data
  internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
Labels: bugfix, approved

#6209 fix(orchestrator): register event chan concurrent map
  internal/tools/orchestrator/scheduler/executor/executortypes/types.go
Labels: orchestrator, bugfix, approved

#6214 feat: AI generate testcase international
  internal/pkg/ai-functions/functions/function.go
  internal/pkg/ai-functions/functions/test-case/function.go
  internal/pkg/ai-functions/functions/test-case/function_test.go
  internal/pkg/ai-functions/functions/test-case/group.go
  internal/pkg/ai-functions/functions/test-case/system-message.txt
  internal/pkg/ai-functions/handler/handler_ai_function.go
Labels: feature, approved

#6215 fix(gittar): better ai mr cr code snippet session
  cmd/gittar/conf/i18n/i18n.yaml
  internal/tools/gittar/ai/cr/impl/cr_mr/mr.go
  internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/prompt-zh.yaml
  internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/prompt.yaml
  internal/tools/gittar/ai/cr/impl/cr_mr_code_snippet/snippet.go
  internal/tools/gittar/ai/cr/impl/cr_mr_file/file.go
  internal/tools/gittar/ai/cr/util/aiutil/invoke.go
  internal/tools/gittar/models/code_reviewe.go
  internal/tools/gittar/models/i18n.go
  internal/tools/gittar/models/note.go
Labels: bugfix, gittar

#6211 fix: fix bulk deletion bug
  cmd/erda-server/conf/i18n/cp/scenarios/issue-manage.yaml
  internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
Labels: bugfix, approved

#6200 feat: add code collection for all branches
  internal/tools/gittar/metrics/collector.go
  internal/tools/gittar/pkg/util/collector_test.go
Labels: feature, approved

#6220 fix(orchestrator): cmp addon slow query sql
  apistructs/addon.go
  conf/erda-configs/i18n/orchestrator.json
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/endpoints/middleware.go
  internal/tools/orchestrator/services/addon/middleware.go
  internal/tools/orchestrator/services/apierrors/errors.go
Labels: orchestrator, bugfix, approved

#6222 feat(ai-proxy): polish audit
  api/proto/apps/aiproxy/audit/audit.proto
  cmd/ai-proxy/conf/routes.yml
  internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
  internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
  internal/apps/ai-proxy/filters/body-size-limit/filter.go
  internal/apps/ai-proxy/filters/context-chat/filter.go
  internal/apps/ai-proxy/filters/context/filter.go
  internal/apps/ai-proxy/filters/rate-limit/filter.go
  internal/apps/ai-proxy/models/audit/dbclient.go
  internal/apps/ai-proxy/models/metadata/meta_audit.go
  internal/apps/ai-proxy/vars/header.go
Labels: feature

#6219 fix: create-state adds duplicate name verification
  conf/i18n/common.yml
  internal/apps/dop/providers/issue/core/state.go
Labels: bugfix, approved

#6225 fix(orchestrator): addon cache custom addon without default version
  internal/tools/orchestrator/services/addon/addon_extension_cache.go
  internal/tools/orchestrator/services/addon/addon_extension_cache_test.go
  internal/tools/orchestrator/services/addon/addon_test.go
Labels: orchestrator, bugfix, approved

#6227 fix: adjust ai-proxy source and email plaintext
  internal/pkg/ai-functions/functions/test-case/group.go
  internal/pkg/ai-functions/handler/utils/handler_function_utils.go
  internal/pkg/ai-functions/sdk/api.go
  internal/pkg/ai-functions/sdk/api_test.go
Labels: bugfix, approved

#6224 chore(erda-server): issue-kanban show all states issues
  internal/apps/dop/providers/issue/core/query/svc.go
Labels: approved

#6230 feat(gittar): ai-mr-cr source add `___${cluster_name}` suffix
  internal/tools/gittar/ai/cr/util/aiutil/invoke.go
  internal/tools/gittar/conf/conf.go
Labels: feature, gittar

#6233 chore: optimize collector-agent memory
  erda.yml
Labels: approved

#6237 feat: remove the logic for deploying the default version of cluster addon
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: feature, approved

#6206 feat: add permission checking logic to the notification group service
  internal/apps/msp/apm/notifygroup/notifygroup.service.go
  internal/apps/msp/apm/notifygroup/provider.go
  internal/core/messenger/notifygroup/group.service.go
Labels: feature, approved

#6240 fix: unify the usage of mock logger in tests
  go.mod
  go.sum
  internal/apps/msp/apm/adapter/adapter.service_test.go
  internal/apps/msp/apm/adapter/adapter_logs_test.go
  internal/apps/msp/menu/menu.service_test.go
  internal/apps/msp/menu/menu_logs_test.go
  internal/apps/msp/tenant/project/project.service_test.go
  internal/apps/msp/tenant/project/project_logs_test.go
  internal/tools/monitor/core/alert/alert-apis/adapt/alert_logs_test.go
  internal/tools/monitor/core/alert/alert-apis/adapt/alert_test.go
  internal/tools/monitor/core/event/query/event.query.service_test.go
  internal/tools/monitor/core/event/query/mock_log_test.go
  internal/tools/monitor/extensions/loghub/exporter/output_test.go
  internal/tools/monitor/extensions/loghub/index/query/clients_mock_logs_test.go
  internal/tools/monitor/extensions/loghub/index/query/clients_test.go
  internal/tools/monitor/extensions/loghub/index/query/index_test.go
  internal/tools/pipeline/providers/edgereporter/reporter_logs_test.go
  internal/tools/pipeline/providers/edgereporter/reporter_test.go
  pkg/mock/logger_mock.go
Labels: bugfix, approved

#6239 feat: add deprecated field for addon
  apistructs/addon.go
  cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: feature, approved

#6241 fix(gittar): add content truncated flag to file code-review prompt
  internal/tools/gittar/ai/cr/impl/cr_mr_file/file.go
  internal/tools/gittar/ai/cr/impl/cr_mr_file/prompt.yaml
Labels: bugfix, gittar

#6245 chore(monitor): upgrade profile client
  go.mod
  go.sum
Labels: approved

#6213 feat: add pipeline_definition_cleanup provider
  cmd/pipeline/bootstrap.yaml
  cmd/pipeline/main.go
  go.mod
  go.sum
  internal/tools/pipeline/dbclient/op_pipeline_base.go
  internal/tools/pipeline/providers/cron/db/define_extra.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup_test.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/provider.go
  internal/tools/pipeline/providers/definition/db/define.go
  internal/tools/pipeline/providers/definition/db/define_extra.go
  internal/tools/pipeline/providers/source/db/source.go
  internal/tools/pipeline/spec/pipeline_base.go
  pkg/arrays/arrays.go
  pkg/arrays/arrays_test.go
  pkg/arrays/example_arrays_test.go
  pkg/mock/logger_mock.go
Labels: feature, approved

#6242 fix: constant appending of errors causing oom
  internal/tools/pipeline/pkg/taskerror/ordered.go
  internal/tools/pipeline/pkg/taskerror/ordered_test.go
  internal/tools/pipeline/providers/reconciler/provider.go
  internal/tools/pipeline/providers/reconciler/task_reconciler.go
Labels: bugfix, approved

#6256 fix(hepa): add api failed due to lost consumerId
  internal/tools/orchestrator/hepa/providers/micro_api/service.go
Labels: hepa, bugfix, approved

#6253 chore: update npm mirrors
  build/dockerfiles/Dockerfile
Labels: approved

#6262 fix(orchestrator): canal admin database param empty
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: orchestrator, bugfix, approved

#6254 chore: remove arch path in single image build
  build/scripts/docker_image.sh
Labels: approved

#6263 feat: add scopeId for notifygroup proto
  api/proto/msp/apm/notifygroup/notifygroup.proto
Labels: feature, approved
