Repository erda-project/erda, pull requests merged in 2024-06, with the labels that each got.

#6357 chore(gittar): update git version to avoid CVE-2024-32002
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  build/dockerfiles/base/Dockerfile
  build/dockerfiles/base/deploy.sh
  build/dockerfiles/base/sbom-amd64.txt
  build/dockerfiles/base/sbom-arm64.txt
  build/scripts/buildkit_image.sh
  build/scripts/docker_image.sh
  pipeline.yml
Labels: gittar

#6360 fix(gh-ci): set safe.directory at Dockerfile side to prevent "dubious ownership" errors
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it.yml
  Makefile
  build/dockerfiles/base/Dockerfile
  build/dockerfiles/base/sbom-amd64.txt
  build/dockerfiles/base/sbom-arm64.txt
  build/scripts/buildkit_image.sh
  build/scripts/docker_image.sh
  pipeline.yml
Labels: bugfix

#6358 fix: pipeline and queue cluster do not match when `job_cluster` is set
  internal/apps/dop/services/pipeline/pipeline.go
Labels: bugfix, approved

#6361 fix(gh-ci): use `--system` instead of `--global` to make it work for all users
  build/dockerfiles/base/Dockerfile
Labels: bugfix

#6364 fix(streaming): return the connection to the pool after `PrepareBatch`
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/external_metric/external_metrics.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/log/log.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/profile/profile.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span.go
Labels: bugfix, approved

#6365 chore: upgrade sarama version
  go.mod
  go.sum
  internal/tools/monitor/core/collector/kafka.go
  internal/tools/monitor/oap/collector/lib/kafka/batchreader.go
  internal/tools/monitor/oap/collector/lib/kafka/consumer.go
  internal/tools/monitor/oap/collector/lib/kafka/consumer_test.go
  internal/tools/monitor/oap/collector/lib/kafka/producer.go
  internal/tools/monitor/oap/collector/lib/kafka/producer_test.go
  internal/tools/monitor/oap/collector/lib/kafka/provider.go
  internal/tools/monitor/oap/collector/lib/kafka/provider_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/kafka/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: approved

#6354 fix: log service multi org search error
  internal/tools/monitor/core/log/query/log.query.service.go
  internal/tools/monitor/core/log/query/log.query.service_test.go
  internal/tools/monitor/core/log/query/routes.go
Labels: bugfix, approved

#6367 chore: cleanup deprecated module
  api/proto-go/go.mod
  api/proto-go/go.sum
  go.mod
  go.sum
  internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_issue/export.go
  internal/apps/dop/providers/issue/core/query/issueexcel/vars/custom_field.go
  internal/pkg/ai-functions/handler/handler_ai_function.go
  internal/pkg/etcdclient/etcdclient.go
  internal/pkg/extension/extension.service.go
  internal/tools/monitor/oap/collector/plugins/receivers/opentelemetry/interceptor.go
  internal/tools/pipeline/providers/queuemanager/manager/snapshot.go
  internal/tools/pipeline/providers/queuemanager/manager/usage.go
  pkg/dlock/dlock.go
  pkg/jsonstore/etcd/etcd.go
Labels: approved

#6368 chore: upgrade base image
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  api/proto-go/Makefile
  pipeline.yml
Labels: approved

#6366 feat(collector): add `dropper` provider for application metric
  cmd/monitor/collector/bootstrap-agent.yaml
  internal/tools/monitor/oap/collector/plugins/all/all.go
  internal/tools/monitor/oap/collector/plugins/processors/dropper/provider.go
Labels: feature, approved

#6372 fix: `transaction-http-analysis` failed to order by avgDuration
  internal/apps/msp/apm/service/view/table/transaction.go
Labels: bugfix, approved

#6373 feat: upgrade ta.js
  internal/tools/monitor/core/collector/statik/statik.go
  internal/tools/monitor/core/collector/ta.js
Labels: feature, approved

#6375 feat: update ta.js (version: 2024-06-25)
  internal/tools/monitor/core/collector/statik/statik.go
  internal/tools/monitor/core/collector/ta-js.md
  internal/tools/monitor/core/collector/ta.js
Labels: feature, approved

#6376 fix(pipeline): pipeline taskOP `queue` panic due to nil flink taskManager status
  internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/util.go
Labels: pipeline, bugfix, approved

#6378 feat: make collector support sentinel mode redis
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
Labels: approved
