Repository erda-project/erda, pull requests merged in 2024-08, with the labels that each got.

#6415 fix(monitor): cpu usage in resource-container-monitor
  internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
Labels: bugfix, approved

#6416 fix(pipeline): task with status NoNeedBySystem cause pipeline status to Failed
  internal/tools/pipeline/aop/plugins/pipeline/basic/plugin.go
  internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_after/plugin.go
  internal/tools/pipeline/aop/plugins/task/unit_test_report/plugin.go
  internal/tools/pipeline/commonutil/statusutil/status.go
  internal/tools/pipeline/commonutil/statusutil/status_test.go
  internal/tools/pipeline/dbclient/op_pipeline.go
  internal/tools/pipeline/pexpr/pexpr_params/task_params.go
  internal/tools/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
  internal/tools/pipeline/pkg/taskinspect/inspect.go
  internal/tools/pipeline/providers/reconciler/snippet.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare.go
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/prepare_test.go
  internal/tools/pipeline/spec/pipeline_task.go
  pkg/expression/expression_execute.go
  pkg/expression/expression_execute_test.go
Labels: pipeline, bugfix

#6412 fix: remove steve cache ttl
  cmd/erda-server/bootstrap.yaml
  internal/apps/cmp/endpoints/endpoints.go
  internal/apps/cmp/initialize.go
  internal/apps/cmp/provider.go
  internal/apps/cmp/steve/aggregator.go
Labels: bugfix, approved

#6417 chore: remove unused orgalorg
  build/dockerfiles/Dockerfile
Labels: approved

#6420 feat(collector): collector `dropper` processor support raw data
  cmd/monitor/collector/bootstrap-agent.yaml
  cmd/monitor/collector/bootstrap.yaml
  internal/tools/monitor/oap/collector/core/model/odata/raw.go
  internal/tools/monitor/oap/collector/plugins/processors/dropper/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider_test.go
Labels: feature, approved

#6421 fix(pipeline): handle task time_begin & cost_time_sec if not set correctly
  internal/tools/pipeline/providers/reconciler/taskrun/taskop/wait.go
  internal/tools/pipeline/spec/pipeline_task.go
  internal/tools/pipeline/spec/pipeline_task_test.go
Labels: pipeline, bugfix

#6423 fix(pipeline): make pipeline definition cleanup works
  internal/tools/pipeline/providers/cron/db/define.go
  internal/tools/pipeline/providers/cron/db/examples/client.go
  internal/tools/pipeline/providers/cron/db/examples/examples.yaml
  internal/tools/pipeline/providers/cron/db/examples/main.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/local_debug/local-debug.yaml
  internal/tools/pipeline/providers/dbgc/definition_cleanup/local_debug/main.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/provider.go
Labels: pipeline, bugfix

#6419 fix: pod info table has not been GC
  internal/tools/orchestrator/scheduler/instanceinfo/pod.go
  internal/tools/orchestrator/scheduler/instanceinfo/pod_test.go
Labels: bugfix, approved

#6422 fix: canal interlink
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_status.go
  internal/tools/orchestrator/services/addon/addon_status_test.go
Labels: bugfix, approved

#6398 fix: cluster registration information is overwritten
  go.mod
  go.sum
  internal/tools/cluster-manager/dialer/server/tunnel-server.go
Labels: bugfix, approved

#6424 feat: cluster addon reset to mse-addon if it has mse nacos
  .erda/migrations/msp/20240809-mse-nacos.sql
  .erda/migrations/msp/20240812-insert-config-center.sql
  cmd/erda-server/bootstrap.yaml
  cmd/erda-server/main.go
  cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
  internal/apps/msp/resource/deploy/coordinator/coordinator.go
  internal/apps/msp/resource/deploy/handlers/configcenter/configcenter.go
  internal/apps/msp/resource/deploy/handlers/externalprovider/externalprovider.go
  internal/apps/msp/resource/deploy/handlers/externalprovider/provider.go
  internal/apps/msp/resource/deploy/handlers/handler.go
  internal/apps/msp/resource/deploy/handlers/registercenter/registercenter.go
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_test.go
Labels: feature, approved

#6427 fix: pipeline stuck in queue status because etcd server abnormal
  internal/tools/pipeline/providers/dbgc/definition_cleanup/provider.go
  internal/tools/pipeline/providers/leaderworker/heartbeat.go
  internal/tools/pipeline/providers/leaderworker/impl_worker.go
Labels: bugfix, approved

#6426 feat: `dropper` processer support metric white list
  cmd/monitor/collector/bootstrap-agent.yaml
  internal/apps/msp/apm/service/apm.service.service.go
  internal/tools/monitor/oap/collector/plugins/processors/dropper/provider.go
Labels: feature, approved

#6425 feat: pod monitoring charts modified to show Pods as the smallest unit
  cmd/monitor/monitor/conf/chartview/cmp/cmp-dashboard-podDetail.json
Labels: feature, approved

#6413 feat: update keda to support autoscaling/v2
  go.mod
  go.sum
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/scaledobject/scaledobject.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/types/type.go
  pkg/k8sclient/apis/keda/v1alpha1/condition_types.go
  pkg/k8sclient/apis/keda/v1alpha1/groupversion_info.go
  pkg/k8sclient/apis/keda/v1alpha1/gvkr_types.go
  pkg/k8sclient/apis/keda/v1alpha1/readme_before_edit_this_package.md
  pkg/k8sclient/apis/keda/v1alpha1/scaledjob_types.go
  pkg/k8sclient/apis/keda/v1alpha1/scaledobject_types.go
  pkg/k8sclient/apis/keda/v1alpha1/triggerauthentication_types.go
  pkg/k8sclient/apis/keda/v1alpha1/withtriggers_types.go
  pkg/k8sclient/apis/keda/v1alpha1/zz_generated.deepcopy.go
  pkg/k8sclient/scheme/register.go
Labels: feature, approved
