Repository erda-project/erda, pull requests merged in 2024-03, with the labels that each got.

#6295 feat(orchestrator): pass elasticsearch spec nodes to plugin
  internal/tools/orchestrator/services/addon/addon_deploy.go
  internal/tools/orchestrator/services/addon/addon_status.go
Labels: orchestrator, feature, approved

#6300 refactor: refactor NameConflict func
  internal/apps/dop/providers/issue/dao/issue_property.go
  internal/apps/dop/providers/issue/dao/issue_test.go
Labels: approved

#6249 feat(streaming): support streaming logs by pipeline mode
  cmd/monitor/streaming/bootstrap.yaml
  go.mod
  go.sum
  internal/apps/msp/apm/trace/query/source/clickhouse_source_test.go
  internal/tools/monitor/core/log/storage/clickhouse/aggregate_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/initializer/mock_test.go
  internal/tools/monitor/core/storekit/clickhouse/table/meta/mock_clickhouse_test.go
  internal/tools/monitor/oap/collector/lib/protoparser/spotlog/spotlog.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/log/log.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/metric/metric_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/builder/span/span_test.go
  internal/tools/monitor/oap/collector/plugins/exporters/clickhouse/provider.go
  internal/tools/monitor/oap/collector/plugins/receivers/kafka/provider.go
Labels: feature, approved

#6258 feat: refactoring DaemonSet and supporting `k8s-snippet` in dice.yml
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/interface.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset/daemonset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/job.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_stateful.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/namespace.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/runtime.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/serviceaccount.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/types/type.go
  internal/tools/orchestrator/scheduler/executor/util/util.go
Labels: orchestrator, feature, approved

#6236 fix: runtime domain api privilege leakage
  conf/erda-configs/permission/backend/sys/org/org.yml
  conf/erda-configs/permission/backend/sys/org/project/app/app.yml
  internal/tools/orchestrator/hepa/providers/domain/domain.service.go
  internal/tools/orchestrator/hepa/providers/domain/provider.go
  internal/tools/orchestrator/hepa/services/domain/impl/impl.go
  internal/tools/orchestrator/hepa/services/domain/impl/impl_test.go
  internal/tools/orchestrator/hepa/services/domain/interface.go
Labels: bugfix, approved

#6305 feat(ai-proxy): support assistant api
  api/proto/apps/aiproxy/model/model.proto
  cmd/ai-proxy/bootstrap.yml
  cmd/ai-proxy/conf/routes/assistant.yml
  cmd/ai-proxy/conf/routes/routes.yml
  internal/apps/ai-proxy/common/request_path.go
  internal/apps/ai-proxy/config/config.go
  internal/apps/ai-proxy/dependent_filters.go
  internal/apps/ai-proxy/filters/audit-before-llm-director/req.go
  internal/apps/ai-proxy/filters/audit-before-llm-director/resp.go
  internal/apps/ai-proxy/filters/context-assistant/filter.go
  internal/apps/ai-proxy/filters/context-file/filter.go
  internal/apps/ai-proxy/filters/context/filter.go
  internal/apps/ai-proxy/filters/openai-director/filter.go
  internal/apps/ai-proxy/models/metadata/meta_client.go
  internal/pkg/ai-proxy/route/route.go
  pkg/reverseproxy/context.go
  pkg/reverseproxy/filter.go
Labels: feature

#6301 fix: set the journal mode to memory in SQLite3
  go.mod
  go.sum
  internal/tools/pipeline/providers/cron/db/define_test.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup_test.go
  internal/tools/pipeline/providers/definition/db/define_test.go
Labels: bugfix, approved

#6298 fix(msp): failed to get notify detail due to msp_env scope type
  apistructs/notify_group.go
  apistructs/notify_group_test.go
  internal/core/legacy/services/notify/notify_group.go
  internal/core/messenger/notifygroup/group.service.go
Labels: msp, bugfix, approved

#6306 fix: fix issue with xorm limit(0) causing no data retrieval
  internal/tools/pipeline/providers/definition/db/define.go
  internal/tools/pipeline/providers/definition/db/define_test.go
Labels: bugfix, approved

#6302 fix: add gittar request path encode
  bundle/gittar.go
  bundle/gittar_test.go
Labels: approved

#6303 fix: xorm.ID() does not support ptr type
  internal/tools/pipeline/dbclient/op_pipeline.go
  internal/tools/pipeline/dbclient/op_pipeline_stage.go
  internal/tools/pipeline/dbclient/op_pipeline_task.go
  internal/tools/pipeline/dbclient/op_pipeline_task_test.go
  internal/tools/pipeline/providers/build/db/ci_v3_build_cache.go
  internal/tools/pipeline/providers/cache/impl_test.go
  internal/tools/pipeline/providers/cron/cron.service_test.go
  internal/tools/pipeline/providers/cron/db/define_extra.go
  internal/tools/pipeline/providers/edgereporter/reporter_test.go
  internal/tools/pipeline/providers/pipeline/callback_test.go
  internal/tools/pipeline/providers/pipeline/create_test.go
  internal/tools/pipeline/providers/pipeline/rerun_test.go
  internal/tools/pipeline/providers/reconciler/snippet_test.go
  internal/tools/pipeline/providers/reconciler/task_reconciler.go
  internal/tools/pipeline/providers/reconciler/task_reconciler_test.go
  internal/tools/pipeline/providers/reconciler/taskpolicy/provider.go
Labels: bugfix, approved

#6308 feat: add random name for sqlite3 file
  go.mod
  go.sum
  internal/tools/pipeline/dbclient/op_pipeline_task_test.go
  internal/tools/pipeline/providers/cron/db/define_test.go
  internal/tools/pipeline/providers/dbgc/definition_cleanup/definition_cleanup_test.go
  internal/tools/pipeline/providers/definition/db/define_test.go
Labels: feature, approved

#6304 feat: add MigrateOrgCustomFileds interface
  api/proto/dop/issue/core/core.proto
  internal/apps/devflow/flow/issue_mock.go
  internal/apps/dop/component-protocol/components/issue-manage/issueTable/render.go
  internal/apps/dop/providers/issue/core/property.go
  internal/apps/dop/providers/issue/core/query/paging.go
  internal/apps/dop/providers/issue/core/query/property.go
  internal/apps/dop/providers/issue/core/query/provider.go
  internal/apps/dop/providers/issue/dao/issue_property.go
  pkg/mock/issue_query_mock.go
Labels: feature, approved

#6319 feat(pipeline): add pipeline archive retain hour env
  internal/tools/pipeline/providers/dbgc/provider.go
Labels: pipeline, feature, approved

#6317 feat(ai-proxy): support complete file apis
  cmd/ai-proxy/bootstrap.yml
  cmd/ai-proxy/conf/routes/assistant.yml
  cmd/ai-proxy/conf/routes/file.yml
  internal/apps/ai-proxy/filters/context-file/filter.go
Labels: feature

#6320 fix(pipeline): pipeline cancel missing user when req userid is empty
  internal/tools/pipeline/providers/pipeline/cancel.go
Labels: pipeline, bugfix, approved

#6311 feat: optimize deploy addon error message alerts
  cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
  internal/tools/orchestrator/services/addon/addon_handler.go
  internal/tools/orchestrator/services/addon/addon_test.go
  internal/tools/orchestrator/services/deployment/deployment_context.go
Labels: feature, approved

#6321 fix: fix batch EOF deletion error
  internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/model.go
  internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
Labels: bugfix, approved

#6324 chore: upgrade erda-infra version
  go.mod
  go.sum
Labels: approved
