Repository erda-project/erda, pull requests merged in 2024-02, with the labels that each got.

#6265 fix(dicehub): public field push exception for the extension
  internal/pkg/extension/db/extension.go
  internal/pkg/extension/extension.service.go
  internal/pkg/extension/extension.service_test.go
Labels: bugfix

#6277 fix: fix SQL injection in cmp
  internal/apps/cmp/dbclient/records.go
Labels: bugfix, approved

#6279 fix(monitor): let the logic of max func be consistent with min, if not existing it is null
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/ckFunctions_test.go
  internal/tools/monitor/core/metric/query/es-tsql/influxql/parse_clickhouse_test.go
Labels: bugfix, approved

#6281 fix: use `container_spec_memory_limit_bytes` as container memory limit metric source
  internal/apps/msp/apm/service/components/resources-container-monitor/container/provider.go
Labels: bugfix, approved

#6282 fix(monitor): failed to parse log ttl duration
  internal/tools/monitor/core/settings/monitor.go
Labels: bugfix, approved

#6286 chore: bump xormplus version
  go.mod
  go.sum
  internal/apps/dop/dbclient/apitest.go
  internal/apps/dop/dbclient/project_test_env.go
  internal/tools/orchestrator/hepa/repository/orm/build_cond.go
  internal/tools/orchestrator/hepa/repository/orm/orm_engine.go
  internal/tools/pipeline/providers/definition/db/define.go
  internal/tools/pipeline/providers/definition/db/define_test.go
  pkg/database/cimysql/mysql.go
Labels: approved

#6223 feat: project level enterprise level duplicate name coverage
  api/proto/dop/issue/core/core.proto
  internal/apps/dop/providers/issue/core/file.go
  internal/apps/dop/providers/issue/core/property.go
  internal/apps/dop/providers/issue/core/query/convert.go
  internal/apps/dop/providers/issue/core/query/issueexcel/sheets/sheet_customfield/import.go
  internal/apps/dop/providers/issue/core/query/property.go
  internal/apps/dop/providers/issue/dao/issue_property.go
  internal/apps/dop/providers/issue/dao/issue_test.go
Labels: feature, approved

#6264 refactor: delete iterations and their sub items together
  internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/model.go
  internal/apps/dop/component-protocol/components/issue-manage/batchOperationTipModal/render.go
  internal/apps/dop/endpoints/endpoints.go
  internal/apps/dop/endpoints/iteration.go
  internal/apps/dop/initialize.go
  internal/apps/dop/providers/issue/core/service.go
  internal/apps/dop/providers/issue/dao/core.go
  internal/apps/dop/services/iteration/iteration.go
Labels: refactor, approved

#6287 feat: add pipeline_crons soft_delete_at
  .erda/migrations/pipeline/20240221-pipeline-crons-add-softdelete.sql
  go.sum
  internal/tools/pipeline/providers/cron/db/define.go
  internal/tools/pipeline/providers/cron/db/define_test.go
Labels: feature, approved

#6289 fix: notifygroup exception notice in erda-server
  api/proto/msp/apm/notifygroup/notifygroup.proto
Labels: approved

#6194 fix: fix pipeline dbgc
  api/proto/core/pipeline/pipeline/pipeline.proto
  apistructs/pipeline.go
  internal/tools/pipeline/dbclient/op_pipeline.go
  internal/tools/pipeline/dbclient/op_pipeline_definition.go
  internal/tools/pipeline/providers/dbgc/dbgc.go
  internal/tools/pipeline/providers/dbgc/dbgc_test.go
  pkg/strutil/example_slice_test.go
  pkg/strutil/slice.go
  pkg/strutil/slice_test.go
Labels: bugfix, approved

#6244 feat: display the app list search results based on their relevancy
  internal/core/legacy/dao/application.go
Labels: feature, approved

#6250 fix: incorrect app pipeline filtering
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/inparams.go
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/inparams_test.go
  internal/apps/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
Labels: bugfix

#6288 fix: fix gittar oom
  internal/tools/gittar/ai/cr/impl/cr_mr/mr.go
  pkg/limit_sync_group/group.go
Labels: bugfix, approved
