Repository erda-project/erda, pull requests merged in 2024-09, with the labels that each got.

#6431 fix: uc login redirect dismatch under NodePort service
  cmd/erda-server/bootstrap.yaml
  internal/core/openapi/openapi-ng/auth/uc-session/login.go
  internal/core/openapi/openapi-ng/auth/uc-session/login_test.go
  internal/core/openapi/openapi-ng/auth/uc-session/provider.go
Labels: bugfix, approved

#6434 feat: diceyml env regexp support .-
  pkg/parser/diceyml/servicename_visitor.go
  pkg/parser/diceyml/servicename_visitor_test.go
Labels: feature, approved

#6433 fix: dice yaml replace * error
  pkg/parser/diceyml/basic_validate_visitor_test.go
  pkg/parser/diceyml/diceyml.go
Labels: bugfix, approved

#6435 fix: dice yaml replace * error
  pkg/parser/diceyml/basic_validate_visitor_test.go
  pkg/parser/diceyml/diceyml.go
Labels: bugfix, approved

#6436 fix(hepa): failed to delete `route` due to nil zoneInfo make panic
  internal/tools/orchestrator/hepa/services/api_policy/impl/impl.go
  internal/tools/orchestrator/hepa/services/endpoint_api/impl/impl.go
  internal/tools/orchestrator/hepa/services/openapi_rule/impl/impl.go
Labels: hepa, bugfix, approved

#6428 feat: get terminal params from args
  internal/tools/orchestrator/endpoints/instance.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
  internal/tools/orchestrator/scheduler/impl/terminal/terminal.go
Labels: feature, approved

#6429 feat: get same mutex lock for registercenter and configcenter
  internal/apps/msp/resource/deploy/coordinator/coordinator.go
Labels: feature

#6438 fix(ai-proxy): dashscope non-stream openai style
  internal/apps/ai-proxy/filters/audit-after-llm-director/resp.go
  internal/apps/ai-proxy/filters/dashscope-director/resp.go
  internal/apps/ai-proxy/filters/dashscope-director/util.go
  internal/apps/ai-proxy/models/metadata/meta_dashscope.go
Labels: bugfix

#6439 fix: sql migrations error
  .erda/migrations/msp/20240809-mse-nacos.sql
  .erda/migrations/msp/20240812-insert-config-center.sql
Labels: bugfix, approved

#6440 fix: new cluster steve not ready
  internal/apps/cmp/steve/aggregator.go
Labels: bugfix, approved

#6441 fix: inject register-center version and gorm query condition
  internal/tools/orchestrator/dbclient/addon_instance.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_test.go
Labels: bugfix, approved

#6442 fix(collector): auth validator is nil
  internal/tools/monitor/oap/collector/plugins/receivers/collector/provider.go
Labels: bugfix, approved

#6443 feat(pipeline): inject project/org default namespace for ci/cd pipeline
  internal/apps/dop/endpoints/pipeline.go
  internal/apps/dop/endpoints/pipeline_test.go
Labels: pipeline, feature, approved

#6444 fix: adjust priority for config namespace
  internal/apps/dop/endpoints/pipeline.go
Labels: bugfix, approved
