Repository erda-project/erda, pull requests merged in 2024-05, with the labels that each got.

#6343 feat: support set some http cookie security configuration
  cmd/erda-server/bootstrap.yaml
  internal/core/openapi/openapi-ng/interceptors/csrf/csrf.go
Labels: approved

#6344 fix: csrf same site type error
  internal/core/openapi/openapi-ng/interceptors/csrf/csrf.go
Labels: bugfix, approved

#6346 fix: manual cherry-pick of #6343 support set some http cookie security configuration
  conf/openapi/openapi.yaml
  modules/core/openapi-ng/interceptors/csrf/csrf.go
Labels: bugfix, approved

#6347 feat: support setting uc openapi session
  cmd/erda-server/bootstrap.yaml
  internal/core/openapi/openapi-ng/auth/uc-session/login.go
  internal/core/openapi/openapi-ng/auth/uc-session/provider.go
Labels: feature, approved

#6348 hotfix: manual cherry-pick of #6347
  conf/openapi/openapi.yaml
  modules/core/openapi-ng/auth/uc-session/login.go
  modules/core/openapi-ng/auth/uc-session/provider.go
Labels: approved

#6349 fix(openapi): unknown unit 'd' in duration
  cmd/erda-server/bootstrap.yaml
Labels: openapi, bugfix, approved

#6342 feat: ta.js support attribute
  internal/tools/monitor/core/collector/statik/statik.go
  internal/tools/monitor/core/collector/ta.js
Labels: feature, approved

#6351 fix(pipeline): the agent is stuck in the waiting logs done due to prepare failure
  internal/tools/pipeline/actionagent/execute.go
  internal/tools/pipeline/actionagent/exit.go
Labels: pipeline, bugfix, approved

#6340 feat: replace apply token to create service account token secret
  cmd/cluster-agent/bootstrap.yaml
  internal/tools/cluster-agent/config/config.go
  internal/tools/cluster-agent/pkg/client/client.go
  internal/tools/cluster-agent/pkg/client/client_test.go
Labels: feature, approved

#6352 fix(monitor): addon alert cross workspace
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_elasticsearch_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_cpu/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_mem/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_mysql_slave_status/analyzer_expression.json
  cmd/monitor/monitor/conf/alert/rules/addon/addon_redis_mem/analyzer_expression.json
  internal/tools/monitor/core/alert/alert-apis/adapt/expression.go
Labels: bugfix, approved

#6355 chore: upgrade infra for grpc server configuration
  go.mod
  go.sum
Labels: approved

#6356 fix(cmp): dbclient sql build error
  internal/apps/cmp/dbclient/records.go
Labels: cmp, bugfix, approved
