Repository erda-project/erda, pull requests merged in 2024-11, with the labels that each got.

#6464 fix(orchestrator): eci fluent-bit sidecar log collect error
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/lifecycle_test.go
Labels: orchestrator, bugfix, approved

#6459 refactor: optimize list hooks for avoid unnecessary json marshal/unmarshal
  internal/core/messenger/eventbox/dispatcher/filters/webhookfilter.go
  internal/core/messenger/eventbox/dispatcher/filters/webhookfilter_test.go
  internal/core/messenger/eventbox/webhook/builtin.go
  internal/core/messenger/eventbox/webhook/http.go
  internal/core/messenger/eventbox/webhook/impl.go
Labels: refactor, approved

#6446 feat: custom deploy addon support cluster addon and can select version
  apistructs/addon.go
  cmd/orchestrator/conf/i18n/orchestrator-log-trans.yaml
  internal/tools/orchestrator/endpoints/addon.go
  internal/tools/orchestrator/endpoints/addon_test.go
  internal/tools/orchestrator/endpoints/endpoints.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
  internal/tools/orchestrator/services/addon/addon.go
  internal/tools/orchestrator/services/addon/addon_extension_cache.go
  internal/tools/orchestrator/services/addon/addon_handler.go
Labels: feature, approved

#6465 fix(ai-proxy): dashscope non-stream support vlm multipart
  internal/apps/ai-proxy/filters/dashscope-director/sdk/converter.go
  internal/apps/ai-proxy/filters/dashscope-director/sdk/converter_test.go
Labels: bugfix

#6447 fix: fix slice init length
  pkg/mock/mock.go
Labels: bugfix, approved

#6466 chore: upgrade kafka go to support arm64
  go.mod
  go.sum
Labels: approved

#6467 chore: update routine version to 1.1.4 from 1.1.2
  go.mod
  go.sum
Labels: approved
