Repository erda-project/erda, pull requests merged in 2025-02, with the labels that each got.

#6489 fix(orchestrator): runtime service wg not released properly
  internal/apps/dop/component-protocol/components/app-runtime/list/list.go
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: approved

#6479 refactor: service group resource subscribe ratio
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/canal/canal_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/daemonset/daemonset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/elasticsearch/elasticsearch.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/interface.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mock/interface_mock.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/mysql/mysql_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/process.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/legacy/redis.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/redis_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/redis/unify.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/rocketmq/rocketmq.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/sourcecov/mock/namespaceutil_mock.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/sourcecov/sourcecov.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/addon/sourcecov/sourcecov_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/affinity.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/check_quota.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/istio.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/job.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/job_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/oversubscriberatio/oversubscriberatio.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/oversubscriberatio/oversubscriberatio_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/podscale.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/registry.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/servicegroup_operations.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/statefulset_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/types/type.go
  internal/tools/orchestrator/scheduler/executor/plugins/k8s/utils.go
  internal/tools/orchestrator/scheduler/executor/util/util.go
  internal/tools/orchestrator/scheduler/executor/util/util_test.go
Labels: orchestrator, refactor, approved

#6491 fix: pipeline EnsureGc nil pointer panic
  internal/tools/pipeline/spec/pipeline.go
  internal/tools/pipeline/spec/pipeline_test.go
Labels: approved

#6493 feat(ai-proxy): support custom displayProviderType for self-hosted provider
  api/proto/apps/aiproxy/model_provider/model_provider.proto
  internal/apps/ai-proxy/filters/azure-director/filter.go
  internal/apps/ai-proxy/filters/bailian-director/filter.go
  internal/apps/ai-proxy/filters/context-audio/filter.go
  internal/apps/ai-proxy/filters/dashscope-director/filter.go
  internal/apps/ai-proxy/filters/openai-director/filter.go
  internal/apps/ai-proxy/filters/openai-v1-models/model_name.go
  internal/apps/ai-proxy/handlers/handler_model_provider/handler.go
  internal/apps/ai-proxy/handlers/handler_rich_client/handler.go
  internal/apps/ai-proxy/models/metadata/meta_model_provider.go
  internal/apps/ai-proxy/models/model_provider/table.go
Labels: feature

#6494 chore: dbmigration baseline change patch order
  .erda/migrations/.patches/patch-20200528-tmc-base.sql
  .erda/migrations/.patches/patch-20210528-cmdb-base.sql
  .erda/migrations/.patches/patch-20210528-monitor-base.sql
  .erda/migrations/.patches/patch-20210528-orchestrator-base.sql
  .erda/migrations/.patches/patch-20210528-pipeline-base.sql
  .erda/migrations/config.yml
  .erda/migrations/orchestrator/20210528-orchestrator-base.sql
Labels: approved
