Repository erda-project/erda, pull requests merged in 2025-05, with the labels that each got.

#6516 feat: skip registercenter if it is terminus-zkproxy
  internal/apps/msp/resource/deploy/handlers/mysql/mysql.go
  internal/tools/orchestrator/services/addon/addon.go
Labels: feature, approved

#6517 chore(pipeline): move dbgc config items from pipeline global into provider
  internal/tools/pipeline/conf/conf.go
  internal/tools/pipeline/providers/dbgc/dbgc.go
  internal/tools/pipeline/providers/dbgc/dbgc_test.go
  internal/tools/pipeline/providers/dbgc/dbgcconfig/config.go
  internal/tools/pipeline/providers/dbgc/dbgcconfig/config_test.go
  internal/tools/pipeline/providers/dbgc/provider.go
  internal/tools/pipeline/spec/pipeline.go
Labels: pipeline

#6520 feat(dop): enhance testset sorting for Recycle Bin
  internal/apps/dop/dao/testset.go
Labels: dop, feature, approved

#6522 feat(ai-proxy): support set extra-body for some models
  cmd/ai-proxy/conf/routes/routes.yml
  internal/apps/ai-proxy/dependent_filters.go
  internal/apps/ai-proxy/filters/extra-body/filter.go
  internal/apps/ai-proxy/filters/extra-body/json_body.go
  internal/apps/ai-proxy/filters/extra-body/json_body_test.go
Labels: feature

#6504 feat: ai-proxy support mcp servers
  .erda/ai-proxy/migrations/ai-proxy/20250321-mcp-server.sql
  api/proto/apps/aiproxy/mcp_server/mcp_server.proto
  internal/apps/ai-proxy/handlers/handler_mcp_server/handler.go
  internal/apps/ai-proxy/handlers/permission/method.go
  internal/apps/ai-proxy/models/mcp_server/dbclient.go
  internal/apps/ai-proxy/models/mcp_server/table.go
  internal/apps/ai-proxy/provider.go
  internal/apps/ai-proxy/providers/dao/provider.go
Labels: feature, approved

#6518 feat(auth): add referer validation for UC login direct
  cmd/erda-server/bootstrap.yaml
  internal/core/openapi/openapi-ng/auth/uc-session/login.go
  internal/core/openapi/openapi-ng/auth/uc-session/provider.go
  internal/core/openapi/openapi-ng/auth/uc-session/refer.go
  internal/core/openapi/openapi-ng/auth/uc-session/refer_test.go
Labels: feature, approved

#6526 feat(ai-proxy): support ai-proxy-admin-ui
  .gitignore
  api/proto/apps/aiproxy/client/client.proto
  api/proto/apps/aiproxy/client_model_relation/client_model_relation.proto
  api/proto/apps/aiproxy/model/model.proto
  api/proto/apps/aiproxy/model_provider/model_provider.proto
  internal/apps/ai-proxy/handlers/apis.go
  internal/apps/ai-proxy/handlers/handler_client_model_relation/handler.go
  internal/apps/ai-proxy/handlers/permission/method.go
  internal/apps/ai-proxy/models/client/dbclient.go
  internal/apps/ai-proxy/models/client_model_relation/dbclient.go
  internal/apps/ai-proxy/models/client_model_relation/table.go
  internal/apps/ai-proxy/models/model/dbclient.go
  internal/apps/ai-proxy/models/model_provider/dbclient.go
  internal/apps/ai-proxy/models/sqlutil/util.go
  internal/apps/ai-proxy/provider.go
  internal/pkg/gorilla/mux/middles.go
Labels: feature
