Repository erda-project/erda, pull requests merged in 2025-06, with the labels that each got.

#6532 feat(ai-proxy): Anthropic-Compatible Director support Thinking config
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/anthropic_official/anthropic.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/anthropic_official/eventstream.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/aws_bedrock/bedrock.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/aws_bedrock/bedrock_test.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/aws_bedrock/eventstream.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/req.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/resp.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/openai_extended.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/getter.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/getter_test.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/thinking.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/openai_extended/thinking/thinking_test.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/req.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/filter.go
  internal/apps/ai-proxy/provider.go
Labels: feature

#6536 fix(orchestrator): instances-usage sql injection
  modules/orchestrator/scheduler/instanceinfo/instance.go
  modules/orchestrator/scheduler/instanceinfo/instance_test.go
Labels: orchestrator, bugfix

#6535 fix(cmp): lack of access authorization
  modules/cmp/alert.go
  modules/cmp/endpoints/cluster.go
  modules/cmp/provider.go
  modules/openapi/api/apis/cmp/cmp_alert_condition.go
  modules/openapi/api/apis/cmp/cmp_cluster_init_command.go
Labels: cmp, bugfix

#6527 feat: add nacos2.3.sql
  cmd/erda-server/conf/msp/init_sqls/tmc/nacos2.3.sql
Labels: feature, approved

#6538 fix(cmp): lack of access authorization
  internal/apps/cmp/alert.go
  internal/apps/cmp/endpoints/cluster.go
  internal/apps/cmp/provider.go
  internal/core/openapi/legacy/api/apis/cmp/cmp_cluster_init_command.go
Labels: cmp, bugfix, approved

#6541 feat(ai-proxy): support route-based multiple APIStyleConfigs
  cmd/ai-proxy/bootstrap.yml
  cmd/ai-proxy/conf/routes/assistant.yml
  cmd/ai-proxy/conf/routes/file.yml
  cmd/ai-proxy/conf/routes/responses.yml
  internal/apps/ai-proxy/filters/directors/custom-http-director/filter.go
  internal/apps/ai-proxy/models/metadata/api_segment/api.go
  internal/apps/ai-proxy/models/metadata/api_segment/api_style/api_style.go
Labels: feature

#6543 feat: add the mcp transport type field
  .erda/ai-proxy/migrations/ai-proxy/20250321-mcp-server.sql
  api/proto/apps/aiproxy/mcp_server/mcp_server.proto
  internal/apps/ai-proxy/models/mcp_server/dbclient.go
  internal/apps/ai-proxy/models/mcp_server/table.go
Labels: feature, approved

#6545 feat(ai-proxy): support invoking completion api by `${publisher}/${model}` format
  .gitignore
  internal/apps/ai-proxy/filters/context/model.go
  internal/apps/ai-proxy/filters/context/model_test.go
  internal/apps/ai-proxy/filters/openai-v1-models/filter.go
  internal/apps/ai-proxy/filters/openai-v1-models/model_name.go
  internal/apps/ai-proxy/filters/openai-v1-models/publisher.go
Labels: feature

#6550 fix(loghub): update file paths for ES index template and rollover
  cmd/monitor/extensions/loghub/conf/output/bootstrap-elasticsearch-rollover.yaml
Labels: bugfix, approved

#6546 feat(openapi): allow UCAddr in referer validation
  internal/core/openapi/openapi-ng/auth/uc-session/refer.go
  internal/core/openapi/openapi-ng/auth/uc-session/refer_test.go
Labels: feature, openapi, approved
