Repository erda-project/erda, pull requests merged in 2025-07, with the labels that each got.

#6551 feat(ai-proxy): add API for updating model abilities info
  api/proto/apps/aiproxy/model/model.proto
  internal/apps/ai-proxy/handlers/handler_model/handler.go
  internal/apps/ai-proxy/handlers/permission/method.go
  internal/apps/ai-proxy/models/model/dbclient.go
Labels: feature

#6554 fix(ai-proxy): ai-proxy ensure sse content-type to text/event-stream (such as aws-bedrock)
  internal/apps/ai-proxy/provider.go
Labels: bugfix

#6555 feat: The log download supports custom duration.
  internal/tools/monitor/core/log/query/provider.go
  internal/tools/monitor/core/log/query/routes.go
Labels: feature

#6558 fix(ai-proxy): support tool call
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/req.go
  internal/apps/ai-proxy/filters/directors/anthropic-compatible-director/common/message_converter/resp.go
Labels: bugfix

#6559 feat(edas): add label support for EDAS applications
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/types/types.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/edas/app.client_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/provider.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go
Labels: feature, approved

#6560 refactor(edas): update label keys for service name and group ID
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas_app_flow_test.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/types/types.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service.go
  internal/tools/orchestrator/scheduler/executor/plugins/edas/wrapclient/kubernetes/service_test.go
Labels: refactor, approved
