Repository erda-project/erda, pull requests merged in 2025-08, with the labels that each got.

#6562 fix(orchestrator): edas scale application command render error
  internal/tools/orchestrator/scheduler/executor/plugins/edas/edas.go
Labels: approved

#6505 fix: add unmark deployment
  internal/tools/orchestrator/services/runtime/runtime.go
Labels: bugfix, approved

#6566 fix(ai-proxy): `/v1/models` and context-find-model only use model.name or publisher/model.name
  internal/apps/ai-proxy/route/filters/request/context-family/context/model.go
  internal/apps/ai-proxy/route/filters/request/openai-v1-models/model_name.go
Labels: bugfix

#6576 fix(ai-proxy): set anthropic req.thinking.budget_tokens=req.max_tokens/2 if empty
  internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/message_converter/req.go
  internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/openai_extended/thinking/thinking.go
Labels: bugfix

#6578 build: upgrade to go 1.24
  .erda/pipelines/ci-build-ce.yml
  .erda/pipelines/ci-deploy.yml
  .github/workflows/ci-it-noneed.yml
  .github/workflows/ci-it.yml
  .golangci.yml
  Makefile
  api/proto-go/Makefile
  build/dockerfiles/Dockerfile-cluster-ops
  build/scripts/buildkit_image.sh
  build/scripts/docker_image.sh
  go.mod
  go.sum
  internal/apps/ai-proxy/route/filters/common/anthropic-compatible-director/common/openai_extended/thinking/thinking_test.go
  internal/apps/ai-proxy/route/filters/common/custom-http-director/body_test.go
  internal/pkg/profileagent/provider.go
  pipeline.yml
  pkg/goroutine_context/context.go
Labels: approved

#6583 feat: openapi settings provider and configurable session expiration time in redis
  cmd/erda-server/bootstrap.yaml
  internal/core/openapi/legacy/auth/auth.go
  internal/core/openapi/legacy/auth/user.go
  internal/core/openapi/legacy/loginserver.go
  internal/core/openapi/legacy/provider.go
  internal/core/openapi/legacy/server.go
  internal/core/openapi/openapi-ng/auth/password/check.go
  internal/core/openapi/openapi-ng/auth/password/provider.go
  internal/core/openapi/openapi-ng/auth/uc-session/check.go
  internal/core/openapi/openapi-ng/auth/uc-session/login.go
  internal/core/openapi/openapi-ng/auth/uc-session/provider.go
  internal/core/openapi/openapi-ng/auth/uc-session/user.go
  internal/core/openapi/openapi-ng/routes/openapi-v1/provider.go
  internal/core/openapi/settings/provider.go
Labels: feature, approved

#6582 feat(release 2.1): openapi settings provider and configurable session expiration time in redis
  cmd/openapi/main.go
  conf/erda/erda.yaml
  conf/openapi/openapi.yaml
  modules/core/openapi-ng/auth/password/check.go
  modules/core/openapi-ng/auth/password/provider.go
  modules/core/openapi-ng/auth/uc-session/check.go
  modules/core/openapi-ng/auth/uc-session/login.go
  modules/core/openapi-ng/auth/uc-session/provider.go
  modules/core/openapi-ng/auth/uc-session/user.go
  modules/core/openapi-ng/routes/openapi-v1/provider.go
  modules/openapi/auth/auth.go
  modules/openapi/auth/user.go
  modules/openapi/loginserver.go
  modules/openapi/provider.go
  modules/openapi/server.go
  modules/openapi/settings/provider.go
Labels: feature, approved

#6586 feat(ai-proxy): add cache for model & provider
  internal/apps/ai-proxy/cache/cachetypes/interface.go
  internal/apps/ai-proxy/cache/config.go
  internal/apps/ai-proxy/cache/config_test.go
  internal/apps/ai-proxy/cache/items.go
  internal/apps/ai-proxy/cache/manager.go
  internal/apps/ai-proxy/common/ctxhelper/keys.go
  internal/apps/ai-proxy/provider.go
  internal/apps/ai-proxy/reverse_proxy.go
  internal/apps/ai-proxy/route/filters/request/context-family/context/model.go
  internal/apps/ai-proxy/route/filters/request/context-family/context/model_test.go
Labels: feature

#6589 fix(ai-proxy): fix concurrent map read and write for resp header
  internal/apps/ai-proxy/route/reverse_proxy/response_header.go
  internal/apps/ai-proxy/route/reverse_proxy/response_modify.go
Labels: bugfix
